### ISSUE TITLE
When i drag the map marker does not follow (vid)

### ISSUE THREAD

**Issue by vapits** [angular-ui/angular-google-maps#1018]
This is a very strange issue.
When i drag the map to see what's arround the marker stays fixed in the center of map area.

``` html
<ui-gmap-google-map center='settings.Location.coords' zoom='12' options='options'>
    <ui-gmap-marker idKey='1' coords='settings.Location.coords'></ui-gmap-marker>
</ui-gmap-google-map>
```

Does anyone else have this problem?
Here's also a screnncast with the problem recorded:
https://www.youtube.com/watch?v=M73ynsngkU8

**Comment by dovk** [comment]
Excellent! Thank you!
