### ISSUE TITLE
Marker offset when two markers are in the exact same location ([MarkerSpiderfier] needed)

### ISSUE THREAD

**Issue by merlihan** [angular-ui/angular-google-maps#1021]
Hi!
This directive is great! Just wondering if you have a way to handle markers that are in the same location.
I am trying to create a map app that handles events around the city. Some events could be in the same location at any given time. I know the default google maps behaviour doesn't do much for that. Does this directive handle that in any way?

See plunker demo here: http://plnkr.co/edit/1vrULXRKZ01mwaK0JDaM

Thanks in advance.

**Comment by darrynten** [comment]
I would love the ability for small offsets when markers are in the same spot. Would be very useful.

**Comment by nmccready** [comment]
I would love someone else to implement it.

**Comment by KasperAndersson** [comment]
What's status on tihs, @nmccready? I'm in the same situation with a project.

**Comment by nmccready** [comment]
Funny you should ask this as someone just contacted me about implementing this via email. They are possibly going to fund me to do this. I am strapped with work and a baby due anyday. So lets see if they come through to make it worth it. Otherwise, whenever I find time I'll try and get to it.

**Comment by nmccready** [comment]
Going to pull in https://github.com/jawj/OverlappingMarkerSpiderfier
