### ISSUE TITLE
clusterer not always redrawing when it should

### ISSUE THREAD

**Issue by nmccready** [angular-ui/angular-google-maps#1028]
clusterer redraws see #1026

**Comment by mirko77** [comment]
@nmccready I have that problem on 2.0.11, I tried 2.0.12 but the markers always disappear after being rendered, zooming in/out does not make them reappear

**Comment by nmccready** [comment]
plunkr?

**Comment by mirko77** [comment]
@nmccready it has something to do with the fit="true" attribute, setting it to false makes everything work as expected

http://plnkr.co/edit/pzfZfOJR8CSDffLgxaXa?p=preview

**Comment by nmccready** [comment]
Thanks

**Comment by nmccready** [comment]
actually digging into this now

**Comment by nmccready** [comment]
as per your example it is confirmed to still occur on master

http://plnkr.co/edit/LeuWHZMEzRfPIf2XG6PM

**Comment by nmccready** [comment]
So playing with your example, it appears that fit seems to be interfering with something. If you remove the fit attribute I do not see the clustering issue. Also this was with removing doRebuildAll as well.

**Comment by nmccready** [comment]
Ahh I think I see the problem. Fit iterates through the markers asynchronously. So it needs to lock on them.
