### ISSUE TITLE
Polygons directive does not use fill parameter

### ISSUE THREAD

**Issue by aplus01** [angular-ui/angular-google-maps#1034]
I was able to resolve the issue by adding 'fill' to this.scopePropNames of the uiGmapPolygons directive and afterwards Polygon directives respect the fill parameter.

```javascript
this.scopePropNames = ['path', 'stroke','fill', 'clickable', 'draggable', 'editable', 'geodesic', 'icons', 'visible'];
```

**Comment by nmccready** [comment]
Any luck on this? Have you tried it recently?

**Comment by nmccready** [comment]
Closing until reply.

**Comment by aplus01** [comment]
Yes, fill is working as expected. Thanks.

**Comment by krewmarco** [comment]
I am doing some dynamic binding of polygons, and "fill" doesn't work.

           <ui-gmap-polygons models="map.zones"
                             path="'path'"
                             visible="true"
                             editable="'editable'"
                             stroke="'stroke'"
                             fill="'fill'"
                             events="map.zoneEvents"
                    >
            </ui-gmap-polygons>

"stroke" seems to work, but not dynamically.  I'm using 2.1.5.   I noticed that it fails to create the "fill" key on the directives child scope.  I'm not quite sure where to make the fix.
![debug](https://cloud.githubusercontent.com/assets/4763482/9507255/b1b01efa-4c01-11e5-9997-f316bf8fd20d.png)
