### ISSUE TITLE
Change image_path (nice to have)

### ISSUE THREAD

**Issue by knapeto** [angular-ui/angular-google-maps#1044]
Hey 

when I have app with ssl, my console debugger write 

Mixed Content: The page at 'https://www.veggnetwork.cz/map' was loaded over HTTPS, but requested an insecure image 'http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m2.png'. This content should also be served over HTTPS.

need rewrite dist/angular-google-maps.js to 

MarkerClusterer.IMAGE_PATH = "//google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m";

**Comment by kylebuckingham** [comment]
Just for the sake of documentation, this is how I was able to make this work:

        $scope.map = {
            events: {
                tilesloaded: function(map) {
                    $scope.$apply(function() {
                        //https fix
                        MarkerClusterer.IMAGE_PATH = "https://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m";
                    });
                }
            }
        };
