### ISSUE TITLE
How to show the driving directions and calculate distance.

### ISSUE THREAD

**Issue by nkiranrao** [angular-ui/angular-google-maps#1052]
I am trying to understand how to use this to showing the driving directions with the 'Waypoints in directions' as shown here: https://developers.google.com/maps/documentation/javascript/examples/directions-waypoints 

but I am unable to understand how  to access t he map object in this code for my purpose of if I am missing anything much simpler like map options.

Can someone please help me to show the driving directions  and calculate the total distance between start and end via the stop by points.

**Comment by GregoryCollett** [comment]
Hey mate, 

I have just been doing the same thing...

Here is an example of how I done it (minus view code)
https://gist.github.com/GregoryCollett/c8e3599f6170127a8159

In the view I added polyline directive and applied PATH response from direction service to a scope variable to be used by polyline..

Hope this helps!

**Comment by nkiranrao** [comment]
Thanks GregoryCollett , I am kind of new to angularJS as well, so would it be possible to share an example View code as well.  

are you suggesting that I actually create a polyline in the following callback?

  directionsService.route(request, function(response, status) {
  //do stuff here with response
  });

**Comment by escapedcat** [comment]
Had the same problem.

I tried this approach:
https://gist.github.com/escapedcat/1a85dc3f04d9689ce48e

1. First get whatever address data (you can skip this if you already have the coordinates in a list)
2. If uiGmapGoogleMapApi is ready create the needed services
3. If your maps instance is ready add the directions to the map.

Hope this helps. Not sure if this is a clean way to do it though...

**Comment by nmccready** [comment]
@escapedcat is there a distance service in that example as well? Either way you'll need some service to get the distance in a similar fashion. I think @escapedcat 's example covers it.

**Comment by escapedcat** [comment]
In this case there's only the **directions service** involved. But I guess you could use the **distance service** in the same way. I don't have any experience with that one though.

**Comment by nkiranrao** [comment]
@escapedcat: That works!!!!  Thanks....

one issue I have is that... now  this is also showing me an additional markers, is there a way I can remove that?  I would like to stick with my usual "ui-gmap-marker" I can't find it from the documentation here: https://developers.google.com/maps/documentation/javascript/directions

**Comment by escapedcat** [comment]
@nkiranrao I saw you had one question regarding markers. But I guess you solved it and removed the question.
Maybe you can share your solution for other people who will find this in the future :)

**Comment by nkiranrao** [comment]
@escapedcat: Yes, I did have a question around how to hide the default markers shown by the direction service as I am already making use of the "ui-gmap-marker", but was able to find a way to suppress the default A, B markers using the "directionsDisplay.setOptions({ suppressMarkers: true })" before calling the "directionsDisplay.setDirections(response)"

**Comment by captainmorgan0** [comment]
@escapedcat Can you please show your extra code. Where is addressService defined? What does the createWaypointsFromAddresses function contain? How does you HTML look?

**Comment by ronniebermejo** [comment]
I struggle with this for some time. This I how I make it work.
Hope it helps some one:

```html
<div id='directions-panel'>
  <ui-gmap-google-map center='vm.map.center' zoom='vm.map.zoom' pan="true" control='vm.control' fit='true' dragabble="true">
    <ui-gmap-markers models='vm.markers' coords="'coords'" options="vm.options"></ui-gmap-markers>
  </ui-gmap-google-map>
```


```javascript

      uiGmapIsReady.promise().then(function(){
        var directionsDisplay = new google.maps.DirectionsRenderer();
        var displayedMap = vm.control.getGMap();
        googleDirections.getDirections(getDirectionsArgs).then(function (directions) {
          directionsDisplay.setOptions({ suppressMarkers: true });
          directionsDisplay.setMap(displayedMap);
          directionsDisplay.setDirections(directions);
          directionsDisplay.setPanel(document.getElementById("directions-panel"));
        });
      });
```

**Comment by nmccready** [comment]
@ronniebermejo so you can take your knowledge and make a directions directive with what you just learned. As you can then use `element` via the directive to do it the "angular way". But yes what you have will work just fine in a controller.

The nice part of using element via the directive is that you dont have to worry about the `id` nor element selection.

**Comment by ronniebermejo** [comment]
@nmccready yes, actually this part of a directive already. I will abstract my code to come up with a generic "directions" directive. Some ideas on the final directive interface/attributes would guide me a lot. I'll be back with my progress. :v:

**Comment by nmccready** [comment]
awesome :+1:

**Comment by gargoura** [comment]
As long as there is no generic "directions" directive. I am trying to make driving directions with the 'Waypoints in directions' But I am still struggling with it..

I already get my current position and the destination position. but I am not able to make the direction between the two points. Would please communicate a clear example on how to make this.

**Comment by coderdecoder** [comment]
@ronniebermejo did you finish your directive? Just curious. Not liking getElementById at all. :)

**Comment by immersiontravis** [comment]
@ronniebermejo, I'd also love to see what you came up with. A directions directive, or even just a good start at one, would be a huge asset for this module.

**Comment by nkiranrao** [comment]
This is what I ended up using, may be it will help you. 

        function DisplayDrivingDirections(rfq, $scope) {
            if (rfq.PickupPoint !== undefined && rfq.DeliveryPoint !== undefined) {
                var directionsServiceRequest = {
                    origin: rfq.PickupPoint.Location,
                    destination: rfq.DeliveryPoint.Location,
                    waypoints: [],
                    optimizeWaypoints: true,
                    provideRouteAlternatives: false,
                    travelMode: google.maps.TravelMode.DRIVING,
                    unitSystem: google.maps.UnitSystem.METRIC
                };

                if (rfq.DropoffPoints !== undefined) {
                    rfq.DropoffPoints.forEach(function (dropoff) {
                        directionsServiceRequest.waypoints.push({ location: dropoff.Location, stopover: true });
                    });
                }
                var directions =
                {
                    TotalDistance: 0,
                    TotalDuration: {},
                    Segments: []
                };
                $scope.directionsService.route(directionsServiceRequest, function (response, status) {
                    if (status == google.maps.DirectionsStatus.OK) {
                        $scope.directionsDisplay.setOptions({ suppressMarkers: true });
                        $scope.directionsDisplay.setDirections(response);

                        directions.TotalDistance = 0;
                        directions.Segments = [];
                        var totalDuration = 0;

                        var route = response.routes[0];
                        // For each route, display summary information.
                        for (var i = 0; i < route.legs.length; i++) {
                            var routeSegment = i + 1;

                            var legDistance = route.legs[i].distance.value; // distance in meters need to devide by 1000 for Km
                            directions.TotalDistance = directions.TotalDistance + legDistance / 1000;

                            var legDuration = route.legs[i].duration.value; // travel time in seconds
                            totalDuration = totalDuration + legDuration;

                            directions.Segments.push({
                                Start: route.legs[i].start_address,
                                End: route.legs[i].end_address,
                                Travel: route.legs[i].distance.text,
                                Duration: route.legs[i].duration.text
                            });
                        }

                        directions.TotalDuration = secondsToTime(totalDuration);
                        $scope.directions = directions;
                    }
                });

            }
        }

and the HTML looks like this
                `<div id="map" data-tap-disabled="true">
                    <ui-gmap-google-map center="mapOptions.center" zoom="mapOptions.zoom" bounds="mapOptions.bounds" frameborder="0" style="border: 0; width:100%; height:100%;" pan="true">
                        <ui-gmap-marker ng-repeat="m in mapOptions.markers" coords='m' icon='m.icon' fit="true" idkey='m.id' click="m.onClick()">
                            <ui-gmap-window show="m.isVisible" closeclick="'onClose'" ng-cloak>{{m.title}}</ui-gmap-window>
                        </ui-gmap-marker>
                    </ui-gmap-google-map>
                </div>`

**Comment by immersiontravis** [comment]
Thanks, but I'm afraid I'm not following that. What is `DisplayDrivingDirections()`? An inner function inside your main controller? I guess that'd work, but it's a bit messy.

**Comment by nkiranrao** [comment]
Thats right, I have a service which is called whenever a point is added to the collection. I had a plan of converting this to a directive, but never got that far. important point was the line that had ` $scope.map = new google.maps.Map(document.getElementById("map"), mapOptions);`

**Comment by sarment0** [comment]
I'm having problems with "google is not defined".  Using @ronniebermejo piece of code. What's wrong?

**Comment by greenie2600** [comment]
Sounds like the Google Maps JavaScript API is not being loaded.

Did you pass your Google Maps API key into GoogleMapApi.configure(), as shown in [the examples](https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/scripts/controllers/example.js)?

    GoogleMapApi.configure({
        key: 'your api key',
        // v: '3.20',
        libraries: 'weather,geometry,visualization'
    });

**Comment by ronniebermejo** [comment]
@sarment0, since that code is using the `google` api global object you need to require the API the google way:  `<script src='//maps.googleapis.com/maps/api/js?libraries=places'></script>
`, this will make available the `google` object

**Comment by sarment0** [comment]
It was a problem with Karma-test, the object  "Google" is not defined, i had to mock the class, everything is fine now. Sorry for any misunderstoods. Thanks guys @ronniebermejo @greenie2600

**Comment by Jp3292** [comment]
How to show the driving directions (root) in <DIV>  as a single string and save in db?
