### ISSUE TITLE
Distorted default map zoom controls

### ISSUE THREAD

**Issue by parky128** [angular-ui/angular-google-maps#1053]
Hi there,

I have just setup this directive for use in my project for the first time, the map is rendering ok, but the zoom controls are a mess. I followed the step by step guide, and am pretty sure I have not missed anything.

![image](https://cloud.githubusercontent.com/assets/10373419/5597369/32a9c0d8-9299-11e4-80d7-090c490acf06.png)

I am using Chrome (Version 39.0.2171.95 m), can anyone help?

Thanks

**Comment by cthrax** [comment]
I don't remember what the fix is, but this is a bootstrap css issue, if you search the closed issues you'll find your answer.

**Comment by parky128** [comment]
Thanks for you answer, found the fix in issue 925 for anyone else that comes across this.

**Comment by stephent** [comment]
Link to original issue: #925
