### ISSUE TITLE
Why lo-dash?

### ISSUE THREAD

**Issue by hexahedron** [angular-ui/angular-google-maps#1055]
Hi everyone, 
I believe that this has already been expressed in the past but I couldn't find an issue. I created his issue is created in order to discuss and understand why using lo-dash in this project is so important and highlight a few problems of using the library.

I experienced a blocker issue while trying to integrate angular-google-maps within a page that lives alongside a requireJS application. problem is that lo-dash was crushing the RequireJS application making things interesting.

Another problem is that an angular project is not necessarily using lo-dash, why someone must be forced to use lo-dash? For example my team disliked the idea in loading lo-dash on the browser just for the angular-google-maps.

I saw that lo-dash is tightly coupled with the application, I think I saw at least 400 references in the main directive alone.

My opinion is that this directive should stay decoupled from lo-dash, use jQuery light for any available operations cherry pick the rest from lo-dash.

**Comment by cthrax** [comment]
Thank you for your opinion and if you would like to spend the time and effort to remove lodash as a dependency, we would certainly entertain the idea. As you said there are 400 references, so this is no trivial task and lodash was chosen because re-inventing the wheel is a terrible idea. Jqlite does not offer the same power that lodash does, so it was not a viable replacement and created quite a bit more work just do things that have already been solved by lodash. 

As to your problem with requirejs, take a look at the lodash fork https://github.com/lodash/lodash-amd/tree/2.4.1 and see if that helps you out.

**Comment by nmccready** [comment]
Underscore would be an alternative where some things are missing that lodash provides. The main thing off the top of my mind would be to deal with `_.clone something, true` deep cloning. Which is easily replaced by other means. Either way the same style would be used with underscore as the other option. Like @cthrax said I am not open to reinventing the same iterators and utils that underscore or lodash provide.

**Comment by hexahedron** [comment]
That makes sense ,for that reason I was talking about cherry picking and not rewriting. Problem is that the directive assumes quite a few things about the ecology of the page. One of this is that you can not have the directive and an irrelevant requireJS application on the same page.

That is not a common case but could be a blocker for some cases.

**Comment by nmccready** [comment]
We had a problem with RequireJS and Grunt Jasmine a while back I wonder if the problem is related. Anyways, @cthrax found a work around for that.

**Comment by hexahedron** [comment]
I was reading on that, I tried it and it didn't really help. The angular application doesn't leave in the RequireJS ecosystem btw. The main problem was that lodash' define module was crashing requireJS.

**Comment by lukehorvat** [comment]
Something like Browserify/webpack could be used to cherry-pick only the Lodash functions that you guys actually use (e.g. `require 'lodash/collection/pluck'`) and bundle them along with the rest of the library. Wrap everything in a big closure so none of the Lodash functions leak out = problem solved. Obviously, it would increase the overall size of the library, so it depends on how much of Lodash is actually utilized by angular-google-maps.

Easier said than done, but it's worth considering. I would like to see the Lodash dependency gone as well.

**Comment by nmccready** [comment]
I welcome someone else tackling the issue. Also lodash has been updated recently and I want to target the new version of it. Supposed to be faster and have many bug fixes.

**Comment by nmccready** [comment]
@lukehorvat if you want to do this , please create a new ticket (boxing lodash and reference this ticket.

**Comment by lukehorvat** [comment]
I'd be happy to investigate this once y'all switch over to gulp. From the looks of #915, it seems you guys already had the same idea (of combining gulp and webpack), so that's cool. :sunglasses:

**Comment by nmccready** [comment]
I'd prefer this to be sooner as gulp is not coming in until 3.0 is released and that is pretty far out.
