### ISSUE TITLE
problem with ng-show in window

### ISSUE THREAD

**Issue by knapeto** [angular-ui/angular-google-maps#1056]
Hey,

I have problem with ng-show and ng-hide
Example:

HTML:
```
<ui-gmap-google-map class="col-md-12"
                    center="map.center"
                    zoom="map.zoom"
                    dragging="map.dragging"
                    draggable="true"
                    control="map.control">
            <ui-gmap-marker ng-repeat="m in map.markers" coords="m" click="m.click()" idkey='m.wonkyId'>
                <ui-gmap-window show="true">
                    <div class="popup" style="width: 350px; height: 20px;">
                        <div ng-controller="winCtrl">
                            {{ m }}
                            <span ng-show="m.showSpan">This won't show..</span>
                        </div>
                    </div>
                </ui-gmap-window>
            </ui-gmap-marker>
        </ui-gmap-google-map>
```

JS:
```
 $scope.map.markers = [
        {
            wonkyId: 0,
            longitude: 4.404418,
            latitude: 51.219053,
            showSpan: true
        },
        {
            wonkyId: 0,
            longitude: 4.5044,
            latitude: 51.40,
            showSpan: false
        }
    ];
```

help me please with this !

Thanks..

**Comment by cthrax** [comment]
Please create a plnkr (http://plnkr.co/) demonstrating the problem and also be sure to tell us what the problem actually is. Then we might be able to help you. http://plnkr.co/

**Comment by nmccready** [comment]
What about ng-if it works fine for markers, which I know for sure.

**Comment by nmccready** [comment]
Closing till plunkr, also try using a template.

**Comment by nmccready** [comment]
I'll copy it too examples and check it out.

**Comment by nmccready** [comment]
I would suggest not using marker or window in that manner. Use markers and window not nested.

**Comment by nmccready** [comment]
Since there have been no replies since the original posting this is going to be closed. Regardless I suggest you pass the marker to a window via templating. There is an example where window can be created via templates. Thus you can pass marker in as a templateParameter.

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/a59887b7eea26cb2bb9deb643a4e744dab06c4df/example/geojson.html#L78

**Comment by nmccready** [comment]
You will see a commit above showing your scenario working fine.

**Comment by meyacine** [comment]
http://plnkr.co/edit/jOydFAdVlNuPKO1qjSY7?p=preview hope it'll be usefull
