### ISSUE TITLE
Cluster Click Event

### ISSUE THREAD

**Issue by merlihan** [angular-ui/angular-google-maps#1058]
Hi there,

I see how to add events to the map and to the individual markers. Just wondering if there is a way to attach say, a click event to the cluster image. I have worked through a number of solutions to handle multiple events at the same location and the one I am hoping to achieve is when a user is fully zoomed in (at this point, the cluster will not break up any further since the markers it contains are in the same location), if they click the cluster image itself, open the info window with the details for all the items in that cluster.

Does that make any senes?  Thanks in advance.

**Comment by cthrax** [comment]
There is the clusterEvents property on markers, see markers in https://angular-ui.github.io/angular-google-maps/#!/api .

**Comment by merlihan** [comment]
Thanks for the speedy reply, @cthrax!  Yes, that is exactly what I was looking for.
For further reference, I had come across the resolved issue here as well: https://github.com/angular-ui/angular-google-maps/blob/master/example/issue-393-cluster-events-mapped.html

**Comment by cthrax** [comment]
Glad to help.
