### ISSUE TITLE
info window with multiple pins data

### ISSUE THREAD

**Issue by merlihan** [angular-ui/angular-google-maps#1060]
Hey guys,

I am looking to create an info window which displays data for multiple pins. Any pointers on where to start here? I have the info window currently working for one pin to one info window, but am looking to show out multiple pin data in one info window. I am using clusterEvents click function which is functioning as it should, but I can't seem to wrap my head around initiating the custom info window. 

Any thoughts?

**Comment by cthrax** [comment]
I would define the window directive as a sibling to the marker(s) and bind it to a list of markers that you filter in your controller. Use another bound variable for whether the marker display's or not and create some sort of logic as to which marker you are using for coordinates (ie, first marker in the list, second, some generated value based on all of them...).

**Comment by merlihan** [comment]
hi @nmccready! It's fairly complex since I will have <h3>, <p>, <br />, <img> and <a> tags in the window while listing out many pins info within it. I am using the window directive (not windows), so that's good. 
I have downloaded the examples and played with info.js (the InfoController). Seems when I change : 
$scope.templateValue = 'hello from the template itself'; to this
$scope.templateValue = '<strong>hello from the template itself</strong>';

the info window spits out the literal <strong> value instead of rendering it as html. Is that what you meant or is there a different workaround?

**Comment by merlihan** [comment]
Ok, so it doesn't seem like i can send a string containing markup from the .js file but as I have read in other threads, if I can pass the object containing the data, I can iterate through that array with ng-repeat (since I am now using the InfoWindowController and infoWindow template). 

This part is working... sort of. My only issue now is that I am broadcasting the data from the parent controller to the child controller, but it is simply refusing to update the $scope.templateValue. 

If I console.log it out, the value is coming through. It just seems to be happening later in the game. Any ideas?

**Comment by merlihan** [comment]
Update: After about two days of trudging through, I have finally done it!  

I ended up using the template parameter and passed in an object with the data. From there I iterated over the items with ng-repeat!

Whoop!

Thanks for all your help.

**Comment by cthrax** [comment]
Glad to hear it!
