### ISSUE TITLE
Total performance degradation when displaying markers

### ISSUE THREAD

**Issue by markotomictoma** [angular-ui/angular-google-maps#1063]
I am new to this framework and I am also not that good with javascript so it can be that I am doing something wrong but so far couldn't figure that out. I made a simple app with array of 1000 objects with lat/long that are stored(hardcoded) in the factory(service). Every time when the pin is moved, I take the new pin's coords and search array for objects that are in radius of 50 Km. Resulted array is then bound to markers and displayed on the map. Number of objects in the resulted array is never bigger than 100. However, even with 50 markers chrome/ff/ie takes 30+ seconds to display. 

I did some debugging and figure out that almost all time goes to this line of code:
this.clonedModel = _.clone(this.model, true); (angular-google-maps.js, method MarkerChildModel)

To me, it looks like that for every marker that should be displayed on the map, whole application model is being cloned. Lodash baseClone method is being executed thousands of time for only a couple of markers. Unfortunately, I am simply not capable of figuring out how to solve this. 

Anybody has a clue?

**Comment by gitnik** [comment]
Do you use the doRebuildAll flags for the markers?

**Comment by markotomictoma** [comment]
No, I don't use them. At least I didn't explicitly write it anywhere in the project, only if it is some default behavior.

**Comment by gitnik** [comment]
I also use a total of 1200+ markers in a project and displaying all of them takes less than 3 seconds for me, so I suppose it might have to do with your code and not ours

**Comment by markotomictoma** [comment]
I stripped out all the user interactions, all the services, all directives I had and performance issues are still there. It's basically example from the website with 60 choords. I will try to figure out how those online javascript playgrounds work and I will upload all the code there.

**Comment by kieferhagin** [comment]
I'm also having an issue displaying around 100 markers. Not using doRebuildAll. The issue isn't necessarily displaying them initially, it seems to be the digest/apply cycle. It takes around 200ms every time I pan the map even 1px to run through all of the markers. Adding InfoWindows renders the map completely unusable.

**Comment by markotomictoma** [comment]
In the meantime I replaced directive with google's native and it renders blazingly fast. Complete model stayed the same so I am pretty sure now that problem isn't in my code but the overhead with copying the model I described in first post

@kieferhagin 
Can you put breakpoint at the same place I described and check how much time goes to baseClone

**Comment by kieferhagin** [comment]
@markotomictoma Sure thing, the model I'm using is fairly large. I removed the model from the marker and just left enough data to render it and it's working a lot better. Definitely something to do with how it manages the data contained in the marker model. Let me breakpoint that and take a look

**Comment by kieferhagin** [comment]
@markotomictoma not finding the line you're referring to. which version are you on?

**Comment by markotomictoma** [comment]
Yesterday is the first time I found out for this directive and downloaded from website. It should be the most up to date - 2.0.12

**Comment by kieferhagin** [comment]
Gotcha. That line doesn't appear to be the issue, at least not for me. I think we may have two different issues here.

**Comment by kieferhagin** [comment]
Might consider putting together a plunker that details your issue, the guys are pretty responsive around here and can help you out if you provide an example.

**Comment by markotomictoma** [comment]
Just to be clear, my issue is not only the initial adding but every change of the choords which redraws the markers which further also triggers the digest including the initial one. Once the markers are displayed there is no lag when moving the map, zooming or clicking on the marker to invoke the window. Everything works smoothly until I change the choords for markers.

**Comment by kieferhagin** [comment]
Gotcha, definitely two different issues then. Mine seems to be related to all the watches around marker models, which it seems the guys are aware of and are fixing in a coming update.

**Comment by cthrax** [comment]
Please put together a plnkr demonstrating the issue so we can regress.

**Comment by markotomictoma** [comment]
Ok, I managed to do it. It's my first time to create something in plnkr so excuse my mistakes.

Here you go: http://plnkr.co/Jj3odiZJuH9WzoFD37uM

If you open it in Firefox it will popup unresponsive script with exact file and line.

**Comment by kieferhagin** [comment]
First issue I see is that you're using the singular `ui-gmap-marker` with an ng-repeat. For better performance, you should be using the plural `ui-gmap-markers` which is optimized for multiple markers.

**Comment by cthrax** [comment]
@kieferhagin beat me to it. See if this solves your issues. http://plnkr.co/edit/61ozvUCpu1qGhf4HvVdE?p=preview

**Comment by nmccready** [comment]
Yes please note ui-gmap-marker is going to be getting kicked tot he curb (aka the crapper) it is not worth it.

**Comment by nmccready** [comment]
ng-repeat is not your friend

**Comment by markotomictoma** [comment]
Yea, that was it. With ui-gmap-markers it works a lot more faster. After this I think that ui-gmap-marker documentation deserves one red Note that it should not be used for multiple markers with ng-repeat. Somehow my brain naturally went for ng-repeat without even looking for dedicated directive. 

Thanks guys, this help is much appreciated!
