### ISSUE TITLE
Support for resizing of marker icons

### ISSUE THREAD

**Issue by ecbrodie** [angular-ui/angular-google-maps#1065]
I am wondering if support can be added in angular-google-maps for resizing marker icons. This would mean that the 'icon' attribute of the Marker directive would need to be extended to take in an object similar to a Google Maps Marker object (https://developers.google.com/maps/documentation/javascript/markers) instead of just an image file name. Alternatively, a brand new attribute could be used to take in this object, so that backwards compatibility is maintained with the original icon attribute.

This is a feature supported by the other angular-google-maps project (https://github.com/allenhwkim/angularjs-google-maps/issues/92), so hopefully it can make it into this project as well.

**Comment by nmccready** [comment]
There is no good reason to use the Marker directive unless you have < 10 markers. What exactly needs to be different on icon. Whatever MarkerOptions google supports we support. You can just use the options attribute.

**Comment by nmccready** [comment]
From looking at angularjs-google-maps on issue #92 I think passing the icon options into options is what you want. So this should be already supported. The icon attribute is simply a convenience, but when It comes to doing more advanced stuff just use options.
