### ISSUE TITLE
Map in modal not centered properly on subsequent modal displays

### ISSUE THREAD

**Issue by emadd** [angular-ui/angular-google-maps#1067]
I've got a map rendered in a modal that centers properly the first time the modal is displayed.  On subsequent displays, the center is positioned to the map's northwest boundary.

[1st Modal Pop](http://i.imgur.com/TrCV1xQ.jpg)

[2nd Modal Pop](http://i.imgur.com/1uUtOGX.png)

**Comment by archer247** [comment]
I'm having the same issue, and im tryin to do something

**Comment by nmccready** [comment]
Try wrapping it in ng-if, read here #1114

**Comment by nmccready** [comment]
I think this is your issue and I am considering it a duplicate.

**Comment by zain-creation** [comment]
i have the same probleme, can someone help me.

**Comment by nmccready** [comment]
This is not a bug you need to resize the actual gMap. Please read the issue and read the google maps sdk. You can resize it via `scope.map.control.refresh()` .

**Comment by nmccready** [comment]
@zain-creation #1114 explains what you need at the bottom also look at the commits.

**Comment by zain-creation** [comment]
thnks @nmccready  for your help, in witch directive i will use ng-if this is my modal code:
<script type="text/ng-template" id="mapModal">
	<div ng-app="info-devices" ng-controller="MapModalController">
        <div class="modal-header">
            <h3 class="modal-title">History map</h3>
        </div>
        <div class="modal-body">
            <ui-gmap-google-map center="map.center" zoom="map.zoom" draggable="true" >
                <ui-gmap-marker coords="marker.coords" options="marker.options" idkey="marker.id">
                </ui-gmap-marker>
            </ui-gmap-google-map>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" ng-click="close()">close</button>
        </div>
    </div>
 </script>

**Comment by nmccready** [comment]
ng-if around the map or a div that encapsulates the map.

**Comment by zain-creation** [comment]
thnks @nmccready for your help

**Comment by Teckloon** [comment]
Hi, 

Do you have solution for it , if the code reside in javascript file.
