### ISSUE TITLE
Marker implementation is twice as slow when using custom scaled icons

### ISSUE THREAD

**Issue by chrisse27** [angular-ui/angular-google-maps#1069]
When using the markers directive with custom scaled icons the rendering becomes very slow. Our current workaround is to create the google.map.Marker ourselves and add them to the map manually.

**Comment by gitnik** [comment]
Plunker?

**Comment by nmccready** [comment]
You need to give us examples. Also try develop. If your using Marker.. well don't use it. Use markers.

**Comment by chrisse27** [comment]
Sorry, but I am using this for a business project and I don't have the time to create a plunkr. Just takes too much time and as it is working with just not using the "angular" markers, I am fine with the solution. Just wanted to let you know that (when looking at the code), it seems to meet that the marker implementation part of angular google maps seems to be overly complex.
