### ISSUE TITLE
Async loading of markers not working

### ISSUE THREAD

**Issue by daniil967** [angular-ui/angular-google-maps#1070]
I am trying to load markers async and they simply don't appear. When I load them from a static factory, its fine, but when I AJAX call it, nothing.

Code is as follows

	$scope.change_type = function(val) {
		var markers = [];
		$scope.eventMarkers = markers
		Events.venues().then(function(selected) {

		for (var i = 0; i <selected.length; i++) {
				venue = selected[i]
				markers.push(createMarker(i,venue))   //makes right data type with id and etc
			};
		console.log(markers)
		$timeout(function(){$scope.eventMarkers = markers}, 300)
		})
	}

Console.log displays items just fine, but nothing appears on the map.
createMarker function works, as I used it before and static markers get generated with it
Console has no errors and has following lines

`XHR finished loading: GET "http://127.0.0.1:5000/".`
`controllers.js:140 [Object, Object, Object, Object, Object, Object, Object]`

Each object has: id, longitude, latitude, icon, content, title, onClick function

Time out was there from previous issue of markers loading problem, I kept it because `$timeout` forces `$apply`

Html file has this
`<ui-gmap-google-map ng-show='mode.state' center="map.center" zoom="map.zoom" draggable="true" options="options" bounds="map.bounds">`
   `{{eventMarkers[0]}}`
    `  <ui-gmap-markers models="eventMarkers" coords="'self'" icon="'icon'" click="'onClick'">`
       `     <ui-gmap-windows show="show">`
           `       <div ng-non-bindable>{{content}}</div>`
       `     </ui-gmap-windows>`
  `    </ui-gmap-markers>`
`</ui-gmap-google-map>`

Where `{{eventMarkers[0]}}` displays data, so clearly its in the scope but not getting to `ui-gmap-markers `

**Comment by gitnik** [comment]
Can you create a plunker?

**Comment by daniil967** [comment]
@gitnik it doesnt exactly work, but I recreated as many elements as I can
Replaced ajax call with $timeout to simulate it

http://plnkr.co/edit/CWk9pLC492PKyJuYzzpC?p=preview

Not the prettiest, first time making such large plunker

**Comment by gitnik** [comment]
That plunker doesn't work. You're missing a lot of dependencies/have a lot of dependencies that are not needed in this context

**Comment by daniil967** [comment]
I updated it, still doesnt work. I have isolated the problem of Plunker not working to the async loading of the factory `Events`. No idea how to fix it in Plunker. 
Strangely, that is what I have pinpointed as my problem with marker loading. When I load them straight from factory, it works just fine. But when promises get involved it all crumbles
http://plnkr.co/edit/CWk9pLC492PKyJuYzzpC?p=preview

Specifically line
`Events.venues().then(function(resp){`

**Comment by gitnik** [comment]
The plunker console tells your exactly what's not working...

**Comment by daniil967** [comment]
Ya problem between chair and the screen, my bad. Was trying to make the code concise for plunker.
Fixed now.

http://plnkr.co/edit/CWk9pLC492PKyJuYzzpC?p=preview

While fixing, problem identified itself. When I use
`foo = venue_locations ; //using this to simulate ajax
 deferred.resolve($timeout(function(){return foo}, 300));`
It displays it no problem, moment I replace it with 
`deferred.resolve($http.get('http://127.0.0.1:5000/markers'))`

In the controller, 
`console.log(markers)`
`$timeout(function(){$scope.eventMarkers = markers}, 300); `
Console shows all the values, but nothing appears on the map when using `$http`

**Comment by gitnik** [comment]
`deferred.resolve($http.get("http://127.0.0.1:5000/markers"))` returns a a promise within a promise. so you would have to call `then().then()`. Alternatively you can just return the `$http` call itself

**Comment by daniil967** [comment]
Tried both methods, same result. 
Key element, is when I check console on the `markers` right before assgining them to scope, it is populated with the right data. Not a promise, so data is there, I can print on the screen or console, but it doesnt get pushed to markers.

**Comment by daniil967** [comment]
I have tried many different variations, with updating rootScope and the watching it, different types of passing data. With `$q`, without it. Result is the same and weird, console right before being pushed to the $scope shows all the data, of right data type. But if its static it works, if it comes from AJAX no.

**Comment by nmccready** [comment]
Do you have anew plnkr? Or is it the same one?

**Comment by daniil967** [comment]
I did some updates. Cleaned it up and made some improvements for clarity. Problem is the same, static cool, ajax not. I verified with .constructor, its all correct types and etc.
http://plnkr.co/edit/CWk9pLC492PKyJuYzzpC?p=preview
if you run a local server with that static data (Flask is the simplest for that) it doesnt work for me.
I tried it multiple times, and no luck.

**Comment by nmccready** [comment]
Your problems are in the comments. Your code was incorrect usage in many places.

http://plnkr.co/edit/pkS2DLbG8KZNQzuCT6hC?p=preview

**Comment by nmccready** [comment]
First you should define eventMarkers as an array early. You were seeing a race condition because at first the markers directive had nothing to go off of. Lastly your window parsing data was incorrect.

**Comment by nmccready** [comment]
Also it is more efficient to use window here.

**Comment by nmccready** [comment]
Here is the one with window http://plnkr.co/edit/3MCjYvn2bE7x0NDqEDEz?p=preview
