### ISSUE TITLE
[master] Retina cluster icons not rendered correctly

### ISSUE THREAD

**Issue by chrisse27** [angular-ui/angular-google-maps#1071]
Retina icons on are rendered with the wrong size (2x).

As you are using MarkerClustererPlus see this fiddle here: http://jsfiddle.net/Rt28T/2/

This would be a viable fix (from the fiddle):

```
ClusterIcon.prototype.show = function () {
  if (this.div_) {
    var img = "";
    // NOTE: values must be specified in px units
    var bp = this.backgroundPosition_.split(" ");
    var spriteH = parseInt(bp[0].trim(), 10);
    var spriteV = parseInt(bp[1].trim(), 10);
    var pos = this.getPosFromLatLng_(this.center_);
    this.div_.style.cssText = this.createCss(pos);
    img = "<img src='" + this.url_ + "' style='position: absolute; top: " + spriteV + "px; left: " + spriteH + "px; ";
    if (!this.cluster_.getMarkerClusterer().enableRetinaIcons_) {
        img += "clip: rect(" + (-1 * spriteV) + "px, " + ((-1 * spriteH) + this.width_) + "px, " +
          ((-1 * spriteV) + this.height_) + "px, " + (-1 * spriteH) + "px);";
    } else {
        img += "width: " + this.width_ + "px;" + "height: " + this.height_ + "px;";
    }
    img += "'>";
```

**Comment by nmccready** [comment]
ClusterIcon is not under my source control. This is something to direct to the google maps util sdk.

**Comment by chrisse27** [comment]
So you are only shipping MarkerClustererPlus with the library? If this is the case, why are you not leaving MarkerClustererPlus out of the distribution? It would make a developer's life much easier. Now I have to ask the marker cluster guys for a fix and then wait until you ship a new version.

**Comment by nmccready** [comment]
Sorry brain fart. We do have overrides. So we can override the prototype.  So the code would be added [here](https://github.com/angular-ui/angular-google-maps/blob/master/src/js/extensions/markerclusterer.js) . Please make a PR and double check that this can not be done via Clusterer Options. I'll look into this more when I get the chance.

**Comment by nmccready** [comment]
To be clear the google sdk libs are downloaded via curl into curl_componenets. The libraries are then loaded into a angular service. Any angular-google maps customizations then are in a separate service to override the functionality.

**Comment by chrisse27** [comment]
Thanks for shedding some light on the process. For now, I filed a bug report with the guys form the google maps util sdk.

**Comment by nmccready** [comment]
@chrisse27 do you have any specs code to make sure this doesn't break existing icons?

**Comment by nmccready** [comment]
Note, https://github.com/googlemaps/js-marker-clusterer/issues/3

**Comment by chrisse27** [comment]
Sorry, right now I do not have any specs for this. If I recall correctly this code is very similar to the fix in the standard MarkerClusterer, but no one can guarantee that some people rely on the current behavior of MarkerClustererPlus. Also, I think this fix disables the option to use sprites for retina icons, but I would have to check again.

**Comment by nmccready** [comment]
Yeah we would need to customize it to support both if possible. I am trying to fix this today in as little time as possible. I want to get 2.0.13 out and move 2.1 to master.

**Comment by nmccready** [comment]
Do you have any urls where people have done this already? Please post them in here.

**Comment by nmccready** [comment]
Here is the [diff](http://www.diffnow.com/?report=olw61) on the code above with ClusterIon for others.

**Comment by nmccready** [comment]
Actually this should be fine, if they are using sprites then they should not enable the enableRetinaIcons option.

**Comment by nmccready** [comment]
Nice work.

**Comment by chrisse27** [comment]
The fix orginally comes from this post btw: http://stackoverflow.com/questions/21047829/how-to-use-marker-clusterer-plus-on-a-google-map-with-retina-images

**Comment by nmccready** [comment]
Do you have some better retina icons or single icon url I could use in the main example? That way I can verify it works and show others easily.

**Comment by nmccready** [comment]
The jsfiddle in SO has an icon but it is pretty hideous.

**Comment by nmccready** [comment]
nvm i think i got one

**Comment by chrisse27** [comment]
OK, I'd recommend https://www.facebookbrand.com/ otw.
