### ISSUE TITLE
[2.0.12] Using ng-model with search-box

### ISSUE THREAD

**Issue by sgimeno** [angular-ui/angular-google-maps#1076]
When using the `search-box` I can't figure out how I can bind/get my view value to the current scope. For me the most angular-natural way would be to use `ng-model` in the `searchbox.tpl.html` file/template:

```
<input type="text" ng-model="map.mySearchBoxModel">
```

Where `map` would be the controller wrapping the `ui-gmap-google-map` directive. Whats the preferred way of doing so atm? Should we document it in the `search-box` docs?

**Comment by kandizzy** [comment]
@sgimeno will have to adjust the directive to support `ng-model`. will PR that soon

**Comment by sgimeno** [comment]
+1

**Comment by dflourusso** [comment]
I am trying
`<ui-gmap-search-box ng-model="uiMapProperties.searchbox.text" template="uiMapProperties.searchbox.template" events="uiMapProperties.searchbox.events" parentdiv="'ui-gmap-search-box-parent'"></ui-gmap-search-box>`
but no success too.

**Comment by kandizzy** [comment]
@dflourusso what does `uiMapProperties.searchbox.template` look like?

**Comment by dflourusso** [comment]
It is my model.. For example in my controller i have `$scope.uiMapProperties.searchbox.template`
I want do a bind on this variable with my searchbox input

**Comment by kandizzy** [comment]
does the HTML in the `uiMapProperties.searchbox.template` include ngModel on the input field simliar to this `<input id="pac-input" class="pac-controls" type="text" ng-model="ngModel" placeholder="Search">`?

**Comment by dflourusso** [comment]
I tryed now on template:
```
<input class="form-control search-box" type="text" placeholder="Digite um endereço" ng-model="text">
```
and controller:
```
$scope.text = 'Rua teste'
  $scope.$watch 'text', ->
    alert 'testes'
```
bu nothing yet.

**Comment by kandizzy** [comment]
try `ng-model="ngModel"`

**Comment by dflourusso** [comment]
Very strange, i put the ng-model here:
```
<ui-gmap-search-box ng-model="ngModel" template="uiMapProperties.searchbox.template" events="uiMapProperties.searchbox.events" parentdiv="'ui-gmap-search-box-parent'"></ui-gmap-search-box>
```
and here:
```
<input class="form-control search-box" type="text" placeholder="Digite um endereço" ng-model="ngModel">
```
And my controller:
```
$scope.ngModel = 'Rua teste'
  $scope.$watch 'ngModel', (n, o)->
    console.log 'testes', n, o
```

On this way my input is filled, but the `$watch` expression do not work

**Comment by kandizzy** [comment]
So the ng-model on `ui-gmap-search-box` should remain 'uiMapProperties.searchbox.text'

The template should be 'ng-model="ngModel"` because it's going to inherit it from the directive

**Comment by dflourusso** [comment]
Very good, now it works perfectly, thanks.

**Comment by kandizzy** [comment]
:+1:

**Comment by intellix** [comment]
After figuring out the magic needed `ng-model="ngModel"` inside the template from reading the above. Still can't get this to work with parentdiv: http://plnkr.co/edit/ezOdzKyxSH7sCr5NUhv0?p=preview

Would be good if the examples/documentation had an example of this. It's all rather confusing

**Comment by kandizzy** [comment]
@intellix  Here you go
http://plnkr.co/edit/d49vG9qEHtELHpHQRcUb?p=preview

I can make a separate example to make it more clear, that line you mentioned is commented out just because it's an alternative- you can use the search box with or without the parentdiv.

**Comment by intellix** [comment]
Argh, did I seriously leave out the ng-model on the one that wasn't working? :D Thanks

**Comment by kandizzy** [comment]
@intellix :D fixed the example to avoid this in future.

**Comment by acedesigns** [comment]
HI @kandizzy 
Sorry to be commenting on a closed issue. But I am running into a similar problem and your [ plunker is broken](http://plnkr.co/edit/d49vG9qEHtELHpHQRcUb?p=preview).

#### So my scenario is that 
1. A use searches for a place in the input box
2. The user presses `Send my location` . So I need to capture the input text so I can make the appropriate API call
3. In the meantime I did an `ng-show` of the model but it comes out empty.

##### http://plnkr.co/edit/mhzGEN?p=preview

Also, how do I zoom out after the place has changed? I hope my question makes sense.

**Comment by kandizzy** [comment]
hi @acedesigns, you were missing searchTerm in your controller. here's an edit of your plunkr
http://plnkr.co/edit/KPBznGFXgYrDPZ390obS?p=preview

When you say zoom out, do you mean altering the map bounds to fit the places found? The main example in this repo for searchbox changes the map bounds to fit the area around whatever places were found. Take a look at the `places_changed` function.
https://github.com/kandizzy/angular-google-maps/blob/master/example/assets/scripts/controllers/search-box.js

**Comment by acedesigns** [comment]
hi @kandizzy 
>"When you say zoom out, do you mean altering the map bounds to fit the places found?"

Yes. Because when I search `Cape Town` the zoom level is too close. I think it's around `16`
Can you also press the `Send my location` and show it on the `<pre>`

**Comment by kandizzy** [comment]
@acedesigns yes check out the map bounds in that example I sent you for the first question. Showing the search term on `<pre>` is basic angular stuff. 'ngModel' is not a variable in your controller, but 'searchTerm' is an example, You could also make another variable for display as necessary depending on what you want to show there and when.
