### ISSUE TITLE
Google Map in modal bad rendering

### ISSUE THREAD

**Issue by mateusz-c** [angular-ui/angular-google-maps#1081]
Google Map render wrong in modal. At first it looks fine but when you move the map the render fails and shows only piece of map. Here screenshot :
![bug](https://cloud.githubusercontent.com/assets/8234378/5758234/d5d2269a-9cc3-11e4-9a82-0afac25672c4.png)

**Comment by mateusz-c** [comment]
it didn't work because in modal was ng-show but to work properly it needs ng-if

**Comment by nmccready** [comment]
Css should fix it too.
