### ISSUE TITLE
Window implementation works in firefox/safari but not in chrome

### ISSUE THREAD

**Issue by ChrisL1200** [angular-ui/angular-google-maps#1085]
Let me preface this by saying it could very well be due to how I am implementing in regards to why it won't work in chrome.  In chrome the window does not render at all.  Here is my code:

https://gist.github.com/ChrisL1200/105976f7ed4e9c3925b1

What am i doing wrong?

**Comment by nmccready** [comment]
plnkr until then this is closed

**Comment by ChrisL1200** [comment]
http://plnkr.co/edit/vp6hjC1uF1mSJ9GgxEKr?p=preview

However the plunker seems to have issues loading the angular-google-maps module.  I have noticed this with other angular-google-maps plunkers that I have found. (http://plnkr.co/edit/bsqILbPPBJnZwyzeumn8?p=preview).

**Comment by nmccready** [comment]
Are you using cdn.rawgit or rawgit. Try either.

**Comment by nmccready** [comment]
You can load code from github off the web. Github explicity blocks it. That is why you need to use raw git.

**Comment by nmccready** [comment]
http://rawgit.com/

**Comment by ChrisL1200** [comment]
Sorry to keep posting about my plnkr issues, i added the rawgit and it does seem to remove the error but the map still isn't populating:

http://plnkr.co/edit/vp6hjC1uF1mSJ9GgxEKr?p=preview

Thanks for the quick feedback.
