### ISSUE TITLE
[master][develop][website] Documentation Update / Along with some API Plural Attribute Renaming

### ISSUE THREAD

**Issue by nmccready** [angular-ui/angular-google-maps#1086]
@gitnik @aesnyder @cthrax @kandizzy @zacronos 
# Missing Documentation Story

(break up into tickets for 2.0.13)
**Cross outs; mark completion**
## markers attributes:
~~- modelsbyref - is for setting watch level. Consider renaming to iswatchdeep I think this attribute should be across all directives. Currently I think this is only in markers.~~

## Plural (any plural directive) attributes:
~~- chunk - defines the chunk size (defaults to whatever is set in _async) uses isFalse to set it to false IE no chunking~~
~~- dorebuildall - was marked as deprecated but I guess we will leave it. But now it is across all plurals for sure.~~
~~- cleanchunk - same as above but for $on. destroy's _async iterator
~~-  control is now across all with the following default functions (for updates without watches)~~
~~-  updateModels()~~
~~-  newModels()~~
~~-  clean~~
~~-  getPlurals() - gets `@plurals` hashmap~~
~~- getManager~~
~~- hasManager~~
~~- managerDraw~~

## services
- ~~uiGmapLogger~~
Now supports log levels and should be documented. The default level is error and doLog is set to true so users wont have swallowed errors.

- ~~uiGmapPromise:~~
```
  #all in all this should be considered to be an outside the library (in uigmap team)
  defer: defer
  promise: promise
  resolve: resolve
  promiseTypes: promiseTypes
  isInProgress: isInProgress
  isResolved: isResolved
  promiseStatus: promiseStatus
  #last two should be documented
  ExposedPromise: ExposedPromise 
  SniffedPromise: SniffedPromise
```
~~- uiGmapAsync - Should be moved to a library of its own with uiGmapPromise~~
```
each: each
map: map
managePromiseQueue: managePromiseQueue
promiseLock: managePromiseQueue
defaultChunkSize: defaultChunkSize
chunkSizeFrom:
```
- ~~uiGmapPropMap~~ (and global window.PropMap) -  `#todo: remove the global`
This is basically a dictionary that supports the iterators each and map. It also will cache its state as an array if `.values() is called`. It is meant to be reusable code to keep you from using object.

## ~~SearchBox~~
~~Is there any missing documentation here. Also are there any services that are useful which people could use that is specific to this directive.~~

## sourcemaps
~~Possibly document that this is available. I have not tested this at all from the standpoint of using this as a thirdparty. I know the sourcemaps work fine from our perspective for doing testing and development in this repo. Anyone care to test this?~~

**Comment by zacronos** [comment]
I strongly suggest having documentation in the same repo/branch as the code.

If someone has to do more effort to find/modify documentation to go with a code change, they are less likely to do it -- making documentation require a separate PR is just the sort of overhead that gets in the way.

Ideally, a single PR should include both code and documentation changes, that way someone can make sure documentation is being updated when reviewing -- and most importantly, it is easy to refuse to merge any PR that doesn't include the appropriate docs change.  It saves time and effort for the person making the PR, and the person reviewing the PR, which makes it much more likely to happen.

The configuration, build tools, etc for whatever makes the website available doesn't necessarily have to go in the same branch -- for example, there could be another branch that knows to pull the main branch, grabs some files from known locations (or builds auto-generated documentation from within the code itself), and then does whatever is needed to make that documentation go up on a website.

**Comment by nmccready** [comment]
Ok I am down for trying it out.
