### ISSUE TITLE
Setting control var of a ui-gmap-markers doesn't work

### ISSUE THREAD

**Issue by captainjim1** [angular-ui/angular-google-maps#1090]
I recently updated my code to use ui-gmap-markers (plural) instead of ui-gmap-marker. I am using the same data-model as I was before, but when I used the ui-gmaps-directive the "control" variables in my model do not get extended with the appropriate functions (getGMarkers, etc).

I pass an object 'location' into my function that builds my markers and I end up with an array of these..
```javascript
var marker = {<br>
    latitude: location.latitude,
    longitude: location.longitude,
    id: location.id,
    show: false,
   control: {}
}
```

.. I would then use this array to build an array of markers..

```html
<ui-gmap-marker ng-repeat="marker in myCtrl.markers" idKey="marker.id" coords="marker" control="marker.control" fit="true">
</ui-gmap-marker>
```
...and everything worked great.. Every marker's control variable had the appropriate functions. The problem was performance really stunk with high data-sets... so now, when I use the other directive...

```html
<ui-gmap-markers models="myCtrl.markers" idKey="'id'" coords="'self" control="'control'">
</ui-gmap-markers>
```
.. I get my markers, performance is great!, but marker.control is still an empty object.

**Comment by nmccready** [comment]
Control is not part of the marker itself. It is part of the controller. It is not a string expression.

``
#your models
scope.markers = [
]
#your control
scope.markerControl = {}
``
