### ISSUE TITLE
ui-gmap-marker and ui-gmap-markers click events don't work the same

### ISSUE THREAD

**Issue by captainjim1** [angular-ui/angular-google-maps#1091]
I recently updated my code to use ui-gmap-markers (plural) instead of ui-gmap-marker. Previously I had been handling click events my passing the current marker-object from my dataSet to a function in my controller ... like this...

```html
<ui-gmap-marker ng-repeat="marker in myCtrl.markers" idKey="marker.id" coords="marker" control="marker.control" fit="true" click="myCtrl.handleClick(marker)">
</ui-gmap-marker>
```

.. the controller stayed in scope, I got the data I needed and life was good. When I changed to the the other directive I no longer have a handle on the current 'marker' to make my controller call.

```html
<ui-gmap-markers models="myCtrl.markers" idKey="'id'" coords="'self" control="'control'" click="myCtrl.handleClick(????)">
</ui-gmap-markers>
```
.. further, I can't actually use that type of notation in the directive parameters (it gets executed at load-time). So, I added a click-function to my data model and had to uncover the function prototype myself (not in the documentation)..

```
onClick = function( googleMarker, eventType, dataModelItem, event){
 // do stuff
 // no scope to controller
}
```
.. at this point I no longer have access to my controller's scope so I'm sort of jammed up. It seems to me that the ui-gmap-markers directive should have a parameter to define the current data-model-object and allow click-events to be called similar to the ui-gmap-marker directive.

**Comment by nmccready** [comment]
Thats ok because marker is going to be eliminated.  If you want it to be identical please PR it. I never use marker myself.

**Comment by captainjim1** [comment]
How would you recommend gaining access to the controller's scope via the markers click handler?

**Comment by nmccready** [comment]
You shouldn't need the scope. Use the control attribute. Then youll have access to the plurals hashmap.

**Comment by nmccready** [comment]
I am closing this since I plan on removing marker in a future release.
