### ISSUE TITLE
Can't find variable: angular And Unable to read "bower_components/uuid/dist/uuid.core.js

### ISSUE THREAD

**Issue by rasekar2000** [angular-ui/angular-google-maps#1095]
Hello All,

 I have followed the https://github.com/angular-ui/angular-google-maps#getting-started steps, still I am seeing the following error while running the https://github.com/angular-ui/angular-google-maps#running-the-example 

grunt --force example
  

Running "jasmine:spec" (jasmine) task
Testing jasmine specs via PhantomJS

>> Error: scripterror: Illegal path or script error: ['lodash'] at
>> _SpecRunner.html:21 
>> .grunt/grunt-contrib-jasmine/require.js:12 v
>> .grunt/grunt-contrib-jasmine/require.js:30 
>> Error caught from PhantomJS. More info can be found by opening the Spec Runner in a browser.
Warning: SyntaxError: Parse error Used --force, continuing.
>> ReferenceError: Can't find variable: angular at
>> tmp/spec/coffee/helpers/google-api-mock.spec.js:6 
>> tmp/spec/coffee/helpers/google-api-mock.spec.js:790 
>> ReferenceError: Can't find variable: angular at
>> tmp/spec/coffee/helpers/google-map-spec-controller.spec.js:4 
>> tmp/spec/coffee/helpers/google-map-spec-controller.spec.js:28 
>> tmp/spec/coffee/helpers/google-map-spec-controller.spec.js:30 
 directives.api.control

     ReferenceError: Can't find variable: module in file:////angular-google-maps/tmp/spec/coffee/helpers/initiator.spec.js (line 25) (1)
     Expected undefined to be defined. (2)
     TypeError: 'undefined' is not an object (evaluating 'this.log.error') in file:////angular-google-maps/tmp/spec/coffee/directives/api/control.spec.js (line 11) (3)

  Please find the attachment with Sublime TEXT Editor & Bash Prompt error details from my MAC laptop... 

  Can you please guide me how to fix the OOTB (Out of the box) program test run 

![bower_components issue](https://cloud.githubusercontent.com/assets/3443965/5787585/63bd7d38-9db9-11e4-890f-2c5c52ad4bbc.png)

**Comment by gitnik** [comment]
npm install & bower install?

**Comment by rasekar2000** [comment]
Hi gitnik,

yes. I did that already ... 
AcumenSekarPro:angular-google-maps rajacumen$ sudo npm install grunt-cli bower
Password:
grunt-cli@0.1.13 node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.5)
└── findup-sync@0.1.3 (glob@3.2.11)

bower@1.3.12 node_modules/bower
├── is-root@1.0.0
├── junk@1.0.0
├── stringify-object@1.0.0
├── which@1.0.8
├── abbrev@1.0.5

**Comment by rasekar2000** [comment]
Hi Nik Karbaum,

   This time, i installed bower and after the review with my friend.. It worked like charm.. Thanks for the hint.. 
 
AcumenSekarPro:angular-google-maps rajacumen$ sudo npm install -g bower
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
bower@1.3.12 /usr/local/lib/node_modules/bower

......

AcumenSekarPro:angular-google-maps rajacumen$ bower install
[?] May bower anonymously report usage statistics to improve the tool over time? Yes
bower uuid#*                not-cached http://github.com/LiosK/UUID.js/archive/v3.2.tar.gz#*
bower uuid#*                   resolve http://github.com/LiosK/UUID.js/archive/v3.2.tar.gz#*
bower bootstrap-without-jquery#*       not-cached git://github.com/tagawa/bootstrap-without-jquery.git#*
.......

AcumenSekarPro:angular-google-maps rajacumen$ grunt --force example
Running "clean:dist" (clean) task
>> 4 paths cleaned.

Running "jshint:all" (jshint) task
>> 2 files lint free.

Thanks and Regards,
Raj
