### ISSUE TITLE
Can't disable dragging on map

### ISSUE THREAD

**Issue by filipesilva** [angular-ui/angular-google-maps#1096]
In the ui-gmap-google-map directive, setting `draggable="false"`seems to have no effect. I tried opening the plunker listed under that directive, setting it to false, and it would still be draggable.

Am I doing something wrong?

Edit: setting draggable in an `options` object seems to work though.

**Comment by nmccready** [comment]
As you can see [here](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/map.coffee#L41-L51)

Draggable is no longer an attribute. If it is in the website / docs then it should be removed. Feel free to PR an update to the website branch.

**Comment by filipesilva** [comment]
Hey I tried making a PR for this. I know it's pretty minor, but this is my first PR so please correct me if I did anything wrong in the procedure.
