### ISSUE TITLE
[2.0.12] ui-gmap-markers not seeing marker property changes.

### ISSUE THREAD

**Issue by jreeter** [angular-ui/angular-google-maps#1097]
It seems that using the ui-gmap-markers directive doesn't see or update the markers on the map when you update marker options.

In this example using **ui-gmap-markers**: http://plnkr.co/edit/Xrdr4zbYd25ftvLZ8W8d?p=preview  the markers get assigned an animation property randomly but they do not animate when it's assigned.

However, it seems using **ui-gmap-marker** works and updates the markers on map correctly: 
http://plnkr.co/edit/Pf31MaCWaJExmkprO2TM?p=preview

**Comment by nmccready** [comment]
This is due to the fact that currently when it checks for differences in the existing array it looks for coords differences only. I am working on a fix. Also this is a relevant to another ticket which sort of makes this a dupe.

**Comment by nmccready** [comment]
#1075 dupe

**Comment by nmccready** [comment]
Continue conversation there.
