### ISSUE TITLE
bounds parameter in `google-map` not working?

### ISSUE THREAD

**Issue by hanfeisun** [angular-ui/angular-google-maps#1099]
The DEMO can be viewed in Plnkr:  http://plnkr.co/edit/xBw6SAAIgezpvp9ndMbP?p=preview

In the document, I saw the description of `bounds` parameter is:

Fit the map in the specified bounds. The expression must resolve to an object having both northeast and southwest properties. Each of those properties must have a latitude and a longitude properties

I set the bounds in scope:

    $scope.bd = {
      northeast: {
        latitude: 51.219053,
        longitude: 4.404418
      },
      southwest: {
        latitude: -51.219053,
        longitude: -4.404418
      }
    }

And used it in directive like this:

    <ui-gmap-google-map bounds="bd" center="map.center" zoom="map.zoom" draggable="true" options="options"></ui-gmap-google-map>

But it seems that there is no effect.. the map is not fitted in my specified bounds.. Does that mean the bounds parameter is not working?

**Comment by nmccready** [comment]
Put some breakpoints in and get back to me. 
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/map.coffee#L248-L256

**Comment by nmccready** [comment]
Its because of a race condition at start. Your telling it to have a center and bounds and it doesnt know which to go to first. If you delay the bounds initialization it works fine.

http://plnkr.co/edit/LboSB7DcJAlFK7lZ1Ir0?p=preview

**Comment by hanfeisun** [comment]
Thanks, nmccreadady.  As I understand, the `center` and `zoom` parameter is meaningless if I want the map  to fit to `bound`, is it right? But if I don't specify the `center` and `zoom` parameter, the `ui-gmap` will not be rendered at all.. Is there anything I can do to specify `bound` only (skip `center` and `zoom`) and still display the map correctly?

**Comment by cthrax** [comment]
You could pass an initial center and zoom as well as an empty bounds, then $watch the bounds and set them to the desired value on first change. (bounds will be set once the map is loaded).

**Comment by tsareg** [comment]
So why this actually was closed? timeout is not guaranteed to work and watching for events is not a superb solution.

**Comment by nmccready** [comment]
@tsareg are stating you want to work on it? By all means if you want to I will re-open.
