### ISSUE TITLE
Customized function for google.maps.circle (Circle Directive)

### ISSUE THREAD

**Issue by trence** [angular-ui/angular-google-maps#1102]
does angular-google-maps support google.maps.MVCObject? I couldn't found a way to implement distance widget for Circle Object(google.maps.Circle) which require the support of google.maps.MVCObject.

Google maps documentation: https://developers.google.com/maps/articles/mvcfun

**Comment by nmccready** [comment]
What is your scenario. I need more input. It really depends on the scenario. In the end your binding to plain old javascript properties and or arrays. So if you use it in that manner then yes it should work. 

If your asking if we are doing any fancy binding and using MVCObject like google intended to drive ui-gmap then the answer is no. MVCObject is overkill especially for what angular already provides you.

**Comment by trence** [comment]
Thanks for your reminder. Sorry that i'm still a newbie here.
However, i would like to know that whether i could provide customize function (e.g. distance calculation) that bind to the google.maps.circle? (Circle directive)

**Comment by trence** [comment]
I found that I could do some trick over the events callback for Circle object.
Thanks @nmccready. Sorry for bothering you.

**Comment by nmccready** [comment]
Cool, I'd love to to see your example it is still hard to figure out what you originally intended.
