### ISSUE TITLE
Performance issue when I embed videos by <iframe> within  <ui-gmap-window>

### ISSUE THREAD

**Issue by hanfeisun** [angular-ui/angular-google-maps#1106]
I have 20 markers on GoogleMap and each marker is related to one video. Therefore, in every `<ui-gmap-window>`, I add a `<iframe>` tag whose `src` is a page contains a flashplayer like this (https://www.youtube.com/embed/6RdrGWWc_4s).  

However, I found this approach affects the performance a lot because the main page will preload the src of every `<iframe>` before the `window.onload` is triggered . It will be great if `<iframe>` tag will not be created at all until I click a marker on Google map.

**Comment by nmccready** [comment]
This depends a lot on how your doing things. My guess is your nesting window in marker. Therefore yes you are preloading it. However, stated in many places there is no requirement to do things that way. Instead have window as a standalone and turn the window on and off as you see fit based on clicking on the marker.  Your other option is to us ng-if wrapped around the iframe.

**Comment by nmccready** [comment]
If this does not solve your problem; then please post how your using this via a plnkr or some code. I will re-open upon that.

**Comment by hanfeisun** [comment]
Thanks! @nmccready

The sample code can be viewed at http://plnkr.co/edit/OdilSR7crYNdRSAlp7mv?p=preview

I embed a `<iframe>` youtube video within `ui-gmap-windows` contained by `ui-gmap-markers`, as can be seen in the picture below, the content of `<iframe>` (6RdrGWWc_4s) blocked the loading of whole page.. Is there a way to delay the `<iframe>` loading inside `ui-gmap-windows`?



![screen shot 2015-01-23 at 10 54 02 am](https://cloud.githubusercontent.com/assets/922081/5869109/74faa302-a2ee-11e4-9245-cc9710e1431b.png)

**Comment by hanfeisun** [comment]
I also found it needs to click a marker twice to make the youtube window appear in the demo above..

**Comment by hanfeisun** [comment]
@nmccready Is it possible for my demo in plnkr above to be modified to be more efficient...

**Comment by nmccready** [comment]
Like this.. did you even try this way? It is described in many spots.

http://plnkr.co/edit/ClS4yROBDl6NJX5WkaDA
