### ISSUE TITLE
Info windows created with the ui-gmap-windows directive do not (sometimes) size correctly

### ISSUE THREAD

**Issue by joukosaastamoinen** [angular-ui/angular-google-maps#1112]
Click the map marker to see the info window.

On Chrome/OS X and Firefox/OS X the text overflows the info window.

I could not pin down the exact circumstances, but the bug is quite easily reproducible with long words in the info window content:
http://plnkr.co/edit/MNVdW7kl4VQqrhWfYvm5?p=preview

**Comment by nmccready** [comment]
Yeah you need to use css to fix it. It is quite possibly bootstrap interfering with it.

**Comment by nmccready** [comment]
Thats what [this](https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/stylesheets/gwin-size-fix.css) is for
