### ISSUE TITLE
fit=true not working

### ISSUE THREAD

**Issue by Morriz** [angular-ui/angular-google-maps#1115]
Hi, I have a map with a ui-gmap-markers cluster that never seem to draw with the cluster in bounds. See the code below. I see the tilesReady event fire before the markers are put on the screen. Race condition in your code? Is there an event that triggers when the cluster is done drawing? So that the setBounds call can be done at the right time? TIA
```
        <ui-gmap-google-map control="map"
                            center="map.center"
                            zoom="map.zoom"
                            draggable="true"
                            pan="true"
                            events="map.events"
                            bounds="map.bounds"
                            fit="true"
                >
            <ui-gmap-markers control="markers"
                             models="quest.waypoints"
                             coords="'self'"
                             events="markers.events"
                    >
                <ui-gmap-windows show="show">
                    <div ng-non-bindable>{{ id }}</div>
                </ui-gmap-windows>
            </ui-gmap-markers>
            <ui-gmap-marker control="marker"
                            coords="quest.location"
                            title="quest.title"
                            idkey="'id'"
                    >
                <ui-gmap-window show="show">
                    <div>{{ quest.title }}</div>
                </ui-gmap-window>
            </ui-gmap-marker>
        </ui-gmap-google-map>
```

**Comment by nmccready** [comment]
There is no fit attribute on the map directive fit is only for markers or things you want your bounds to adjust too.

**Comment by nmccready** [comment]
Did u try it on markers?

**Comment by Morriz** [comment]
I managed to get it to work with fit="true" on the marker cluster, jay!

On a side note: in order to retain the initial bounds, could you expose that somehow? By enrichment or some event perhaps?

Thanks for all the hard work!

**Comment by nmccready** [comment]
That's something you should do in your controller. At some ui-gmap could add a basic controller as a factory for users to extend.

**Comment by nmccready** [comment]
Please note #1028

**Comment by nmccready** [comment]
Can you make your request for initial bounds another ticket please? I will close this ticket as it seems to be resolved.
