### ISSUE TITLE
DrawingManager and Polygons

### ISSUE THREAD

**Issue by ElectricMaxxx** [angular-ui/angular-google-maps#1119]
Hi,

i am trying to get drawed polygons out of the map to persist them. But this does not really work.

Got the following directive with its options:

```
                <ui-gmap-google-map events="map.events" center="map.center" zoom="map.zoom" draggable="true" options="map_options">
                    <ui-gmap-drawing-manager options="drawingManagerOptions"
                                             control="drawingManagerControl"></ui-gmap-drawing-manager>
                    <ui-gmap-polygon
                            static="polygon.option.static"
                            ng-repeat="polygon in map.polygons track by polygon.id"
                            path="polygon.path"
                            stroke="polygon.option.stroke"
                            visible="polygon.option.visible"
                            geodesic="polygon.option.geodesic"
                            fill="polygon.option.fill"
                            editable="polygon.option.editable"
                            draggable="polygon.option.draggable"
                            ng-cloak="">
                    </ui-gmap-polygon>
                </ui-gmap-google-map>
```
The map and existing polygons are displayed very well, but drawing new ones does not.
That are my drawing options:

```
            DEFAULT_POLYGON_OPTION = {
                stroke: {color: '#ffff00', opacity: 1, weight: 3 },
                editable: true,
                zIndex: 1,
                fill: {color: '#eeac1a', opacity: 0.75},
                static: false
            },
            DEFAULT_MAP_CONTROL_OPTIONS = {
                zoomControlOptions: {
                    position: google.maps.ControlPosition.LEFT_CENTER
                },
                panControlOptions: {
                    position: google.maps.ControlPosition.LEFT_CENTER
                }
            },
            DEFAULT_DRAWING_MANAGER_OPTIONS = {
                drawingMode: google.maps.drawing.OverlayType.POLYGON,
                drawingControl: true,
                drawingControlOptions: {
                    position: google.maps.ControlPosition.TOP_CENTER,
                    drawingModes: [
                        google.maps.drawing.OverlayType.POLYGON
                    ]
                },
                polygonOptions: DEFAULT_POLYGON_OPTION
            }
```
Those are going directly into the scope object. As said the existing ones are fine and cool, they got the color i whant them to have and the other options too. 

When drawing new ones my polyongs do have a different color - ok, i can live with that, but it looks like the drawing options arn't really in sync with the new polygon or the other way around.

The other problem is the data of the new polygon. As the google docs are saying: 

"Options to apply to any new polygons created with this DrawingManager. The paths property is ignored, and the map property of a new polygon is always set to the DrawingManager's map."

So i tried to get them by the ` polygoncomplete` event. I needed the drawing manager object for that so i tried:

```
                 uiGmapGoogleMapApi.then(function(maps) {
                    google.maps.event.addListener(maps.drawing.DrawingManager, 'polygoncomplete', function(polygon) {
                        var path = polygon.getPath();
                        map.polygons.push(path);
                    });
                });
```

and the same for the `getDrawingManager()` function on the `drawingManagerControl` object. Nothing happens.

**Comment by ElectricMaxxx** [comment]
OK ... moved the complete application to an own implementation with direct usage of the google maps api. thanks.

**Comment by sushantkr17** [comment]
I am facing the same problem. How you have solved this ? Can you please share some part of your code.

**Comment by nmccready** [comment]
So I don't think the drawing manager is really setup to have binding of the polygons out of it yet. Also you could add the same control functionality to get access to the gObject as well. None of this is rocket science and can be copied or extended from other parts of the code base.

The Freedrawmanager does have some simple binding going on and some logic could be copied from there.

**Comment by ElectricMaxxx** [comment]
yea that's it. I solved the problem by letting this module go and implementing my own service wchich uses the the google maps api directly. I don't get the databinding by that, but i hooked into several maps events and refreched my data. By doing that i fetched the polygons from the map while saving and everything was fine. 
In the google api drawing a polygon and displaying it by throwing polygons on the map is nearly the same and coupled.

**Comment by sushantkr17** [comment]
Thank you very much. It worked for me

**Comment by nmccready** [comment]
@ElectricMaxxx why not contribute instead of letting go? You can always try and make it better. I can't always respond on demand. Remember this is free.

**Comment by ElectricMaxxx** [comment]
Yea this is normally my way, but needed a fast and quick solution for a customer product. The second reason was my low angular experience at that moment.

**Comment by nmccready** [comment]
No worries, feel free to dig in later.
