### ISSUE TITLE
Support for Google Maps API for Work

### ISSUE THREAD

**Issue by smaye81** [angular-ui/angular-google-maps#1121]
Is there support for the Google Maps API for Work?  I noticed that in your configuration example, there is a place to put an API key, but Google Maps for Work provides a client ID and a crypto-signing key which do not work the same way as appending an API into the URL.  

Just wondering if this supports that approach in anyway because I can't find documentation stating it does.

**Comment by cthrax** [comment]
I'm not familiar with using Google Maps API for Work, so we'd need a little more to go on to be sure. However, if it's something you do after the maps API is loaded, there a promise you can attach to to configure it. You can also pass any query parameter you want by configuring the provider as demonstrated in the example.

If that doesn't help, I'd need an example of how you interact with the Work version.

**Comment by smaye81** [comment]
Actually, it looks like you might support it, although I'm not sure if this is intended or not.

To use Google Maps for Work, you specify your client ID in the URL requests rather than an API key:

https://developers.google.com/maps/documentation/business/clientside/auth

However, if I config my app module with a property of 'client' and use my signing key instead of an API key, I noticed this gets sent in the initial call to Google Maps:

```
app.config(['uiGmapGoogleMapApiProvider', function (GoogleMapApi) {
	GoogleMapApi.configure({
		client : 'mykey',
		v: '3.17',
		libraries: 'weather,geometry,visualization'
	});
}]);
```

I get an error message saying I am not authorized to use my client ID from my current URL, but that is expected since that is configuration I need to do on my side.

Any idea if this is intended behavior or just a side effect of appending the entire object I pass to 'configure' to the query string in the initial maps call?

**Comment by cthrax** [comment]
It is intended behavior.  We take the configuration object verbatim to create queryParameters and we wanted to leave room for unexpected query params.
