### ISSUE TITLE
marker cluster errors, but only sometimes

### ISSUE THREAD

**Issue by Morriz** [angular-ui/angular-google-maps#1123]
I get errors sometimes, but only in mobile Safari (race condition?):

Error: undefined is not an object (evaluating 'scope.models.length')
didQueueInitPromise@http://192.168.1.111:8100/lib/angular-google-maps/dist/angular-google-maps.js:1379:27
createMarkersFromScratch@http://192.168.1.111:8100/lib/angular-google-maps/dist/angular-google-maps.js:4144:39
http://192.168.1.111:8100/lib/angular-google-maps/dist/angular-google-maps.js:4024:68
MarkersParentModel@http://192.168.1.111:8100/lib/angular-google-maps/dist/angular-google-maps.js:4084:40
http://192.168.1.111:8100/lib/angular-google-maps/dist/angular-google-maps.js:6576:49
processQueue@http://192.168.1.111:8100/lib/angular/angular.js:13175:29
http://192.168.1.111:8100/lib/angular/angular.js:13191:39
$eval@http://192.168.1.111:8100/lib/angular/angular.js:14388:28
$digest@http://192.168.1.111:8100/lib/angular/angular.js:14204:36
http://192.168.1.111:8100/lib/angular/angular.js:14427:33
completeOutstandingRequest@http://192.168.1.111:8100/lib/angular/angular.js:4902:15
http://192.168.1.111:8100/lib/angular/angular.js:5282:33
angular.js:11835Error: undefined is not an object (evaluating 'parentModel.gMarkerManager')
http://192.168.1.111:8100/lib/angular-google-maps/dist/angular-google-maps.js:6574:41
$digest@http://192.168.1.111:8100/lib/angular/angular.js:14230:31
http://192.168.1.111:8100/lib/angular/angular.js:14427:33
completeOutstandingRequest@http://192.168.1.111:8100/lib/angular/angular.js:4902:15
http://192.168.1.111:8100/lib/angular/angular.js:5282:33
angular.js:11835Error: undefined is not an object (evaluating 'newValue.length')
http://192.168.1.111:8100/lib/angular-google-maps/dist/angular-google-maps.js:4070:29
$digest@http://192.168.1.111:8100/lib/angular/angular.js:14230:31
http://192.168.1.111:8100/lib/angular/angular.js:14427:33
completeOutstandingRequest@http://192.168.1.111:8100/lib/angular/angular.js:4902:15
http://192.168.1.111:8100/lib/angular/angular.js:5282:33
angular.js:5021

**Comment by nmccready** [comment]
I'm going to need more context via an example.

**Comment by ddegasperi** [comment]
I had exactly the same problem. I've tried the "markers" example from the API documentation, but my mistake was to use the ng-controller attribute on the ui-gmap-google-map. After moving the ui-gmap-google-map directive into a div with the ng-controller attribute it worked for me.

**Comment by Morriz** [comment]
Tnx. I assume "outside of the div" in your latter sentence ;)

Anyway, the current solution sometimes times out, and forgets to enrich the stubs given in the attributes. It's unreliable and leads to errors.

**Comment by ddegasperi** [comment]
Sry, you're right. For better comprehension here my code:

The following code works for me:
```html
<div id="map-canvas" ng-controller="GoogleMapsController as gmapCtrl">
    <ui-gmap-google-map center="map.center" zoom="map.zoom" draggable="true" options="options" bounds="map.bounds">
        <ui-gmap-markers models="randomMarkers" coords="'self'" icon="'icon'">
        </ui-gmap-markers>
    </ui-gmap-google-map>
</div>
```

The following code didn't work and throwed the same errors:
```html
<ui-gmap-google-map center="map.center" zoom="map.zoom" draggable="true" options="options" bounds="map.bounds" ng-controller="GoogleMapsController as gmapCtrl">
    <ui-gmap-markers models="randomMarkers" coords="'self'" icon="'icon'">
    </ui-gmap-markers>
</ui-gmap-google-map>
```

**Comment by nmccready** [comment]
@Morriz you need to produce an example with the problems. I am using this directive and I have no issues other than the one's slated to be fixed for 2.0.13.

**Comment by Morriz** [comment]
Sorry about the late reply, but I believe the problem is solved now. Since the last update I don't see it anymore.

It's would still be more than preferable to offer some callbacks / events to notify the users of the 'whatever we try to render asynchronously is ready now' moments, like when your code finished rendering a cluster of markers...don't you think? It's kind fire and forget now, no way to know when your code does anything...

**Comment by nmccready** [comment]
If there are callbacks in MarkerClustererPlus then it can be added. Otherwise it will have to be hashed into MarkerClusterPlus. If you would like this feature feel free to work on it and PR it. You might want to make a new soley ticket for this.
