### ISSUE TITLE
ngClick in InfoWindow

### ISSUE THREAD

**Issue by bwasnie1** [angular-ui/angular-google-maps#1128]
Hi there!

I am facing the problem, that I can't bind ngClick inside an InfoWindow. I want to fire a function, when I click on a specific element inside the InfoWindow.

My code looks like this (Jade):

```
ui-gmap-markers(models='markers', coords='"self"', icon='"icon"')
    ui-gmap-windows(ng-cloak)
        .gmap-info-window(ng-non-bindable)
            .gmap-info-window-image
                img(src='{{image}}')
            .gmap-info-window-content
                strong {{local}}
                div {{title}}
```

I know that 'ng-non-bindable' ignores everything inside that element. Do you have a clue?

-------
Update

Okay, I found out how to fire ngClick:

```
div(ng-controller='OffersCtrl')
  a(ng-click='showOffer(id)')
    .gmap-info-window(ng-non-bindable)
      .gmap-info-window-image
        img(ng-if='image', src='{{image}}')
      .gmap-info-window-content
        strong {{local}}
        div {{title}}
```

But now I have another problem. I cannot pass a parameter from the marker object to the ngClick function.

**Comment by gitnik** [comment]
Can you open a plunker? Would make things a lot easier

**Comment by nmccready** [comment]
You should use templating for InfoWindow instead. It is way more powerful. Look at the examples for templateParameter and templateUrl. It also requires a controller dedicated for the window itself.

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/example/example.html#L66-L70

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/example/example.html#L81-L85

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/example/issue-1056-ng-show-window.html#L22-L23

**Comment by gigmaps** [comment]
just a point that ng-click this doesn't work in InfoBox due to the way the contextmenu is handled...

**Comment by nmccready** [comment]
PR it, so I can see line by line comparisons.

**Comment by gigmaps** [comment]
PR created
to be fair - it seems like ng-click was working ok with "ignoreHandler" - turns out we had one errant ng-click function in the main controller instead of the infowindow template controller...

however, using `cancelHandler` instead of `ignoreHandler` for `contextListener_` does have the advantage of being able to inspect the infoBox on right click... (invaluable during build) and still prevents propagation of click event up to the map.
