### ISSUE TITLE
Windows doesn't seem to be watching the show variable

### ISSUE THREAD

**Issue by jawache** [angular-ui/angular-google-maps#1130]
This works fine with Window but with Window>>s<< no matter the value of 'show' it doesn't seem to open/close the InfoWindow, i've created a quick gif to show.

http://recordit.co/qGstvDVeay

This is using the official plunker from the windows example in the docs, i've just wrapped the onClick code with $scope.$apply and setup an alert.

**Comment by jawache** [comment]
I suspect this might just be a documentation issue.

Created a plunker that works: http://plnkr.co/edit/QMA254wAAHC9clnnPKXR?p=preview

The 'show' variable doesn't not seem to be watched or have any input into whether the InfoWindow is displayed. 

Only the visible attribute of the window options object has an effect....

**Comment by nmccready** [comment]
Your example shows options.visible to work; but it would be better to show , "show" being broken.

**Comment by nmccready** [comment]
Appears to be working fine to me; http://plnkr.co/edit/gtJ7YiaW91R53xc2349q

**Comment by jawache** [comment]
Hia,

Created a vid to show you what i'm seeing: https://www.youtube.com/watch?v=hBMfwegfyuM&feature=youtu.be

Cheers,

Asim

**Comment by nmccready** [comment]
Ok, gothca I see the difference now.

**Comment by nmccready** [comment]
So this works as desired when you remove the $apply .
http://plnkr.co/edit/gtJ7YiaW91R53xc2349q?p=preview

**Comment by nmccready** [comment]
So i think this is ok.
