### ISSUE TITLE
Same Lat Long Markers on click causes cluster to hide markers

### ISSUE THREAD

**Issue by pipecomo** [angular-ui/angular-google-maps#1131]
If more than 2 markers have exactly the same lat and long the cluster does not display the markers. There needs to be a method to accommodate more than 1 marker at the exact same lat long within the map cluster click function

**Comment by nmccready** [comment]
Yes there is, you need to read into the configuration options on markerclusterer itself.

**Comment by nmccready** [comment]
You can change the calculation and the minimum distance to start clustering. Lastly, if you have two items in the same spot.. well for that zoom level you shouldn't be using clustering.  We hope to pull in marker spiderfier as that would be useful for that situation. But also there is nothing preventing you from digging into the code and contributing back.

**Comment by nmccready** [comment]
http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.16/docs/reference.html
