### ISSUE TITLE
Wrong check for latitude AND longitude in maybeCoords in map.coffee

### ISSUE THREAD

**Issue by serioushaircut** [angular-ui/angular-google-maps#1133]
On latest commit in branch develop (08f077e5a597c2b700f014c8e6e94cec0c1b6db5), as well as on master.

The maybeCoords check in file
https://github.com/angular-ui/angular-google-maps/blob/develop/src/coffee/directives/api/map.coffee
in line: 197
    
    if maybeCoords?.latitude? and maybeCoords?.latitude?
    
should check for longitude the second time, right?!
Cheers
SH

**Comment by nmccready** [comment]
Yes thank you, nice catch.

**Comment by nmccready** [comment]
done
