### ISSUE TITLE
TypeError: cannot read 'push' of undefined when adding a circle to the map

### ISSUE THREAD

**Issue by SamVerschueren** [angular-ui/angular-google-maps#1142]
Hi

I added a ui-gmap-circle to the map and got the following error
```
TypeError: cannot read 'push' of undefined
```

I traced down the issue and the issue is in the file ```directives/api/models/parent/circle-parent-mode.coffee``` (https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/parent/circle-parent-mode.coffee). 

At line 32, the events object is being retrieved and at line 34 a listener is added. But if you didn't provide an events object to the ```ui-gmap-circle``` directive, the listeners array is undefined and you try to push a listener to an undefined list. This will cause the error I got.

The documentation also states that the events attribute in the directive is optional (http://angular-ui.github.io/angular-google-maps/#!/api). So we should add an extra check first if listeners is undefined or not.

If I find some time, I might add a pull request for this issue.

**Comment by nmccready** [comment]
What version are you working against? I just made changes to circle 2 or so days ago on master.

**Comment by SamVerschueren** [comment]
I am working with the one provided in the quickstart (https://raw.githubusercontent.com/angular-ui/angular-google-maps/master/dist/angular-google-maps.min.js). I added it today so it will be the version from yesterday.

**Comment by SamVerschueren** [comment]
I made a plunkr to show the output. You can find it here http://plnkr.co/edit/B6CRPgQDU0o8qQDHNA8g.

When you run it and then open the console, you will see the error message:
```
 TypeError: Cannot read property 'push' of undefined
    at new CircleParentModel (angular-google-maps.js:3656)
    at angular-google-maps.js:5685
    at deferred.promise.then.wrappedCallback (angular.js:11682)
    at angular.js:11768
    at Scope.$get.Scope.$eval (angular.js:12811)
    at Scope.$get.Scope.$digest (angular.js:12623)
    at angular.js:12849
    at completeOutstandingRequest (angular.js:4411)
    at angular.js:4725
```

**Comment by nmccready** [comment]
should be fixed http://plnkr.co/edit/63hSw89tfK6vOMULYHiQ
