### ISSUE TITLE
Switch Lat/Long for Point Coordinates

### ISSUE THREAD

**Issue by mikenikles** [angular-ui/angular-google-maps#1145]
Hey,

There seems to be a bug at https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/utils/gmap-util.coffee#L31 where lat/long are mixed up. See http://geojson.org/geojson-spec.html#id2.

Simply changing line 31 to `new google.maps.LatLng(value.coordinates[0], value.coordinates[1])` should fix the issue.

Cheers,

Mike

**Comment by nmccready** [comment]
I am not sure how to go about this as if this is the spec, then it Postgres is wrong they are revered in postgis. @rickhuizinga any ideas?

**Comment by nmccready** [comment]
@mikenikles I think your code base has them reversed as you can see here lat bounds are +-90 and Long is +-180. In the spec you sent me all the first coords in the array are mostly > 100, therefore long.
so `new google.maps.LatLng(value.coordinates[1], value.coordinates[0])` stands
