### ISSUE TITLE
performance problem polygon editing with many points is verry slow

### ISSUE THREAD

**Issue by svycka** [angular-ui/angular-google-maps#1146]
for example http://angular-ui.github.io/angular-google-maps/#!/demo try to edit and add more corners to polygon about 50 is enough I think. Editing becomes imposibble and if I add even more entire polygon stops rendering at all. with 100% cpu on chrome

**Comment by nmccready** [comment]
Polygon? or Polygons.. if your using ng-repeat then you need to siwtch.

**Comment by svycka** [comment]
@nmccready I have tested it with ng-repeat but just one polygon as in example above

**Comment by nmccready** [comment]
Ahh, well editable does slow stuff down significantly. It how is the behavior with editable in pure google maps? Anyways I would limit editing if I were you. The slow down with editing would be with the arraysync code.

**Comment by nmccready** [comment]
Sorry, I didn't read your problem thorough enough (half fallen asleep I guess).  So the slow down has to be here. To be honest I am not the most familiar with this [code](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/utils/array-sync.coffee). @rickhuizinga and @nlaplante are more familiar with it then I am. I can look but if you can dig into it, it would be appreciated.

**Comment by nmccready** [comment]
You might be better off turning static on and then getting the gObject from control (in polygons). Then you can get the paths directly from that. This way the watchers are off for array sync. My guess this would be way faster.

**Comment by nmccready** [comment]
updates?
