### ISSUE TITLE
Dynamically added markers shows 0 length on  `ui-gmap-markers` control object.

### ISSUE THREAD

**Issue by roylee0704** [angular-ui/angular-google-maps#1148]
As described above, markers will be dynamically assigned to models:

```html
<ui-gmap-markers 
models="ctrl.arrMarkers" 
control="ctrl.markers.control" 
click="'onclick'" 
icon="'icon'" 
options="'options'">
</ui-gmap-markers>
```

But after that when I'm trying to access the marker controls, it shows the following on console.log:

```js
{getChildMarkers: function, 

getGMarkers: function () {arguments: [Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them]get arguments: function ThrowTypeError() { [native code] }set arguments: function ThrowTypeError() { [native code] }caller: (...)get caller: function ThrowTypeError() { [native code] }set caller: function ThrowTypeError() { [native code] }length: 0name: ""prototype: angular.module.factory.Markers.link.scope.control.getGMarkers__proto__: function Empty() {}
```

---

On top of that ,It shows 0 length, notice also on argument of both functions: getChildMarkers and getGMarkers, I received the following error:
`[Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them]`

---

Question: Is there anything that I've missed out? How can I access markers control, as I would like to use google marker api.

**Comment by nmccready** [comment]
So what resolved this?
