### ISSUE TITLE
best way to access map.control functions from ui-gmap-map-control controller

### ISSUE THREAD

**Issue by gigmaps** [angular-ui/angular-google-maps#1153]
struggling to get a `ui-gmap-map-control` accessing the main map controller `$scope.map.control.` functions
other than using a rather _brittle_ method of `$scope.$parent... x 4`
eg
`$scope.$parent.$parent.$parent.$parent.map.control.refresh({latitude: 32.779680, longitude: -79.935493});`

**Plunker** is here: http://plnkr.co/edit/GcTp5HLWYCnYdwqqOZHy?p=preview

Is there a more robust method of using the API functions (other than using std google.maps methods) ?

Methods I've tried
- using a $controller 'mixin' (ie `$controller('mainCtrl', {$scope: $scope});` within the `ui-gmap-map-control` controller)
the problem with this is that it forces the main controller to run again which causes an `undefined` error on $scope.map.control (since it's within the 'uiGmapIsReady' promise that has already returned the 1st time the controller ran)

see the Plunker console output : 

    start of mainCtrl  
    mainCtrl uiGmapIsReady has returned  
    uiGmapIsReady says map1 === map2 true  
    start of refreshMap  
    refreshMap uiGmapIsReady has returned  
    start of mainCtrl  
    refreshMap $scope $  
    mainCtrl uiGmapIsReady has returned  
    angular.js:11607 TypeError: undefined is not a function

notice how the `mainCtrl` runs twice... ?

- using an `angular.extend` - same problem as using `$controller`

- most robust method seems to be to use standard google.maps calls from within the child controller `uiGmapIsReady` promise (based on the map instance object returned)
ie `setCentre()` and `setZoom()` as a replacement for `refresh` etc

- defining the `ui-gmap-map-control` controller as being the main controller - obviously not a suitable method - as it makes the main controller run again after map load (with all sorts of errors and undesirable effects)

note that I'm using `uiGmapIsReady` in both the main and map-control controllers...
(it has to be used in the main controller or else it gives `undefined` when trying to define `map.control.getGmap()` prior to map ready)

what is the suggested approach ?

I realise this is partly an angularjs question - extending controller scopes etc - but it's related to the `uiGmapIsReady` function 
which is giving the `TypeError` when using the standard approaches suggested everywhere:
http://stackoverflow.com/questions/21483555
http://stackoverflow.com/questions/16539999
(please bear with me,  I can assure you I've spend a _hours_ of time reviewing the API, examples and SO)

also I haven't seen any examples in this repo using a `map.control` function within a `ui-gmap-map-control` button
search terms used :
- ui-gmap-map-control
- map.control.getGmap
- map.control.refresh
- map-control

**Comment by nmccready** [comment]
Why use another controller? Use a factory and or service and pass the existing scope on. Or communicate to controllers indirectly using broadcast or emit. There is tons of stuff on the internet on controller to controller communication.

**Comment by nmccready** [comment]
Ok you using another controller cause you need one for the map-control widgets. Yes the best method for communicating with the buttons is using emit or broadcast.

**Comment by gigmaps** [comment]
thanks for the reply
i believe i've covered most of the standard (direct) controller-controller $scope passing methods
I'll have a go at:
- using emit-broadcast 
- see if a factory/service is possible (or efficient)

as a (slight) aside, what was the `controller='{expression}'` of `ui-gmap-map-control` designed for if not to link the map-control to a controller ?

**Comment by nmccready** [comment]
```
app.config([ '$provide', ($provide) ->
  #recommended way of dealing with clean up of angular communication channels
  #http://stackoverflow.com/questions/11252780/whats-the-correct-way-to-communicate-between-controllers-in-angularjs
  $provide.decorator '$rootScope', [ '$delegate', ($delegate) ->
    Object.defineProperty $delegate.constructor::, '$onRootScope',
      value: (name, listener) ->
        unsubscribe = $delegate.$on(name, listener)
        @$on '$destroy', unsubscribe
        unsubscribe

      enumerable: false

    $delegate
]])
.config([ '$provide', ($provide) ->
```

**Comment by nmccready** [comment]
I just forgot about the map-control needing dedicated controllers. So yes in the end your broadcasts and emits will call a callback within the map controllers scope.

**Comment by gigmaps** [comment]
thanks - i'll try to wrap my head around emit-broadcast
got the basic concept - just need to apply it efficiently, once the map loads to have access to the widgets

**Comment by gigmaps** [comment]
the `map-control` object functions seem to work OK when the `$scope.map.control` is passed to a service function after the `uiGmapIsReady` promise returns
...not sure if this is the ideal solution but avoids using $rootscope & emit-broadcast etc

http://plnkr.co/edit/Yo8r50lGoAAenwLX1hlr?p=preview

**Comment by nmccready** [comment]
Yup that works as well. Several ways to skin a cat. nice
