### ISSUE TITLE
ui-gmap-markers control object functions missing in 2.0.12 ?

### ISSUE THREAD

**Issue by gigmaps** [angular-ui/angular-google-maps#1155]
trying to update the markers model  using a `ui-gmap-markers` map control function 
$scope.markerControl.updateModels(myMarkersArray)
but getting an `undefined` error for the `updateModels()` function

when I output my map-control object to console it looks like this:
`Object {getGMarkers: function, getChildMarkers: function}`

which looks more like what's expected from the `ui-gmap-marker` control object ?

...and doesn't seem include _any_ of the `ui-gmap-markers` control functions mentioned in the docs:
- getPlurals()
- updateModels()
- newModels()
- clean()
- getManager()
- hasManager()
- managerDraw()

I notice the API docs say that this is from 2.0.13 onwards, however the functions already exist in 2.0.12 :
https://github.com/angular-ui/angular-google-maps/blob/master/dist/angular-google-maps.js#L6656-L6689

Are these `ui-gmap-markers` to be included in the next release - or am I missing something ?

PS I'm definitely using `ui-gmap-markers` and not `ui-gmap-marker`...
PPS by comparison my $scope.map.control object looks like this:
`Object {refresh: function, getGMap: function, getMapOptions: function, getCustomEventListeners: function, removeEvents: function}`
...ie more functionality than the API docs suggest - which is more what i'd expect - rather than having the docs ahead of the code :-)

**Comment by nmccready** [comment]
Are you making sure to access the control object after isReady or GoogleMapApi is called. Remeber the control gets slapped on by the directive and it is not immediate. So you should delay your interaction with it.

**Comment by nmccready** [comment]
Your statement that 2.0.12 has the same Plurals functionality is incorrect.

https://github.com/angular-ui/angular-google-maps/blob/2.0.12/src/coffee/directives/api/plural.coffee
vs
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/plural.coffee

https://github.com/angular-ui/angular-google-maps/blob/2.0.12/src/coffee/directives/api/markers.coffee
vs
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/markers.coffee#L35

**Comment by gigmaps** [comment]
you're right it is working - at least in this plunker
http://plnkr.co/edit/3itoozzntXxDPnpXA7j5?p=preview

i'm defining it (both in the plunker and my app) within the `uiGmapIsReady` promise return - and passing the object to a service (as per my map-control solution of yesterday)

unsure why my app is _not_ working for marker-control object while map-control object comes out fine
...either way it's at my end and thanks for the quick response !

PS wasn't trying to compare particular functions - just noting that the markers control functions were all in the 2.0.12 release - even though the docs says `New in v2.0.13` (which hasn't been released yet)

**Comment by nmccready** [comment]
Ok, I think the disconnect that the control functions were there but they have been renamed in 2.0.13. They are now across the board for all plural directives with all with the same interface.

**Comment by nmccready** [comment]
So this can be closed?

**Comment by gigmaps** [comment]
yes thanks !

**Comment by gigmaps** [comment]
just to close this out more thoroughly:
if you're using the release version 2.0.12 of `angular-google-maps` 
(ie `//rawgit.com/angular-ui/angular-google-maps/2.0.12/dist/angular-google-maps.js` )
the marker control functions _*won't*_ work:
http://plnkr.co/edit/UhcCQRNDlNUafJ53LsDl?p=preview

if you're using the latest `master/dist` -  _after_ version 2.0.12
(ie `//rawgit.com/angular-ui/angular-google-maps/master/dist/angular-google-maps.js` )
the marker control functions *_will*_ work
http://plnkr.co/edit/UhcCQRNDlNUafJ53LsDl?p=preview

so the docs are correct in saying `New in v2.0.13` :-)

**Comment by nmccready** [comment]
Right, I am in the process of pushing 2.0.13 documentation . Maybe I should of held off. Until the version was out. My bad.

**Comment by gigmaps** [comment]
no it's all good :-)  
glad i knew about the control functions ahead of time - perfect for what i need to do
