### ISSUE TITLE
labelAnchor is reset to 0,0 when the Marker coords are changed

### ISSUE THREAD

**Issue by markygab** [angular-ui/angular-google-maps#1157]
Hi, having this issue with marker labels. You can reproduce it on your demo map by dragging a marker with the label drag me.
Also noticed that the syntax is labelAnchor: "50 60" when i think it should be labelAnchor: new google.maps.Point(50, 60). This had me in a puzzle for ages.

**Comment by sime** [comment]
Yes! I have had that issue, and found it impossible to update a labelAnchor.

http://plnkr.co/edit/8tYzhEOwfWRVIpeOuCnb

If the last uses google.maps.Point() rather than a string. The labelAnchor can be updated.

**Comment by nmccready** [comment]
If you have identified the problem please submit a PR.

**Comment by markygab** [comment]
Not sure what a PR is, but its fixed by checking the type of the anchor in the getLabelPositionPoint function. See:

        getLabelPositionPoint: function(anchor) {
          if (anchor instanceof google.maps.Point) return anchor; // new line
          var xPos, yPos;
          .....

**Comment by nmccready** [comment]
PR is pull request IE improving the code base and taking credit for it.

**Comment by juancolacelli** [comment]
When you overwrite the marker's options and you drag, zoom in or zoom out the map, "labelAnchor" is replaced by "0 0".

**Comment by nmccready** [comment]
Closed via #1178
