### ISSUE TITLE
Documentation bug on Firefox

### ISSUE THREAD

**Issue by fulup-bzh** [angular-ui/angular-google-maps#1158]
Sample HTML and Javascript are not visible on Firefox when they work on Chrome. [Firefox 3.5 with OpenSuse 13.2]

For example on marker API page: http://angular-ui.github.io/angular-google-maps/#!/api

While main page is visible and sample map rendering works fine. If you click on HTML/JS it has no effect. Looks like some CSS are wrong. The display zone for HTML/JS is visible but is only 5mm hight with no contend.

**Comment by nmccready** [comment]
If you can find a fix please PR. Ive been trying to spend more time on the documentation but I need to start making priorities for other projects.

**Comment by nmccready** [comment]
Also PR against the website branch.

**Comment by nmccready** [comment]
I have no plans to support or fix that old of a browser.
