### ISSUE TITLE
Missing support for zIndex

### ISSUE THREAD

**Issue by sheoak** [angular-ui/angular-google-maps#1159]
I think the support for the zIndex option in [polylines](https://developers.google.com/maps/documentation/javascript/reference#Polyline) is missing:

    zIndex — number : The zIndex compared to other polys.

I have tested with 2 `<ui-gmap-polylines>` containing both a lot of paths values (>4000). The lines of the first tag are randomly over or behind the second. No idea why yet, but since I can’t set the z-index I can’t fix the issue. I will try to reproduce it and put it online.

**Comment by nmccready** [comment]
So polylines, and polygons no longer evaluate strings, try using an expression instead. Follow this code to debug https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/options/builders/common-options-builder.coffee#L44

**Comment by sheoak** [comment]
Thanks for the quick answer!

Not sure what you mean, I don’t see z-index option in angular-google-maps documentation?
I just realized I’m actually using polyline, not polyline**s**, sorry for the confusion.

I tried this but nothing happens:

    <div ng-repeat="polylines in config.polylines">
        <ui-gmap-polyline
            path="polylines.path"
            stroke="polylines.stroke"
            z-index="polylines.zIndex"
            static="true"
            fit="true">
     </div>

**Comment by sheoak** [comment]
The polylines stopped being randomly over/behind after updating to the last version. Not sure it’s related because I’ve updated many libraries. I do not need z-index anymore but it still doesn’t seem to be apply.

**Comment by nmccready** [comment]
I'll check this out with some specs if I can. But I may postpone this to 2.1.

**Comment by nmccready** [comment]
@sheoak did you dig anymore into this?

**Comment by sheoak** [comment]
@nmccready I couldn’t find what was really going on, I would need some more time, but that won’t happen before a while… I have the feeling that it happens when the CPU is overload but it’s hard to say. Sometimes the map is perfect, sometimes the polylines z-index just go crazy. I think the z-index attribute is useless in my case.

**Comment by nmccready** [comment]
OK well 2.1 has some time if you want to pursue this further we can. If you can come up with an example the exhibits the issue; that would be excellent.

**Comment by alexjoverm** [comment]
Same here, there is no z-index in the documentation, and even if you use it, the attribute is ignored. Please, it would be really nice to have this attribute working

**Comment by nmccready** [comment]
I think all that needs to be added is
`zIndex: '=zindex'`
[here](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/i-polyline.coffee#L17)

**Comment by nmccready** [comment]
I think this should resolve it a1c9383
