### ISSUE TITLE
Options 'scalescontrol: false' not taken in account ?

### ISSUE THREAD

**Issue by fulup-bzh** [angular-ui/angular-google-maps#1160]
I'm trying to configure my map, the option "mapTypeControl" works, but  'scalescontrol' does not ? Looking at google API/Doc I do not understand ?

As one option works, hopefully the error should not be a spelling error within my HTTP or JS file. Look like scaleControl is just ignored ?

Extract from my controller
```
var mapevents = { // Handler function(maps, events, optional google args)
            idle: scope.DisplayRoute // wait map to be idle before building route
};
scope.map = { 
            Center : {latitude: 47.6, longitude: -2.7},
            Zoom   : 8,
            Events : mapevents,
            Options: {
                rotateControl:  true,
                mapTypeControl: true,
                scaleControl:   false,
                mapTypeControlOptions: {style: maps.MapTypeControlStyle.DROPDOWN_MENU}
            },
            Control: {} // should exist and be empty!!! Will be replaced by map control object.
        };
```
My HTTP file. I use "controller as DisplayGMap' model.
```
<ui-gmap-google-map center="DisplayGMap.map.Center" zoom="DisplayGMap.map.Zoom" draggable="true" options="DisplayGMap.map.Options"  control="DisplayGMap.map.Control" events="DisplayGMap.map.Events" >

        <ui-gmap-marker coords="DisplayGMap.marker.coords" options="DisplayGMap.marker.options" events="DisplayGMap.marker.events" idkey="DisplayGMap.marker.id"></ui-gmap-marker>
        <ui-gmap-rectangle bounds="DisplayGMap.zone1Bounds" events="DisplayGMap.zone1Events" draggable="true" fill="'#FFFFFF .5'"></ui-gmap-rectangle>

    </ui-gmap-google-map>
```

**Comment by nmccready** [comment]
Please make a plunkr. Also DisplayGMap does not map to your controller.

**Comment by fulup-bzh** [comment]
DisplayGMap map my controller or nothing would work. I will check to reproduce the problem on a plunkr.

**Comment by fulup-bzh** [comment]
Sorry for the delay, this is my 1st plunkr and it was longer than expected to have something clean enough to make it public.  http://embed.plnkr.co/O3mFnm/preview

It you change map's options in DisplayGMapMod.js [line 45] you may check that "mapTypeControl" works when "scaleControl" or "rotateControl" does not.

**Comment by nmccready** [comment]
`DisplayGMapController as DisplayGMap` is what I thought you might be doing via routeProvider, but with the context you gave me prior, I could not tell. This is why plunkrs are so important.

**Comment by fulup-bzh** [comment]
I agree plunkrs is a nice tool, nevertheless as any tools it take sometime to get it right. Now that you can see full source code, any idea why mapTypeControl works and scaleControl does not ? Did I mess up somewhere in my code ?

**Comment by nmccready** [comment]
No not yet, I started digging into it and I got sidetracked by my real job. I would double check the google sdk for bugs on this as well. Cause there is nothing fancy we are doing against the options. But in the end walking through the code with break points on watches on options and center is where I would start.

**Comment by fulup-bzh** [comment]
Not a /angular-ui/angular-google-maps issue. I tried with google native call and it does not work either.

**Comment by nmccready** [comment]
Sorry I could not get to this in time. I will still try to look into this.
