### ISSUE TITLE
Undefined variables in /src/coffee/directives/api/managers/clusterer-marker-manager.coffee

### ISSUE THREAD

**Issue by panchenko** [angular-ui/angular-google-maps#1161]
Line 22: Logger.error msg

**Comment by panchenko** [comment]
Also optionsName in line 70: `$log.info "#{optionsName}: Clearing event: #{eventName} to clusterer"`

**Comment by nmccready** [comment]
where you working off of? I need context.

**Comment by nmccready** [comment]
Are you overriding the default logger? This should not be happening. Keep your issue down to one as your other reported is obviously the same problem. #1162

**Comment by panchenko** [comment]
The full context in #1162, master branch, undefined variables are `Logger` and `optionsName`

**Comment by panchenko** [comment]
Only `$log` is injected https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/managers/clusterer-marker-manager.coffee#L22

**Comment by panchenko** [comment]
`clearEvents` has only `(options)` as parameter https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/managers/clusterer-marker-manager.coffee#L70

**Comment by nmccready** [comment]
Ahh doh.. yes Logger should be $log my bad nice catch.

**Comment by nmccready** [comment]
If u want to submit a PR and take the credit please do so.

**Comment by nmccready** [comment]
This goes for both issues #1162 as well.
