### ISSUE TITLE
Undefined variable in src/coffee/directives/api/models/parent/rectangle-parent-model.coffee

### ISSUE THREAD

**Issue by panchenko** [angular-ui/angular-google-maps#1162]
Line 25
```javascript
if bound?
 $log.error "Invalid bounds for newValue: #{JSON.stringify scope.bounds}" #note if bouds is recursive this could crash
```

**Comment by nmccready** [comment]
where you working off of? I need context.

**Comment by nmccready** [comment]
master develop, specific version

**Comment by nmccready** [comment]
not sure how your getting this. 

https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/parent/rectangle-parent-model.coffee#L3-L5

It is defined via injection. Please make a plunkr.

**Comment by panchenko** [comment]
Sorry, I was not specific enough.
Context: we use the generated .js file in our project and IDE highlights some identifiers in red in that file :-) So I found the original .coffee files on the master branch and filed the issues.

`bound` is not defined here.

**Comment by nmccready** [comment]
Do you want to PR the fixes?
