### ISSUE TITLE
InfoWindows does not open at the first click on Chrome and App based on Chrome

### ISSUE THREAD

**Issue by ziobudda** [angular-ui/angular-google-maps#1165]
Hi, I'm using your module in my app based on angularjs (but I have the same problem in Chrome standard browser on my mac) with this html: 

<ui-gmap-google-map set-height center='map.center' zoom='map.zoom' data-tap-disabled="true">

            <ui-gmap-markers models="locations" coords="'self'">
                <ui-gmap-windows show="show">
                    <div ng-non-bindable>
                        <a href="">{{::title}}</a><br>
                        <img class="markerImg" src="{{::field_immagini}}">
                            <br><br>
                            <a href="#/tab/location/{{::id}}">Vai alla scheda</a>
                    </div>
                </ui-gmap-windows>
            </ui-gmap-markers>
        </ui-gmap-google-map>

and this JS: 

    $scope.map = { center: { latitude: 41.9, longitude: 12.4833333 }, zoom: 5 };
    $scope.locations = $localstorage.getObject('locations');
    angular.forEach($scope.locations,function(v,k) {
        $scope.locations[k].id = k;
        $scope.locations[k].longitude = $scope.locations[k].locationsZB.coordinates[0];
        $scope.locations[k].latitude = $scope.locations[k].locationsZB.coordinates[1];
        $scope.locations[k].icon = $scope.locations[k].field_immagini;
        $scope.locations[k].show = false;
        $scope.locations[k].onClick = function() {
            console.log("Clicked!");
            $scope.locations[k].show = !$scope.locations[k].show;
        };

    });

The problem is that the infowindow is not opened at the first click, but at the second or third.

I have found this problem in the API docs section, too. In this case I need to click on the "black circle" of the marker to open it ("windows" section). And this is not so "good".

However thanks for this module.

**Comment by nmccready** [comment]
Plnkr please

**Comment by ziobudda** [comment]
Hi, you can try with API example in "windows" section in the main site, where is present the same problem. 
Go to http://angular-ui.github.io/angular-google-maps/#!/api
Choose "windows" in the left sidebar.
In the example maps with markers try to click to a marker. In my iMac infowindows does not open at the first click and however I need to click the "black circle".  I have tried with Chrome and with Firefox. 
On my smartphone (where there are the exactly same problems) I have Chrome on Lollipop.

How can I attach a video ? 

M.

**Comment by jelleVandendriessche** [comment]
I'm having the same issue.
To open a infowindow I have to click twice at a marker.
 [plnkr link](http://plnkr.co/edit/2iUCZn1Fl0DiRt29BbM2?p=preview) This is the same code like in the api docs.
IStackoverflow](http://stackoverflow.com/questions/14226975/angularjs-ng-include-inside-of-google-maps-infowindow)I believen they had the same issue here (not the main topic but reading the solution they had the same problem).

**Comment by nmccready** [comment]
@ziobudda to attach videos you best using animated gifs which you can enter into github via `![](someurl)`

**Comment by nmccready** [comment]
Your plunkr is incorrect windows with show needs to evaluate to a string. With " 'show' " http://plnkr.co/edit/mquvONeSDXLtkd8RCaXP?p=preview

**Comment by jelleVandendriessche** [comment]
Please update the plunkr (and documentation) in your api documentation because in the examples you do "show"

**Comment by nmccready** [comment]
Sure.. why don't you update it? It just as easy for anyone else to contribute.

**Comment by nmccready** [comment]
It's on the website branch.

**Comment by nmccready** [comment]
It basically a wiki where **everyone** is expected to help out. Remember this is free I can't paid a whole of **zero** for this.
