### ISSUE TITLE
How to get map handle before the map is display ?

### ISSUE THREAD

**Issue by fulup-bzh** [angular-ui/angular-google-maps#1166]
I draw a route on a map and want map zoom/center to bound with my route.

Unfortunately with angular-google-maps I only get the map handle through  uiGmapIsReady.promise().then(function(maps) after the map has been computed. As all my functions are asynchronous, if possible I would like to avoid serialization of  route extraction and map preparation.

Question: is it possible to prepare the map and get a handle without giving center/zoom ? and them bound map handle as soon as route is known with  map.fitBounds(bounds) ?

**Comment by darylyu** [comment]
If you grouped your route inside a single `ui-gmap-markers` tag, you can use fit="true" inside the tag

**Comment by fulup-bzh** [comment]
Finally I abandoned /angular-ui/angular-google-maps and moved back for native GMAP API. Looking to my application, it's finally a simpler option.
