### ISSUE TITLE
Markers Windows not re-rendering content

### ISSUE THREAD

**Issue by xpingfighter** [angular-ui/angular-google-maps#1169]
I've got a Markers directive with a child Windows directive, and when I update the content in the model, it doesn't get reflected in any of the InfoWindows that are open (or closed for that matter).

Debugging the code led me to `WindowsParentModel.prototype.pieceMeal...` at line 5497, specifically `return _this.figureOutState...` at line 5517.  `figureOutState` is the method that determines whether the markers model has changed and returns an object `payload` containing marker adds, removals, and updates.  However, only adds and removals are handled when the promise returns
in lines 5520:
`return _async.each(payload.removals, function(child) {...`
and 5530:
`return _async.each(payload.adds, function(modelToAdd) {...`

Updates seem simply to be ignored and seem to be the reason for the lack of re-rendering.

I've hacked in a fix locally, but I'd prefer if someone more familiar with the code took a look and let me know if my analysis is correct.

I'm using angular-google-maps version 2.0.12.

**Comment by nmccready** [comment]
Please test against master and if it still doesn't work; then I will dive into it.

**Comment by xpingfighter** [comment]
Test against master, still doesn't work.  Update code in master also missing.

**Comment by nmccready** [comment]
Please make a plnkr with your issue.

**Comment by nmccready** [comment]
Update code has been working from me, so I need to see your use case.

**Comment by nmccready** [comment]
Ok, so one thing I have been meaning to get to (which I thought I did) is allow a user to define their comparison/ comparator via attributes. This is because markers and windows for that matter currently only decide to update the element if the position of the marker and or window model changes. You can see this in modelKeyComparison. The only place this is different is Rectangle I believe. Now in the mean time you can easily override this via using angulars decorator pattern to override / extend how markersparentmodel and or windowsparentmodel's modelKeyComparison behaves.

**Comment by xpingfighter** [comment]
I'll get the plnkr to you by the end of the weekend.

**Comment by xpingfighter** [comment]
I've distilled the code into only the necessary pieces to show the buggy behavior:

http://plnkr.co/edit/38hg04Te9FrPhPLLxmau

**Comment by xpingfighter** [comment]
Just looked into decorating modelKeyComparison--and it's not going to help.  There's nothing actually wrong with the modelKeyComparison as it is now--it correctly compares the old and new infowindow content and returns an update payload.  The problem is that the update payload isn't being handled.

If you compare `MarkersParentModel.prototype.pieceMeal` at line 4243 with `WindowsParentModel.prototype.pieceMeal` at line 5497, you can see that the Markers pieceMeal method handles add, removals, and updates, whereas Windows pieceMeal only handles adds, and removals.

**Comment by nmccready** [comment]
Ah, ok I'll check into adding the update.

**Comment by nmccready** [comment]
Great plnkr btw

**Comment by xpingfighter** [comment]
Awesome!  Thank you so much!
