### ISSUE TITLE
Info window does not open at the right place

### ISSUE THREAD

**Issue by blckshrk** [angular-ui/angular-google-maps#1171]
I have a bug with the `ui-gmap-windows` directive.

![capture d ecran 2015-02-19 a 14 02 30](https://cloud.githubusercontent.com/assets/2818075/6266990/3d86df5a-b840-11e4-8574-2855ad51e806.png)

Only one window is opening correctly, all others opens at the left. I used the following code inspired by the documentation.

```html
<ui-gmap-google-map center="map.center" zoom="map.zoom">
    <ui-gmap-markers idKey="'bid'" models="markers" coords="'self'" doCluster="false" fit="'true'" icon="'icon'" click="'onClick'">*
        <ui-gmap-windows show="'show'">
            <div ng-non-bindable>m{{bid}}</div>
        </ui-gmap-windows>
    </ui-gmap-markers>
</ui-gmap-google-map>
```

```js
$scope.markers.map(function (marker) {
    marker.icon = THEME_BASE + 'images/icon.png';
    marker.show = false;
    marker.onClick = function () {
        $log.debug('clicked');
        marker.show = !marker.show;
    }

   return marker;
});
```

Ideally I would like to have only one window open at the same time (with auto closing for the other(s)). Any idea ?

Thanks

**Comment by nmccready** [comment]
So you need all windows open immediately when the markers render correct?

**Comment by blckshrk** [comment]
Actually I want to open the window when I click on a marker and if il click on an other one the previous window closed and a new appear at the right place. Sorry it's pretty basic functionality but I have pain to explain myself!

**Comment by nmccready** [comment]
Right, the reason I ask is because the scenario I just explained is the only reason you would ever want to user windows transcluded with markers. If you search closed issues you will find a lot on this topic. It is way more efficient to use window or windows outside of markers and add them to the windows array on demand (when needed).

**Comment by nmccready** [comment]
BTW the best explanation is usually a running example / plnkr.

**Comment by cdarken** [comment]
@nmccready maybe it should pe specified in the documentation what you said about using windows outside of markers directive

**Comment by nmccready** [comment]
Yes I need to do this. I'll make a ticket for it.

**Comment by blckshrk** [comment]
Hi,

Mea culpa! I just found how to use `ui-gmap-window` outside `ui-gmap-markers` and it's working like a charm.

I put my implementation in case.

```html
<ui-gmap-google-map center="map.center" zoom="map.zoom">
    <ui-gmap-window show="map.window.show" coords="map.window.model" options="map.window.options" closeClick="map.window.closeClick()">
        <div ng-non-bindable>test</div>
    </ui-gmap-window>
    <ui-gmap-markers idKey="'bid'" models="map.markers" coords="'self'" doCluster="false" fit="'true'" icon="'icon'" events="map.markersEvents" options="'options'"></ui-gmap-markers>
</ui-gmap-google-map>
```
```javascript
$scope.map = {
    center: {
        latitude: 50.6278,
        longitude: 3.0583
    },
    zoom: 12,
    markers: [], // array of models to display
    markersEvents: {
        click: function(marker, eventName, model, arguments) {
            $scope.map.window.model = model;
            $scope.map.window.show = true;
        }
    },
    window: {
        marker: {},
        show: false,
        closeClick: function() {
            this.show = false;
        },
        options: {} // define when map is ready
    }
};

uiGmapGoogleMapApi.then(function(maps) {
    // offset to fit the custom icon
    $scope.map.window.options.pixelOffset = new google.maps.Size(0, -35, 'px', 'px');
});
```

Thanks! =)

**Comment by nmccready** [comment]
If someone wants to make the documentation for this and add it to the website branch it would be **GREATLY** appreciated :) . Ticket here https://github.com/angular-ui/angular-google-maps/issues/1176

**Comment by adam-back** [comment]
Thanks @blckshrk. Your answer really helped. I'll work on contributing to the website docs as a way of saying thank you.

**Comment by blckshrk** [comment]
@adam-back We're welcome! Happy to help ;-)

**Comment by piotrowski** [comment]
@blckshrk Thanks for posting your correct code back then. Helped a lot.
