### ISSUE TITLE
Add an option to wrap google links

### ISSUE THREAD

**Issue by QuentinFchx** [angular-ui/angular-google-maps#1175]
When using a map within an hybrid app (Phonegap), a [lot](http://forum.ionicframework.com/t/inappbrowser-with-google-maps-external-link/13237/2) [of](http://stackoverflow.com/questions/13355842/cordova-phonegap-and-google-maps-v3-javascript-api-how-to-add-backbutton-functi) [people](http://stackoverflow.com/questions/14870884/phonegap-how-to-get-back-when-google-maps-terms-of-use-is-pressed?rq=1) ran into issues with the links included at the bottom of the map. IE: It redirects the whole app to "Terms of use", making impossible to go back to the app (even with hardware buttons).

One workaround is to use the [in-app browser](https://github.com/apache/cordova-plugin-inappbrowser/blob/master/doc/index.md) and to add something like:
```coffeescript
wrapMapLinks = ->
    map = $scope.map.control.getGMap()
    return unless map
    google.maps.event.addListenerOnce map, 'idle', ->
        return if $scope.map._wrapped
        angular.element map.getDiv()
        .on 'click', (e)->
            return unless e.target.tagName == 'A'
            e.preventDefault()
            $window.open e.target.href, '_blank', 'location=yes'
        $scope.map._wrapped = true
```

Would it be possible to include this behavior in the library (Since the control on "when the map is completely loaded" is easier to have) ?

**Comment by cthrax** [comment]
"Would it be possible to include this behavior in the library (Since the control on "when the map is completely loaded" is easier to have) ?"

What do you mean? All of the google maps API events are accessible directly to the consumer of the library.

Personally, I'm not sure why the library would try and impose click behavior for consumers like this. The intent of the library is to be an angular shim to the google maps API, and defining behavior like this makes it more into a custom google maps implementation. But that's just my $.02, I could be talked out of it.

**Comment by QuentinFchx** [comment]
My point was exactly about "is it in the scope of the lib ?".
The fix is really light (and could be even lighter if implemented directly in the lib), we could only enable it through an option/config.
But because it only impacts hybrid-apps, I was not sure about the relevance of its implementation.

**Comment by cthrax** [comment]
Ah, yeah, given that being the question, I think it's beyond the scope of the library. That's a consumer specific use case. If you're looking at a library that "just works" with the hybrid-app use case, you could easily write a library that is just a wrapper on top of ui-gmaps that adds this functionality by default.

I'll consider this closed, unless there is disagreement.

**Comment by QuentinFchx** [comment]
Lgtm :)
At least if other people ran into this issue, a fix is available in this repo aswell (still place for improvement around my code though :p)
