### ISSUE TITLE
How to access constants like "BOTTOM_LEFT" for mapTypeControlOptions.position?

### ISSUE THREAD

**Issue by funkflute** [angular-ui/angular-google-maps#1177]
how can I set map options for mapTypeControlOptions, using the constants?

    options: {
    	mapTypeControlOptions: {
    		position: BOTTOM_LEFT,
    	},
    	scrollwheel: false
    },

**Comment by cthrax** [comment]
It's best to set an empty object to the options attribute of your map and then use `uiGmapGoogleMapApi.then(function(maps)...` to set the options with the provided maps object. That way you are guaranteed the google maps API is loaded so you can use those constants.

**Comment by funkflute** [comment]
Gotcha, I created some strings and used them to create them on the fly:

    angular.forEach($scope.map.options,function(value,key) {
    	if (key.indexOf('ControlOptions') > 0) {
    		var pos = $scope.map.options[key].position;
    		$scope.map.options[key].position = maps.ControlPosition[pos];
    	}
    });
