### ISSUE TITLE
Cannot Get Data from Google Maps API

### ISSUE THREAD

**Issue by AddoSolutions** [angular-ui/angular-google-maps#1179]
I don't know CoffeeScript, or I would do this myself, but the data returned from Google Maps API cannot be used in the events bound to a given manager.

See:
https://developers.google.com/maps/documentation/javascript/drawinglayer

Example:
```
google.maps.event.addListener(drawingManager, 'circlecomplete', function(circle) {
  var radius = circle.getRadius();
});
```

We needs access to "circle" to do anything with it.

The change needs to happen here:
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/utils/add-events.coffee

The code SHOULD look like this:

Near line 685 of the non minified code:

```
              if (scope.events.hasOwnProperty(eventName) && angular.isFunction(scope.events[eventName]) && !doIgnore) {
                return google.maps.event.addListener(gObject, eventName, function(gData) {
                  if (!scope.$evalAsync) {
                    scope.$evalAsync = function() {};
                  }
                  return scope.$evalAsync(eventHandler.apply(scope, [gObject, gData, eventName, model, arguments]));
                });
              }
```

I set the return data to be `gData`, that is the only change I made.  Unfortunately, I don't know coffee script, or I would do a fork and merge request.

**Comment by nmccready** [comment]
I think your referring to this code ad nothing in add-events applies to what you quoted in code.

https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/utils/events-helper.coffee#L8-L14

The gObject being passed in should be the same reference as gData.

**Comment by nmccready** [comment]
Therefore I do not understand the need for this change.

**Comment by AddoSolutions** [comment]
The data is not the same though, I just tried it and it certainly is different.

**Comment by nmccready** [comment]
So it is a Circle, but not the latest reference?

**Comment by AddoSolutions** [comment]
In this case, I need the circle radius and Lat/Long of where it was created, and without that object, I have no way of getting that information.

**Comment by nmccready** [comment]
Ok, so what are you getting for the normal gObject? undefined? Cause `gObject === gData`

**Comment by AddoSolutions** [comment]
I get the Drawing Handler, not the circle object in `gObject`, `gData` contains the circle

**Comment by nmccready** [comment]
Ok, I'll dig deeper. I am working on other tickets. In the mean time it would be helpful if you create an example with a hook to the event returning the wrong object. Log it or use an alert. ty

**Comment by AddoSolutions** [comment]
Ok, I can't JSON Stringify it, looks like the best I can do is change the code as I am suggesting, and set a breakpoint inside the called function.  The results are in the screenshot attached (sorry for the ghetto response styles)
![screen shot 2015-02-25 at 7 28 22 pm](https://cloud.githubusercontent.com/assets/3859209/6383993/a64dd758-bd24-11e4-95cb-e3c1be70b72e.png)

**Comment by AddoSolutions** [comment]
That was for a marker, this is for a circle.
![screen shot 2015-02-25 at 7 30 27 pm](https://cloud.githubusercontent.com/assets/3859209/6384008/d32a4c34-bd24-11e4-8261-e54242c5201d.png)

**Comment by nmccready** [comment]
I need concrete examples. So I can see the full context how your getting this.

**Comment by AddoSolutions** [comment]
Oh, my apologies!  This is the file I was testing with (a slightly modified version of the drawing example of this library):

http://plnkr.co/edit/P4PT3SdVSa2WFfJ5MxkO

(It can't seem to load script.js, so it doesn't work right there…)

```
<!DOCTYPE html>
<html xmlns:ng="http://angularjs.org/" ng-app="appMaps">

<head>
    <meta charset="utf-8" />
    <title>AngularJS Plunker</title>

    <script src="//maps.googleapis.com/maps/api/js?libraries=weather,geometry,visualization,places,drawing&sensor=false&language=en&v=3.17"></script>
    <script data-require="angular.js@1.2.x" src="https://code.angularjs.org/1.2.26/angular.js" data-semver="1.2.26"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.js"></script>
    <script src="code.js"></script>

    <!--css-->
    <style type="text/css">
        html, body, #map_canvas {
            height: 80%;
            width: 80%;
            margin: 0px auto;
        }

        #map_canvas {
            position: relative;
        }

        .angular-google-map-container {
            position: absolute;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
        }
    </style>
</head>

<body ng-controller="mainCtrl">
    <div id="map_canvas" >
    <ui-gmap-google-map center="map.center" zoom="map.zoom" draggable="true" options="options" bounds="map.bounds">
        <ui-gmap-drawing-manager options="drawingManagerOptions" control="drawingManagerControl" events="events"></ui-gmap-drawing-manager>
    </ui-gmap-google-map>
</div>

<pre ng-bind="drawingManagerControl|json"></pre>
<!--example-->
</body>

<script type="text/javascript">
angular.module('appMaps', ['uiGmapgoogle-maps'])
.controller('mainCtrl', function($scope) {
  $scope.map = {center: {latitude: 40.1451, longitude: -99.6680 }, zoom: 7, bounds: {}};
  $scope.options = {scrollwheel: true};
  $scope.drawingManagerOptions = {
    drawingMode: google.maps.drawing.OverlayType.MARKER,
    drawingControl: true,
    drawingControlOptions: {
      position: google.maps.ControlPosition.TOP_CENTER,
        drawingModes: [
          google.maps.drawing.OverlayType.MARKER,
          google.maps.drawing.OverlayType.CIRCLE
        ]
    },
	  markerOptions: {
    	editable: true,
    	clickable: true,
    	draggable:true,
	  },
    circleOptions: {
    	editable: true
      }
    };
  $scope.markersAndCircleFlag = true;
  $scope.drawingManagerControl = {};
  $scope.$watch('markersAndCircleFlag', function() {
    if (!$scope.drawingManagerControl.getDrawingManager) {
      return;
    }
    var controlOptions = angular.copy($scope.drawingManagerOptions);
    if (!$scope.markersAndCircleFlag) {
      controlOptions.drawingControlOptions.drawingModes.shift();
      controlOptions.drawingControlOptions.drawingModes.shift();
    }
    $scope.drawingManagerControl.getDrawingManager().setOptions(controlOptions);
  });


$scope.events = {'markercomplete': function(gObject, gData) {
console.debug(gData);
}, 'circlecomplete': function(gObject, gData) {
console.debug(gData);
}};


});

</script>

</html>
```

**Comment by nmccready** [comment]
ty

**Comment by nmccready** [comment]
Next time please give me a working example. I had to spend 30minutes to get your example even close to working. http://plnkr.co/edit/5SsEgGHXZBF6jFzdu4h5

**Comment by nmccready** [comment]
The circle and or marker gets passed up fine. http://plnkr.co/edit/5SsEgGHXZBF6jFzdu4h5
