### ISSUE TITLE
Using ng-repeat in marker tag with nested window causes all info windows to open

### ISSUE THREAD

**Issue by theo2xl** [angular-ui/angular-google-maps#1183]
http://plnkr.co/edit/EMvQfSThRBLOZbqH3MIC?p=preview

Above is the Plunker link to show that I am trying to open a single info window on a marker within an ng-repeat. This causes all info windows within the repeat to be opened. Is there a way to target just the window for that marker?

**Comment by nmccready** [comment]
The bug is in your plunkr. Your pointing all the Windows to the same windowOptions. Therefore when visible is true they all are true. Therefore they all will show. You need to make your windows options unique per window.

**Comment by Tudes** [comment]
theo2xl I followed your example but custom markers are not working anymore.
