### ISSUE TITLE
After adding marker model isn't updated

### ISSUE THREAD

**Issue by piernik** [angular-ui/angular-google-maps#1185]
I want to add marker on click. Here is preview http://plnkr.co/edit/cAc6DMgtOPhqJQusevhW?p=preview
Problem is that after click event vm variable isn't updated, thoug new coords are there (console.log).  Why? I don't know what I'm doing wrong

**Comment by piernik** [comment]
I've got it - I need `$scope.$apply();`

**Comment by nmccready** [comment]
Try $evalAsync it is better and less overhead. Or $timeout.

**Comment by nmccready** [comment]
$timeout calls $digest internally which only fires off children scopes. $apply is the whole shebang.

**Comment by piernik** [comment]
thx
