### ISSUE TITLE
SearchBox invalid template should be handled

### ISSUE THREAD

**Issue by nmccready** [angular-ui/angular-google-maps#1187]
This line should be prevented if scope.template is undefined.

https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/search-box.coffee#L41

Otherwise an error at 
https://github.com/angular/angular.js/blob/77d8ae1d458ce526f77d059bae05100299d10f67/src/ng/urlUtils.js#L101
Is hit and protocol is null. This results when the url is undefined.
```
function urlIsSameOrigin(requestUrl) {
  var parsed = (isString(requestUrl)) ? urlResolve(requestUrl) : requestUrl;
  return (parsed.protocol === originUrl.protocol &&
          parsed.host === originUrl.host);
```
@kandizzy

**Comment by nmccready** [comment]
Possibly a one time watch should take place until the template is defined. Or we should use $log.error.

**Comment by kandizzy** [comment]
@nmccready ok I will have some time to fix it this weekend.

**Comment by nmccready** [comment]
np ty

**Comment by kandizzy** [comment]
@nmccready is there something I need to install for beforeAll to work in `jasmine:consoleSpec`?
