### ISSUE TITLE
ui-gmap-google-map ng-repeat 

### ISSUE THREAD

**Issue by tommykennedy** [angular-ui/angular-google-maps#1188]
I am looking to repeat maps on a timeline. I was wondering the best approach to do this and how to initialise the maps in the controller. 

                        <div ng-repeat="question in questions">
                            <h3>{{question.question}}</h3>
                            <div ng-if="question.answerOptions.location">
                                <ui-gmap-google-map center='map.center' zoom="map.zoom" id="{{question.id.replace('#','')}}">
                                    <script type="text/ng-template" id="searchbox.tpl.html">
                                        <input type="text" placeholder="Pick location" ng-model="address">
                                    </script>
                                    <ui-gmap-search-box position="TOP_LEFT" template="searchbox.template" events="searchbox.events"></ui-gmap-search-box>
                                    <ui-gmap-layer namespace="weather" type="WeatherLayer" show="showWeather"></ui-gmap-layer>
                                </ui-gmap-google-map>
                                <button class="btn btn-default btn-xs" ng-click="showAdd()">Answer</button>
                            </div>
                            <hr>
                        </div>

**Comment by nmccready** [comment]
So your going to need to extend your map(s) controller to have a scope.maps var which is somehow based off question. Or if you have all the info you need in a question use the data out of it as you already have that array. If you need different height and styling then your going to have to do some unique naming (class or id) to encapsulate the `<div class="angular-google-map"><div>`.  That way you can create the correct css selectors to set the correct height or other items.

**Comment by tommykennedy** [comment]
I am confused on how to accomplish this. The controller is at the top of a panel called timelineController. The ng-repeat repeats the section.

    define(function () {
         return ['$scope', '$sails', '$upload', '$timeout', 'uiGmapGoogleMapApi', function ($scope, $sails, $upload, $timeout, GoogleMapApi) {

        $scope.question = [{id:1,answerOptions:{location:true}},{id:2,answerOptions:{location:false}},{id:3,answerOptions:{location:true}},{id:4,answerOptions:{location:true}}];
       
        GoogleMapApi.then(function (maps) {
            $scope.map = {
                center: {
                    latitude: 45,
                    longitude: -73
                },
                zoom: 1
            };
            $scope.options = {
                scrollwheel: false
            };
            $scope.showWeather = true;

            var events = {
                places_changed: function (searchBox) {
                    var place = searchBox.getPlaces();
                    if (!place || place == 'undefined' || place.length == 0) {
                        console.log('no place data :(');
                        return;
                    }

                    $scope.map = {
                        "center": {
                            "latitude": place[0].geometry.location.lat(),
                            "longitude": place[0].geometry.location.lng()
                        },
                        "zoom": 10
                    };
                    $scope.marker = {
                        id: 0,
                        coords: {
                            latitude: place[0].geometry.location.lat(),
                            longitude: place[0].geometry.location.lng()
                        }
                    };

                }
            }

            $scope.searchbox = {
                template: 'searchbox.tpl.html',
                events: events
            };

        });
