### ISSUE TITLE
2.0.14 Meteor Self Install for Publish

### ISSUE THREAD

**Issue by nmccready** [angular-ui/angular-google-maps#1190]
See #1174 

- ~~dynamic version checking of package.json~~
- ~~installation of meteor binary scripted into scripts/publish **if needed**~~ 2688cad

**Comment by nmccready** [comment]
@Urigo https://github.com/angular-ui/angular-google-maps/blob/master/package.js#L4

The version should be pulled in from package.json so this is not a headache to keep in sync with package.json and or bower.json.

**Comment by nmccready** [comment]
2.0.13 was pushed manually once I noticed the version mismatch on package.js.

**Comment by nmccready** [comment]
@Urigo can we use node `require` to pull in the json we want w/ meteor? If not what would be the standard way to load the file?

**Comment by nmccready** [comment]
Where is the api documentation for using Package and api in meteor? Heck for that matter the global object is different as well. This does not seem to be in the docs anywhere.

**Comment by nmccready** [comment]
Think I found it here https://github.com/meteorhacks/npm. `Npm.require`

**Comment by nmccready** [comment]
Resolved

**Comment by Urigo** [comment]
Great, just saw your solution with  Npm.require  (in packages you don't need MeteorHacks package, Meteor has this natively, but I see you already done that).
Very cool

**Comment by nmccready** [comment]
Yeah MeteorHacks just let me know what to look for. I think MeteorHacks is just an examples app/repo.

**Comment by Urigo** [comment]
It's just that the Npm.require is only for packages and MeteorHacks expose it also for the application itself.
