### ISSUE TITLE
Can't get the markers draggable (in the search places context )

### ISSUE THREAD

**Issue by brieygu** [angular-ui/angular-google-maps#1194]
Hi,

In the searchbox examples supplied, if can't get the markers become draggable. 

If tried to set the marker options to draggable:true but their can't be moved.

-> Restarted chrome and all seems ok now

**Comment by georapbox** [comment]
In your HTML include the property events="markersEvents":

```html
<ui-gmap-markers idkey="map.idkey" models="map.markers" options="'options'" coords="'self'" icon="'icon'" click="onClicked" events="markersEvents"></ui-gmap-markers>
```

Then in Javascript:

```js
$scope.markersEvents = {
            dragend: function (marker, eventName, args) {
                var lat = marker.getPosition().lat(),
                      lon = marker.getPosition().lng();

                console.log('latitude: ', lat);
                console.log('longitude: ', lon);
            }
};
```

Now on <code>dragend</code> event you should see the new coordinates of the marker.
Hope this helps.

**Comment by brieygu** [comment]
great, it works !!!

many thanks for your valuable help !!!

**Comment by RajanJS** [comment]
Thanks a lot!!!!! @georapbox
