### ISSUE TITLE
Reference to angular google maps polygon objects?

### ISSUE THREAD

**Issue by dustin-leigart** [angular-ui/angular-google-maps#1199]
Hello my friends

actually this is not a issue, but I’m not sure how I am able to get a reference to all the polygons that are currently active in my google maps object:

````
<ui-gmap-google-map center='map.center' zoom='map.zoom' events='map.events' control="map.control" nbounds="map.bounds" options="map.mapOptions">
                <ui-gmap-marker ng-repeat="(key, data) in locations" idKey="key" coords="data.mapCoordinates" events="data.events"></ui-gmap-marker>

                <ui-gmap-layer type="FusionTablesLayer" options="map.fusionLayer" events="map.fusionLayer.events" show="true"></ui-gmap-layer>

                <ui-gmap-polygon static="true" 
                    ng-repeat="p in polygons track by p.id"
                    path="p.path" 
                    stroke="p.stroke" 
                    visible="p.visible"
                    clickable="true"
                    geodesic="p.geodesic" 
                    fill="p.fill" 
                    fit="false" 
                    editable="p.editable"
                    events="map.polygon.events"                    
                    draggable="p.draggable">
                </ui-gmap-polygon>

                <ui-gmap-window coords="infoWindow.coords" show="infoWindow.show" options="infoWindow.options"></ui-gmap-window>
</ui-gmap-google-map>
````

as you see I’m using the ui-gmap-polygon directive in conjunction with a scope array, which gets filled when a specific country is selected, eventually their states/postal code areas get loaded as polygons into the scope array, and angular google maps is handling everything correct. What I’m missing now is that I don’t know how to get a reference to all these polygon objects, which should be cached somewhere, am I right? I need them to get the center location of each polygon, so I can show a label within, so the user knows which polygon is which postal code area.

Usually we would add polygons via `polyArray.push(new google.maps.Polygon())`, so I would have a cached version, but right now I don’t know whats to best way do it, when the polygons are getting created by the angular directive.

I’m quite new to angular, so be forgiving is something doesn’t make that much sense and there could be a much better solution - I’d be very glad if you can point me into the right direction! If you need more code snippets or informations, just tell me.

Thanks in advance! :)

edit: If you see a simpler way how I could pass each polygon a label with a name to (which needs to be shown static, not on hover) - that’d be even greater, because simply enough, thats what I need to accomplish here.

**Comment by nmccready** [comment]
Your best approach is to not use polygon but use polygons. Also I highly suggest not using ng-repeat on marker (it is slow as dog-%$$). Both of those directives have a control attribute which you can get access to the functions you want. See the documentation.

**Comment by nmccready** [comment]
http://angular-ui.github.io/angular-google-maps

**Comment by dustin-leigart** [comment]
Thank you very much! I’ve changed my marker and polygon directives to the plural versions.
Anyways, it seems like the polygons control object doesn’t provide the same methods as the control object that gets created by the "markers"-directive. Only got the methods
````clean()````, ````newModels()````, ````updateModels()````. The other methods mentioned in the documentation like ````getPlurals()```` seem to be missing, or am I missing something there? 

I just logged the polyControl object to the console, to see which methods it is providing.

````
<ui-gmap-markers models="locations" coords="'mapCoordinates'" idKey="'Id'" events="'events'" click="'click'" control="map.markerControl">
                    <ui-gmap-window coords="infoWindow.coords" show="infoWindow.show" options="infoWindow.options"></ui-gmap-window>
</ui-gmap-markers>

<ui-gmap-polygons 
                    models="map.polygons"
                    idKey="'id'"
                    static="true" 
                    control="map.polyControl"
                    path="'path'" 
                    stroke="{color: '#000000', weight: 1, opacity: 0.5}" 
                    visible="true"
                    clickable="true"
                    geodesic="true" 
                    fill="{color: '#0080bc', opacity: 0.5}" 
                    fit="true" 
                    editable="false"
                    events="map.polygon.events"                    
                    draggable="false"
                    chunk="100"
                    cleanchunk="200">
</ui-gmap-polygon>
````

```` 
console.log($scope.map.polyControl);
````

````
 current poly control: Object {updateModels: function, newModels: function, clean: function}clean: function (){return h.rebuildAll(a,!1,!0)}newModels: function (b){return a.models=b,h.rebuildAll(a,!0,!0)}updateModels: function (b){return a.models=b,h.createChildScopes(!1)}__proto__: Object
````

Anyways switching to the plural directives brought a lot of performance to the app already, thank you!

**Comment by dustin-leigart** [comment]
Takin’ it all back! Problem was at my end, since I still had 2.0.12, therefore the methods weren’t available. Updated now and will continue working my into the center of the polygons! :)

Thanks for the lightning-fast help!

**Comment by nmccready** [comment]
:+1:

**Comment by dextermcconnell** [comment]
I would like to trigger a click on a specific polygon in the array, how do I accomplish it?
Like: google.maps.event.trigger(model, "click", model.model);

**Comment by MichaelYao88** [comment]
bump^ I would also like to know this

**Comment by dextermcconnell** [comment]
try this piece of code

`      angular.extend($scope, {
        map: {
          control: {},
          center: {
            latitude: 17.44,
            longitude: 78.45
          },
          options: {
            streetViewControl: true,
            scaleControl: true,
            panControl: false,
            maxZoom: 15,
            minZoom: 3,
          },
          getPolyFill: function(model) {
            if (!model) {
              uiGmapLogger.debug("model undefined!");
              return;
            }
            polyFillCtr += 1;
            return {color: '#05A777', opacity: '0.5', weight: 2};
          },
          polyEvents: {
            click: function(gPoly, eventName, polyModel) {
              var activeregions, idx, options;
              idx = vm.activepolygons.indexOf(polyModel.title);
              options = {
                weight: 1,
                fillColor: '#ec1c28',
                opacity: '0.5',
                strokeColor: '#ec1c28'
              };
              if (idx > -1) {
                vm.activepolygons.splice(idx, 1);
              } else {
                vm.activepolygons.push(polyModel.title);
              }
              if (gPoly.fillColor === '#ec1c28') {
                options.fillColor = '#05C68C';
                options.strokeColor = '#ec1c28';
              }
              if (gPoly.fillColor === '#EC9EA4') {
                options.fillColor = '#05C68C';
                options.strokeColor = '#05C68C';
              }
              return gPoly.setOptions(options);
            },
            mouseout: function(gPoly, eventName, polyModel) {
              var idx;
              $scope.mouseover = false;
              $scope.map.window.marker.coords = null;
              $scope.map.window.polygon.show = false;
              $scope.map.window.polygon.title = '';
             return gPoly.setOptions({
                  weight: 1,
                  fillColor: '#05A777',
                  opacity: '0.6',
                  strokeColor: '#05A777'
                });
            },
            mouseover: function(gPoly, eventName, polyModel) {
              var bounds, coords, idx, ind, options, _i, _len, _ref;
              $scope.mouseover = true;
              options = {
                weight: 1,
                fillColor: '#ec1c28',
                opacity: '0.5',
                strokeColor: '#ec1c28'
              };
              if (gPoly.fillColor === '#ec1c28') {
                options.fillColor = '#EC9EA4';
                options.strokeColor = '#ec1c28';
              }
              if (gPoly.fillColor === '#05A777') {
                options.fillColor = '#05C68C';
                options.strokeColor = '#05A777';
              }
              bounds = new google.maps.LatLngBounds();
              _ref = polyModel.path;
              for (ind = _i = 0, _len = _ref.length; _i < _len; ind = ++_i) {
                coords = _ref[ind];
                bounds.extend(new google.maps.LatLng(coords.latitude, coords.longitude));
              }
              gPoly.setOptions(options);
              $scope.map.window.marker.coords = {
                latitude: bounds.getCenter().lat(),
                longitude: bounds.getCenter().lng()
              };
              $scope.map.window.polygon.show = true;
              $scope.map.window.polygon.title = polyModel.title;
              return $scope.$apply();
            }
          },
          draw: void 0,
          markers: [],
          markerEvents: {
            click: function(gMarker, eventName, model) {
              console.log('marker clicked..');
              $scope.map.window.marker = model;
              $scope.map.window.show = true;
              return $scope.$apply();
            }
          },
          window: {
            marker: {},
            show: false,
            polygon: {
              show: false,
              title: ''
            },
            options: {},
            title: ''
          },
          infoWindowWithCustomClass: {
            options: {
              boxClass: 'custom-info-window',
              disableAutoPan: true,
              closeBoxMargin: "0px",
              closeBoxURL: ""
            },
            show: true
          },
          zoom: 3,
          dragging: true,
          bounds: {},
          polys: [],
          draw: void 0,
          markers: [],
          refresh: function() {
            return $scope.map.control.refresh(origCenter);
          }
        }
      });`
