### ISSUE TITLE
Question : Change title on cluster

### ISSUE THREAD

**Issue by PierreBrisorgueil** [angular-ui/angular-google-maps#1202]
Hi, I have just a small question. I'm currently trying to display on a cluster, names of the markers it contains.

For that I just tried to change the title on mouseover :

			clusterEvents: {
				mouseover: function(cluster, clusterModels) {
					var title = "";
					_.each(clusterModels, function(marker) {
						title = title + marker.nom + "; ";
					});
					cluster.markerClusterer_.title_ = title;
					console.log("Cluster Models: clusterModels: ", cluster);
				}
			},

This works, but with a bug , I have to move the map or zoom in order to actualize data , that's normal. it's probably not the good way. 

- So  it's possible to initialize the titles to different values ​​at the loading ?

- Or it's possible to initialize a window on mouseover, and close it on mouse out ? because the position is known, this would make a window template, probably the best solution if we have lot of name in the cluster. I don't find how to pop a window on this event, probably with your example of "".

But how to close it at the mouseout ? I have some problem with this second part. On all my windows i have a link who show an angular-strap aside. I still have not arrived to close windows after the appiration of this aside. 

thank you for the advice and sorry for my english ;), if I find the solution I 'll post here.

**Comment by nmccready** [comment]
Could you make a simple plnkr to detail your issue further?

**Comment by ppdg** [comment]
Yep, of course :) sorry,

http://plnkr.co/edit/2oEmuyeRpKzWKfVniUog?p=preview
http://embed.plnkr.co/2oEmuyeRpKzWKfVniUog/preview

On the second link, juste put you mouse on a cluster, you will see "Hi i'm a cluster", move the map, and put your mouse on the cluster again. 

It's normal :). But : 

- it's possible to initialize the titles of clusters to different values ​​at the loading of the map ? 
- Or it's possible to initialize a window on mouseover, and close it on mouse out ?

**Comment by nmccready** [comment]
So basically you want clusteroOptions affecting the title based of each cluster. So in a sense a cluster is an average of markers into one cluster. So lets say you wanted to display the State for a bunch of markers all in one cluster. You could just grab the first marker in a cluster and assume (not always right) that it is the correct State for the cluster.

Am I headed down the correct path?

**Comment by nmccready** [comment]
Anyways, looking at MarkerCluster it looks like the title is a global property for all Clusters. So yes if you need it different for each individual Cluster; then you will need to set it on the fly. Also you want you setTitle and I am not sure how you get it to refresh (there is redraw but it was causing some recursion and didnt work either).  I am afraid you will need to dig into the MarkerClusterPlus lib.

**Comment by ppdg** [comment]
Okokey, Thanks for all :)
it looks like it is possible : 
- http://www.albertosarullo.com/blog/google-map-v3-extend-markerclusterer-javascript-library
- http://www.piste-ciclabili.com/test/markercluster/

whatever, i give up the title , and look to create a personnal tooltip, or use the window, on the coordinates of the mouse/cluster, if you have any ideas about this ! 
- http://jsfiddle.net/ErYub/
- http://www.geocodezip.com/v3_markerclustererplus_examples_simple_exampleA.html?

i will post my result here.

**Comment by leodonny** [comment]
I'm working with @PierreBrisorgueil on this project and I found out a way to open and close an infoWindow without refresh the map.
Here the js part :

```javascript
clusterEvents: {
     mouseover: function(cluster, clusterModels) {
          $scope.info = "";
          _.each(clusterModels, function(marker){
                    $scope.info += marker.name+'</br>';
                    $scope.GG.map.infoCluster.coords = {longitude : cluster.center_.B , latitude : cluster.center_.k};
                    $scope.GG.map.infoCluster.show = true;
               });
          $scope.$apply();
     },
     mouseout : function(){
          $scope.GG.map.infoCluster.show = false;
          $scope.$apply();
     }
}
```

clusterEvents is the clusterEvents attribut. In infoCluster, coords and visibility are stocked. For each marker I display its name in the $scope.info variable.
The key of this code is $scope.$apply().

However there still a problem : the infoClusters blink when the mouse pass over the cluster

**Comment by nmccready** [comment]
@leodonny use scope.$evalAsync() or wrap your call in $timeout they do the same thing but are more efficient than $apply().

**Comment by PierreBrisorgueil** [comment]
@nmccready  thx for all, I think you can close the ticket, if one day ... I have time for work on that, i will let you know.

**Comment by nmccready** [comment]
Cool
