### ISSUE TITLE
Quick Start And Async Loader Example

### ISSUE THREAD

**Issue by webjunkie01** [angular-ui/angular-google-maps#1206]
I'm just starting to use the new 2.x version and came across the Async loader example. 

The current code on the quick start and documentation sections did not work for me, I got the following error "Error: [$injector:unpr] Unknown provider: GoogleMapApiProviders error".
```javascript
.config(['uiGmapGoogleMapApiProvider', function(GoogleMapApiProviders) {
    GoogleMapApiProvider.configure({
     //key: 'your api key',
      v: '3.17',
      libraries: 'weather,geometry,visualization'
    });
}])
```

But this one did work:
```javascript
.config(['uiGmapGoogleMapApiProvider', function (GoogleMapApi) {
  GoogleMapApi.configure({
    //key: 'your api key',
    v: '3.17',
    libraries: 'weather,geometry,visualization'
  });
}])
```
I'm wondering if the code examples are wrong or is it me who's not understanding correctly.

**Comment by cthrax** [comment]
There is no difference between those two code examples, both use angular's array notation for DI and inject uiGmapGoogleMapApiProvider .

**Comment by webjunkie01** [comment]
That's exactly what I thought. Wait, I think an s in missing in the quick start example when loading maps from China is mentioned. (http://angular-ui.github.io/angular-google-maps/#!/use)
```javascript
GoogleMapApiProvider.configure({
```

**Comment by cthrax** [comment]
Ah, you are correct. The 's' is missing which is going to break everything.

**Comment by nmccready** [comment]
So the example needs to be fixed only or is there an API problem?

**Comment by webjunkie01** [comment]
Just the example. The API is working fine.

**Comment by pcbulai** [comment]
@nmccready this one is fixed
