### ISSUE TITLE
How to close ui-gmap-windows programtically?

### ISSUE THREAD

**Issue by Pinny3** [angular-ui/angular-google-maps#1208]
Hi there,

I wonder how it is possible to close a

ui-gmap-windows

programatically?

Any ideas / hints?

Regards,

Christian

**Comment by nmccready** [comment]
Whether you want to close all or one you need to read the documentation on Plural control.

**Comment by nmccready** [comment]
`$scope.control.getPlurals()` returns a PropMap.. then iterate through all of them via PropMap.prototype.each . You will have access to each childmodel and gObject. You can call destroy on each Child and or call the gObject directly and close it yourself.
