### ISSUE TITLE
undefined variable

### ISSUE THREAD

**Issue by emnuu** [angular-ui/angular-google-maps#1209]
line:21 angular-google-maps/src/coffee/directives/api/models/parent/rectangle-parent-model.coffee
refers to a variable called rectangle which is undefined.

**Comment by nmccready** [comment]
U mean [here](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/parent/rectangle-parent-model.coffee#L21)

**Comment by nmccready** [comment]
Seems like a pretty easy fix? Why not submit a patch.
