### ISSUE TITLE
drop animation

### ISSUE THREAD

**Issue by houmanka** [angular-ui/angular-google-maps#1210]
Hi guys,
How do I make the drop animation for the markers? I have tried many ways however it doesn't seem to be supporting it.
Thanks

**Comment by nmccready** [comment]
The google enum is not available until after the sdk is ready. So you can set the marker's options after `uiGmapIsReady.promise().then` or set the options on an event handle on the marker itself.


https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/scripts/controllers/issue-482-markers-animation.js#L103

https://github.com/angular-ui/angular-google-maps/blob/master/example/issue-482-markers-animation.html#L35
