### ISSUE TITLE
Markers/Window, Windows not showing in main demo

### ISSUE THREAD

**Issue by neeg** [angular-ui/angular-google-maps#1214]
Markers are broken in 2.0.14 and 2.0.15
Example: click on plane marker in demo has no effect (http://angular-ui.github.io/angular-google-maps/#!/demo)

**Comment by nmccready** [comment]
Ahh well this is not exactly accurate it appears window and windows is broken. Thanks.

**Comment by nmccready** [comment]
Ill have to figure out which avenue of showing a window got broken. I am using it locally via markers with window and it is working fine. So it is likely just windows.

**Comment by nmccready** [comment]
Actually this might not be a bug as the example is running against 2.1.X with a 2.0.X frontend. So the bug might just be the docs.

**Comment by nmccready** [comment]
![screen shot 2015-03-10 at 4 51 05 pm](https://cloud.githubusercontent.com/assets/583593/6585022/ab45fb34-c745-11e4-9bc4-ddfb65e6c445.png)

**Comment by nmccready** [comment]
Nope, nvm it is broken on both. But I need to fix the website demo as well to point to the correct version.

**Comment by nmccready** [comment]
Found the problem

**Comment by nmccready** [comment]
in 2.0.16

**Comment by neeg** [comment]
Thanks for the quick bugfix!
