### ISSUE TITLE
add Geocoder() to uiGmapGoogleMapApi

### ISSUE THREAD

**Issue by mLaird** [angular-ui/angular-google-maps#1216]
As best that I can tell, uiGmapGoogleMapApi does not support / provide access to Google's Geocoder(). Thus it is not possible to do 'reverse geocoding' - enter a latitude and longitude and receive back a JSON object with descriptions of that location, e.g., country, state, county, city, street address, ZIP, type of facility, etc. This is a request to have Geocoder() accessible through uiGmapGoogleMapApi.  Geocoder() has at least one other capability, normal geocoding, but all capabilites are provided through its parameter interface.

**Comment by yourivdlans** [comment]
I think what you are looking for is this.

http://angular-ui.github.io/angular-google-maps/#!/api

```javascript
app.controller('MapController', function(uiGmapGoogleMapApi) {
  uiGmapGoogleMapApi.then(function(maps) {
    latlng = new maps.LatLng(40.399516, 40.399516);
    geocoder = new maps.Geocoder();
    geocoder.geocode({'latLng': latlng}, function(results, status) {
      // Do something with result
    });
  });
});
```

**Comment by nmccready** [comment]
Is @yourivdlans solution sufficient? I am not really clear to what @mLaird is requesting to be cleaner.

**Comment by mLaird** [comment]
Yes, yourivdlans's idea works. I was using things like uiGmapGoogleMapApi.then(function(Geocoder) basically not realizing that Geocoder() is within the maps object. Thanks for your help.  Hope this helps others.

**Comment by Sshuichi** [comment]
Can the geocoder return a promise?
