### ISSUE TITLE
Keep only one InfoWindow open at a time 

### ISSUE THREAD

**Issue by phamductri** [angular-ui/angular-google-maps#1219]
I have multiple InfoWindow on my map, using ui-gmap-windows. However, I want to keep only one InfoWindow open at a time, like in this StackOverflow question : http://stackoverflow.com/questions/2223574/google-maps-auto-close-open-infowindows?rq=1. But I don't know how to do it with the current capability of angular-google-maps. Care to show me an example how to do this with the current Angular Google Map v2.0.16 ?

**Comment by cthrax** [comment]
Look at the FAQ on the website.
