### ISSUE TITLE
Markers directive 

### ISSUE THREAD

**Issue by jgarcia99** [angular-ui/angular-google-maps#1223]
The docs for the markers directives is for random locations on the map but what if i have 5 locations that I want to show ng-repeat is not working can you give an example of a map with more then 1 location?

**Comment by cthrax** [comment]
The randomness makes no difference, it's just creating an array of markers, do the same with your static 5.

**Comment by jgarcia99** [comment]
$scope.markerList = [
        {
            // id: 1,
            // coords: {
                latitude: 28.593178,
                longitude: -81.361418,
            // }
        }, {
            // id: 2,
            // coords: {
                latitude: 28.568422,
                longitude: -81.346529
            // }
        }, {
            // id: 3,
            // coords: {
                latitude: 28.571854,
                longitude: -81.389863
            // }
        }, {
            // id: 4,
            // coords: {
                latitude: 28.549242,
                longitude: -81.352306
            // }
        }, {
            // id: 5,
            // coords: {
                latitude: 28.555688,
                longitude: -81.207649
            // }
        }];

    });

**Comment by jgarcia99** [comment]
what more do i need to do?

**Comment by jgarcia99** [comment]
@cthrax thanks for writing back im an angular noob

**Comment by cthrax** [comment]
An id is required, as per the docs and example, but other than that, assuming you have everything else the it should work. See this example, http://plnkr.co/edit/eaRudM9MBGseu4OX5Zxq?p=preview .

**Comment by jgarcia99** [comment]
thanks alot @cthrax really appreciate it

**Comment by cthrax** [comment]
The best thanks is always contributing back to the project wherever you can. :)

**Comment by nmccready** [comment]
:+1:

**Comment by jgarcia99** [comment]
sure no problem let me get my angular skills up to par lol :+1: cool

**Comment by chreestopher** [comment]
Im having an issue where when I scroll through the map, my markers jump to new positions each time i stop scrolling. is this a known issue? or expected behavior? is there an attribute I can use to specify for the marker to stay at its position?
