### ISSUE TITLE
ui-gmap-windows will not use template

### ISSUE THREAD

**Issue by funkflute** [angular-ui/angular-google-maps#1225]
http://codepen.io/anon/pen/zxMEEK

Nested ui-gmap-windows won't use a templateUrl to display a marker window. It puts a white triangle in the upper left of the map and fails.

			<ui-gmap-markers models="map.markers" idKey="'id'" coords="'self'">
				
				<ui-gmap-windows show="'show'" templateUrl="map.infoWindowTpl"></ui-gmap-windows>
			</ui-gmap-markers>

![screen shot 2015-03-16 at 5 27 22 pm](https://cloud.githubusercontent.com/assets/7559852/6676897/baa6ceda-cc01-11e4-9d62-bef9c8e9b122.png)

**Comment by funkflute** [comment]
any help here?

**Comment by nmccready** [comment]
Do you really need all windows open at once?

**Comment by nmccready** [comment]
See the FAQ search `window at a time`
http://angular-ui.github.io/angular-google-maps/#!/faq

**Comment by nmccready** [comment]
If you leave it you could try wrapping the templateUrl in additional quotes but I doubt that will work.

**Comment by funkflute** [comment]
I only need 1 window shown at a time. I've used the FAQ and made this: http://plnkr.co/edit/GBEdbD9pqSjjJDyyGVuK
But I can't get the window to be attached to the marker, (using windows inside of markers did attach them) and if I try and use a templateURL that still fails as well.

Thanks.

**Comment by nmccready** [comment]
Yeah you have to adjust the anchor to make it not cover.

**Comment by nmccready** [comment]
Forked and done.
http://plnkr.co/edit/f2gxG7DM1U8IlOXfRiuT?p=preview

**Comment by nmccready** [comment]
Same issue was right here.
https://github.com/angular-ui/angular-google-maps/blob/master/example/issue-1056-ng-show-window.html
https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/templates/issue-1056-template.html

#1056

**Comment by nmccready** [comment]
pixleOffset is now in plnkr
