### ISSUE TITLE
Module dependency crash angular app on IE

### ISSUE THREAD

**Issue by iGitScor** [angular-ui/angular-google-maps#1226]
Hi,

I have an issue with the implementation of the angular-google-map directive on IE8.
After the implementation, the map works on Chrome, Firefox and IE 9+ but crash the angular application (the binded data are not filled {{ data }} and controllers/directives are not called) 

I declared the dependcy with the code above :
``
var app = angular.module("portfolio", ['uiGmapgoogle-maps'])
``

Then I configure the provider with this code :
```
app.config(function (uiGmapGoogleMapApiProvider) {
  uiGmapGoogleMapApiProvider.configure({
    key: // My key is inserted here,
    v: '3.17'
  });
});
```

After that I declare my controller 

``
app.controller("PortfolioController", ["$scope", "$http",'uiGmapGoogleMapApi', ...
``

If you need more information please feel free to ask me some details

Thanks

iGitScor

**Comment by nmccready** [comment]
You need to look up how to use angular in old IE. The declarations must be much more explicit. You will also need to shim and shiv the heck out of it. Honestly I don't think it is worth your time.

**Comment by nmccready** [comment]
Let google be your guide.. here are a few top searches.

http://blog-it.hypoport.de/2013/08/24/how-to-make-your-angularjs-app-work-in-ie-8/
http://henriquat.re/appendix/angularjs-and-ie8/necessary-changes-for-ie8-compatibility.html

**Comment by iGitScor** [comment]
Resolved with another fix (similar to the solutions of the mentioned articles)

```
<!--[if lt IE 9]>
    <script>
        document.createElement('ui-gmap-google-map');
        document.createElement('ui-gmap-markers');
    </script>
<![endif]-->
```

Thank you for your help and good job for the work ! :+1:
