### ISSUE TITLE
Polylines creates only one path, ignores additional paths

### ISSUE THREAD

**Issue by fbliss** [angular-ui/angular-google-maps#1228]
[{"id":1,"icons":{"icon":{"path":"M 0,-1 0,1","strokeOpacity":1,"scale":4},"offset":0,"repeat":"20px"},"path":[{"latitude":42.125093,"longitude":-72.749538},{"latitude":44.261134,"longitude":-88.40676},{"latitude":37.386052,"longitude":-122.083851}],"stroke":{"color":"#932023","weight":2},"editable":false,"draggable":false,"geodesic":true,"visible":true}]

Will only produce the first segment, and ignores the final path element.

**Comment by fbliss** [comment]
The third element is culled somewhere in the __extends() function.  console.log(child) from within the __extends() function shows all three data points included, everything after __extends is called shows only 2 points.

        __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

**Comment by fbliss** [comment]
I think this may have been a caching issue, I have no idea why.

**Comment by nmccready** [comment]
no worries
