### ISSUE TITLE
Increase polylines resolution of direction paths

### ISSUE THREAD

**Issue by BenjaminAbt** [angular-ui/angular-google-maps#1230]
Hej Hej,

I'm using polylines to show the route between two points.Therefore I'm using the directionService.route() method.

The problem is the resolution is not high enough.
You can see the pink-red line is not matching the highway curve. 
![angularmapresolution](https://cloud.githubusercontent.com/assets/6189336/6729950/ccc36a8c-ce37-11e4-9926-046ec16663e0.JPG)
On highways thats maybe okay, but in cities that is horrible. It should be like the yellow highlighted way:
![angularmapresolution](https://cloud.githubusercontent.com/assets/6189336/6730031/917eadbe-ce38-11e4-9f04-ab83a0a4fc22.JPG)

The Google API returns 242 Waypoints for 1600 KM. I think this is not enough.
Is there any way to get more points or a better curve?

Thanks.

**Comment by nmccready** [comment]
Thats a google backend problem / question. I honestly have no clue. This would be better asked on google groups. If you figure it out please post back.
