### ISSUE TITLE
drawingmanager example not working

### ISSUE THREAD

**Issue by jimgibbs** [angular-ui/angular-google-maps#1232]
I am attempting to utilize the drawingmanager. I am running into an issue that the debugger indicates that google is not defined.

This appears to be the same issue for the example in the documentation too.

I would appreciate some assistance.

**Comment by ballistic** [comment]
Are you setting the drawingManagerOptions in the uiGmapGoogleMapApi() method?

**Comment by jimgibbs** [comment]
I was not, thanks for the feedback.

Thanks!
