### ISSUE TITLE
Pan to marker infoWindow --Question

### ISSUE THREAD

**Issue by adamkarb** [angular-ui/angular-google-maps#1233]
Been loving the library so far, but I am stuck on something... The map wants to always pan to an open window when I drop a new pin.  For example,
A user drops a pin in washington and leaves a marker window open.  They then zoom in on Florida and drop a pin, but immediately get panned back to washington because the whole map wants to fit all the infowindows.  I couldn't find the attribute to cancel this feature.  Anyone know?

**Comment by nmccready** [comment]
You need to disable the auto panning on the window options which is on by default on google.

**Comment by nmccready** [comment]
`disableAutoPan`

https://developers.google.com/maps/documentation/javascript/reference#InfoWindowOptions

So tell the window directive you have some options and then set `disableAutoPan:true`.

**Comment by adamkarb** [comment]
awesome
