### ISSUE TITLE
How to put text above custom icon image?

### ISSUE THREAD

**Issue by nykolaslima** [angular-ui/angular-google-maps#1235]
Guys,

This is a doubt about how to put a text above custom icon image.

I'd configure the custom icon image but I need to put a number in it. How can I do that?

**Comment by jmichaliga** [comment]
in the ui-gmap-marker, you can set the html attribute options to an object with "labelContent and labelClass" to set your text and style it. I'm actually having a little trouble positioning it with labelAnchor myself. Note, you must be on 2.0.17 - was on 2.0.12 and it would not work.

**Comment by jmichaliga** [comment]
Turns out the regex on the getLabelPositionPoint was erroring for me. A quick fix in the generated src straightened it out.

          //anchor = /^([-\d\.]+)\s([-\d\.]+)$/.exec(anchor);
          anchor = anchor.split(',');
          xPos = parseFloat(anchor[0]);
          yPos = parseFloat(anchor[1]);

**Comment by nmccready** [comment]
@jmichaliga is correct
