### ISSUE TITLE
Title of infowWindow is wrapping text then overflowing

### ISSUE THREAD

**Issue by adamkarb** [angular-ui/angular-google-maps#1239]
So I have a problem where the title content (The stuff that is going into the info window attached to the marker) is sometimes overflowing the box.  I cannot tweak it to make it work, and am wondering what the directives are doing to achieve this height property.  It looks as though the height is always a multiple of 18px.  Here is a demo of the problem and I'll attach some code.  Any thoughts on why the text is wrapping and overflowing?  Using css there were no properties that I could use to remedy this.

https://fowl-landing.firebaseapp.com/#/geo

     <ui-gmap-google-map center='map.center' zoom='map.zoom' events="events">
            <ui-gmap-markers models="markers" options="'options'" coords="'self'" icon="'icon'">
                <ui-gmap-windows show="show" options="'options'">
                    <p class="window-title" ng-non-bindable>{{title}}</p>
                </ui-gmap-windows> 
            </ui-gmap-markers>    
        </ui-gmap-google-map>
        <form id="report-form">
        <div class="form-group report">
            <label class="label-text" for="hunt-report">Add a report, then click the map to place a marker!</label>
            <textarea ng-model="userInput" id="hunt-report" class="form-control" rows="3" placeholder="Share a little about the hunt..." required></textarea>
        </div>
    </form>

And the JS

    .controller('gMap', function ($scope, uiGmapGoogleMapApi, $firebaseArray, $firebaseObject) {
    console.log('gMap controller works');
    
    $scope.map = {
        center: {
            latitude: 38.2, 
            longitude: -98.5795
        },
        zoom: 4
    };
    
    var mapPins = new Firebase('https://fowl-landing.firebaseio.com/pins');
    
    $scope.userInput = '';
    
    $scope.markers = $firebaseArray(mapPins);
    
    
    $scope.events = {
        click: function (map, eventName, handlerArgs) {
            if ($scope.userInput == '' || $scope.userInput == undefined) {
                    console.log($scope.userInput)
                    return alert("Please fill out a form before placing a marker");
                }
            $scope.$apply(function() {
                //console.log($scope.markers)
                //console.log(handlerArgs)
                
                $scope.markers.$add({
                    id: $scope.markers.length,
                    latitude: handlerArgs[0].latLng.lat(),
                    longitude: handlerArgs[0].latLng.lng(),
                    showWindow: true,
                    title: $scope.userInput,
                    options: {
                        animation: api.Animation.DROP,
                        title: handlerArgs[0].latLng.toUrlValue(),
                        disableAutoPan: true
                    }
                });
               return $scope.userInput = '';
            });
        }
    };

    var api;
    uiGmapGoogleMapApi.then(function(googleMaps) {
        api = googleMaps;
    });
    
    

    

});

**Comment by nmccready** [comment]
It is CSS problems in google maps. Please search bootstap and google maps window style problems.

**Comment by nmccready** [comment]
Here  is some css that will improve your situation immediately.

```
.gm-style img
  max-width: none

.gm-style label
  width: auto; display: inline

.middle
    display table
    width 50%
    margin-left auto
    margin-right auto

/*
Use bootstraps container w/ some overrides, nice thing about this on bootstrap is there is
psuedo element with clearfix and display: table; , all after (which is why I know .middle works above)
*/

.full-width.container
    width 100%
    padding-left 0
    padding-right 0

/*
http://stackoverflow.com/questions/1554893/google-maps-api-v3-infowindow-not-sizing-correctly
*/
.gm-style-iw{
  overflow:auto !important;
  max-width:300px;
  max-height:175px
}
.gm-style-iw > div{
  overflow:auto !important;
  max-width:300px;
  max-height:175px;
}
```
