### ISSUE TITLE
Problems with markers on second map

### ISSUE THREAD

**Issue by vladimir050486** [angular-ui/angular-google-maps#1240]
{"_id":"55126a7eec158c95092edf55","owner":"54f49af28932bc9a95d914e9","title":"check3","phone":"","addressInCity":"","destination":"Kuala Lumpur Federal Territory of Kuala Lumpur Malaysia","about":"Some additional info!!!","date_exec":"2015-04-04T18:30:00.000Z","coords":[{"longitude":101.68685499999992,"latitude":3.139003}],"audio":[],"videos":[],"photos":[],"party":[],"date_created":"2015-03-25T07:57:50.008Z"}

--This is an object I recieve from mongodb, expressjs to angularjs. Objects like this a lot... How should I implement this data to different maps and markers? Because your static data solves problem with markers on more then one map, but what if data is dynamic? I can not make it with data-ng-repeate...

**Comment by vladimir050486** [comment]
I cannot use this service in directive. Why?

**Comment by vladimir050486** [comment]
Data changes in coords field...

**Comment by nmccready** [comment]
Read the documentation. You don't need ng-repeat. Search examples and closed/open issues. Lastly search stackoverflow.

If nothing solves your issue, then create plnkr exhibiting your issue in a small clean example.

**Comment by vladimir050486** [comment]
I need ng-repeat, because I have a lot of data incoming from mongodb...
I'm creating different items with location marked on map. So how would I do it without ng-repeate?

**Comment by nmccready** [comment]
The plural directive takes care of rendering multiple for you. Please read or make and example as I don't see your problem.

**Comment by vladimir050486** [comment]
https://github.com/vladimir050486/eventi/blob/session/public/parts/maintainEvents.html

https://github.com/vladimir050486/eventi/blob/session/public/js/controller.js

page:-> https://enveti.com
login: check1@gmail.com
pwd: xxx
After ---> myevents -> maintainevents    (and vualya)

**Comment by vladimir050486** [comment]
The problem is that all maps displays great, but no markers at all...

**Comment by vladimir050486** [comment]
Or if I change markers to marker and get rid of model, then all markers displays on first map.

**Comment by vladimir050486** [comment]
In master branch there no markers displaying variant and in session branch there markers on one map only.

**Comment by vladimir050486** [comment]
So what about it?

**Comment by vladimir050486** [comment]
Solved issue by covering marker array into markers and using ng-repeat two times...
I can send you my git repo, so you could give advices to people how to solve it...

**Comment by vladimir050486** [comment]
I think your workout in angular-google-maps is really bad!!!
Nothing works proper, what the f...

**Comment by vladimir050486** [comment]
Trying to put labels on markers, it's f....g crazy...
What does work exact as in docs???

**Comment by vladimir050486** [comment]
How to make marker draggable=true??? 
Does this option works only with markers???
