### ISSUE TITLE
Unable to find/access control.getGMap()

### ISSUE THREAD

**Issue by Rmacias12** [angular-ui/angular-google-maps#1243]
I am using **angular-google-maps 2.1.0-X.0 2015-02-27** with **AngularJS 1.3.15**

I have been trying to get direct access to the google map generated once everything initializes, but have been unsuccessful with errors like **TypeError: undefined is not a function**.

The map does end up intializing and displaying, but ultimately I am trying to access `fitBounds()` method fro the `getGMap()` instance that is returned. But it seems that the `$scope.control` object is never being updated with the proper object.

Here is my controller code:
````
app.controller('MainController', 
  ['$scope', 'uiGmapGoogleMapApi', 'uiGmapIsReady', 
  function ($scope, uiGmapGoogleMapApi, uiGmapIsReady) {
    $scope.markers = [
        { latitude: 33.970675, longitude: -118.454618, description:"marker1"},
        { latitude: 34.970675, longitude: -118.454618, description:"marker2"},
        { latitude: 33.974246, longitude: -118.455458, description:"marker3"}
    ]
    $scope.control = {}
    
    uiGmapGoogleMapApi.then(function (maps) {
        $scope.bounds = new maps.LatLngBounds();
        angular.forEach($scope.markers, function (value, key) {
            var myLatLng = new maps.LatLng($scope.markers[key].latitude, $scope.markers[key].longitude);
            $scope.bounds.extend(myLatLng);
        });
        $scope.map = { center: { latitude: $scope.bounds.getCenter().lat(), longitude: $scope.bounds.getCenter().lng() }, zoom: 13 };
        $scope.map.options = { MapTypeId: maps.MapTypeId.SATELLITE };
    });
    uiGmapIsReady.promise().then(function (maps) {
        // This line returns: "TypeError: undefined is not a function"
        $scope.control.getGMap().setZoom(11);
    });
}])
````
And here is my markup
````
        <ui-gmap-google-map center="map.center" zoom="map.zoom" options="map.options" control="control">
            <ui-gmap-marker idkey="$index" coords="item" ng-repeat="item in markers track by $index">
                <ui-gmap-window options="windowOptions" closeclick="closeClick()">
                    <p class="google-window" go-click="/jobs/{{item.jobid}}">{{item.description}}</p>
                </ui-gmap-window>
            </ui-gmap-marker>
        </ui-gmap-google-map>
````

Please help if possible.

**Comment by Rmacias12** [comment]
Actually, I think it is working now:
but upon the first script processing, i get the "undefined" error, but I tried a $timeout and it seems to work:
````
    uiGmapIsReady.promise().then((function (maps) {
        $timeout($scope.setFitBounds,"2000")}));


    $scope.setFitBounds = function () {
        $scope.control.getGMap().fitBounds($scope.bounds);
    }
````

Is there a way to prevent the initial **TypeError: undefined is not a function**

**Comment by nmccready** [comment]
I think someone else reported a problem with isReady. Anyways if you did your control code inside `   uiGmapGoogleMapApi.then(->)` it should work also.

**Comment by Rmacias12** [comment]
I had `ng-controller='Main Controller'` in my markup as well. I removed that and everything is fine now with no errors.

**Comment by nmccready** [comment]
nice find

**Comment by tharrington** [comment]
this does not work for me:

$scope.map.mapControl.getGMap(); is undefined even when called from  uiGmapGoogleMapApi.then(function(maps) {

**Comment by wrummler** [comment]
@tharrington This is one of [our frequently asked questions](https://github.com/angular-ui/angular-google-maps/wiki/FAQ), specifically [this one](https://github.com/angular-ui/angular-google-maps/wiki/FAQ#why-am-i-getting-an-error-when-evaluating-controlgetgmap-why-is-controlgetgmap-undefined). Basically, `uiGmapGoogleMapApi` is for guaranteeing the presence of the `google.maps` object, not the completion of `control` object augmentation. Use the `isReady` service for the latter. If you need to follow-up, please post a new issue with more details [including an MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE). Thanks.
