### ISSUE TITLE
Does anyone know how to get the latest version up to jsDelivr

### ISSUE THREAD

**Issue by runxc1** [angular-ui/angular-google-maps#1247]
I was looking to add the latest version to my script bundle from jsDelivr and it looks like jsDelivr still only has 1.1 which quite old.  Does anyone know how to get the latest up on jsDelivr   http://www.jsdelivr.com/#!angular.google-maps

**Comment by nmccready** [comment]
Go to its github project. My bet is you need to fork it and PR the latest to it.
