### ISSUE TITLE
Cannot selected text of search box on Firefox

### ISSUE THREAD

**Issue by chanchunghao** [angular-ui/angular-google-maps#1248]
Hi, I tried to write a demo for search box <a href="http://plnkr.co/edit/xpIV8yoThChXq7d6sHKG?p=preview">here</a>. It work fine on Chrome, but on Firefox (v36.0.4) I can't selected text in the search box and when I click on the search box, it only focus at the last position. 

Is there something wrong in my code ?

Thank!

**Comment by kandizzy** [comment]
@chanchunghao It's not your code, I see the same behavior. As far as I can tell it's not happening outside of Plunkr- I'm not sure what the issue is yet.

**Comment by wrummler** [comment]
I can't reproduce this in Chrome or Opera, but I can in Firefox, using the downloaded files from Plunker served locally. Guessing it's Google's or Mozilla's issue, not sure which.

**Comment by rockn1994** [comment]
Is this issue resolved ?
