### ISSUE TITLE
ReferenceError: scope is not defined at new DrawingManagerParentModel

### ISSUE THREAD

**Issue by madvas** [angular-ui/angular-google-maps#1249]
I always get error `ReferenceError: scope is not defined` when using `<ui-gmap-drawing-manager>` . 
I did little bit of debugging and found out that this line is invalid: 
https://github.com/angular-ui/angular-google-maps/blob/master/dist/angular-google-maps.js#L4154

`scope.$on('$destroy', (function(_this) {`
Since in the function, there's defined only `scope1` or `this.scope`, so there should be probably `this.scope` instead.

Thanks

**Comment by nmccready** [comment]
Yeah another coffeescript upgrade issue, simple enough fix.

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/parent/drawing-manager-parent-model.coffee#L29

see the issue? scope doesnt exist, just @scope

**Comment by nmccready** [comment]
2.0.19 released
