### ISSUE TITLE
I use ui-gmap-circle  as marker. The marker changes (moves out the location) when I drag map around.

### ISSUE THREAD

**Issue by icn** [angular-ui/angular-google-maps#1251]
http://plnkr.co/edit/03E478Zb7LfIJXz5UmfD?p=preview

I would like the marker sticked to the location I set

**Comment by nmccready** [comment]
This is because the map center is two way bound. You move the map and coords change and since your coords are the same for the circle.. your circle will move.

**Comment by icn** [comment]
Hi @nmccready ,

So how do I fix the circle marker to a fixed lcoation (even when map moving around)?

Thanks

**Comment by nmccready** [comment]
Please think on this.

**Comment by icn** [comment]
@nmccready 
Could you please give a hint? I am totally new on google map and angularjs.

Thanks

**Comment by nmccready** [comment]
Just make a another coordinate object and name it something different. Have the circle bind to that.

**Comment by icn** [comment]
@nmccready 

Thanks

I have tried to add

                 coords ="settings.Location.coords_fix"
or
           position =  "settings.Location.coords_fix"

to

<ui-gmap-circle options="{draggable: true}" center='settings.Location.coords'
                    radius='250'
                      fill='{
                    color: "#08B21F",
                    opacity: 0.5
                }'
                
                 coords ="settings.Location.coords_fix"
            
                  stroke='{
                    color: "#08B21F",
                    weight: 2,
                    opacity: 1 }'
                      clickable='true'
                      draggable='true'
                      editable='false'
                      visible='true'
                  >
                  </ui-gmap-circle>    

It seems not working? How to bind?

**Comment by nmccready** [comment]
This is why I said think cause sometimes you need to figure out things for yourself. But as I said you need to separate the positions/coords.

http://plnkr.co/edit/bbrBO9vcam7jVsmhc0vE

**Comment by NitsanBaleli** [comment]
thank you @nmccready  for the plnkr, I was having the same issue and now it's fixed.

**Comment by sentient** [comment]
I see the deep clone on settings.marker but I don't see it being used. What am I missing?
```    
// WE NEED TO CLONE THE MARKER DEEP (NEW REFERENCE)
// THIS IS BECAUSE THE ORIGINAL LOCATION IS BOUND TO THE MAP CENTER
// THIS WAY THE MARKER STAYS PUT!
$scope.settings.marker = _.clone($scope.settings.Location, true);
```

**Comment by nmccready** [comment]
@sentient can you highlight the lines your talking about by copying urls instead of code.

**Comment by sentient** [comment]
I don't know how I reference a line number in a particular file in the plunkr example.

But it is in the script.js file on line 28. I think it is just some irrelevant code in the plunkr. 
http://plnkr.co/edit/bbrBO9vcam7jVsmhc0vE

**Comment by nmccready** [comment]
What your missing is that the location of the marker is independent of the center of the map. It is just cloning the same lat lon.  Nothing more complicated about it.
