### ISSUE TITLE
uiGmapIsReady resolves only the first time for the second map on page

### ISSUE THREAD

**Issue by megatrond** [angular-ui/angular-google-maps#1252]
Minimal example here: http://jsfiddle.net/dyfe7s8t/1/

Basically, I open a map in a ngDialog, and wait for the map to be ready using the uiGmapIsReady promise. However, this only gets resolved the first time I open the modal. If you close the modal, and then open in again, the promise never resolves.

I have worked around this by calling .promise() with 2 the first time, and then with 1 the subsequent calls. This feels like a super shitty way to do it though...

Am I going about this all wrong, or is this an issue with the directive?

EDIT: Typos

**Comment by nmccready** [comment]
Well there is probably a bug in there. Have you tried digging in?

**Comment by nmccready** [comment]
If you figure it out PR it to 2.0.X first, then it will be rolled to 2.1.X and master.

**Comment by megatrond** [comment]
Seems to be that the uiGmapMap directive is calling reset() on IsReady, and this sets the counter to 0 when it should be decremented.

How can we know how many map instances there are left on the page?

Also, I have absolutely no clue whatsoever how to write coffeescript, but if I manage to find a way to fix it I'll try my best :smile:

**Comment by nmccready** [comment]
cool thanks

**Comment by megatrond** [comment]
Possibly related to #1224

**Comment by evanog** [comment]
Has this issue been fixed yet?

**Comment by megatrond** [comment]
Yes, my PR seems to have made it onto the master branch

**Comment by sime** [comment]
For any people for arrive to this ticket because they find uiGmapIsReady never leaves the pending state, try putting the promise at the top of your controller.

**Comment by armensg** [comment]
@sime I tried that but I still have this issue. The promise never seems to resolve on the second time i  open the modal. The map is only rendered the first time and the second time i get these error 

```
angular.js:13550 angular-google-maps: a center or bounds property is required(anonymous function) @ angular.js:13550(anonymous function) @ angular-google-maps.js:6689processQueue @ angular.js:15961(anonymous function) @ angular.js:15977Scope.$eval @ angular.js:17229Scope.$digest @ angular.js:17045Scope.$apply @ angular.js:17337(anonymous function) @ angular.js:25023jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549
angular.js:13550 searchBox: the events property is required
```
