### ISSUE TITLE
Polylines/Polygons not responding to visible/editable changes

### ISSUE THREAD

**Issue by cmorford** [angular-ui/angular-google-maps#1255]
This bug appears to have been fixed in Issue #1059, but has regressed in version 2.0.17 forward. 

I modified the plnkr from the previous issue to include one polyline and one polygon to toggle visibility.

http://plnkr.co/edit/Ar6kuqf7IQO1HSjoCZ7M?p=preview

**Comment by nmccready** [comment]
Confirmed

**Comment by nmccready** [comment]
Feel like writing a spec for this? That way it is caught in the future?

**Comment by cmorford** [comment]
I'm just getting started into mean stack dev/coffeescript so may take me a little bit to get up to speed.

**Comment by nmccready** [comment]
Np just asking for help as I am getting more active on other projects.

**Comment by ajones-miovision** [comment]
I've also noticed that changes to the path property (setting it to a new array) doesn't seem to get picked up.

**Comment by nmccready** [comment]
Updated plnkr here http://plnkr.co/edit/Ar6kuqf7IQO1HSjoCZ7M?p=preview

**Comment by markmssd** [comment]
I am using the latest version (v2.3.2), and this issue seems to have reappeared for the ```editable``` option.

**Comment by nmccready** [comment]
Please re-open a new issue linking this one.
