### ISSUE TITLE
markers events

### ISSUE THREAD

**Issue by Wouter007** [angular-ui/angular-google-maps#1257]
Hi,

I'm new to both Angular and the Google API, but wanted to try some basic things. When I look at the documentation it says:

>Custom events to apply to the Marker. This is an associative array, where keys are event names and values are handler functions.

>The handler function takes four parameters (note the args are expanding on the original google sdk's default args):
>1. Marker: the GoogleMaps Marker object
>2. ...

So I tried this:

main.html:
```html
    <ui-gmap-google-map ui 
      center='map.center' 
      zoom='map.zoom' 
      options='options' 
      events='map.events'
    >

      <ui-gmap-markers
        models="markerList"
        coords="'self'"
        icon="'icon'"
        events="markerEvents.events"
      >
      </ui-gmap-markers>

    </ui-gmap-google-map>
```
main.controller.js:

``` javascript
$scope.markerEvents = {
        events: {
          click: function(marker) {
            $scope.$apply(function(marker) {
              console.log(marker);
            });
          }
        }
      };
```

But my clicked marker isn't logged. Instead the whole scope is logged. What am I doing wrong?

Thanks for your help.

Wouter.

**Comment by nmccready** [comment]
@Wouter007 take a look at all the arguments passed. All javascript functions always have the `arguments` variable. There you'll see what your looking for.

**Comment by Wouter007** [comment]
Ok, thanks! Got it working :+1:

**Comment by Wouter007** [comment]
This is what I've done:

```javascript
      $scope.markerEvents = {
        events: {
          mouseover: function(marker) {
            marker.model.show = !marker.model.show;
          },
          mouseout: function(marker) {
            marker.model.show = !marker.model.show;
          },
          click: function(marker) {
            $scope.openInfoWindow(marker.model);
          }
        }
      };
```

**Comment by nmccready** [comment]
So this can be closed?

**Comment by Wouter007** [comment]
Yes, thanks for your help.

**Comment by nmccready** [comment]
np
