### ISSUE TITLE
do Rebuild All not working

### ISSUE THREAD

**Issue by leandrozapata** [angular-ui/angular-google-maps#1259]
I need to update my marks after change the model, but not working. This is my angular html code:

![sin titulo](https://cloud.githubusercontent.com/assets/1922237/6948497/981641a4-d884-11e4-8c1a-5b1aac392bd4.png)

and this my controller metod for refresh:

$scope.loadMap = function ()
                {
                   
                    Location.getAll({ from: $scope.filter.from, to: $scope.filter.to, deviceId: $scope.filter.deviceId }, function (data) {
                        
                      //Here update the model
                        angular.forEach(data, function (value, key) {
                            var marker = {};
                            marker.id = value.locationId;
                            marker.title = value.userName;
                            marker.coords = { latitude: value.latitude, longitude: value.longitude };
                            $scope.markers.push(marker);
                        });

                       
                    }, function () {
                     
                    });

                }

Thanks for your help.

**Comment by gitnik** [comment]
Plunker please

**Comment by wrummler** [comment]
Closing this one due to inactivity. Feel free to follow up with requested details. Thanks.
