### ISSUE TITLE
app restart required if started without network?

### ISSUE THREAD

**Issue by motzy** [angular-ui/angular-google-maps#1263]
Hello, I am using angular-google-maps in an Ionic/Cordova app and I used uiGmapGoogleMapApiProvider as recommended.

Everything works fine. The problem is that if I start my app without any connectivity and then turn on connectivity there is no way (that I have found) to reinitialize the gmaps api without restarting my app.

**Comment by nmccready** [comment]
You might want to dig into the uiGmapGoogleMapApi code also did you try refresh and or resizing the google map when the connection came back? Also probably a simple ng-if around the whole map div which is bound to the connection would refresh the map as well. 

If that doesn't work; then youll need to dig in. I am busy among other project and I do not have time to commit to this currently. Therefore I am looking for others to step up.

**Comment by wrummler** [comment]
Closing this one due to inactivity. @motzy Feel free to follow up with more details (e.g. whether the suggested `ng-if` approach or any other approach worked for you). Thanks.

**Comment by motzy** [comment]
Yes, in the end, what worked for me was a full refresh of the page within a timeout (I am unsure as to why it requires the timeout):
```javascript
   $timeout(function(){
          $window.location.reload(true);
   }, 0);
```
Thank you, keep up the great work.
