### ISSUE TITLE
Initiate Map with bounds

### ISSUE THREAD

**Issue by verblick** [angular-ui/angular-google-maps#1264]
Hi,

I have been trying around and stuck on how to set a map by using just bound. The reason that I'm doing is that because we have save the bounds parameters every time user move around the map and push to the URL state.

/map/18.732545042371417,104.92694075700001,16.112240274248013,99.12615950700001

However when I try to init the map only bounds value it doesn't work seems like it needs center and zoom value set also.

Any way I could make this happens?

**Comment by nmccready** [comment]
It requires center and zoom currently, but you can bind bounds as well. So I guess do the math and initially have both. Otherwise make a change and pull request it.

**Comment by jrslv** [comment]
:+1:

**Comment by wrummler** [comment]
Consolidating to issue #1360.
