### ISSUE TITLE
Cannot read property 'getGMap' of undefined

### ISSUE THREAD

**Issue by verblick** [angular-ui/angular-google-maps#1265]
I'm not able to access the map instance with getGMap(). Was searching around and haven't figured out a way to do it. Tried IsReady and it doesn't work too. 

HTML

    <ui-gmap-google-map bounds="map.bounds" center='map.center' zoom='map.zoom' events="events" control="map.control"></ui-gmap-google-map>

Controller

    uiGmapGoogleMapApi.then(function(map) {
        var map = $scope.map.control.getGMap();
    });

**Comment by nmccready** [comment]
You need to assign the control attribute to an object on your end.

`$scope.map.control = {};
uiGmapGoogleMapApi.then(function(map) {
    var map = $scope.map.control.getGMap();
});
`

**Comment by verblick** [comment]
@nmccready  I tried with the code you mentioned and it giving me another error

    // Log TypeError: undefined is not a function
    $scope.control = {};
    uiGmapGoogleMapApi.then(function() {
        map = $scope.map.control.getGMap();
    });

    // This works
    $scope.control = {};
    uiGmapGoogleMapApi.then(function() {
        $timeout(function(){
            map = $scope.map.control.getGMap();
        },  100);
    });

**Comment by nmccready** [comment]
Have you tried debugging the code? Regardless make an example that produces the same error on plnkr.
