### ISSUE TITLE
API services documentation links

### ISSUE THREAD

**Issue by vuxor** [angular-ui/angular-google-maps#1266]
You should change links in your API documentation because they all lead to develop branch and all we get is 404 error.

To reproduce:
- go to http://angular-ui.github.io/angular-google-maps/#!/api
- under Services choose Async, Logger, IsReady or PropMap
- click on Source code link

**Comment by nmccready** [comment]
Please PR fixes to the website branch.

**Comment by vuxor** [comment]
I made pull request to the website branch.
