### ISSUE TITLE
error within chunking iterator: ReferenceError: map is not defined

### ISSUE THREAD

**Issue by BMo-design** [angular-ui/angular-google-maps#1269]
Hi,
I updated my code to the latest version (angular-google-maps 2.1.0-X.8 2015-03-28).
Now I get an error by using polylines: "error within chunking iterator: ReferenceError: map is not defined".
Same error appears in your exmaple files "angular-google-maps-master/example/shapes-lines.html".
Regards
Benedikt

**Comment by nmccready** [comment]
The example probably needs to be updated to 2.1 . Please feel free to update it.

**Comment by BMo-design** [comment]
hm, but I also get this error in my project. Do you not what I have to change?

**Comment by nmccready** [comment]
Did u try debugging it?

**Comment by BMo-design** [comment]
Line 2730  _this.extendMapBounds(map, pathPoints); - map is undefined

**Comment by BMo-design** [comment]
in uiGmapgoogle-maps.directives.api create()

I think you should use "map1"

**Comment by nmccready** [comment]
Did you try your fix and work against that?

**Comment by BMo-design** [comment]
Yes, i changed line 2730 and 2734 from map to map1 -> error disappeared.

**Comment by BMo-design** [comment]
can you please fix that, so that I can use the minified version again :)

**Comment by nmccready** [comment]
PR your fix and I will review it.

**Comment by nmccready** [comment]
Change the corresponding coffee file. Then run `grunt mapAll` then create a pull request (PR).

**Comment by BMo-design** [comment]
:) ... I'm working old fashion without grunt and coffee files.
