### ISSUE TITLE
Change location of circles on map through code

### ISSUE THREAD

**Issue by jjbskir** [angular-ui/angular-google-maps#1271]
Hey, I was able to draw a circle perfectly with this code, but when I went to dynamically change the circle's center later on through code I was not able to unless I also changed the circles radius. Is this a bug or meant to be?

My code to initialize the circle:
```html
<ui-gmap-circle center='circle.center'
            radius='circle.radius'
            fill='circle.fill'
            stroke='circle.stroke'
            clickable='circle.clickable'
            draggable='circle.draggable'
            editable='circle.editable'
            visible='circle.visible'
            events='circle.events'>
		</ui-gmap-circle>
```
```javascript
    $scope.circle = {
        id: 1,
        center: {
            latitude: centerLat,
            longitude: centerlon
        },
        // radius in meters
        radius: 50,
        stroke: {
            color: '#08B21F',
            weight: 2,
            opacity: 1
        },
        fill: {
            color: '#08B21F',
            opacity: 0.5
        },
        geodesic: true, // optional: defaults to false
        draggable: true, // optional: defaults to false
        clickable: true, // optional: defaults to true
        editable: true, // optional: defaults to false
        visible: true, // optional: defaults to true
        control: {}, 
        events: {
            radius_changed: function(googleCircle, eventName, circle) {
            }, 
            center_changed: function(googleCircle, eventName, circle) {
            }
        }
    };
```
What did not change the circles center location on the map:
```javascript 
$scope.circle['center'] = newCords;
```

What did work:
```javascript
$scope.circle['center'] = newCords;
$scope.circle['radius'] = $scope.circle['radius'] + 1;
```

**Comment by nmccready** [comment]
Probably a bug it appears center is not being watched correctly.

**Comment by jjbskir** [comment]
Ok, is there any way to better track the center? Does it have to do with the Angular or Google Maps code?

**Comment by nmccready** [comment]
I am asking you to look at the code, but I am suggesting it is probably an issue with the directive.

**Comment by gitnik** [comment]
Looks like it, `center` is not watched

**Comment by jjbskir** [comment]
Ok, well let me know if there is anything I can do to help fix the bug.

**Comment by nmccready** [comment]
Marking as duplicate and goig with issue #1285

**Comment by nmccready** [comment]
@jjbskir I am not seeing this https://github.com/angular-ui/angular-google-maps/pull/1432/files#diff-d418b8980cee4c4ceee90cddd57dcd67R106 

https://github.com/angular-ui/angular-google-maps/pull/1432/

Can  you please make a plnkr?

**Comment by nmccready** [comment]
No response closing.
