### ISSUE TITLE
Drag operation over map does not work at Chrome

### ISSUE THREAD

**Issue by ComeOutToPlay** [angular-ui/angular-google-maps#1273]
I followed this steps:

1) I took the example for SearchBox from http://angular-ui.github.io/angular-google-maps/#!/api

and I cloned at Plnkr.

  http://plnkr.co/edit/nhTPuPvpQfsX1fKF5aYo?p=preview

I observe it works good, in Plnkr.

2) I put the files at Plnkr in my Web Server.
3) I access my Web Server test from Firefox, and it works well.
4) I access my Web Server test from Chrome and it almost works well.But, the drag operation over the map does not work, even when I am not getting any error at the console.

I am using Chrome Version 41.0.2272.118 (64-bit) on a MAC running OSX Yosemite. I use Mongoose as Web Server.

Any comment will be appreciated

**Comment by ComeOutToPlay** [comment]
I tested the same using ng-map and it happens the same.
I tested using leaflet and it works OK.

So... I think is something from google maps, but not from angular-google-maps.

**Comment by GilbertChan** [comment]
@ComeOutToPlay did you find a solution to this issue? I am having the same issue where drag works on IE and Firefox but not in Chrome.
