### ISSUE TITLE
Angular Material and Angular Google Maps second render doesn't show

### ISSUE THREAD

**Issue by mdelgadov** [angular-ui/angular-google-maps#1274]
When using angular google maps 2.0.19 and angular material, a Google Map displays properly the first time it loads. But if the user clicks on a different state and then comes back, without reloading, of course, it only displays a corner of the original map.

![untitled](https://cloud.githubusercontent.com/assets/1537551/7131306/695bc3c2-e24b-11e4-9204-c24c55d14205.png)

Notice on the left the angular material look and on the right the empty space in darker gray, where the rest of the map should show.

The configuration is pretty vanilla:

       <ui-gmap-google-map draggable="true"
             pan="true"
            zoom="map.zoom"
            dragging="true"
            center="map.center"
            events="map.events"
            control="map.control"
            refresh="true">
And the loading from the controller also:

              $scope.map = addressStore.setMap({lat: address.latitude,
                        lng: address.longitude}); 
              //...also loads other parameters.

I also use the recommended configuration:

    .config(function (uiGmapGoogleMapApiProvider) {
        uiGmapGoogleMapApiProvider.configure({
            //key: 'your api key',
            v: '3.17',
            libraries: 'weather,geometry,visualization'
          });
      })

          uiGmapGoogleMapApi.then(function (maps) {
                $scope.googleVersion = maps.version;
                maps.visualRefresh = true;
            });

In a previous project had the same problem with Angular UI but got solved with this command at the begining of the controller:

        google.maps.visualRefresh = true;
But then I moved to Angular Material in this app and the problem showed again.

Thanks in advance.

**Comment by nmccready** [comment]
This is all over the place (for answers), this is a google thing. The map needs to be told to resize when it is hidden. If it is removed via ng-if there are no issues.

**Comment by emps** [comment]
mdelgadov i have fixed this problem
