### ISSUE TITLE
ng click in gmaps-window doesnt work

### ISSUE THREAD

**Issue by gerlstar** [angular-ui/angular-google-maps#1275]
Why is it that in order for getDirections to be called, it has to be in $root ? My ui-gmap below is already assigned to a controller via routes. Here is its source:

                 angular.module('projApp').controller('MainCtrl', function ($scope) { 
                  //this works
                  $scope.$root.getDirections = function () {alert('here')};

                  //this should work!
                  $scope.getDirections = function () {alert('here')};
                }

HTML

                <ui-gmap-google-map center='mapInfo.map.center' zoom='mapInfo.map.zoom'>
                 <ui-gmap-marker coords="mapInfo.marker.coords" options="mapInfo.marker.options" idkey="mapInfo.marker.id">
                 <ui-gmap-window ng-cloak closeClick="closeClick()">
                    <ui-gmaps-window>
                        <a ng-click="getDirections()" class="location" href="#">Doesnt work</a>
                        <a ng-click="$root.getDirections()" class="location" href="#">works</a>
                    </ui-gmaps-window>      
                  </ui-gmap-window>
              </ui-gmap-marker>
          </ui-gmap-google-map>

**Comment by nmccready** [comment]
use template or templateUrl as your window template and bind it to a controller. There are examples of this.

**Comment by gerlstar** [comment]
I found this in your example.html

         <ui-gmap-window show="map.templatedInfoWindow.show" coords="map.templatedInfoWindow.coords"
                options="map.templatedInfoWindow.options"
                templateUrl="map.templatedInfoWindow.templateUrl"
                templateParameter="map.templatedInfoWindow.templateParameter" ng-cloak>
        </ui-gmap-window>


      templatedInfoWindow: {
        templateUrl: 'assets/templates/info.html',
        templateParameter: {
          message: 'passed in from the opener'
        }
      },


    <div ng-controller="InfoController" style="white-space:nowrap">
    <div ng-cloak>
        <strong>I'm loaded from an external template, yay!</strong>
        <div ng-cloak>
            Parameter from opener: {{ parameter.message }}
        </div>
        <div ng-cloak>
            Template specific: {{ templateValue }}
        </div>
    </div>
</div>

I dont want controller defined like the one above. I have my controller  in routes. Therefore I have this: 

    <ui-gmap-google-map center='location.mapInfo.map.center' zoom='location.mapInfo.map.zoom'>
                    <ui-gmap-marker coords="location.mapInfo.marker.coords" options="location.mapInfo.marker.options" idkey="location.mapInfo.marker.id">
                        <ui-gmap-window ng-cloak closeClick="closeClick()" templateUrl="'components/map.html'">                          
                        </ui-gmap-window>
                    </ui-gmap-marker>
                </ui-gmap-google-map>

but now whenever I click on the marker, I get the error 
![screen shot 2015-04-21 at 10 55 32 am](https://cloud.githubusercontent.com/assets/3219706/7255069/fed478bc-e814-11e4-9e1e-7879fa75baf7.jpg)

**Comment by adam-back** [comment]
@gerlstar, did you ever resolve this? I'm having a similar issue with an Ionic project...

**Comment by wrummler** [comment]
@gerlstar If you can follow up, please include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) so that we can continue looking into this for you. Plunker is preferred, but anything you're comfortable with is also fine as long as it works. Thanks.

@adam-back Definitely feel free to add a link to an example of your own. Thanks.

**Comment by wrummler** [comment]
Closing this one due to inactivity. Feel free to follow up with requested details. Thanks.
