### ISSUE TITLE
Per-model click handler error: "click is not a function"

### ISSUE THREAD

**Issue by bensgroi** [angular-ui/angular-google-maps#1276]
In the ui-gmap-markers controller, I can't seem to get the per-model click handler to work. If I use 

    <ui-gmap-markers models="markers" coords="'self'" click="'onClick'"></ui-gmap-markers>

I get the error "click is not a function", even though there's only one marker and it has a `onClick` function. If instead I use

    <ui-gmap-markers models="markers" coords="'self'" click="clickMarker"></ui-gmap-markers>

and have a function on the controller `clickMarker`, it works correctly. The problem is, the `this` context in `clickMarker` ends up as the window, which means that when using this with the "controller as" syntax, I can't access the rest of the controller.

According to the documentation, using the first method should work. Is this a new issue?

Example Plunker: http://plnkr.co/edit/g4wnztDgePNPaRs8GE1W?p=preview (See the console for the error)

**Comment by cthrax** [comment]
If I'm understanding correctly, you have a couple things incorrect. The click attribute should be an angular expression, not a string AND it should be a call to the function itself, not just the name of the function.

Additionally, if you want to modify 'this' than you need to use javascript's bind function when defining the function. Here's an example. http://plnkr.co/edit/23z6mdjWjzZ3mngFjhLz?p=preview

**Comment by bensgroi** [comment]
The documentation pretty clear states that "click" can be a string that represents a function on the marker's model, or an Angular expression. From the documentation:

    click: //used as "'someProp'" or '"someProp"' , notice the quotes!! otherwise a normal expression (non special quotes)

So this functionality must have been removed and the documentation wasn't updated.

**Comment by cthrax** [comment]
It does look that way, we'd welcome a patch to the documentation if you're willing. I know there was a massive overhaul in this area which prompted the major rev bump. Not sure what you're updating from or to, but it would not be surprising if this was missed during that time. We're sorely hurting for additional contributors on this project because the 5k unique visitors each month can find and file more bugs and features than we can currently keep up with.

**Comment by bensgroi** [comment]
Okay, makes sense. I'll take a look and see if I can contribute. Thanks for your help!
