### ISSUE TITLE
Can not use parentdiv with search-box

### ISSUE THREAD

**Issue by DanSimchi** [angular-ui/angular-google-maps#1278]
When I'm trying to add the attribute parentdiv to the ui-gmap-search-box element, the search box  is gone. it's a known issue?

**Comment by kandizzy** [comment]
@DanSimchi would you make a plunkr of this please?

**Comment by kandizzy** [comment]
It is working in this plunkr. Please let me know if you have issues in your code, and please provide your own plunkr if so.
http://plnkr.co/edit/1rpXQhcZqwJ7rv0tyK9P?p=preview

**Comment by DanSimchi** [comment]
Thanks! 
It was my mistake.:)

**Comment by DanSimchi** [comment]
Thanks!
It was my mistake. sorry for that:)
