### ISSUE TITLE
Searchbox outside map ! 

### ISSUE THREAD

**Issue by Sshuichi** [angular-ui/angular-google-maps#1279]
Hello ! Can we use the searchbox outside the map, like a normal input ? 
if yes, how do we proceed ?

**Comment by kandizzy** [comment]
@Sshuichi yes, please use the `parentdiv` param in the search-box directive API.

**Comment by Sshuichi** [comment]
Hello Carrie ! 
It does not work unfortunately .. 
I always need to wrap the search box inside the map tag

**Comment by kandizzy** [comment]
@Sshuichi Ok, it used to work in the example. I'll make a plunkr and see what's up with it.

**Comment by kandizzy** [comment]
It is working in this plunkr. Please let me know if you have issues in your code, and please provide your own plunkr if so.
http://plnkr.co/edit/1rpXQhcZqwJ7rv0tyK9P?p=preview

**Comment by Sshuichi** [comment]
Thanks ! now it's clear.
So should I understand that the search box should be always wrapped inside the map ? 
I want to use only the text input, if possible

**Comment by kandizzy** [comment]
Yes, it has to be wrapped in the map directive. To use it alone will be an enhancement, I'll have to give that some thought.

**Comment by Sshuichi** [comment]
Thank you very much.

**Comment by koop4** [comment]
any update about this request?
