### ISSUE TITLE
Auto Panning for custom window stops working after applying

### ISSUE THREAD

**Issue by kelvinw88** [angular-ui/angular-google-maps#1281]
I am having an issue where it pans to the wrong location / not fully correct location  when I auto pan happens for custom window.
Wondering If I am the only person facing this issue

Thanks

**Comment by funkflute** [comment]
I'm getting the same thing. The first time I show my window (ui-gmap-window) it auto-pans. But if I hide it, then show it again, (in my case by clicking on another marker) it does not auto-pan.

**Comment by darsee** [comment]
Not sure if this will help, but I was seeing similar behaviour: clicking a marker near the edge of the map would pan to fit the InfoWindow, but clicking another marker (without closing the first) would not pan the map.

I found that if I called `hideWindow` on the window control in the marker click event, the map panned as expected. Here are the relevant bits of my map config:

```
$scope.map = {
    markersEvents: {
        click: function(marker, eventName, model) {
            $scope.map.window.control.hideWindow();
            $scope.map.window.model = model;
            $scope.map.window.show = true;
        }
    },
    window: {
        control: {},
        show: false
    }
};
```

**Comment by wrummler** [comment]
I've got an app with the same setup (one window shared among multiple markers, autopan when opened/reopened on each marker), but I haven't observed this behavior. The map pans to fit the window every time.

Could someone provide a verifiable example (using Plunker/JSFiddle/etc) showing this behavior? We can reopen and investigate more when we have that. Thanks.
