### ISSUE TITLE
Circle events

### ISSUE THREAD

**Issue by simon-jouet** [angular-ui/angular-google-maps#1285]
Hi,

So on angular-google-maps 2.0.16 .. 2.1.0 (haven't tried any previous version) the circle events are not triggered and the changes in center / radius are not reflected on the model. After a short walk through the code the problem is with scope.events on the circle, if it is not set then the listeners event are not set.

The quick fix is to define events (event it points to an empty object) and the changes will be reflected on the model. This bug might be related to #1271

**Comment by FELS-michael** [comment]
+1 This had me stumped for quite some time till I decided to see if I could get the radius change via the events and suddenly the bindings worked

**Comment by nmccready** [comment]
Thanks, I'll try to check this out and fix it.

**Comment by nmccready** [comment]
@simon-jouet can u check this against master and see if it is still an issue?

**Comment by nmccready** [comment]
Closing and going forward with #1328
