### ISSUE TITLE
Marker Window data not showing.

### ISSUE THREAD

**Issue by andrewuscf** [angular-ui/angular-google-maps#1287]
So I have been looking up the issues but can not seem to find one similar to mine. I know you can't you ng-repeat and such inside the ui-gmap-window. But I am trying to get it to display data in the window it displays in the outside of the map but not in the window. here is the template.

    <div ng-controller="MainCtrl">

    <ui-gmap-google-map center="map.center" zoom="map.zoom" draggable="false"
                            options="map.options" events="map.events" control="googlemap" class="angular-google-map-container">

        <ui-gmap-window coords="MapOptions.markers.selected.coords"
                        show="windowOptions.show" options="windowOptions" closeClick="closeClick()" ng-model="MapOptions.markers">
                    <p models="MapOptions.markers" >{{ MapOptions.markers.selected.data }}</p>
            </ui-gmap-window>

         		<ui-gmap-markers models="markers" idkey="markers.id" coords="'coords'"
                             click="onClick" events="markers.events" doCluster="true">

        		</ui-gmap-markers>

         	</ui-gmap-google-map>
    <p ng-model="MapOptions.markers" >{{ MapOptions.markers.selected.data }}</p>
    </div>

and here is the controllers:

   .controller('MainCtrl', function ($scope, $http, uiGmapGoogleMapApi, uiGmapIsReady) {

    uiGmapGoogleMapApi.then(function (maps) {
        $scope.googlemap = {};
        $scope.map = {
            center: {
                latitude: 37,
                longitude: -122
            },
            zoom: 4,
            pan: 1,
            options: $scope.mapOptions,
            control: {},
            events: {
                tilesloaded: function (maps, eventName, args) {},
                dragend: function (maps, eventName, args) {},
                zoom_changed: function (maps, eventName, args) {}
            }
        };
    });

    $scope.windowOptions = {
        show: false
    };

    $scope.onClick = function (data) {
        $scope.windowOptions.show = !$scope.windowOptions.show;
        //console.log(data.Lf.Cb.model.data);
    };

    $scope.closeClick = function () {
        $scope.windowOptions.show = false;
    };

    $scope.title = "Window Title!";

    uiGmapIsReady.promise() // if no value is put in promise() it defaults to promise(1)
    .then(function (instances) {
    })
        .then(function () {
        $scope.addMarkerClickFunction($scope.markers);
    });

    $scope.markers = [];
    $http.get('http://localhost:8000/api/companies/?format=json').success(function(data) {

        data.forEach(function (item){
            var newMarker = {
                id: item.id,
                coords: {
                    latitude: item.latitude,
                    longitude: item.longitude
                },
                data: item.name
            };

            $scope.markers.push(newMarker);
        });
    }).then(
        $scope.addMarkerClickFunction = function () {
            var newmark = $scope.markers;
            newmark.forEach(function (value) {
                value.onClick = function () {
                    $scope.onClick(value.data);
                    $scope.MapOptions.markers.selected = value;
            };
        });
    }
    );

    $scope.MapOptions = {
        minZoom: 3,
        zoomControl: false,
        draggable: true,
        navigationControl: false,
        mapTypeControl: false,
        scaleControl: false,
        streetViewControl: false,
        disableDoubleClickZoom: false,
        keyboardShortcuts: true,
        markers: {
            selected: {}
        },
        styles: [{
            featureType: "poi",
            elementType: "labels",
            stylers: [{
                visibility: "off"
            }]
        }, {
            featureType: "transit",
            elementType: "all",
            stylers: [{
                visibility: "off"
            }]
        }]
    };
});

**Comment by nmccready** [comment]
@andrewuscf look at the examples and look into the attributes template , templateUrl, and templateParam. This is what you should use.
