### ISSUE TITLE
Any way of reducing file size?

### ISSUE THREAD

**Issue by jon64digital** [angular-ui/angular-google-maps#1288]
Firstly, let me say that Angular Google Maps is a great product and I've already used it very effectively in one website :)

The trouble is that I've been trying to optimize a new site and have >530k javascript including all the Angular libraries, jQuery and a jQuery carousel plugin. I noticed that Angular Google Maps alone is 190k and depends on lodash which is another 50k and I'm not using otherwise.

I know there are lots and lots of features that I will never use so I wondered if there's any way to reduce it down to it's basic functionality (include a map, basic centering/scrolling, a few markers and maybe info windows when you click on a marker) to get this file size down a bit?

I'll never use polygons, heat map layers or anything like that on a basic site, I just can't justify >240k to put a simple map on a website (e.g. a simple search which plots results on a map).

Anybody got any ideas?

**Comment by gitnik** [comment]
You will probably need to do that yourself. I don't see us providing different versions with different functionality

**Comment by jon64digital** [comment]
OK thanks, I understand that. I'll have to have a look through the codebase and see if I can roll my own :)

**Comment by nmccready** [comment]
To tell you the truth we just did this with streetviewpanorama on 2.1.X. If you want to make the concat grunt part and PR it by all means do it. Just give it a respective name for the dist out.
