### ISSUE TITLE
Custom parameter in the marker

### ISSUE THREAD

**Issue by lcpereira** [angular-ui/angular-google-maps#1291]
Hello,

I can't assign a custom parameter in the marker? For example, I want the marker has the attribute "name", so when I raise the event "click", the object that would return, would also the attribute "name", is it possible?

**Comment by wrummler** [comment]
AGM doesn't support extending API objects. What you want is possible, but you'd need to grab the `google.maps.Marker` instance itself (which can be facilitated by the marker directive's `control` parameter; see AGM's docs) and do the extension yourself.
