### ISSUE TITLE
Using Gmap methods such as fitBounds on Angular-Google-map?

### ISSUE THREAD

**Issue by CoenWarmer** [angular-ui/angular-google-maps#1292]
Is it possible to call Gmap API functions like fitBounds on a map object spawned by angular-google-map? If so, how? :)

**Comment by cdownie** [comment]
You need to grab a reference to the GMap object, can do so like:

$scope.map.mapControl.getGMap();

**Comment by CoenWarmer** [comment]
Awesome, thanks!

**Comment by CoenWarmer** [comment]
When I use ```$scope.map.mapControl.getGMap();``` in my controller, I'm seeing

TypeError: Cannot read property 'mapControl' of undefined

I'm setting a map with:

```javascript
      $scope.map = {
        center: {
          latitude: latitude,
          longitude: longitude
        },
        zoom: 16,
        bounds: {}
      };
```

I'm of course calling $scope.map.mapControl.getGMap() after I set the map. What am I doing wrong?

**Comment by cdownie** [comment]
Sometimes the timing can be off, and you end up calling it before the map is fully initialized. There is  an IsReady service that returns a promise you can use, I've also had success using a watch that waits until mapControl exists:

$scope.$watch($scope.map.mapControl, function(){ //do some stuff })

Addtionally, make sure to assign control in the directive markup:

<ui-gmap-google-map bounds='map.bounds' control="map.mapControl">
