### ISSUE TITLE
Map centers to infoWindow on Marker Close

### ISSUE THREAD

**Issue by nolandubeau** [angular-ui/angular-google-maps#1293]
Hi,

I am noticing strange inconsistent behaviour when displaying markers with ng-repeat vs the model approach.  See the following snippets: 

///// ng-repeat
 <ui-gmap-marker ng-repeat="m in alertMarkers" coords="m" icon="m.icon" click="onMarkerClicked(m)" doCluster="map.cluster" idKey="m.id" options="m.options">
                <ui-gmap-window ng-cloak>
                    <div>
                        <p class="fs-subhead">{{m.info.event}}</p>
                        <p>Sender: {{m.info.senderName}}</p>
                        <p>Coordinates: {{ m.latitude | number:4 }}, {{ m.longitude | number:4 }}!</p>
                    </div>
                </ui-gmap-window>
            </ui-gmap-marker>

///// models
           <ui-gmap-markers models="alertMarkers" coords="'self'" icon="'icon'" click="onMarkerClicked" doCluster="map.cluster">
    <ui-gmap-windows show="'showWindow'" ng-cloak doRebuildAll="false">
        <div>
            <p ng-non-bindable class="fs-subhead">{{info.event}}</p>
            <p ng-non-bindable>Sender: {{info.senderName}}</p>
            <p ng-non-bindable>Coordinates: {{ latitude | number:4 }}, {{ longitude | number:4 }}!</p>
        </div>
    </ui-gmap-windows>
</ui-gmap-markers>

Let's say I have two markers in the alertMarkers array, and both infoWindows are open.  One marker is in Montreal, and one marker in Toronto.

When using the models approach if I close the marker in Montreal, the map automatically centers/focuses to the marker/infoWindow in Toronto.

If I replace the models code with the ng-repeat approach, the above does not happen.  If I close the infoWindow in Montreal, the map stays in the current position.  This is the behaviour that I want to achieve with the models approach, and I would prefer to use the models approach for performance reasons.

Is there a way to prevent this behaviour when using the models approach?

On a side note, it appears that the doCluster option does not work when using ng-repeat.

Thanks!

Nolan

**Comment by gitnik** [comment]
1. Don't use ng-repeat with markers
2. Create a plunker

**Comment by wrummler** [comment]
Closing this one due to inactivity. Feel free to follow up with requested details. Thanks.
