### ISSUE TITLE
labelAnchor is undefined

### ISSUE THREAD

**Issue by stenmuchow** [angular-ui/angular-google-maps#1295]
It seems sometimes as I navigate around my app and change map coordinates I get this error:

http://puu.sh/hnTWR/43e8cc18ce.png

It's related to function below. the variable anchor is undefined and the app crashes. If I pass it a new constructor function when anchor is undefined then it seems to fix the problem. Maybe there is something deeper going on here. I dont know. This however has fixed the issue.

```javascript
  var anchor = this.marker_.get("labelAnchor") || new google.maps.Point(0,0);
```

I am more than willing to submit a PR, but first I want to make sure its approved.

```javascript
/**
 * Sets the anchor point of the label.
 * @private
 */
MarkerLabel_.prototype.setAnchor = function () {
  var anchor = this.marker_.get("labelAnchor") || new google.maps.Point(0,0);
  this.labelDiv_.style.marginLeft = -anchor.x + "px";
  this.labelDiv_.style.marginTop = -anchor.y + "px";
  this.eventDiv_.style.marginLeft = -anchor.x + "px";
  this.eventDiv_.style.marginTop = -anchor.y + "px";
};
```

**Comment by dlukez** [comment]
Looks like the same problem I encountered. See https://github.com/angular-ui/angular-google-maps/pull/1294
