### ISSUE TITLE
Sending api key to Google (for 'Google Maps API for Work')

### ISSUE THREAD

**Issue by armyofda12mnkeys** [angular-ui/angular-google-maps#1296]
Hey, 
I saw this ticket related to sending up the Google API key:
https://github.com/angular-ui/angular-google-maps/issues/1121
(we use 'Google for Work' so we can use Google maps on our secure https websites, and maybe also for getting 'more requests allowed')

and was just curious:
Here is my app config (with our api key blurred out):
https://flic.kr/p/rZtFvs
The config part I used is copied from above and put into my main .config() func for the module:
```  
uiGmapGoogleMapApiProvider.configure({
      client : 'our-companys-key',
      v: '3.17',
      libraries: 'weather,geometry,visualization'
});
```

and here is a pic of the network request I see going to google when the angular-google-map gets displayed on the page:
https://flic.kr/p/sgZUxK

Shouldn't the api-key be appended in the params?

Thanks for any advice to get this working,
Ari

**Comment by nmccready** [comment]
I think all you should have to do is the below.
```
uiGmapGoogleMapApiProvider.configure({
      client : 'our-companys-key',
      v: '3.17',
      libraries: 'weather,geometry,visualization'
      key: 'YOUR_API_KEY'
});
```

**Comment by armyofda12mnkeys** [comment]
So like that JIRA states "To use Google Maps for Work, you specify your client ID in the URL requests rather than an API key" so like i wouldn't use the 'api-key' but only the 'client' param. 
Yet 'client' isn't being passed it looks like. 
Like shouldn't I see that param being passed to the http://maps.google.apis.com/maps/api/js?sensor=false network request?
I dont...

On a comparision, our prod server which doesn't use angular-google-maps calls the google maps api directly in a url like so:
https://maps-api-ssl.google.com/maps/api/js?v=3&client=OurCompanyKey&sensor=false&language=en

Maybe something changed in the plugin as in the referenced JIRA, the original poster made it seem like it was passing that client variable in the request.

(Also on a sidenote wondering if you can specific to use https:// in the api request to google so 'Google for Work' can work correctly since we use it on https websites and i assume the communication to 'Google for Work' also has to be https?)

**Comment by nmccready** [comment]
Ok, your correct via:
https://developers.google.com/maps/documentation/javascript/tutorial#Loading_the_Maps_API
https://developers.google.com/maps/documentation/business/clientside/#client_id

Make the necessary changes to make it work correctly and submit a PR.

**Comment by nmccready** [comment]
I would it make it flexible to take either more options or handle of `transport` and `isGoogleMapsForWork`.

```
uiGmapGoogleMapApiProvider.configure({
      client : 'our-companys-key',
      v: '3.17',
      libraries: 'weather,geometry,visualization'
      key: 'YOUR_API_KEY'
      transport: 'http'
      isGoogleMapsForWork: true
});
```
Then in the [maploader/GoogleMapApiProvider](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/providers/map-loader.coffee#L13-L14)

Use lodash omit
```
query = _.map _.omit(options, ['transport', 'isGoogleMapsForWork']), (v, k) ->
          k + '=' + v
```

**Comment by nmccready** [comment]
Of course there is some more basic stuff left but I think I gave you enough to run.

**Comment by armyofda12mnkeys** [comment]
Cool thanks nmccready! i'll take a look :).

**Comment by nmccready** [comment]
When your done please submit the PR to 2.0.X branch so it can be merged to 2.1.X -> master

**Comment by nmccready** [comment]
This fix is relevant to both branches.

**Comment by armyofda12mnkeys** [comment]
Hey nmcready, 
This is my first time editing coffeescript and using git (still using svn at work hehe) ... 
I shouldn't do a PR request unless the code is 100% working, right?
So any issues I should bring up here before the PR request?

I forked 2.0x branch and submitted the changes within my fork.
The appropriate changes are very minimal and I compiled the coffeescript by running grunt 'grunt && grunt mappAll', but the map doesn't even show (not even for the normal options without params I added like below (which I checked and aren't passed with the request):
```
  uiGmapGoogleMapApiProvider.configure({
      v: '3.17',
      libraries: 'weather,geometry,visualization'
      //client: 'our-company-key',
      //key: 'test-should-remove-if-using-client-param',
      //,transport: 'https',
      //,isGoogleMapsForWork: true
  });
```
The request looks good to me:
https://maps.googleapis.com/maps/api/js?v=3.17&libraries=weather,geometry,visualization&language=en&sensor=false&callback=onGoogleMapsReady801

Is there anyway you can take a look and see why its breaking the map since the changes are very minimal?
Wondering if its another commit that may have broke it.
My changes are in:
https://github.com/armyofda12mnkeys/angular-google-maps/blob/2.0.X/src/coffee/providers/map-loader.coffee

Kinda stumped, but let me know if there's anything I can do from my end,
Thanks,
Ari

**Comment by armyofda12mnkeys** [comment]
So quick followup, I compiled that 2.0x branch without my changes within the bower_components/ folder (just in case other files are referenced inside of the project other than dist/) and still get a grey map.
Hmm, is the 2.0x branch temporarily broken?

**Comment by armyofda12mnkeys** [comment]
EDIT: deleted my last 2 comments, realized the 'grey map' was showing up because I edited the template for the map itself the other day and removed the ui-gmap-google-map's center attribute hoping that ui-gmap-markers' fit attribute would fit all the markers without the need to specifying a center point. I added that center attr back in and looks good, i'll request a PR now :).

**Comment by chandoo** [comment]
We need to send 'channel' through the configuration of uiGmapGoogleMapApiProvider. Is there already a configuration parameter for it?

**Comment by nmccready** [comment]
Add it to options any option you add will be put into the query
