### ISSUE TITLE
Searchbox-> protocol undefined

### ISSUE THREAD

**Issue by pziegler** [angular-ui/angular-google-maps#1297]
Hello all,
Ive been trying to add in a maps/searchbox (http://plnkr.co/edit/tpOrGY6wa06cCTPtZFr7)
I created a plinkr with most other stuff stripped out.. I can't figure out why it isnt working. Can someone help me pls? I keep geeting this protocol undefined.
I have looked at the other threads and I don't see where mine is much different than the example..

**Comment by kandizzy** [comment]
@pziegler this works for me. I didn't change much of your code. http://plnkr.co/edit/GkyystN317qUJBhVifNY?p=preview

**Comment by pziegler** [comment]
yeah, thx.. but when I try to use it in my full app things break ;/
http://plnkr.co/edit/6ML888aM9O4R0TItCWO1
any idea ?

**Comment by kandizzy** [comment]
The changes I made to make this work were providing the correct path to the scripts.js and styles.css, nothing changed in regards to this directive. I think it's a debugging problem rather than a problem with this directive.

**Comment by kandizzy** [comment]
I looked at it for you because just because I know where to look- your reference to the parent div was incorrect. It was a string, not an expression. Then you needed a bit of CSS to make sure that .pac-container would show.

http://plnkr.co/edit/tx3l4G7cjhbNvizeArBF?p=preview

Hope this helps.

**Comment by pziegler** [comment]
thx so much!
