### ISSUE TITLE
Ionic js support?

### ISSUE THREAD

**Issue by eangeles92** [angular-ui/angular-google-maps#1300]
Does angular-google-maps work using the ionic framework?(http://ionicframework.com/) Has anyone done this and seen results? thanks

**Comment by nmccready** [comment]
Search issues closed and open and there should be some.

**Comment by eangeles92** [comment]
how is this a duplicate? incorrect label.

**Comment by cthrax** [comment]
@eangeles92 if you do a quick search through issues, you'll find a plethora of ionic questions and answers. So this is a duplicate of all of those. It boils down to the project has no ionic champion and the biggest contributors do not use ionic, so it might accidentally work, but no support/testing goes into making it work.

**Comment by nmccready** [comment]
We need a champion for that.

**Comment by eangeles92** [comment]
yeah I'm trying to write an ionic app and hopefully put it into production using this awesome library but I'm running into issues. It works well in the browser but not when I run it in the ionic emulator. @nmccready I volunteer to look more into it and share my knowledge.

**Comment by eangeles92** [comment]
btw Ionic is based on angular so I would have thought it would be quite seamless to integrate angular google maps into an ionic app.

**Comment by kandizzy** [comment]
Hi @eangeles92 I am aware issues with SearchBox and Autocomplete selection when using ionic- there are a bunch issues referencing this. I'll make any changes necessary to this directive to support this, but as mentioned I don't use ionic- so any development environment you set up for testing would really help. Let me know if you do. Thanks!
