### ISSUE TITLE
Safari crash on iPad

### ISSUE THREAD

**Issue by larsha** [angular-ui/angular-google-maps#1302]
Hi,

Using angular google maps with approximately 300 markers on the map (using clustering) and when on a high zoom level (e.g. 15) and zooming out fast the app crashes safari and safari reloads on iPad Air 2 running iOS 8.1.

This also happens on the demo map here: http://angular-ui.github.io/angular-google-maps/#!/demo

I have also tried removing clustering, minimizing markers to about 10 with no luck. Removing markers completely or simply adding one marker seems to solve the problem.

Can anyone point me in the right direction or know anything about this?

**Comment by nmccready** [comment]
try setting chunk="false" on markers and see if that helps at all.

**Comment by larsha** [comment]
That didn't solve the problem, however I think I have found the problem. 

I'm using this on my markers:

```
labelContent: '',
labelAnchor: '',
labelClass: ''
```

I assume angular google maps is using markers with label for this or am I wrong? It seems to be a problem with just marker with label plugin. I also did a rewrite of my app not using angular google maps and using marker with label, and that app also worked fine until I added the marker with label plugin with custom html to each marker.

**Comment by deliriousrhino** [comment]
@larsha what do you mean by using InfoWindow as a label?

**Comment by wrummler** [comment]
Marking this with external due to @larsha's rewrite w/o AGM still exhibiting the problem.

Closing due to found alternative:

> Using InfoWindow as a label seems to solve the issue.

Follow-ups with other alternatives and relevant discussion are still welcome. Thanks.
