### ISSUE TITLE
Window not rebuilt after coords are added asynchronously. 

### ISSUE THREAD

**Issue by geralddzx** [angular-ui/angular-google-maps#1304]
I added a marker that doesn't have coords at first. I used geocoder to add the coords later. However, this will draw the marker on the map when the coords are added later but the window will not work.

**Comment by wrummler** [comment]
It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it demonstrates the behavior you're asking about. Thanks.

**Comment by wrummler** [comment]
Closing this one due to inactivity. Feel free to follow up with requested details. Thanks.
