### ISSUE TITLE
Position for custom icon

### ISSUE THREAD

**Issue by ollietreend** [angular-ui/angular-google-maps#1309]
Hi,

When using custom icons on markers, is it possible to set the position of that icon?

It looks like the default alignment for custom icons is to assume that the 'point' is in the centre of the bottom edge of the image.

However my icon looks like this:
![Custom icon](http://i.imgur.com/JuZK6UA.png)

I know this is possible with the Google Maps API by using the Icon object. However since the ngMarker directive takes care of this, I wonder whether this is possible?

Thanks

**Comment by jmichaliga** [comment]
You can set the origin offset on the icon. Very much like,
icon:{url:'image.png', origin: new google.maps.Point(40,50) }

On Mon, May 4, 2015 at 12:26 PM, Ollie Treend <notifications@github.com>
wrote:

> Hi,
>
> When using custom icons on markers, is it possible to set the position of
> that icon?
>
> It looks like the default alignment for custom icons is to assume that the
> 'point' is in the centre of the bottom edge of the image.
>
> However my icon looks like this:
> [image: Custom icon]
> <https://camo.githubusercontent.com/9b26c2aa4372a42792271c4aa4da9765df2757d2/687474703a2f2f692e696d6775722e636f6d2f4a755a4b3655412e706e67>
>
> I know this is possible with the Google Maps API by using the Icon object.
> However since the ngMarker directive takes care of this, I wonder whether
> this is possible?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/angular-google-maps/issues/1309>.
>



-- 
Justin Michaliga

(901) 264-9244

www.jmichaliga.com
twitter.com/jmichaliga

**Comment by wrummler** [comment]
@ollietreend Closing this one. Feel free to follow-up with details if the question wasn't answered. Thanks.
