### ISSUE TITLE
Google Maps InfoWindow Width Stuck at 707px

### ISSUE THREAD

**Issue by bernhardmostrey** [angular-ui/angular-google-maps#1311]
I'm using Angular Google Maps to integrate Maps in my website.

I have a div inside my infowindow that has a width and height set, this works fine until I set it bigger than 707px, then it doesn't size any bigger.

I have my div set at 900px but that's not working, any help?

ALSO: The InfoWindow options don't seem te work. I have maxWidth and disableAutoPan set, not doing anything.

http://i.stack.imgur.com/EK7gR.png

**Comment by nmccready** [comment]
plnkr

**Comment by wrummler** [comment]
@bernhardmostrey Closing this one due to inactivity. Feel free to follow up with the requested [verifiable example](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) of the behavior. Thanks.
