### ISSUE TITLE
This is an error?

### ISSUE THREAD

**Issue by johnfelipe** [angular-ui/angular-google-maps#1313]
Running "watch:all" (watch) task
	Waiting...
	Warning: Command failed: /home/notroot/angular-google-maps/node_modules/grunt-open/node_modules/open/vendor/xdg-open: 1: /home/notroot/angular-google-maps/node_modules/grunt-open/node_modules/open/vendor/xdg-open: xdg-mime: not found
	xdg-open: no method available for opening 'http://localhost:3100/example/example.html'

**Comment by nmccready** [comment]
This is from building ui-gmap locally?
