### ISSUE TITLE
Render is slow with big

### ISSUE THREAD

**Issue by cgarnier** [angular-ui/angular-google-maps#1314]
With a 4000 points polyline, rendering is can be really slow.

**Comment by gitnik** [comment]
Can you set up a plunker?

**Comment by ballistic** [comment]
@cgarnier Have you tried using polylines vs. polyline? Also, have you tried making it static?

**Comment by cgarnier** [comment]
NO i havent but i will try this thanks

**Comment by nmccready** [comment]
Make sure you try options to speed it up like static, and disable editable. editable is the number one thing that will slow it down terribly. There is nothing that can be done on that one as that is googles issue.

**Comment by nmccready** [comment]
Seems like @ballistic 's answer resolved your issue.
