### ISSUE TITLE
places_changed event is not fire when searchbox options autocomplete = true 

### ISSUE THREAD

**Issue by johnlim5847** [angular-ui/angular-google-maps#1315]
i'm trying to restrict the search on certain country so what i did is i enabled autocomplete in searchbox options and use componentRestrictions to get the job done.Everything is working i can see the result on the search dialog box but when i pressed enter on selected result the places_changed is not fired,if i set the autocomplete = false it is working but componentRestrictions is not working. May i know is there any solution for this case ?

**Comment by kandizzy** [comment]
The event for Autocomplete is `place_changed`. It's in the [example](https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/scripts/controllers/search-box-autocomplete.js#L90)

Let me know if this works for you.

**Comment by wrummler** [comment]
@johnlim5847 Closing this one. Feel free to follow-up with details if the question wasn't answered. Thanks.

**Comment by jonathan-chin** [comment]
@kandizzy Thanks, your comment saved me. I was having the same issue.

On the Angular Google Maps API Documentation, it mentions that there is only one event, "places_changed". It isn't obviously clear that autocomplete has a different set of events.
