### ISSUE TITLE
How do I pan to a point on the map ? (using a JS function with Latitude and Longitude)

### ISSUE THREAD

**Issue by mkyukov** [angular-ui/angular-google-maps#1318]
I have a map defined in the html DOM. I want to pan to different locations upon clicking external elements outside of the map. How can I do that?

**Comment by pcbulai** [comment]
In your template, add this to your external elements that trigger the map to pan to different locations

```
<span ng-click="updateCoords(34, -118)"></span>
```

And in your controller

```
$scope.updateCoords = function(lat, lng){
  $scope.map.center = {
    latitude: lat,
    longitude: lng
  }
}
```

**Comment by wrummler** [comment]
@mkyukov Closing this one. Feel free to follow-up with details if the question wasn't answered. Thanks.
