### ISSUE TITLE
markers click function fires at the initialize of map and markers and windows doesnt work properly

### ISSUE THREAD

**Issue by LRKOKO** [angular-ui/angular-google-maps#1319]
hello

 first of all my html is like this
![html](https://cloud.githubusercontent.com/assets/12475219/7667171/a55324da-fc07-11e4-9d50-91bff99f8f2f.PNG)

and my controller for gmap is like this : 

    angular.module('deneme').controller('GoogleMapCtrl', function($scope, mapService, $location) {

      $scope.map = {
        center: {
          latitude: 0,
          longitude: 0
        },
        zoom: 0,
        events: {
          tilesloaded: function(map) {
            $scope.$apply(function() {
              $scope.mapInstance = map;
            });

          }
        }
      };
      $scope.markers = [];
      $scope.options = {
        scrollwheel: false
      };
      $scope.haluka = false;

      var iconBase = 'https://maps.google.com/mapfiles/kml/shapes/';

      $scope.markers = mapService.items();

      mapService.removeItem();

      $scope.googleSearch = function(start, finish) {
        var startsplit = start.split(" ");
        var finishsplit = finish.split(" ");
        var url = "https://maps.google.com/maps?hl=tr&saddr=";
        for (var j = 0; j < startsplit.length; j++) {
          url = url + "+" + startsplit[j];
        }
        url = url + "&daddr=";
        for (j = 0; j < finishsplit.length; j++) {
          url = url + "+" + finishsplit[j];
        }
      };

      $scope.CenterFinder = function(agencies) {
        var latAve = 0;
        var longAve = 0;
        for (var i = 0; i < agencies.length; i++) {
          latAve += parseFloat(agencies[i].coords.latitude);
          longAve += parseFloat(agencies[i].coords.longitude);
        }

        latAve = latAve / agencies.length;
        longAve = longAve / agencies.length;

        $scope.map.center = {
          latitude: latAve,
          longitude: longAve
        };

        var maxLatDiff = 0;
        var maxLongDiff = 0;
        if (agencies.length > 0) {
          for (i = 0; i < agencies.length; i++) {
            for (var j = 0; j < agencies.length; j++) {
              if (i != j) {
                var latDiff = Math.abs(agencies[i].coords.latitude - agencies[j].coords.latitude);
                var longDiff = Math.abs(agencies[i].coords.longitude - agencies[j].coords.longitude);
                if (latDiff > maxLatDiff) {
                  maxLatDiff = latDiff;
                }
                if (longDiff > maxLongDiff) {
                  maxLongDiff = longDiff;
                }
              }
            }
          }
        }
        if (maxLatDiff > maxLongDiff) {
          $scope.map.zoom = Math.floor(15 - 5 * maxLongDiff / 3);
        } else {
          $scope.map.zoom = Math.floor(15 - 5 * maxLongDiff / 3);
        }
      };

      $scope.eventdeneme = function() {
        console.log("event");
      };

      $scope.closeClick = function(data) {
        console.log(data);
      };

      $scope.onClick = function() {
        console.log("tık");
      };

      $scope.getDirection = function(marker) {

        for (var i = 0; i < $scope.markers.length; i++) {
          $scope.markers[i].InfoShow = false;
          $scope.markers[i].DirectionShow = false;
        }

        marker.DirectionShow = true;
        $scope.FinishPoint = marker.Info.ServiceAddress;
      };

      $scope.closeMarker = function(marker) {
        marker.InfoShow = false;
        marker.DirectionShow = false;
      };

      $scope.ShowChange = function(marker) {
        marker.show = false;
      };

      $scope.CenterFinder($scope.markers);
    });

first of all as i stated at the title my onclick function fires for each marker when initializing the map and when i click markers, it calls onclick function for each markers instead  only clicked one. In addition, windows work when i click markers on map but even if i click another marker or the same marker windows stays.

Are there any way or easy turn around. I searched github but could not able to find a solution even though i tried all other rest solutions. Thanks in advance.

**Comment by wrummler** [comment]
It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it demonstrates what you're asking about by showing what you've tried. Thanks.

**Comment by wrummler** [comment]
Closing this one due to inactivity. Feel free to follow up with the requested link to an example. Thanks.
