### ISSUE TITLE
is it possible to have clusters with ui-gmap-marker rather than ui-gmap-markers?

### ISSUE THREAD

**Issue by capsule5** [angular-ui/angular-google-maps#1320]
I need ui-gmap-markers to use clusters
But mouseover / mouseout event are not working properly with ui-gmap-windows and ui-gmap-markers.

`<ui-gmap-markers models="markers" coords="'self'" icon="'icon'" doCluster="true" events = "'events'">
            <ui-gmap-windows show="'infoWindow'" >
                <p ng-non-bindable>{{infoWindow}}</p>
            </ui-gmap-windows>
        </ui-gmap-markers>`

infoWindow is updating well but the window is flashy and finally doesn't hide
Also get really slow when there's a lot of markers.

ui-gmap-marker with ng-repeat is faster and makes the window show hide properly...
`<ui-gmap-marker ng-repeat="marker in markers" idKey='$index' coords='marker.coords' icon='marker.icon' events = 'marker.events' options = 'marker.options' >
		    <ui-gmap-window options="windowOptions" show = "marker.infoWindow" >
                <div>{{$index}}</div>
            </ui-gmap-window>		        
		</ui-gmap-marker>`

but is it possible to do clusters then?

**Comment by wrummler** [comment]
It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it demonstrates what you're asking about. Thanks.

**Comment by wrummler** [comment]
Closing this one due to inactivity. Feel free to follow up with the requested link to an example. Thanks.

**Comment by ektanandwani** [comment]
I got the same question.
[(https://plnkr.co/edit/ld42cipNypQmzIupUAjF?p=info)]
Is this sample code sufficient ?
