### ISSUE TITLE
Unknown provider: uiGmapGoogleMapApiProvider

### ISSUE THREAD

**Issue by eablokker** [angular-ui/angular-google-maps#1321]
I am struggling to get the Google Maps SDK Async Loader working. I'm getting `Error: [$injector:unpr] Unknown provider: uiGmapGoogleMapApiProvider`. I have Lodash and angular-google-maps.js loaded in my project already. They are combined, not minified, using Gulp.

```
angular
	.module('myApp', [
		'ngRoute',
		'ngResource',
		'ngStorage',
		'appRoutes',
		'MainController',
	])
    .config(['uiGmapGoogleMapApiProvider', function(uiGmapGoogleMapApiProvider) {
		uiGmapGoogleMapApiProvider.configure({
			key: 'my-api-key',
			v: '3.17',
			libraries: 'weather,geometry,visualization'
		});
	}]);
```

What could be the issue? The docs say `To utilize this provider you must load it and configure it properly. Please note the defaults!` but the link to the defaults is broken.

**Comment by eablokker** [comment]
Why do I always answer my own questions right after asking?

I had to add 'uiGmapgoogle-maps' to my module dependencies
```
.module('myApp', [
        'ngRoute',
        'ngResource',
        'ngStorage',
        'appRoutes',
        'MainController',
        'uiGmapgoogle-maps'
    ])
```
This was surprisingly difficult to find in the docs. It wasn't mentioned in the API Documentation, but it is mentioned on the quick start page further down the page after the whole bit about china.

**Comment by daywong1119** [comment]
@eablokker  useful, this post saved me

**Comment by AkkaVoskuil** [comment]
Saved me too :)

**Comment by cdipaolo** [comment]
^ likewise
