### ISSUE TITLE
Map rendering on height change

### ISSUE THREAD

**Issue by SaleGajic** [angular-ui/angular-google-maps#1322]
I am trying to make map with initial 50px height, but when button is clicked, map should change height to 400px. I did this with pure CSS, and my CSS looks like this:
``` CSS
.angular-google-map-container { height: 400px; position:relative;}
.collapsed .angular-google-map-container {height: 50px;}
.angular-google-map-container {transition: all 0.5s ease}
```
Of course, i ran into standard issue when resizing map. But i don't know how should i properly call resize event on my map. I did found workaround but it's pretty messy.
My template looks like this:
``` HTML
<div class="row" ng-class="{'collapsed':mapCollapsed}">
  <ui-gmap-google-map center="map.center" zoom="map.zoom" draggable="true" events="map.events"></ui-gmap-google-map>
</div>
<div class="row" style="text-align: center; border:1px; background:lightgray; cursor:pointer; padding:10px;" ng-click="toggleCollapsMaps()">SHOW/HIDE Map</div>
```
And my javascript looks like this:
``` javascript
    var mapRef;
    $scope.map = {
        center: {latitude: 58.1473727, longitude: 7.9973672 },
        zoom: 12,
        events: {
            bounds_changed: function (map) {
                $scope.$apply(function () {
                    mapRef=map;
                });
            }
        }}
    $scope.options = {
      scrollwheel: true
    };

      $scope.mapCollapsed=true;
      $scope.toggleCollapsMaps = function(){
          $scope.mapCollapsed = !$scope.mapCollapsed;
          if(!$scope.mapCollapsed){
              $timeout(
                  function(){
                      google.maps.event.trigger(mapRef, 'resize')
                  },500);

          }
      }
```
I am saving reference to map on event i expect to be called before someone click on SHOW/HIDE map, then when map is opening, i am waiting 500ms before calling resize, to be sure that CSS transition is over. Still during the transition map is not rendered well. :(

Any advice on resizing?

**Comment by nmccready** [comment]
http://stackoverflow.com/questions/18444161/google-maps-responsive-resize

You need to use ng-if or hook to an event or watch to know when the map is reshown to resize it.

I need to add this to the FAQ as this is asked all the time.

**Comment by pcbulai** [comment]
I believe this one is solved already.

"If rendering starts before elements are full size, google maps calculates according to the smaller size. This is most commonly the case with a hidden element (eg, ng-show). To fix this, use "ng-if" instead, as this will wait to attach to the DOM until the condition is true, which should be after everything has rendered fully."

**Comment by nmccready** [comment]
cool

**Comment by UnnikrishnanBhargavakurup** [comment]
@ pcbulai - It's working like a magic :+1:
