### ISSUE TITLE
Drawing order of polylines

### ISSUE THREAD

**Issue by charlesmigli** [angular-ui/angular-google-maps#1325]
Hi, 
I have multiple polylines of different colors that can overlap but I can't control the ordre in which they are rendered.
Any clues on how to set the equivalient of the z-index of the polylines ?

Thanks!

**Comment by wrummler** [comment]
I don't think it's in the docs yet, but a `zIndex` attribute seems to be recognized, based on a quick glance over [this code](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/child/base-poly-child-model.coffee#L101-L103).

You could try that, and if that doesn't work you'll probably have to directly set z-indices by grabbing the `google.maps.Polyline` objects via the `control` object on the `ui-gmap-polylines` directive.

If you need to follow-up, please include an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE). Plunker is preferred, but anything you're comfortable with is also fine as long as it demonstrates what you're asking about by showing what you've tried. Thanks.
