### ISSUE TITLE
ui-gmap-markers - idkey issue 

### ISSUE THREAD

**Issue by dehian** [angular-ui/angular-google-maps#1326]
Hi, I have an issue about the markers
I get this error message
"Marker model has no id to assign a child to. This is required for performance. Please assign id, or redirect id to a different key.
"
I think it is an issue with the definition of the idKey attribute.

I have this kind of json
{
    "results": [
        {
            "info": {
                "identifier": 5712612,
                "location": {
                    "geo": {
                        "latitude": 50.4648366,
                        "longitude": 4.6686973
                    }
                }
            }
        },
        {
            "info": {
                "identifier": 5707298,
                "location": {
                    "geo": {
                        "latitude": 51.2207824,
                        "longitude": 4.4100115
                    }
                }
            }
        }
    ]
}

it only works when identifier is on first level...i cannot make it work when the identifier is inside another object on the second level﻿

Is it needed that the Idkey is inside top object?
How can i refer to this key?

**Comment by caioiglesias** [comment]
Well... It's in the docs! 

You have to modify your JSON.

**Comment by ektanandwani** [comment]
I got the same error even when idKey is assigned to all the elements pushed in the array to be displayed.
