### ISSUE TITLE
Circle directive not updating center on drag (broken in 2.0.13 release)

### ISSUE THREAD

**Issue by mikepugh** [angular-ui/angular-google-maps#1328]
See this Plunkr:

http://plnkr.co/edit/Io7ynZQ0ljsPucub3Djb?p=preview

Notice if you drag the circle, the Marker tracks its center and the JSON at the top of the window updates as the circle moves.

Update the angular-google-maps library to version 2.0.13 or higher and notice that dragging the center does not update the circle center property anymore.

**Comment by mikepugh** [comment]
It appears [this line](https://github.com/angular-ui/angular-google-maps/blob/553c5b732e8ff8428c60c78fae9eee3d69b933a1/src/coffee/directives/api/models/parent/circle-parent-model.coffee#L38) is where things are going wrong.

The setEvents function call returns undefined since it looks like scope.events is undefined and fails the if block within setEvents.

**Comment by danielmpla** [comment]
Discoverd same problem a week ago and posted it on StackOverflow, thought it was my failure and not a bug. Thanks for workaround and hoping for a bugfix soon.

At least in the latst release 2.1.0 there is the same problem with the radius property.

**Comment by nmccready** [comment]
Be nice if a spec was written as well.

**Comment by nmccready** [comment]
Duplicate #1285

**Comment by nmccready** [comment]
Reopening since this one has a plnkr

**Comment by nmccready** [comment]
I see the problem and the fix. Trying to make a spec to make the fix last.

**Comment by nmccready** [comment]
#1452 PR
