### ISSUE TITLE
Markers rendering issue

### ISSUE THREAD

**Issue by micahbule** [angular-ui/angular-google-maps#1330]
I've tried to search the repo for similar cases, but I can't find one.

Case: I'm trying to add markers to the map on mouse clicks.
Problem: The added markers are pushed to the modelsArray, however they won't immediately render to the map. I needed to zoom in/out to see them.

Plunker: http://plnkr.co/edit/sZkarSefOzkzDd8W3RsC?p=preview

EDIT: I tried to use newModels() and updateModels() to manually update the modelsArray. newModels() work, but it says it renders everything from scratch (which would cause problems when I'll be loading a whole lot of markers). updateModels() does work, but same problem as above.

**Comment by caioiglesias** [comment]
Not an issue.

You are missing $scope.$apply();

http://plnkr.co/edit/WJqiwoKBL6ZWVGJDKAoW?p=preview

**Comment by micahbule** [comment]
@caioiglesias alright, that did work. Thanks.

**Comment by caioiglesias** [comment]
Also remove doRebuildAll="true" to get rid of the flicker.
