### ISSUE TITLE
2 maps with customer marker

### ISSUE THREAD

**Issue by kelvinw88** [angular-ui/angular-google-maps#1333]
custom marker doesn't work when there are 2 maps. 
Even the example doesn't work

**Comment by wrummler** [comment]
What is the URL and/or repo path of the example that isn't working? When you view it, how is it failing to work?

This sounds like something we'd definitely want to know more about. Feel free to follow up with these details, and we can reopen this issue. Thanks.

**Comment by nmccready** [comment]
@kelvinw88 if you make an example I'll re-open.
