### ISSUE TITLE
Reference same map instance across multiple routes / controllers

### ISSUE THREAD

**Issue by eablokker** [angular-ui/angular-google-maps#1334]
I am building an app built around the map, where the same map persists across every route and controller. Currently, I have the `<ui-gmap-google-map>` directive sitting outside of the ng-view so that the map doesn't get redrawn every time I navigate to another route.

Main file:
```
<div id="map-view" ng-controller="ProjectController" ng-init="index()">
	<ui-gmap-google-map center="map.center" zoom="map.zoom" options="map.options" events="map.events">
			
		<ui-gmap-markers models="projects" coords="'self'"></ui-gmap-markers>
			
	</ui-gmap-google-map>
</div>
	
<div ng-view>
</div>
```

View:
```
<div ng-controller="ProjectController" ng-init="index()">
	<div ng-repeat="project in projects">
		<article class="project">
			{{project.name}}
		</article>
	</div>
</div>
```

What I have seems to work, but it requires firing the same controller twice, getting the same resource from the API twice. Is there some way I can put the map into the ng-view and have it persist across all routes?

What is the best way to render the same map instance across every route, and ideally preventing redraw?

**Comment by wrummler** [comment]
I can't be sure that this is applicable without seeing a full example, but try moving the resource retrieval logic from `ProjectController` to a service that can cache it for second and subsequent requests from the controller instances.

If that doesn't work for some reason, feel free to follow up with what went wrong as well as a small example of the problem on Plunker/JSFiddle/etc. Closing for now. Thanks.
