### ISSUE TITLE
polygon click event on FusionTablesLayer

### ISSUE THREAD

**Issue by kadalt** [angular-ui/angular-google-maps#1335]
Is there a way to listen click event on polygons? Neither ui-gmap-google-map directive events array nor ui-gmap-layer options work.

**Comment by kadalt** [comment]
I handled this way:

<ui-gmap-layer type="FusionTablesLayer" show="true" onCreated="fusionTable2CallBack" options="fusionTableLayerOptions2"></ui-gmap-layer>



        $scope.fusionTable2CallBack = function (layer) {
            layer.addListener('click', function() {
                alert("done");
            });
                console.log("layer");
            }

**Comment by chvenkat668** [comment]
Hi All,

I am also face this issue, my client what display the modal on click on drawn polygon with longitude and latitude, Please help me.

I am able draw the polygon, but i am unable to display the modal.
