### ISSUE TITLE
ui-gmap-markers, problem with my format?

### ISSUE THREAD

**Issue by chocamo** [angular-ui/angular-google-maps#1336]
I am having some performance issues with the following I'm not sure due to the amount of markers ~200 or maybe the ng-repeat so I am trying to change it from this:

```html
<!-- m.location.geography is a geojson point -->
<ui-gmap-marker 
	ng-repeat="m in vm.route[0].markers" 
	idKey="'_id'" 
	options="{ title: m.type, icon: vm.getIcon(m) }"
	labelContent="m.type" coords="m.location.geography">
</<ui-gmap-marker>
```

to this:

```html
<ui-gmap-markers models="vm.routes[0].markers"
       idkey="'_id'"
       coords="'location.geography'"
       options="'{ title: self.type, icon: vm.getIcon(self) }'">
</ui-gmap-markers>
```

```javascript
vm.getIcon(m) {
   return { url: 'http://www.google.com/mapfiles/dd-start.png' };
}
```

With the ui-gmap-markers directive I get the error:

```javascript
 Cannot read property 'type' of undefined
    at b.module.service.g (/angular-google-maps.min.js:5:12399)
    at Object.b.module.service.equalCoords (/angular-google-maps.min.js:5:14354)
    at k.b.module.factory.f.modelKeyComparison (/angular-google-maps.min.js:5:19553)
    at a (/angular-google-maps.min.js:5:18292)
    at /angular-google-maps.min.js:5:22172
    at Array.forEach (native)
    at k.b.module.factory.figureOutState (/angular-google-maps.min.js:5:21986)
    at /angular-google-maps.min.js:7:13695
    at /angular-google-maps.min.js:5:23882
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js:138:175
```

Any thoughts? I thought it was the options= parameter but I get that error even without specifying any options. Are there any recommended best practices for performance? It takes about 40 seconds for my map to display with ~200 icons and a very large linestring rendered with ui-gmap-polyline

**Comment by wrummler** [comment]
It looks like your `options` attribute value on the markers directive is invalid. It should be the property name to look up on each marker model for the options object. Try setting it something like `options="'options'"` and then assign the object you want (`{ title: self.type, icon: vm.getIcon(self) }`) to each marker model's `options` property when preparing the models.

Also, I'm not sure `'self'` has the semantics you might be expecting there. It's only a special value for the `coords` attribute, as far as I know and as far as the docs go... But if you've got some `var self = ...` floating around in your model setup, it might be what you intended.

Generally, 200 icons shouldn't take 40 seconds. Depends on the actual code, though. A "very large" linestring might take 40 seconds to render, I imagine. How many points are in the linestring and how long is the WKT?

Also, providing a [demonstrating example](http://stackoverflow.com/help/mcve) would help figure things out.

**Comment by wrummler** [comment]
@chocamo Closing this one. Feel free to follow up with details if your question wasn't answered. Thanks.
