### ISSUE TITLE
execute function when dragging stops.

### ISSUE THREAD

**Issue by HarrisRobin** [angular-ui/angular-google-maps#1341]
Hi,

So I know that the directive supports 'dragging' on the map but is there anything that let's you run a function once the user is done dragging or do i need to implement a debounce function to avoid running the function countless times?

I didn't find anything in the docs about this. 
Thank you,

**Comment by wrummler** [comment]
Have you tried the [`dragend`](https://developers.google.com/maps/documentation/javascript/events) event? Here's an easy mod of the ui-gmap-google-map example plunk to demo: 

http://plnkr.co/edit/zMxAv7QIGYMuEYzEn0FK?p=preview

**Comment by wrummler** [comment]
Closing this one. Feel free to follow-up with details if the question wasn't answered. Thanks.
