### ISSUE TITLE
How can I trigger a marker event from another link

### ISSUE THREAD

**Issue by danielmariz** [angular-ui/angular-google-maps#1346]
I have a list of gps positions and I need to center the map, zoom it and open the marker window when I click on each item.

using panTo, setZoom and some trigger event.
But I couldn't figure it out yet.

Some help?

**Comment by wrummler** [comment]
> But I couldn't figure it out yet.

This is not a very specific problem. What have you tried? How did it not meet your requirements?

Showing what you've done in a plunker would be helpful. Here's [the example for the `windows` directive](http://plnkr.co/edit/ujv5hbc0jbp4Ag0LIUQB?p=preview). It's probably enough for you to figure out how to do what you want.

Just a note: Centering on the marker and showing the marker's window are clearly specified, but you should think about how you need to zoom. A single lat/lng doesn't clearly imply a specific zoom level.

**Comment by danielmariz** [comment]
Oh sorry about that.

It's a complex Typescript+angular project. I could figure out how to do this.

**Comment by sean-stanley** [comment]
plunker link is broken
