### ISSUE TITLE
[Question] add marker with current position

### ISSUE THREAD

**Issue by floriansemm** [angular-ui/angular-google-maps#1347]
Is it possible to add a marker to the map with the current position of the user?

**Comment by wrummler** [comment]
Sure, within some margin of error depending on the device (and assuming the user gives permission for the device and browser to determine this information). See [*Using geolocation* at MDN](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation).

Beyond that, it's a matter of adding the marker via, for example, a conditionally compiled `marker` directive or an addition to the `models` array of a `markers` directive. Dynamically updating it with a [watch](https://code.angularjs.org/1.4.0/docs/guide/scope) of some sort would be possible as well.

**Comment by nmccready** [comment]
You would use this somewhere, http://www.w3schools.com/html/html5_geolocation.asp and on its callback update your location. This location should be bound to the map marker directive and there you have it.

**Comment by floriansemm** [comment]
Great thanks!

**Comment by gargoura** [comment]
Would you please give me an example on how to add a marker to the map with the current position of the user?

**Comment by Fattouh92** [comment]
it is not working. please check issue @[1970](https://github.com/angular-ui/angular-google-maps/issues/1790)
