### ISSUE TITLE
Please follow semver when bumping minor versions

### ISSUE THREAD

**Issue by mrm007** [angular-ui/angular-google-maps#1348]
`2.0.20` depended on Lo-Dash `~2.4.1`.
`2.0.21` bumps the Lo-Dash dependency to `~3.8.0` which makes the angular-google-maps release break backwards compatibility.

**Comment by christopherthielen** [comment]
As well as the angular dependency changing from `>=1.2.0` to `"~1.3.15"`

**Comment by nmccready** [comment]
The `>=1.2.0 to "~1.3.15"` was to get travis to work. What would I bump 2.0.X to? There already exist 2.1.0?

**Comment by nmccready** [comment]
Also the `>=1.2.0 to "~1.3.15"` restriction is there because I have not verified that it works with 1.4+. If someone wants to take the time to play around with some of the examples; I'd be happy to remove that restriction.

**Comment by christopherthielen** [comment]
As a maintainer of other FOSS projects, I feel your pain!  

Because of the angular bump, bower updated our app from angular 1.2.28 to 1.3.15 (which we caught early in dev process, and added a resolution for in our bower.json).

You should be able to use ">=1.2.0 <1.4.0" to specify no less than 1.2.0 but not 1.4.0+.  A n equivalent range shorthand would be "1.2 - 1.3"

See also "Advanced Range Syntax": https://github.com/npm/node-semver

**Comment by nmccready** [comment]
Ok, ill bump the next 2.0.X and 2.1.X angular ranges to `"1.2 - 1.3"`. Will this satisfy?

**Comment by nmccready** [comment]
@christopherthielen having a brain fart and searching issue; where did u see the `>=1.2.0 to "~1.3.15"` . I am having trouble finding the file.

**Comment by christopherthielen** [comment]
@nmccready I think `1.2 - 1.3` will be good! :+1: 

https://github.com/angular-ui/angular-google-maps/blob/master/bower.json#L6-L7

**Comment by nmccready** [comment]
Ah, I thought I put  `>=1.2.0 <1.4.0` in already, must have been a angular-leaflet I was thinking of.

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/commit/475cc13086250d867727ef08b2b3faf3a0486dc0

https://github.com/angular-ui/angular-google-maps/commit/cbebf1aaa7ca092b4b7a99c22b580ec1430c101f

**Comment by nmccready** [comment]
On 2.0.X and 2.0.22

**Comment by mrm007** [comment]
Awesome, thanks.

**Comment by christopherthielen** [comment]
:+1:  thank you
