### ISSUE TITLE
How to display trusted html inside infowindow

### ISSUE THREAD

**Issue by nazbert** [angular-ui/angular-google-maps#1353]
Hi all,

I am currently trying to place a string of trusted html inside a infowindow that is meant to display all of the marker titles under a cluster, separated by new lines. Everything seems to work fine except when I try to bind the trusted text to the element via ng-bind-html. When the infowindow first opens it is sized according to the text (but with no text visible) and moments later it flashes then the infowindow becomes tiny. I've done as much reading as I could find and I think I know why this is happening, I just don't know how to fix this.

**Comment by nmccready** [comment]
Can you make a basic example on plunkr with what your doing? Are you using template, templateData or templateUrl?
