### ISSUE TITLE
Polygons idKey not passing to object

### ISSUE THREAD

**Issue by ringerx** [angular-ui/angular-google-maps#1357]
I am generating a series of polygons. I have tried using both the polygons model and ng-repeat, but the idKey attribute is not getting passed. How can I get this attribute passed to my polygons?
```
<ui-gmap-polygons
                models="polygonList"
                idKey="'id'"
                control="map.polyControl"
                path="'coordinates'"
                stroke="map.polygons.stroke"
                visible="true"
                clickable="true"
                geodesic="true"
                fill="map.polygons.fill"
                events="map.polygons.events"
                >
</ui-gmap-polygons>

polygonList.JSON:  
{
    "geometry": {
      "type": "Polygon",
      "center": {
        "latitude": "40.755531175665",
        "longitude": "-73.9699292467286"
      }
    },
   "id": 666,
    "coordinates": [
      {
        "latitude": 40.75679999999994,
        "longitude": -73.95974000000007
      },
      {
        "latitude": 40.75778444444438,
        "longitude": -73.95909444444447
      },
      {
        "latitude": 40.76298666666662,
        "longitude": -73.97168333333337
      }
    ]
  }
```

**Comment by nmccready** [comment]
idKey is supposed to default to 'id' but how do you know its not getting passed? Error in browser, debugging? I'll copy this into a plunkr.

**Comment by ringerx** [comment]
mouseover event console.log returns...
undefinedidKey: "id"

**Comment by nmccready** [comment]
You don't really have a list of polygons there. You have one Polygon object, so I think your data is mal-formatted.

**Comment by nmccready** [comment]
I set this up and its not working. Get your polys rendering and then I'll look at it. http://plnkr.co/edit/GTD3YJWIECF04zP0rW0T

**Comment by ringerx** [comment]
here is the working plunkr
http://plnkr.co/edit/P4x9kkWQHDf3PVf8GrS2

**Comment by nmccready** [comment]
Its there use your debugger and check `arguments` in your watch. `arguments` is always in every function in javascript. So the model is your third arg arguments[2].

**Comment by nmccready** [comment]
And that is exactly what the code says here googleobject, eventName, model, arguments (original googe args)
