### ISSUE TITLE
Center and Zoom are Required Even When Using Bounds

### ISSUE THREAD

**Issue by iamchairs** [angular-ui/angular-google-maps#1360]
If i'm supplying bounds I shouldn't need to set the center or zoom.

Plunkr: http://plnkr.co/edit/3ZKHN4xejuZdtvVGajSi?p=preview

html:
```
<ui-gmap-google-map bounds="map.bounds" options="options"></ui-gmap-google-map>
```

js:
```
$scope.map = {
    bounds: {
        "northeast":{"latitude":38.9528601,"longitude":-94.7140479},
        "southwest":{"latitude":38.8054929,"longitude":-94.928023}
    }
};
```

**Comment by nmccready** [comment]
True; look at the map.coffee file and release the restriction. But it needs to have a zoom or at least a default zoom in the map.coffee file itself.  So `center || bounds` and `zoom =  scope.zoom or defaultZoom`.

**Comment by drew-r** [comment]
+1
