### ISSUE TITLE
click event on marker not working

### ISSUE THREAD

**Issue by nicopace** [angular-ui/angular-google-maps#1363]
Hi,
I added a click event on a single marker, and it is not working.
I created a codepen that reproduces the bug.
http://codepen.io/anon/pen/GJvxaX?editors=100

Regards,

**Comment by wrummler** [comment]
[Angular expressions](https://docs.angularjs.org/guide/expression) are evaluated against a scope, not the window object, so `alert` doesn't exist in the execution context of your `click` expression.

E.g. see [this SO answer](http://stackoverflow.com/a/25907787/402749) and/or [this Scott Allen post](http://odetocode.com/blogs/scott/archive/2013/02/25/expressions-in-angularjs.aspx).

If you really need to call `alert`, throw in a controller that exports a function that calls it. Always access `window` properties (like `alert`) by injecting [`$window`](https://docs.angularjs.org/api/ng/service/$window), a mockable alias to the object.

**Comment by nicopace** [comment]
Ok, I updated the example and now it works.
Here it is the example working: http://codepen.io/anon/pen/GJvxaX?editors=100

thanks!
