### ISSUE TITLE
Custom icon image for marker ignored

### ISSUE THREAD

**Issue by soee** [angular-ui/angular-google-maps#1368]
Hi, 

i'm using latest version now but since some time my custom icon image for marker is ignored and always the default one is used. The custom image worked few version before (i'm not sure what version was it exactly, but it was like 3-4 month ago).

GM api v.3.18

**Comment by RyanDale** [comment]
How are you passing the icon into the ```ui-gmap-marker``` directive? According to the documentation you are supposed to pass it in via the ```icon``` param, but that doesn't appear to be working for me. It does appear to work correctly if you include the icon in the options.

**Comment by soee** [comment]
I have defined it as icon param and this won't work. Passing path to icon through 'options' works as @RyanDale said.

**Comment by wrummler** [comment]
@soee It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it works. Thanks.

**Comment by wrummler** [comment]
Closing this one due to inactivity. Feel free to follow up with requested details. Thanks.
