### ISSUE TITLE
Marker position not updating after position changes

### ISSUE THREAD

**Issue by grillorafael** [angular-ui/angular-google-maps#1369]
Hi guys.

Here is my code.

```
<ui-gmap-google-map
                            options='mapOptions'
                            center='vessel.last_known_position'
                            zoom='initialZoom'
                        >
                            <ui-gmap-marker idKey='vessel._id' coords='vessel.last_known_position'></ui-gmap-marker>
                        </ui-gmap-google-map>
```

This map is inside a ng-repeat (I have a list and each element has a map).

When I update my `vessel.last_known_position` the map changes its center but the marker does not.

Any idea?

**Comment by wrummler** [comment]
It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it works. Thanks.

**Comment by wrummler** [comment]
Closing this one due to inactivity. Feel free to follow up with requested details. Thanks.

**Comment by agaskell** [comment]
MCVE for this issue: http://plnkr.co/edit/cm82PUbbPas0PvoAYN6F?p=preview
