### ISSUE TITLE
Polygon Directive id not passing to object

### ISSUE THREAD

**Issue by ahmadyaqob** [angular-ui/angular-google-maps#1374]
Hi all,
http://plnkr.co/edit/Per0NKShWUcpoiO8mvtj?p=preview
In this plunkr I have set up click event to the polygon,the issue that the polygon id is not passing into the model but all the other attributes are passed, how can i pass the id attribute into the polygonEvent?

**Comment by nmccready** [comment]
Your title is misleading as your using the polygon directive. Yes the ID does not appear to be in the model / scope. Therefore it just needs to be added which should be a simple PR. Otherwise I would suggest just using polygons especially if your using multiple polys.

**Comment by ahmadyaqob** [comment]
In my situation i need to pass dynamic id for the polygons,on the click event i want to redirect the view using the polygon id.

I used the same way with markers the data passed and it works fine ,now i am using multiple polys but i used polygon with ng-repeate,passing the id suppose to work fine with polygons directive or its the same?

**Comment by nmccready** [comment]
Like I said why are you using `ui-gmap-polygon` use `ui-gmap-polygons`.

**Comment by AbderrahimDz24** [comment]
I have the same issue and I use ui-gmap-polygon because I had this [issue](https://github.com/angular-ui/angular-google-maps/issues/1562) with the ui-gmap-polygons.
```
//i-polygon.coffee
    IPolygon.scope =
        id:= '=id' // does adding this line do the trick 
        path: '=path'
        ...
```
