### ISSUE TITLE
accessing polygon objects

### ISSUE THREAD

**Issue by ringerx** [angular-ui/angular-google-maps#1375]
using a mouse event i can access the polygon object with arguments[2]. but how can i access a specific polygon on page load or by using function?

**Comment by nmccready** [comment]
Which directive? If its polygons use the `control` attribute. Then use `getPlurals()[id]`.

https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/plural.coffee#L17

**Comment by nmccready** [comment]
I assume your already using events so you get access to the gObject and model in that event. So getPlurals allows you to get access to the gObjects and models without an event.

**Comment by wrummler** [comment]
@ringerx Closing this one. Feel free to follow-up with details if the question wasn't answered. Thanks.
