### ISSUE TITLE
Changing radius of a circle object also triggers center_changed event.

### ISSUE THREAD

**Issue by sam2x** [angular-ui/angular-google-maps#1377]
Hi, 

Not sure if it's related to https://github.com/angular-ui/angular-google-maps/issues/1068, but changing only the radius of a circle triggers also "center_changed" (center of circle doesnt move during radius change). This is annoying, in my case i need to apply two different "code" according a specific event.

Regards.
S

**Comment by nmccready** [comment]
Related to #1285

**Comment by sam2x** [comment]
for me it's not related to #1285. The #1285 ticket is related to events that doesnt trigger. i haven't any problem to triggers circle events.

**Comment by nmccready** [comment]
Ok, well if I work on it I will probably look into both at the same time. So it is related in the workflow of things.

**Comment by nmccready** [comment]
@sam2x we need an example. We need to know how your changing it; from the model or from the gObject. Please produce a plnkr.

**Comment by nmccready** [comment]
To me this sounds like your talking about the Circle itself being adjusted and firing off both google events internally. If this is the case it's highly likely a google problem.

**Comment by sam2x** [comment]
hey, sry i can't provide a snippet right now (i'll have time to do it tomorrow). Yeah this is exactly the problem, the event is fired on both "events", even if the radius hasnt changed.

**Comment by nmccready** [comment]
@sam2x ping

**Comment by nmccready** [comment]
I might push this to 2.1.7 (or 2.2.1, if 2.1.6 becomes 2.2.0). There a some some decent changes and I should get a release of master pushed out.

**Comment by sam2x** [comment]
hey, is there any "base" snippet that i could easily modify to show you the bug?

**Comment by nmccready** [comment]
Yes fork this and modify it. Notice the scripts point at rawgit.com at master. You can also point it at specific versions.

**Comment by sam2x** [comment]
sorry, when you say "fork this", which url you're talking about ?

**Comment by nmccready** [comment]
plnkr has the option to fork the example and make it your own. It is pretty st8 forward.

**Comment by nmccready** [comment]
![screen shot 2015-08-25 at 5 27 41 pm](https://cloud.githubusercontent.com/assets/583593/9480049/9f113ca6-4b4e-11e5-89c5-f42e3bdf63dd.png)

**Comment by sam2x** [comment]
Excellent, thanks you. 
Here the reproduced problem : http://plnkr.co/edit/SQduueLvwBDajKgAuiaf
Step : 
- Use the rounded pin in the center of the circle to move the circle and center_changed will trigger (no problem here),  
- Use one of the four rounded pin around the circle to reduce the radius, and *both* radius_changed and "center_changed" event will trigger (only radius_changed should be triggered).

**Comment by nmccready** [comment]
ty I will look into it

**Comment by sam2x** [comment]
huuuu, i also triggered the radius_changed when i moved the circle (with the center of the circle). should have been only 'center_changed'... i'm a bit confusing about what could be the prob :s

**Comment by nmccready** [comment]
Yeah me as well; like I said somewhere else it could be a google thing. I have seen some strange stuff in circle anyways already. Which is why we have the radius hacks in the codebase to begin with.

**Comment by sam2x** [comment]
ok thx for acknowledging this behaviour. 2questions : 
- To advice google-map-dev i guess they will need a "native" version of this behaviour ?
- Else, do you know any alternative to a "circle-like" drawing/canvas, i want to provide "scope/area" delimited by a specific radius to my users (something easy to use like this circle) ?

**Comment by nmccready** [comment]
I still need to dig into your issue and see if I can figure out if anything is on us. However, if you can make a native example that has similar if not the same issue; that would help immensely.

**Comment by sam2x** [comment]
Ok i have finished a native example : http://plnkr.co/edit/s30qiHpqYHFTJliwT5zJ?p=preview
All the highlighted issues reported seems to not occurs on native examples.

**Comment by sam2x** [comment]
Note that on the native example, the circle events are triggered correctly only "one time", while on the angular-google-maps, triggering one event seems to fired his handler multiple times at once.

**Comment by sam2x** [comment]
Meeeeh i don't have skill to read the coffee that handle this part :/

**Comment by nmccready** [comment]
cool thanks for the native

**Comment by nmccready** [comment]
I figured the issue out. It is actually a pretty standard angular 1 problem. My bad; needed to add some gates to make sure were not updating scope too much. This is something angular 2 is not supposed to have issues with.

**Comment by nmccready** [comment]
PR'd

**Comment by nmccready** [comment]
@sam2x thanks for the example

**Comment by sam2x** [comment]
Great! Glad you spot the bug, good job and thank you for your time.
