### ISSUE TITLE
Fix API Documentation nested urls

### ISSUE THREAD

**Issue by DavidePastore** [angular-ui/angular-google-maps#1380]
Hi, it would be cool if the **API Documentation** would have separate urls for each provider/service/directive, so navigation or sharing documentation about a particular thing becomes simpler.  Even if you navigate around the API section, the url remains [http://angular-ui.github.io/angular-google-maps/#!/api](http://angular-ui.github.io/angular-google-maps/#!/api).

**Comment by cthrax** [comment]
We would welcome the pull request.

**Comment by nmccready** [comment]
Should be resolved.

**Comment by DavidePastore** [comment]
Is this already online?

**Comment by pcbulai** [comment]
No, it's not. My PR is still open and will probably remain that way until I solve Travis CI failures(see https://github.com/angular-ui/angular-google-maps/issues/1402).

**Comment by DavidePastore** [comment]
@pcbulai Thanks! It works cool! :+1:
