### ISSUE TITLE
click event on info window does not work.

### ISSUE THREAD

**Issue by nendhruv** [angular-ui/angular-google-maps#1383]
click event does not work on info window but it seems to work fine on markers. 

```
<ui-gmap-google-map center="map.center" zoom="map.zoom" options="options">
  <ui-gmap-markers models="markers" coords="'self'" icon="'icon'" click="clickPin">
    <ui-gmap-windows show="show">
      <div ng-non-bindable="ng-non-bindable" click="sideNav">
        window content
      </div>
    </ui-gmap-windows>
  </ui-gmap-markers>
</ui-gmap-google-map>
```

**Comment by wrummler** [comment]
`click` is not an HTML attribute, so you can't use it on a `div` like your snippet is showing. You should use either `onclick` or `ng-click`, depending on whether you want to evaluate the click expression against the global object or against current Angular scope.

If you need to follow-up, it's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it works. Thanks.
