### ISSUE TITLE
Any update need for angular google map for Google Maps APIs change to use SSL SHA-256

### ISSUE THREAD

**Issue by stl-winniechan** [angular-ui/angular-google-maps#1386]
I got an email today from Google maps support team about Google Maps APIs is going to roll out with SSL SHA-256. I ran the openssl command from the email on my app server and it ran fine. 
However, is there update from the angular google map directive side needed for this change? 
Any advice will be helpful. Thanks.

**Comment by nmccready** [comment]
URLS to more info on this?

**Comment by wrummler** [comment]
@stl-winniechan Closing this one due to inactivity. Feel free to follow up with requested details. Thanks.
