### ISSUE TITLE
Load cluster images over https

### ISSUE THREAD

**Issue by MKraijenoord** [angular-ui/angular-google-maps#1390]

**Comment by wrummler** [comment]
This seems like an external issue with `markerclustererplus`, see [here](https://code.google.com/p/google-maps-utility-library-v3/source/browse/tags/markerclustererplus/2.1.1/src/markerclusterer.js?r=457#1614).

AGM could maybe monkeypatch it with something like

    MarkerClusterer.IMAGE_PATH = MarkerClusterer.IMAGE_PATH.replace('http:', 'https:');

as an afterword in [uiGmapGoogleMapsUtilV3](https://github.com/angular-ui/angular-google-maps/blob/master/src/js/wrapped/google-maps-util-v3.js). (I haven't tested with this or any other related change.)

**Comment by cthrax** [comment]
Another option, which I chose, was to host the clusterer images the same place I'm hosting my app and setting custom icons that point there.
