### ISSUE TITLE
Unable to set Mouseover, Mouseout listener at Polygon 

### ISSUE THREAD

**Issue by ultimatecoder** [angular-ui/angular-google-maps#1391]
I am using Angular JS 1.3.14 and Angular-google-maps version 2.0.16. I am trying to add Mouseover event listener for Polygon. But It seems that the event Mouseover is fired when Polygon is clicked rather than Mouse moving on it.
Is it bug in the given version? Or someone has successfully implemented it?

**Comment by wrummler** [comment]
It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it demonstrates the behavior you're asking about. Thanks.

**Comment by ultimatecoder** [comment]
I found I was loading too much polygons. So the polygons was not drawing and I was trying to fire the event. Closing this.

**Comment by wrummler** [comment]
:+1:
