### ISSUE TITLE
i am showing multiple maps on same page inside each search results, page got stuck and irresponsive

### ISSUE THREAD

**Issue by sarbjeetsingh** [angular-ui/angular-google-maps#1396]
i am showing multiple maps on same page inside each search results, page got stuck and irresponsive 
actually it waits untill all maps load

**Comment by wrummler** [comment]
It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it demonstrates the behavior you're asking about. When we have a clear example, we can reopen the issue. Thanks.
