### ISSUE TITLE
Zoom Level on "place_changed" event in searchbox

### ISSUE THREAD

**Issue by marcuschristiansen** [angular-ui/angular-google-maps#1397]
I'm battling to change the Zoom Level after the autocomplete place_changed fires. It zooms in all the way to the maximum number.

**Comment by wrummler** [comment]
It's best to include a link to an immediately runnable [MCVE](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) when raising issues like this. Plunker is preferred, but anything you're comfortable with is also fine as long as it demonstrates the behavior you're asking about. Thanks.

**Comment by marcuschristiansen** [comment]
Hi.

Thank you for your reply. You can check the result on storefinder.hashfff.com/app/index.html 

Search for a place and see that it zooms in all the way. I hope this helps.

**Comment by wrummler** [comment]
I searched for Gauteng and it didn't zoom in all the way.

**Comment by marcuschristiansen** [comment]
Not to worry. I managed to fix the issue.

**Comment by wrummler** [comment]
:+1: Thanks for confirming.
