### ISSUE TITLE
Marker Click Event Not Registering Unless 'draggable' == true

### ISSUE THREAD

**Issue by cdipaolo** [angular-ui/angular-google-maps#1400]
I have a map with markers and the `click` callback will not register unless the 'draggable' option is set to 'true' in the options directive attribute. Does anyone have any idea why this is necessary? What am I doing wrong? Setting 'clickable' doesn't work (and should be the default anyways)

This works only with 'draggable':
```html
<ui-gmap-google-map class="has-header" center="map.center" zoom="map.zoom">
    <ui-gmap-markers models="markers" coords="'self'" options="{draggable:true}" click="onMarkerClick"></ui-gmap-markers>
</ui-gmap-google-map>
```

```js
$scope.onMarkerClick = function(marker, eventName, mk) {
    // go to kitchen detail
    console.log('click!!');
    $scope.detail(mk.id);
};
```

**Comment by cdipaolo** [comment]
Update:

I fixed this. It's an issue with Ionic, which masks taps. All I had to do was add `data-tap-disabled="true"`

http://forum.ionicframework.com/t/google-maps-click-event-not-working/4481

can close this now. Hope this helps someone else in the the same situation

**Comment by cthrax** [comment]
Nice! Thanks for reporting back!

**Comment by Cdvalencia** [comment]
on this url show you, as must to make it:
https://developers.google.com/maps/documentation/javascript/examples/directions-draggable?hl=es-419
