### ISSUE TITLE
How can I make a marker animate smoothly when its coordinate changes?

### ISSUE THREAD

**Issue by youfacepalm** [angular-ui/angular-google-maps#1404]
Is there a way to animate marker to new position during coordinate updates like in this example: http://terikon.github.io/marker-animate-unobtrusive/demo/unobtrusive/markermove-sliding.html

**Comment by cthrax** [comment]
This library does not have the animate functionality. You'd ought to be able to add the functionality in yourself by pulling out what that library does and using the native marker object that ui-gmaps provides.
