### ISSUE TITLE
Slowness with markers directive with > 150 markers

### ISSUE THREAD

**Issue by RossRothenstine** [angular-ui/angular-google-maps#1406]
EDIT: This was a red herring, sorry. The problem wasn't with the clusters directive, but my application code. How do I close this?

I have a markers array with around 150-300 markers at any given time. When the viewport is moved away from the area, I load more markers from the server, which empties the array and refills it.

There is some considerable lag in this process, as it takes the map a long time to redraw. I assume because the $digest process is doing a deep check of the array and its objects (the objects only have 3 fields, the coords, icon, and id). Profiling shows a long $digest process as well.

My work-around is to add 'ng-if="markers.length"' to the markers directive, and clear the array before making the HTTP request, which will $destroy the directive and load in the new markers, without a $digest.

Here's the pre-workaround directive:

<ui-gmap-markers ng-if="markers.length" models="markers" coords="'location'" icon="'icon'">

There must be a better approach to this, any ideas?

**Comment by cthrax** [comment]
If you merge the array instead of clearing it out, it actually is optimized to work with the ids of each marker. Some users have claimed to use 1000s without issue.

**Comment by RossRothenstine** [comment]
Do you think this approach would work if there are duplicate markers within the area? There is potential that the new viewport will intersect the old, and some duplicate markers would exist in the response payload. I could keep a local mapping of currently loaded markers, and remove those that weren't duplicated by the response.
