### ISSUE TITLE
Why AngularJS infoWindow beyonds the bounds? Blocked by days......

### ISSUE THREAD

**Issue by huangye177** [angular-ui/angular-google-maps#1409]
Hi, 

I have a marker and Infowindow in the map, the marker's location will be changed onClick, and its InfoWindow should be always shown.

However, my code below get the following behaviour: once the map is loaded for the first time, the map will be adjusted after loading, and the Infowindow of the mark can be fully displayed inside the viewpoint, nothing beyonds the boundary.

If I clicked somewhere close to boundary in the map, the marker will be shifted as expected, but its InfoWindow will beyond the viewpoint, therefore part of the InfoWindow is nolonger seen.

I suppose that is because some attributes of the Marker or the InfoWindow is reset (InfoWindowOptions. disableAutoPan?), but I cannot find which one should be reset, and why.

I am blocked by this issue by days, any help will be appreciated!

Cheers,

The stackoverflow issue with code is created:

http://stackoverflow.com/questions/31660864/why-angularjs-infowindow-beyonds-the-bounds

Thanks again!

**Comment by huangye177** [comment]
No one experienced same issue?

**Comment by nmccready** [comment]
Can you produce a plnkr instead?
