### ISSUE TITLE
DrawingManager event support?

### ISSUE THREAD

**Issue by thienth** [angular-ui/angular-google-maps#1410]
Hi,
i'm using angular-google-maps to create a google maps in my project following the guild in http://angular-ui.github.io/angular-google-maps/#!/api
i've using DM to draw some polygon in the map, so i can't find any event to get the polygon information like overlaycomplete, polygoncomplete like:
drawingManager = new google.maps.drawing.DrawingManager({options});
google.maps.event.addListener(drawingManager, 'overlaycomplete', function (e) {});
Can you please help me to do this?
Thank you.

**Comment by nmccready** [comment]
The DrawingManager is very minimal at the moment. Someone needs pull in the EventsHelper service to make the event handling similar to the rest of the directives. The directive could use more scope attributes for sure so feel free to contribute.

**Comment by picheli20** [comment]
To anyone on the future who is searching for the Listener Events, you can have a instance of "new google.maps.drawing......" with the factory uiGmapGoogleMapApi, its a promise wich return a instance of gMaps.
