### ISSUE TITLE
How to use the control filed in angular-google-maps

### ISSUE THREAD

**Issue by huangye177** [angular-ui/angular-google-maps#1412]
Hi, 

How could I use the control filed of the angular-google-maps components? For example, marker has a control filed, but the document is too brief, and I have the problem to find an useful example. 

So, if I have a map and marker like this
```
<ui-gmap-marker coords="marker.coords" options="marker.options" events="marker.events" idkey="marker.id" control="marker.control">
</ui-gmap-marker>
```

with javascript:
```
$scope.mapControl = function(marker) {
  return marker;
}

$scope.marker = {
      id: 0,
      coords: {
        latitude: 40.1451,
        longitude: -99.6680
      },
      options: { draggable: true },
      control: $scope.mapControl,
      events: {
        dragend: function (marker, eventName, args) {
          $log.log('marker dragend');
          var lat = marker.getPosition().lat();
          var lon = marker.getPosition().lng();
          $log.log(lat);
          $log.log(lon);

          $scope.marker.options = {
            draggable: true,
            labelContent: "lat: " + $scope.marker.coords.latitude + ' ' + 'lon: ' + $scope.marker.coords.longitude,
            labelAnchor: "100 0",
            labelClass: "marker-labels"
          };
        }
      }
    };
```

then I can get the marker through this control attribute and apply google map native action on that?
```
$scope.mapControl.setAnimation(google.maps.Animation.BOUNCE);
$scope.mapControl.setMap(null);
```

How should I use it?

Thanks!

Cheers, 
Ye

**Comment by cthrax** [comment]
The control is added after the library is loaded, attach to the uiGmapIsReady promise and you can use the control once everything is loaded.

**Comment by huangye177** [comment]
@cthrax thanks for catch up, but is there any use case and example code? It sounds like I do not need to do anything here and can simply call "$scope.marker.control" to get it? But then? How to use it? What is its capability?

**Comment by cthrax** [comment]
@huangye177 the api for the control is dependent on the directive and outlined at http://angular-ui.github.io/angular-google-maps/#!/api for each directive that has the control option. A quick look in the examples folder produced this https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/scripts/controllers/issue-484-markers-self.js but I'm sure there are other examples in there.
