### ISSUE TITLE
No demo or tutorials

### ISSUE THREAD

**Issue by pulkitnandan** [angular-ui/angular-google-maps#1414]
Hi, Can you please let me know how to build something using your api without investing my month in learning the documentation. Do you really expect people will first read your documentation and figure out may be from the source of the code that it may to this thing.
Atleast single example to show how a simplest of angular google maps will work,

**Comment by cthrax** [comment]
If you spent half the you spent writing up this rude comment belittling the time that people spend VOLUNTEERING to do work, you might have found these links on the website http://angular-ui.github.io/angular-google-maps/#!/use http://angular-ui.github.io/angular-google-maps/#!/demo or possibly the entire folder marked "example" in the git repo. https://github.com/angular-ui/angular-google-maps/tree/master/example .

Please try and be a bit more considerate when utilizing open source projects. You have as much as power as anyone else that contributes to this project to make it better than what it is. The difference is that the contributes found the time to make something, and while not perfect, has been done and given for free.
