### ISSUE TITLE
Marker not being added to map

### ISSUE THREAD

**Issue by werdnanoslen** [angular-ui/angular-google-maps#1416]
I have a fairly simple map app going on [here](http://andyhub.com/demos/mobile-map-io/www/#/map), but I'm unable to get a marker to show up using the ui-gmap-marker directive (see [map.html](https://github.com/werdnanoslen/mobile-map-io/blob/master/www/templates/map.html#L19) and centerOnMe in [controllers.js](https://github.com/werdnanoslen/mobile-map-io/blob/master/www/js/controllers.js#L13). I'm pulling angular-google-maps ~2.1.5 from [bower](https://github.com/werdnanoslen/mobile-map-io/blob/master/bower.json).

**Comment by pcbulai** [comment]
@werdnanoslen see my PR I've just submitted to your repository.

**Comment by pcbulai** [comment]
@cthrax this can be closed.
