### ISSUE TITLE
How can we show an info window on clicking of Cluster Icon/pin?

### ISSUE THREAD

**Issue by maramkiran** [angular-ui/angular-google-maps#1417]
How can we show an info window on clicking of Cluster Icon/pin?

**Comment by RyanDale** [comment]
You can do that by adding a clusterEvents click listener. The below example should be what you need.

In your HTML:
```
        <ui-gmap-google-map ui-map="model.myMap" control="map.control">
            <ui-gmap-markers
                doCluster="true"
                events="map.markerEvents"
                clusterEvents="clusterEvents"
                clusterOptions="map.clusterOptions">
            </ui-gmap-markers>
        </ui-gmap-google-map>
```

In your controller:
```
        $scope.clusterEvents = {
            click: function(cluster, clusterModels) {
                //Add InfoWindow initialization here
            })
        };
```

**Comment by maramkiran** [comment]
Hi RyanDale, thanks for response. also provide sample code for initialization for Infowindow.

**Comment by RyanDale** [comment]
I omitted the implementation because the window directive is well documented. Take a look  [here](http://angular-ui.github.io/angular-google-maps/#!/api/window). You can find several examples that utilize the InfoWindow [here](https://github.com/angular-ui/angular-google-maps/tree/master/example). If you run into any issues you can't resolve, post your code and I will attempt to help.

**Comment by maramkiran** [comment]
yes the documentation is very good. But there am unable to find how to initialize infowindow from scripting side. If possible provide sample code to initialize infowindow from scripting side rather in view.

**Comment by RyanDale** [comment]
You can inject ```uiGmapGoogleMapApi``` into your controller and instantiate it by doing something like this I believe. There is some good documentation about the options you can use [here](https://developers.google.com/maps/documentation/javascript/infowindows).

```
new uiGmapGoogleMapApi.InfoWindow(options);
```

**Comment by nmccready** [comment]
@RyanDale your assumptions appear to be correct as creating the window via scripting from the Custer Event should do the trick. Yes it is not the most angular approach, but it does the job. If you would like to make it more angular please feel free to expand the directives and make a PR.

**Comment by nmccready** [comment]
no reply or feedback closing, will reopen otherwise.
