### ISSUE TITLE
help with free draw polygons

### ISSUE THREAD

**Issue by maeishoj** [angular-ui/angular-google-maps#1426]
Hi everyone,

I was looking at the free-draw-polygons example, as that is something i currently need, and looks pretty neat.

However I was "porting" the code into my own controller and i did not quite get why it seemed so "complicated" needing, factory, services, etc so I though to keep it to bare minimum and have the button in the $templateCache, calling directly a method in the scope for calling: "$scope.map.draw()" and "$scope.map.polys = [];".

However when I click draw, I get "$scope.map.draw is not a function" because it's undefined by default.
Can someone explain me why?

**Comment by maeishoj** [comment]
Never mind, i figured it out. I just dont use templates and put buttons elsewhere and call directly map.draw().

**Comment by suyogkrazz** [comment]
how did you exactly solved id?? I am still getting $scope.map.draw is not a function error

**Comment by maeishoj** [comment]
@suyogkrazz when you define $scope.map add the draw property and then from any regular button you can say ng-click="draw()" and then in your controller you have $scope.draw = function(){ $scope.map.draw() }
