### ISSUE TITLE
Try create infowindow for polygon

### ISSUE THREAD

**Issue by brillliant** [angular-ui/angular-google-maps#1427]
Guys, 

I add  

=======================
               <ui-gmap-windows>
                    <h1> test </h1>
                </ui-gmap-windows> 
========================
info markers - and it help to add infowindows for them.

But is DON'T WORK for polygons.
Is it possible to do that with polygons?

http://plnkr.co/edit/uRvwUQnQoMstTnES0IYE

Could you suggest the way to solve this problem different way?
Thank you in advance.

**Comment by nmccready** [comment]
I don't plan on adding windows to be nested underpolygons. It has created more hell then it has solved under markers. Anyway you should be able to use window or windows via polygon or polygons via events. All you need to do is think outside of the box and use some angular glue (binding).

**Comment by nmccready** [comment]
modded your plnkr to show it can work if you think hard.
http://plnkr.co/edit/kZlDGs65NgUV0azYG0bP?p=preview
