### ISSUE TITLE
ng-if with ui-gmap-markers fit=true doesn't bound correctly on first time it's shown

### ISSUE THREAD

**Issue by jgr3go** [angular-ui/angular-google-maps#1428]
I have a list view/map view screen, that uses an `ng-if` around the map to decide whether to show it. The map defaults to hidden (while the markers are loaded), and if the user shows the map, a `ui-gmap-markers` directive renders the markers, but the map position never updates to rebound itself around the markers, even when `fit="true"`. 

The weird part is that if you toggle the map off and back on again, the second time it's inserted into the DOM, it renders correctly, with nothing else having changed.  Seems to be an initialization problem or something. 

plnkr: http://plnkr.co/edit/W7Kv5GlhxYmYCF3uK3X6?p=preview
If you hit Toggle Map, the center is somewhere in Kansas (the default center of the map). But if you hit Toggle two more times to hide and reshow it, it centers correctly on the marker. 

I've tried lots of tricks with ng-if's, $timeout's, etc, but can't get this to work.

**Comment by namelivia** [comment]
+1 having this issue too. @jgr3go , did you find some tricky way to get this working?

**Comment by xavhan** [comment]
I have also this issue, I tried some stuff with ng-show instead of ng-if but not much luck either, I the markers are here but the map background does not load.

**Comment by davidpelayo** [comment]
It's also happening to me in `2.3.2` and haven't still found a proper way to hack it. Any insights?

**Comment by davidpelayo** [comment]
As @namelivia pointed out, I could hack it by setting the markers data after displaying the map.
I will try to review the source code to detect the error and upload a fix.

**Comment by davidpelayo** [comment]
Still having the same issue. Anyone could find the solution?

**Comment by davidpelayo** [comment]
Still having the same issue: http://plnkr.co/edit/soESE7mAC1n5bn61pxGI?p=preview
