### ISSUE TITLE
Visualization layer not working

### ISSUE THREAD

**Issue by MattDionis** [angular-ui/angular-google-maps#1431]
The below code works great for everything but the visualization, specifically heatmap, layer. This layer simply does not appear on my map:

```<ui-gmap-google-map center='playerMap.center' zoom='playerMap.zoom'>
  <ui-gmap-layer type="TrafficLayer" show="true"></ui-gmap-layer>
  <ui-gmap-layer type="BicyclingLayer" show="true"></ui-gmap-layer>
  <ui-gmap-layer namespace="visualization" type="HeatmapLayer" show="true"></ui-gmap-layer>
  <ui-gmap-markers
    models="playerMap.markers"
    coords="'self'"
    icon="'icon'"
    doCluster="playerMap.cluster"
    options="'options'">
    <ui-gmap-windows isIconVisibleOnClick="true">
      <b ng-non-bindable>Address: {{location}}</b>
    </ui-gmap-windows>
  </ui-gmap-markers>
</ui-gmap-google-map>```

I've made sure to include the visualization library in my index.html where I pull in the Google Maps API:

`<script src="//maps.googleapis.com/maps/api/js?v=3.exp&libraries=visualization&sensor=false"></script>`

**Comment by nmccready** [comment]
Figure it out?

**Comment by MattDionis** [comment]
Not exactly. I did, however, realize that it wasn't an 'issue' so much as me not understanding how to implement it. I added an `onCreated` callback (`playerMap.heatLayerCallback`) to the `ui-gmap-layer` element. My confusion is how to write this callback function in my controller. My data looks something like this ```vm.markers = [{id: id, latitude: latitude, longitude: longitude}, {...}, ...]```. I realize I need to attach the coordinates to my layer through the callback, but do not understand how to write `vm.heatLayerCallback`.

**Comment by nmccready** [comment]
I assume you've looked at the existing example in examples?

**Comment by MattDionis** [comment]
Yes, and I've altered it to the below to at least get started. Obviously the `sampleData` area is where I need to grab the coords from my actual `vm.markers` array. That's where I get tripped up.

```var heatLayer = null
vm.heatLayerCallback = function(layer) {
    heatLayer = new HeatLayer(layer);
};

  var HeatLayer = function(heatLayer) {
    var sampleData = [
      new google.maps.LatLng(33.2192774, -84.8359395)
    ];

    var pointArray = new google.maps.MVCArray(sampleData);
    heatLayer.setData(pointArray);
  };```
