### ISSUE TITLE
lodash.js

### ISSUE THREAD

**Issue by kingonoverall** [angular-ui/angular-google-maps#1433]
Hi, kann you change : 
from: http://angular-ui.github.io/angular-google-maps/vendor/scripts/lodash.compat.js 
to : http://angular-ui.github.io/angular-google-maps/vendor/scripts/lodash.js
in the html code so the main page (http://angular-ui.github.io/angular-google-maps/) and most important in the demo page can work properly and not thow the " _.get is not a function" error.
thx

**Comment by nmccready** [comment]
It's fixed on master.

**Comment by kingonoverall** [comment]
hi, there is stil the "TypeError: _.get is not a function" error on the Demo page (check to console 
output) and the 2/3 of the examples on the map are missing (rectangle, polygon, etc.)
I see you use version 2.4.1 (http://cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js)
I also has the same problme with 2.4.1 , after changing to  version 3.10.1 (//cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.js)  the problem was gone.

**Comment by nmccready** [comment]
I haven't pushed the website.  But yes 2.4.1doesnt work as there error states you need _. Get which is in 3.7+ or so. It was stated in a recent ticket as well. I don't have the number but search and ye shall find it.

**Comment by nmccready** [comment]
Re-opening to have a discussion how how we should version bump the next release. Possibly to 2.2.X due to the breaking change of lodash.  BTW this is from this PR https://github.com/angular-ui/angular-google-maps/pull/1389

**Comment by nmccready** [comment]
As discussed here as well https://github.com/angular-ui/angular-google-maps/issues/1429.  Where valid lodashes for future releases are 3.7+ (latest is 3.10.1).

**Comment by wrummler** [comment]
If we're doing semver, shouldn't a breaking change (whether in API or via dependency) be a major bump? Unless we're doing a custom type of semver? I may've missed discussion elsewhere about it.

**Comment by nmccready** [comment]
I agree @wrummler but people going to 2.1.6 that use old lodash will expect the old one to work. If we move to 2.2.X is in a way a breaking change.  Reasoning from here #1348

**Comment by nmccready** [comment]
I am gonna polyfil lodash if _.get is missing to resolve the error without going to 2.2.

**Comment by nmccready** [comment]
#1455
