### ISSUE TITLE
How to use infobox instead of infowindow

### ISSUE THREAD

**Issue by youfacepalm** [angular-ui/angular-google-maps#1434]
Hello, thanks for the awesome library! Is there any documented resource that explains the usage of infobox with this library? I could not find it in the official docs on your website. Thanks!

**Comment by Danscho** [comment]
Add a boxClass property to your window options object.

e. g.: 
    windowOptions:{
        boxClass: "YOUR CSS CLASS",
        boxStyle: { "YOUR STYLE" }
    }

**Comment by youfacepalm** [comment]
Thank you very much for saving my day. It would be nice if this is included in the official docs

**Comment by nmccready** [comment]
@youfacepalm if you'd like to contribute feel free to PR what you have learned to the website branch.

**Comment by arielmcm** [comment]
I can't make it work with angular-google-maps 2.2.1... even when I try the fiddle above with that version it doesn't work. Is there another way to do it?

**Comment by Danscho** [comment]
Updated fiddle [http://jsfiddle.net/Danscho/L789znLk/18/](url) (google maps was not loaded because I didn't use https -> fixed link)
Working fiddle for v2.2.1: [https://jsfiddle.net/Danscho/206b3dnm/2/](url

**Comment by arielmcm** [comment]
It works, Thanks!!
