### ISSUE TITLE
event when (info) window is Ready

### ISSUE THREAD

**Issue by jlempis** [angular-ui/angular-google-maps#1437]
Hi,

I want to customise the window (opened on marker's clik)

I wold execute jquery  code wihen then Window is Ready and i want to trap the "domeready" event is fired (Like http://en.marnoto.com/2014/09/5-formas-de-personalizar-infowindow.html)

Is it possible to do so ? 

Thanks in advance

John

**Comment by nmccready** [comment]
Please start reading about angular anywhere. Then please start reading the website documentation. People will then help you when you have more experience under your belt.
