### ISSUE TITLE
How can I print the map?

### ISSUE THREAD

**Issue by upmauro** [angular-ui/angular-google-maps#1440]
Does anyone know how I can print the map?

**Comment by wrummler** [comment]
Not sure what you mean. To get the same result as if you printed the webpage a la <kbd>CTRL</kbd>+<kbd>P</kbd>? There's no functionality like this in AGM, and I'm not even sure browser JS can trigger the browser to print anything.

If you meant something else, please follow-up with clarification and more details. Closing for now, but please reopen if you follow-up. Thanks.

**Comment by samirfor** [comment]
I think @upmauro mean is this: https://developers.google.com/maps/documentation/static-maps/intro#quick_example

You can build a url that will return a static image, then print it.

Source: http://stackoverflow.com/questions/3730767/how-to-print-google-map-markers

**Comment by nmccready** [comment]
Probably could use  a headless browser to save the map off as well. We did something similar with Phantomjs
