### ISSUE TITLE
Page crashes when the polygon data is large

### ISSUE THREAD

**Issue by vppravi93** [angular-ui/angular-google-maps#1443]
Hi,
I used ```<ui-gmap-polygon .... editable="false" static="true" > ``` to display polygon where i feed around 15K latlongs,which works properly,but setting  editable to ```true ```,causes the page to crashes.

**Comment by nmccready** [comment]
Not surprised editable is a huge overhead. Figure out a a way around it to show less when you need to edit.

**Comment by nmccready** [comment]
Editable is entirley a google thing so it is not an issue here.
