### ISSUE TITLE
How do you support multple MarkerClusters

### ISSUE THREAD

**Issue by tianxu0836** [angular-ui/angular-google-maps#1444]
Is there are way to support multiple markerClusters?
Lets say if you want marks A,B,C only group by the cluster A, marks D,E,F,G only group by cluster B. 
No matter how you zoom, A,B,C should only be inside cluster A but not B. Same thing for marksers D,E,F,G.
How can I make this happen in angular-google-maps?
Does it support this feature? Is there an example?

**Comment by nmccready** [comment]
It may as I am not entirely sure. You will need to dig into the cluster tool from google maps api tools.

https://github.com/angular-ui/angular-google-maps/blob/master/curl.json#L5

**Comment by nmccready** [comment]
Specifically you need to look here http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.1.1/docs/reference.html at 
class MarkerClustererOptions calculator.
