### ISSUE TITLE
getting click event on marker click

### ISSUE THREAD

**Issue by Ardenexal** [angular-ui/angular-google-maps#1446]
Is it possible to get the click event when you're clicking on a marker I need to detect if the shift or ctrl key is being pressed when the marker is clicked for selecting multiple markers but is seems that only parameter that relates to the event is the event string which would be 'click'

**Comment by nmccready** [comment]
When the event happens in click check the window.event object. The info should be in there with attributes `metaKey` and `keyCode`.
