### ISSUE TITLE
Destroying a second set of marker while the first one is spiderfied triggers errors

### ISSUE THREAD

**Issue by Quovadisqc** [angular-ui/angular-google-maps#1449]
On zoom_changed, I use getZoom() to remove a list of markers at a certain zoom level.

My second list of markers doesn't use grouping ( cluster / spider ) and it seems to trigger errors.

I made a set of screenshots that should help debugging the issue:
http://imgur.com/FvNOm7s,1TNCWCS,fFwO3fl

Plunkr:
http://plnkr.co/edit/dlYebBzzUPPNN22rzv4w?p=info

Thanks!

**Comment by nmccready** [comment]
Ahh my bad there is no destroy method in the basic markers manager. Either PR a fix and add destroy which calls clear internally.

https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/managers/marker-manager.coffee

**Comment by nmccready** [comment]
Actually F it Ill do it now since the fix is so easy.

**Comment by nmccready** [comment]
Fixed, retest the plnkr with a blown cache, or another browser.
