### ISSUE TITLE
How to prevent map from being draggable?

### ISSUE THREAD

**Issue by srachit** [angular-ui/angular-google-maps#1454]
I could not find any reference to this in the docs. The things I have tried are
` <ui-gmap-google-map center="map.center" control="control" zoom="map.zoom" dragging=false>`
` <ui-gmap-google-map center="map.center" control="control" zoom="map.zoom" dragging="false">`
` <ui-gmap-google-map center="map.center" control="control" zoom="map.zoom" draggable=false>`
` <ui-gmap-google-map center="map.center" control="control" zoom="map.zoom" dragging="false">`

**Comment by nmccready** [comment]
Use `options="options"`

```coffee
scope.options = 
  draggable: false
```

**Comment by srachit** [comment]
Thanks!

**Comment by nmccready** [comment]
Np
