### ISSUE TITLE
TypeError: Illegal invocation

### ISSUE THREAD

**Issue by miclaus** [angular-ui/angular-google-maps#1461]
I have a route where a template is loaded, where I use the `ui-gmap-google-map` directive, and a controller. However *from time to time* I get the below error and nothing works afterwords anymore. I can't set markers, when moving the map, more errors get thrown and after **hours** of debugging I can't get to the bottom of this.

Console:
![screen shot 2015-08-31 at 13 10 27](https://cloud.githubusercontent.com/assets/4658706/9577539/256a174a-4fe2-11e5-9128-479f1f128988.png)

Has anybody had such an issue?

**Comment by nmccready** [comment]
please produce an example thus does not help

**Comment by nmccready** [comment]
needs plnkr

**Comment by miclaus** [comment]
I'll try to find some time to do a plunker next week.

However I have an example of the error online:
Go to http://mobilot.fhstp.ac.at/#/t2/map, then select "Neue Station" from the sidenav, then select the "Ort" tab and after a few seconds the error should appear in the console.

**Comment by nmccready** [comment]
Closing since no plnkr. Will re-open when one occurs.

**Comment by karser** [comment]
I encountered the same errors If I pass negative numbers to idKey attribute in ui-gmap-marker
