### ISSUE TITLE
HTML tags not working in marker window.

### ISSUE THREAD

**Issue by rakeshsthakur** [angular-ui/angular-google-maps#1464]
HTML tags were being displayed as they were onto the map; ex: < strong> hello </ strong>, instead of **hello**. I'm using version: 2.1.6
I gave a it a try to use ng-bind-html directive, but this resulted in an empty window, however the same $scope element was being displayed correctly on other parts of the page.
![screenshot from 2015-08-31 21 13 46](https://cloud.githubusercontent.com/assets/8661145/9596160/9c956782-5025-11e5-89ec-47f1bfd53667.png)

**Comment by nmccready** [comment]
Not enough information to reproduce, please provide an example. Also there are many examples where this is working.

**Comment by rakeshsthakur** [comment]
OK. Below an example form my project.

**Jade View:**
```
ui-gmap-google-map(center='map.center' zoom = 'map.zoom')
    ui-gmap-marker(coords = "marker.coords" idkey="marker.id")
        ui-gmap-window(options = "windowOptions" closeClick="colseClick()")
            {{title}}
```
**Controller:**
```
'use strict';
app.controller("mapCtrl", function($scope, uiGmapGoogleMapApi) {
    $scope.map = { center: { latitude: 0, longitude: 0 }, zoom: 8 };
    $scope.marker = {
        id: 1,
        coords: {
            latitude: 0,
            longitude: 0
        }
    };
    $scope.windowOptions = {
        visible: false
    };

    $scope.onClick = function() {
        $scope.windowOptions.visible = !$scope.windowOptions.visible;
    };

    $scope.closeClick = function() {
        $scope.windowOptions.visible = false;
    };
    $scope.title = '<div id="siteNotice">'+
        '</div>'+
        '<h1 id="firstHeading" class="firstHeading">Uluru</h1>'+
        '<div id="bodyContent">'+
        '<p><b>Uluru</b>, also referred to as <b>Ayers Rock</b>, is a large '+'</div>';

    uiGmapGoogleMapApi.then(function(maps) {

    });
});
```
I have also tried using jade in the $scope.title, but even that did not work.
Thanks,

**Comment by rakeshsthakur** [comment]
I have figured out a workaround from other examples, instead of styling the elements in the $scope.title, now I'm doing this under the ui-gmap-window tag in the main page.

**Comment by nmccready** [comment]
Yes that is recommended approach.
