### ISSUE TITLE
Map is flickering once displayed on page

### ISSUE THREAD

**Issue by bgold0** [angular-ui/angular-google-maps#1466]
I have the following code. When the map is loaded it just starts flickering. I've tried both ways of loading Google Maps API v3 but I can't figure out why it won't work. Does anyone have any suggestions?

[Video of the flickering map](http://streamable.com/evxw)

	<div ng-repeat="data in dataArray">
		<div ng-click="data.showMap = !data.showMap">
			<div>View Map</div>
		</div>
		<div ng-if="data.showMap" class="item" style="height:300px;">
			<ui-gmap-google-map center='data.map_data.center' zoom='data.map_data.zoom'></ui-gmap-google-map>
		</div>
	</div>

**Comment by nmccready** [comment]
Please produce a plnkr.

**Comment by bgold0** [comment]
I try but I get a
> QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

Here is the plunkr: http://plnkr.co/edit/lzMa1I50SBDS3dQGOYGv

**Comment by nmccready** [comment]
Thanks

**Comment by bgold0** [comment]
So does this seem to be an error on my end? Can i do anything to fix this?

**Comment by nmccready** [comment]
I did run the plnkr but didn't dive into it yet. Sorry I am am busy with this project and ng-leaflet and a full time job. I'll try to get to this when I can. 

Again if you need it immediately resolved diving in and contributing is recommended.

**Comment by nmccready** [comment]
It is on the milestone list therefore it is more than likely going to be looked at soon.

**Comment by nmccready** [comment]
So I am not sure this is valid yet. The link function on the directive is being hit from ng-if constantly which means its not the directive. It means its something in the setup of your controller and html. 

I'll keep digging but my guess is it is something with how ng-click works and digest; where something unexpected is happening.

**Comment by nmccready** [comment]
Well.. hmm it might be a watch depth thing.

**Comment by nmccready** [comment]
Yeah this is not the directive but a recursive design problem over your data. You can watch the html view and the whole app is rerendered constantly and this is not to do with this directive specifically.

**Comment by nmccready** [comment]
![screen shot 2015-09-14 at 1 05 36 pm](https://cloud.githubusercontent.com/assets/583593/9856206/4ea8ff90-5ae1-11e5-8899-4b812288fbd2.png)

**Comment by nmccready** [comment]
nvm I take back some of that as I changed
```
      <div ng-if="data.showMap" class="item" style="height:300px;">
        <div>
          hi
        </div>
        <!-- <ui-gmap-google-map center='data.map_data.center' zoom='data.map_data.zoom'></ui-gmap-google-map> -->
      </div>
```

and the recursion does not occur. So more digging.

**Comment by nmccready** [comment]
Still not sure what to make of this. Down deep in angular you can see here that ngIf is being fired when it really should not  (nothing changed). See the image and look at the `arguments`.

![screen shot 2015-09-14 at 2 04 13 pm](https://cloud.githubusercontent.com/assets/583593/9857632/9cddf6ae-5ae9-11e5-83e3-9df00248c1fe.png)

**Comment by nmccready** [comment]
Well `scope.$on('destroy', ->)` is being called just as much so something is causing the directive to be cleaned up.

**Comment by nmccready** [comment]
@bgold0 so this is a rather interesting issue which appears to be a bug or misunderstanding of limitation in angular itself. One thing is for certain in that angular 1.3.14 seems to behave (less buggy) than 1.4.5.

1.3.14 version of plunkr using a template instead of ui-gmap (to prove it is not ui-gmap):

![](http://g.recordit.co/ZrYLbHTxVi.gif)

1.4.5 version of plunkr using a template instead of ui-gmap (to prove it is not ui-gmap):
Shows flicker when mouse hovers over template. *not* shown in gif as it was not capturing the mouse. Anyway if you run it you'll see that the mouse goes from hand pointer to mouse arrow constantly and thus flickers.

![](http://g.recordit.co/pMeadMRUQs.gif)


In the end this appears to be an angular problem.

**Comment by nmccready** [comment]
Further notes, since seeing the flicker in ng-include (another independent scope directive) and seeing scope destroy and link constantly be called; there is nothing internally that is causing this.

**Comment by nmccready** [comment]
Modded plnkr with ng-include (which will be added to examples)
http://plnkr.co/edit/WDWlwWywr8eYMUunZjTs?p=info

**Comment by nmccready** [comment]
Just thought of a work around. I recommend writing your own `ng-if` call it whatever you want (maybe `ng-our-if`). Anyway copy and paste the necessary angular code and make sure the watch for ngif only continues if the watch values are different. That should solve your problem.
