### ISSUE TITLE
New cluster/spiderfy properties in markers directive not working

### ISSUE THREAD

**Issue by thatgirlcancode** [angular-ui/angular-google-maps#1468]
I noticed the doCluster and clusterOptions are now marked deprecated in the latest version. So I tried the new type properties, but they don't appear to be working. Here is my plunk... 

http://plnkr.co/edit/Kdi9ZILLarOSSkZiDDWq?p=preview

Am I doing something wrong?

**Comment by thatgirlcancode** [comment]
I figured out the issue in my local code, still not sure what's happening in this plunk though...

**Comment by nmccready** [comment]
Ok, the main issue is your pointing againt 2.0.X  I did not make any updates to 2.0.X as I am done maintaining both. So it is on 2.1.X and 2.1.6 only. 

Fixed here. You either need to bind it or set it to `"'cluster'"`

http://plnkr.co/edit/AB87rqoEumsmv8ZH6i0b?p=preview
