### ISSUE TITLE
[master] Documentation is unclear on how to set refresh

### ISSUE THREAD

**Issue by ChickenFur** [angular-ui/angular-google-maps#147]
In the master branch example it shows how if you have the map set to hidden you can get it to display properly when it is displayed using the attr: refresh="!isMapElementHidden"

I am using r1-dev and my map element is hidden until a button click.  The google map only fills the top left corner of the div until I resize the window.

From the new example I was hoping I could do the following:

```
<div class="google-map span9"
             center="map.center"
             zoom="map.zoom"
             draggable="true"
             dragging="map.dragging"
             bounds="map.bounds"
             refresh="!map.isMapElementHidden">
</div>
```

but this doesn't work.  How do I set it so it expands to fill the div on display?

![screen shot 2013-11-26 at 10 27 13 am](https://f.cloud.github.com/assets/587181/1624810/6a544a2a-56c8-11e3-8388-5eaad0fecd2f.png)

**Comment by jjbskir** [comment]
I see this issue was resolved awhile ago, but in case any one had the same issue as @StudentJoeyJMStudios it is b/c the $scope was updated outside of the Angular context and in the google call back function. Same issue as here - http://stackoverflow.com/questions/27995864/scope-is-not-accessible-from-callback-function-after-following-google-docs - Within the call back function $scope.$apply(); needs to get called.

**Comment by meyacine** [comment]
I've fixed this problem with a minimum manipulation, as i've seen in your messages. The map get refreshed when resize is triggered. So i've done it with gmap api's. Here is a plunker demo
http://plnkr.co/edit/jOydFAdVlNuPKO1qjSY7?p=preview

**Comment by nmccready** [comment]
@meyacine thank you. If you want to copy this and PR it to the examples directory I will surely accept it. Thanks again.

**Comment by hillaryskye** [comment]
Is there a way to refresh without the ng-click on a redirect in an a tag?

**Comment by nmccready** [comment]
Use $timeout which is triggered when your ng-show bound porperty changes.

**Comment by hillaryskye** [comment]
My issue is that I am using Google maps without the UI Angular, just pure Angular and Google Maps and when I redirect to a new page, the Google Maps doesn't appear unless I refresh the page.  I'm not sure what I need to put $timeout on.  I have an init function upon loading on the page, should I put it there?  Thanks, Hillary

**Comment by svkmedia** [comment]
I fix this problem with CSS visibility.
My map is in modal but modal has display: block and visibility: hidden.
When you click button to open modal just set visibility: visible
