### ISSUE TITLE
array prototype collision

### ISSUE THREAD

**Issue by NewestUser** [angular-ui/angular-google-maps#1476]
I have noticed in my project that when I change Array.prototype and use [ui-router](https://github.com/angular-ui/ui-router) upon performing a <code>state</code> transition a error occurs.

**Comment by nmccready** [comment]
Example?

**Comment by NewestUser** [comment]
![screenshot from 2015-09-04 23 01 56](https://cloud.githubusercontent.com/assets/7418570/9693425/0c1a00e6-5359-11e5-8b75-e8822f27dbcb.png)

This is where It points (if i'm not mistaking smthing)
```javascript
        removeEvents: function(listeners) {
          var key, l;
          if (!listeners) {
            return;
          }
          for (key in listeners) {
            l = listeners[key];
            if (l) {
              google.maps.event.removeListener(l);
            }
          }
        }
```

Currently in my project I have modified <code>Array.prototype</code> like so:
```javascript
Array.prototype.first = function () {
  return this[0];
};
```

**Comment by nmccready** [comment]
When I mean example I really need a plnkr which has the error in it so I can walk the debugger. Thanks. 

Well I would look into `google.maps.event.removeListener(l);` which my guess relies on `Array::first` my guess is you should not be messing with it. Especially if google is relying on it in a certain way. If you need your on impl of first then make it `Array::ourFirst` or something.`

**Comment by nmccready** [comment]
Anyway this collision is between you, google, and the browser not the directive.
