### ISSUE TITLE
ui-gmap-markers accessing individual marker data. 

### ISSUE THREAD

**Issue by zevkirsh** [angular-ui/angular-google-maps#1480]
dear angular google maps comunity

I  love your code and thank you for it. I love it so much and am using it so much that I am now finding an obstacle i am encountering.

we want to write a click function, to alert the specific geolocations of a set of markers,
we can do it with ui-gmap-marker with an ng-repeat but there is no way to access individual marker data with ui-gmap-markers .

we might be wrong, but we dont' think there is a method of doing it

essentially we want t use ui-gmap-markers and be able to alert different things for different markers

.

i am not certain you will understand the description of my problem, as I may not be clearly descriving the problem. if you would like more clarity to understand the problem
we are having PLEASE ASK ME.

and of course if you do understand the problem we are describing.
if you can help us in any way we would be very appreciative.

**Comment by nmccready** [comment]
hah just replied to this on g+; anyway if you can make a plnkr it would help a lot. 

But here is an example:

https://github.com/angular-ui/angular-google-maps/blob/master/example/issue-74-markers-events.html

https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/scripts/controllers/issue-74-markers-events.js#L84-L91

**Comment by zevkirsh** [comment]
thanks we are trying to avoid ngrepeat. 

to define the callback function we are loopiong through our array of models and defining that call back function. 
we just made an oversite.
