### ISSUE TITLE
Onclick make a specific vertex editable in polygon

### ISSUE THREAD

**Issue by vppravi93** [angular-ui/angular-google-maps#1481]
Is there a way or an option in the ` polygon directive` to make a specific vertex editable by clicking on the vertex instead of making the whole vertices editable in polygon?

**Comment by nmccready** [comment]
Not that I know of, feel free to dig into it.

**Comment by nmccready** [comment]
If you choose to dig in, I will leave this open for another Milestone and you can be assigned the ticket.
