### ISSUE TITLE
Can't display item info on windows directive nested in a markers directive

### ISSUE THREAD

**Issue by nahuelsgk** [angular-ui/angular-google-maps#1484]
I've been searching through many posts and I can't solve this issue:
On my HTML I have:
```
<div class="map-container">
                <ui-gmap-google-map center="map.center" zoom="map.zoom" control="mapControl">
                    <ui-gmap-markers models="markers" coords="'coordinates'" fit="true" icon="'icon_url'">
                        <ui-gmap-windows show="'showWindow'">
                            <div>
                                <p>Dynamic Marker created via a delay!</p>
                                <div ng-non-bindable>Title: {{title}}</div> //I'm not able to display of the title!!
                            </div>
                        </ui-gmap-windows>
                    </ui-gmap-markers>
                </ui-gmap-google-map>
            </div>
```
On my JS:
```
angular.module('postsAllCtrl', ['postService', 'uiGmapgoogle-maps'])

    .controller('postsAllController', function($scope, $http, Post) {

        $scope.loading   = true;
        $scope.search    = '';
        $scope.map       = {
            center:  {latitude: 0, longitude: 0},
            zoom:    16
        };
        $scope.mapControl = {};
        $scope.markers   = [
            {
                coordinates: { longitude:0, latitude: 0,id:1},
                id:1,
                showWindow: false,
                title: 'Hola 1',
                icon_url: '/assets/dashboard/images/pinview-mock-user@2x.png'
            },
            {
                coordinates: {longitude:2, latitude: 10,id:2},
                id:2,
                showWindow: false,
                title: 'Hola 2',
                icon_url: '/assets/dashboard/images/pinview-mock-user@2x.png'
            }
        ];
```
And the only result I got is this:
![screen shot 2015-09-07 at 18 32 18](https://cloud.githubusercontent.com/assets/4019628/9720490/eceb5714-558e-11e5-92bf-deca77e718bc.png)

I've been looking to several posts. And actually don't know why the code in the api demo is working ( http://angular-ui.github.io/angular-google-maps/#!/api/windows ). The version I'm working on is the version 2.2.

**Comment by nahuelsgk** [comment]
I was doing some test and I think the problem is the framework I'm using: Laravel.
The templating motor is Blade, and to parse the model it uses the '{{model->param}}'; the same as angular. And to make Laravel working with Angular we modifiy interpolate provider:

  $interpolateProvider.startSymbol('<%');
  $interpolateProvider.endSymbol('%>'); 

So when I try to parse the model info on the windows shows as it follows:
![screen shot 2015-09-08 at 09 51 05](https://cloud.githubusercontent.com/assets/4019628/9729356/2a197e6a-560f-11e5-9722-6a383c2b85a9.png)

**Comment by nahuelsgk** [comment]
I close the issue because, of course is a problem a issue of combining the two templating motors: Blade and Angular. 
The solution(workaound):
a) On Laravel controller: (not necessary like this)
```
\Blade::setContentTags('<%', '%>');
\Blade::setEscapedContentTags('<%%', '%%>');
```

b) On html:
Angular can template as usual and Blade with this new tags.
c) Now maps renders the info of the model.

My conclusion: there's an issue on rendering the windows template when the interpolateProvider is change like this:
```
$interpolateProvider.startSymbol('<%');
$interpolateProvider.endSymbol('%>');
```

**Comment by nmccready** [comment]
Thanks for closing and posting a solution, glad you figured it out.
