### ISSUE TITLE
Markers doRebuildAll=false still rebuilds all markers

### ISSUE THREAD

**Issue by rcino** [angular-ui/angular-google-maps#1485]
Not sure if this is related to [#1447](https://github.com/angular-ui/angular-google-maps/issues/1447)

When pushing markers to array, even with doRebuildAll=false specified, markers seem to be rebuilt (assuming since they flash).  When adding 1000's of markers, this gets cumbersome.

This was working with 2.0.12, but seems to no longer work with 2.2.0.  I created a Plunker to compare.  You can simply comment out the 2.2.0 scripts and uncomment the 2.0.12 scripts in the HTML to see the difference.  I added Animation to markers so it's easier to see.  Click "Add Marker" to randomly add a marker and see them re-build.  

[Plunker example](http://plnkr.co/edit/OWQLY8dJHoLr75X6V6yw?p=preview)

Love this library, thanks in advance for the help.  Happy to add to the example if needed.

**Comment by pluthong** [comment]
is it fixed?
