### ISSUE TITLE
After the latest release, getting an Ingector Error

### ISSUE THREAD

**Issue by janurag** [angular-ui/angular-google-maps#1486]
As soon as I changed my version to older one my error got resolved.

- [ ] Below is error

> Error: [$injector:modulerr] http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=mainApp&p1=%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.3.14%2F%24injector%2Fmodulerr%3Fp0%3DuiGmapgoogle-maps%26p1%3D%255B%2524injector%253Amodulerr%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.3.14%252F%2524injector%252Fmodulerr%253Fp0%253DuiGmapgoogle-maps.directives.api%2526p1%253D%25255B%252524injector%25253Amodulerr%25255D%252520http%25253A%25252F%25252Ferrors.angularjs.org%25252F1.3.14%25252F%252524injector%25252Fmodulerr%25253Fp0%25253DuiGmapgoogle-maps.directives.api.models.parent%252526p1%25253D%2525255B%25252524injector%2525253Amodulerr%2525255D%25252520http%2525253A%2525252F%2525252Ferrors.angularjs.org%2525252F1.3.14%2525252F%25252524injector%2525252Fmodulerr%2525253Fp0%2525253DuiGmapgoogle-maps.directives.api.models.child%25252526p1%2525253D%252525255B%2525252524injector%252525253Amodulerr%252525255D%2525252520http%252525253A%252525252F%252525252Ferrors.a

## Here is what I did:
**Original**
https://rawgit.com/angular-ui/angular-google-maps/master/dist/angular-google-maps.js
**Solution**
Original changed to this:
https://rawgit.com/angular-ui/angular-google-maps/2.1.5/dist/angular-google-maps.js

*Hope this help somebody*

**Comment by sven-er** [comment]
have you insert the new Dependency ?
<script src="http://cdn.rawgit.com/nmccready/angular-simple-logger/0.0.1/dist/index.js">

**Comment by nmccready** [comment]
@janurag please read the readme and check existing tickets
