### ISSUE TITLE
Add angular-simple-logger to dependencies

### ISSUE THREAD

**Issue by trongrg** [angular-ui/angular-google-maps#1487]
Hi @nmccready,

First of all, thanks for the great plugin.

I see that you closed #1477 by adding angular-simple-logger to readme

However, this will make angular apps that depend on this plugin breaks right after `bower update`, like mine

If nemLogging is a dependency, IMHO, it is best to add it to dependencies in bower.json, so bower automatically resolve that, and we don't have broken apps.

**Comment by nmccready** [comment]
yes ? https://github.com/angular-ui/angular-google-maps/blob/master/bower.json#L7

**Comment by nmccready** [comment]
It is there so not sure what your problem is.
