### ISSUE TITLE
Module 'uiGmapgoogle-maps' is not available! You either misspelled the module name or forgot to load it.

### ISSUE THREAD

**Issue by MichaelGofron** [angular-ui/angular-google-maps#1489]
I am receiving this error when trying to follow the quickstart guide on the angular-google-maps website.

I have followed the instructions on the guide and I am not sure what I'm doing wrong.

I have imported the lodash, angular-google-maps, google-maps cdn files; I have bower installed the dependency, set up the config in the main app.js file, set the module on the app.js file, and added the directive.

I am somewhat confused as to whether I am doing it right because the documentation appears to be conflicting here: https://angular-ui.github.io/angular-google-maps/#!/use vs here: http://angular-ui.github.io/angular-google-maps/#!/api/GoogleMapApi where the config in one uses the uiGmapGoogleMapApiProvider and the other uses GoogleMapApiProviders

**Comment by cthrax** [comment]
@MichaelGofron actually they are both using uiGmapGoogleMapApiProvider, one is using the angular array notation for dependency injection and doing a rename on the variable passed to the config function, the other is using implicit DI. If you're still having problems, it's a lot easier to help out when there's a plnkr demonstrating the problem.  Thanks!

**Comment by nmccready** [comment]
Do you have the new logging dependency? angular-simple-logger? 

Also as for the conflicting documentation.

```
angular.module('myApplicationModule', ['uiGmapgoogle-maps'])
.config( ['uiGmapGoogleMapApiProvider', function(GoogleMapApiProviders) {
        GoogleMapApiProviders.configure({
            china: true
        });
    }]
);
```

vs
```
.config(function(uiGmapGoogleMapApiProvider) {
    uiGmapGoogleMapApiProvider.configure({
        //    key: 'your api key',
        v: '3.20', //defaults to latest 3.X anyhow
        libraries: 'weather,geometry,visualization'
    });
})
```

The first has an annotation where 'uiGmapGoogleMapApiProvider' is injected into `GoogleMapApiProvider` where `GoogleMapApiProvider` could be named `zipodityDooDah` and it still would work.



```
angular.module('myApplicationModule', ['uiGmapgoogle-maps'])
.config( ['uiGmapGoogleMapApiProvider', function(zippy) {
   zippy.configure({
            china: true
        });
    }]
);
```

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/bower.json#L7

**Comment by nmccready** [comment]
If your still seeing strange errors; can you make a plnkr I can run and I will get to it.

**Comment by MichaelGofron** [comment]
I can try to set up a plnkr to re-create the issue although I'm not sure whether I will be successful. My project code can also be found here under the feat/maps branch: https://github.com/MichaelGofron/IndigenousNoodle

**Comment by KaioWeb** [comment]
[ Possible Resolution ]
I had the same problem
In my case I lacked import the file angular-simple-logger.min.js

**Comment by awwong1** [comment]
I'm getting this error as well. I followed all of the quickstart steps from the website.
I'm adding angular-google-maps to a barebones angular-fullstack project generated from https://github.com/DaftMonk/generator-angular-fullstack. 

It seems to fail when running "karma:unit" (karma) task.

However, `grunt build` and `grunt serve` still work fine and the website behaves as expected. (Map shows up, is interactive, etc)
