### ISSUE TITLE
2.2.0 not working with Meteor (stable) (dependency issue)

### ISSUE THREAD

**Issue by ervinfetic** [angular-ui/angular-google-maps#1490]
Following the tutorial on the angular meteor website (http://angular-meteor.com/tutorials/angular1/google-maps) when adding the google maps as a dependency the application comes up with the following error:

Error: [$injector:nomod] Module 'nemLogging' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

The error only shows up when using the latest version of google maps. I fixed the error by using a previous version of google maps (2.1.0).

**Comment by nmccready** [comment]
There is a new dependency which is in the readme, package.json, bower.json, and there are probably 4 closed issues about this same topic. I might have missed something in meteor as it is not my main gig (not an expert in it).

**Comment by nmccready** [comment]
#1486 #1487 #1477

**Comment by nmccready** [comment]
@ervinfetic the problem is here https://github.com/angular-ui/angular-google-maps/blob/master/package.js#L20-L24

In reality the dependencies to package.js should be coming from package.json.

**Comment by ervinfetic** [comment]
Really I do not know much about that. I only described my experience with angular-meteor tutorial and problem that I had in the sixteenth step. I replaced current dependency with previous version of google-maps and that's it.

Best, Ervin.

**Comment by nmccready** [comment]
Yes its a problem with our meteor setup. I will resolve it and try to redeploy it.

**Comment by mikemorris46** [comment]
Had the same problem as ervinfetic and used the same workaround - will retry with latest version (2.2.1) when available.

**Comment by nmccready** [comment]
pushed 2.2.1 fixed

https://atmospherejs.com/angularui/angular-google-maps

**Comment by mikemorris46** [comment]
Retried with version 2.2.1 - works great. Many thanks
