### ISSUE TITLE
after update to 2.2  ui-gmap-polygon fit="true" is not working

### ISSUE THREAD

**Issue by yesarpit** [angular-ui/angular-google-maps#1493]
After Updating my package to 2.2,
I am unable to get auto fit for < ui-gmap-polygon. >

howeever fit is working fine for < ui-gmap-markers >

**Comment by nmccready** [comment]
Polygon fit true never worked. It only works for polygons. I am working on this issue though.

**Comment by nmccready** [comment]
#1458

**Comment by ashtt** [comment]
@yesarpit  any updates or solution for this issue ?

**Comment by yesarpit** [comment]
@ashtt As mentioned above by @nmccready it doesnt works for polygon.
As a workaround I manually created auto fit function for polygon. I Don't have that code with me right now.
You can also play with google maps api directly to get an alternative.

**Comment by ashtt** [comment]
I am just curious that how did it worked in 2.1.5 and stopped working in 2.3.2 for me ?!
*Just mentioned the versions very smoothly* B-|
