### ISSUE TITLE
API Documentation preview not working

### ISSUE THREAD

**Issue by Janjuks** [angular-ui/angular-google-maps#1495]
Scripts are not found in http://angular-ui.github.io/angular-google-maps/#!/ API Documentation page. None of previews are working because of this.

**Comment by nmccready** [comment]
@pcbulai can u check this out. I know its broke; just havent looked at it. I dont think it should be too bad to figure out.

**Comment by pcbulai** [comment]
Will do.

**Comment by nmccready** [comment]
Fixed here for most examples. DrawingManager needs to be rewritten.

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/commit/383e671a09ee30174aebdc139e394eba464c710c
