### ISSUE TITLE
click or dblclick event in polygon (drawing manager)

### ISSUE THREAD

**Issue by cristianhoyos66** [angular-ui/angular-google-maps#1496]
Hi,
first of all, thank you for so good directive 

I'm using drawing manager and I dont get the way to get coordinates of a polygon drawn when this change. If I drag a polygon ¿how to know current coordinates? I assumed that it could be with click and dblclick event, but I dont get how to use it.

**Comment by nmccready** [comment]
Yes this code needs to be added as it was never implemented. I believe this is talked about somewhere else in a ticket.

As you can see it is very barebones. https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/parent/drawing-manager-parent-model.coffee

**Comment by nmccready** [comment]
So the sky is the limit on how you would like this implemented if you want to contribute and make it yours.

**Comment by cristianhoyos66** [comment]
I find a way to do this, when a polygon is drawn save inmediatly in polygons directive and i can use click in this object
