### ISSUE TITLE
Please integrate angular-simple-logger

### ISSUE THREAD

**Issue by adyba** [angular-ui/angular-google-maps#1499]
The new version has a new `angular-simple-logger` dependency, which looks very modular&sexy. 
The trouble is those 60 effective lines of code shut down every single sample|Plunk|JsFiddle|CodePen web wide. Even `angular-google-maps` documentation is down #1495.
Please repeat yourself and include `angular-simple-logger` into master branch we all are linking for years. 
BTW `angular-simple-logger` official dist filename is `index.js`

**Comment by piernik** [comment]
And index.js isn't minified ;)

**Comment by nmccready** [comment]
I'll minify it but I am not integrating it. Many libraries have dependencies. I have been integrating libraries for a while. This has been basically a pleasantry but probably not the right way. This can lead to duplicate dependencies in a code base unexpectedly.

**Comment by adyba** [comment]
To be honest, you haven't integrated an external library. You have just decided to keep a 60 lines of your own code as a standalone library just to make other people life bit more difficult. I would never suggested this if you weren't sole and only contributor of `angular-simple-logger` (1st commit on Sep 3, 2015) and `angular-google-maps` were the only package that uses da chunk.

**Comment by nmccready** [comment]
@adyba get a life . This library depends on angular and lodash. What is one more dependency? Also the main reason it is an external dependency is because it is an angular library. Therefore I don't need to hide it from global scope.
