### ISSUE TITLE
Problem with angular $routeProvider

### ISSUE THREAD

**Issue by juliantiemann** [angular-ui/angular-google-maps#1506]
Hey, there is a problem with using angular-google-maps and the angular route provider.

i have a really simple map setup, only for testing

In the controller: 
```
$scope.map = { center: { latitude: 45, longitude: -73 }, zoom: 8 };
```
In the View:
```
<ui-gmap-google-map center='map.center' zoom='map.zoom'></ui-gmap-google-map>
```
And really simple routes
```
.when('/', {
  templateUrl: 'views/main.html',
  controller: 'MainCtrl',
})
.when('/about/', {
  templateUrl: 'views/about.html',
  controller: 'AboutCtrl',
})
```

Now every time i change the page I get the following error message. What can I do? I think this should not happen in the very standard setting
```
TypeError: a[Ec] is not a function
    at Object.S.removeListener (main.js:19)
    at Object.angular.module.service.$log.removeEvents (angular-google-maps.js:942)
    at angular-google-maps.js:6454
    at Scope.parent.$get.Scope.$broadcast (angular.js:16200)
    at Scope.parent.$get.Scope.$destroy (angular.js:15812)
    at cleanupLastView (angular-route.js:909)
    at update (angular-route.js:950)
    at Scope.parent.$get.Scope.$broadcast (angular.js:16200)
    at angular-route.js:619
    at processQueue (angular.js:14634)
```
This only happens, when i leave the page.

**Comment by juliantiemann** [comment]
I was searching for a solution for some hours now, and just saw, that there is a ng-route example after i posted this. I'll check that one out first. Sorry

**Comment by juliantiemann** [comment]
This issue was caused by another js library

**Comment by nmccready** [comment]
Thank you for posting back to help others.
