### ISSUE TITLE
Auto Deploy Website to gh-pages via travis

### ISSUE THREAD

**Issue by nmccready** [angular-ui/angular-google-maps#1507]
Would nice to add some auto deploy scripts to travis anyone care to make that a task and take it on?

#1504

**Comment by cthrax** [comment]
I made some changes on website, this should work now.

**Comment by nmccready** [comment]
kick arse! :+1:

**Comment by nmccready** [comment]
@cthrax can u reference the commits here?

**Comment by cthrax** [comment]
It took a few commits to get right, didn't have a local travis to run against, so it necessitated committing and trying and it out.

**Comment by nmccready** [comment]
nice
