### ISSUE TITLE
kml layer google.maps[this.attrs.type] is not a function error

### ISSUE THREAD

**Issue by jbduzan** [angular-ui/angular-google-maps#1508]
Hellow,

I'm trying to display a layer from a kml file using ui-gmap-layer directive.

I've got the following error on run : 

```javascript
TypeError: google.maps[this.attrs.type] is not a function
    at f.b.module.factory.f.createGoogleLayer (angular-google-maps.min.js:7)
    at f.a [as createGoogleLayer] (angular-google-maps.min.js:7)
    at new f (angular-google-maps.min.js:7)
    at angular-google-maps.min.js:8
    at processQueue (angular.js:14567)
    at angular.js:14583
    at Scope.parent.$get.Scope.$eval (angular.js:15846)
    at Scope.parent.$get.Scope.$digest (angular.js:15657)
    at angular.js:15885
    at completeOutstandingRequest (angular.js:5394)
```

I've made a plunker to show you : http://plnkr.co/edit/HPcnQmuar73uLrmWqpgT?p=preview

**Comment by nmccready** [comment]
I'm not sure if every layer possible will work with layer. In general it works with most and the code is quite easy to follow and expand. I can look at the plnkr and give you guidance, but I think the directive itself may need to be expanded.

**Comment by jbduzan** [comment]
Ok, i will give it a look and try to expand it. Thx

**Comment by nmccready** [comment]
We can leave this open if you want to mention commits and what not. I will openly accept PRs/commits for layer.

**Comment by bberenberg** [comment]
I just tried to use HeatmapLayer and ran into the same problem, really disappointing after I spent a bunch of time implementing the rest of the map.

**Comment by nmccready** [comment]
@bberenberg have u looked in the main example on how heatmap is implemented?

**Comment by bberenberg** [comment]
@nmccready I couldn't really figure out the example code, ended up moving to ng-map which has been much simpler to work with.

**Comment by nmccready** [comment]
@bberenberg no problem I recommend using that anyway as I don't have the time to support this anymore.
