### ISSUE TITLE
Installation issue - Module 'nemLogging' is not available

### ISSUE THREAD

**Issue by FrancescoMussi** [angular-ui/angular-google-maps#1512]
Hello guys! 
Have made some attempts to set it up, but i always arrive to the point when the app crash giving the following error:

Error: [$injector:modulerr] Failed to instantiate module my_app due to:
[$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps due to:
[$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.directives.api due to:
[$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.directives.api.models.parent due to:
[$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.directives.api.models.child due to:
[$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.directives.api.utils due to:
[$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.extensions due to:
[$injector:modulerr] Failed to instantiate module uiGmapgoogle-maps.providers due to:
[$injector:modulerr] Failed to instantiate module nemLogging due to:
[$injector:nomod] Module 'nemLogging' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I have installed angular-google-maps using bower.
Did i miss something?

Thank you!

**Comment by nmccready** [comment]
Please search some relatively recent issues as this is a dupe. Your missing a new dependency which can be found in package.json, bower.json and package.js.

**Comment by FrancescoMussi** [comment]
Sooorry.. I need help!
I have installed angular-simple-logger with bower and now the app doesn't crash anymore.
However the map is not working. I get this error:

Error: _ is not defined
@http://localhost/.../angular-google-maps.min.js:5:2940
