### ISSUE TITLE
scrollwheel: false not working

### ISSUE THREAD

**Issue by mackelito** [angular-ui/angular-google-maps#1513]
When adding "scrollwheel: false" as an option it's still possible to scroll the map.

**Comment by nmccready** [comment]
What about messing with css and using overflow on the map container?

**Comment by nmccready** [comment]
I know this is besides the point , but looking for workarounds.

**Comment by mackelito** [comment]
Sorry... this "bug" was on the other side of the screen... aka, Me! ;)

**Comment by nmccready** [comment]
np thanks for closing
