### ISSUE TITLE
Memory leak when updating markers

### ISSUE THREAD

**Issue by spyridonas** [angular-ui/angular-google-maps#1523]
I have 3 markers on my page and i update them every second. Before i insert them on the map i create an array with all the properties and an info window but i don't set a click handler, it automatically appears when i click. Now the problem is that every time i update the array and re-insert it to the scope, a new $scope object is created every time , and that's leads to memory leak. How can i destroy/unbind the previous $scope.markers ? i tried markers.$destroy() but it didn't work. I am using version 2.2.1

**Comment by brgrz** [comment]
Do you notice memory leaks with or without Chrome dev tools opened?

**Comment by spyridonas** [comment]
The app gradually slows down and i opened chrome dev tools to investigate, along with Shift+Esc thing. I found that i had new scopes object on top of the old ones with the Batarang chrome plugin.

**Comment by brgrz** [comment]
Batarang could also be the issue. BTW isn't Batarang dead/not working anymore?

**Comment by spyridonas** [comment]
I develop an app using ionic framework and angular-google-maps, it also goes slow on mobile when i compile. Batarang was last updated 13 days ago(on their github account) so i don't think it's dead.
My temporary fix is to clear the scope, $scope = $scope.$new(); but it explodes the whole program... at least the watcher dont go above 100 that way ( if i don't do that, watchers can go over a million)

**Comment by nmccready** [comment]
please keep this down to 1 issue since they are basically the same #1524

**Comment by nmccready** [comment]
No offense to batarang.. but it has been kinda crappy for a while. It is always slow on any angular app and debugging with it is near impossible since they made the big ui change. Log statements for debugging and or using chrome debugger works best for me.
