### ISSUE TITLE
Supporting tilt

### ISSUE THREAD

**Issue by behappyrightnow** [angular-ui/angular-google-maps#1526]
I was trying to find how to support tilt gestures but could not find anything. In Google Maps, ctrl+click allows tilting - I am trying to get that to work in the API with angular-google-maps. I tried setting the rotate control to true in map options, but that did not work either.

```
$scope.map = {
        center: { latitude: 45, longitude: -73 },
        zoom: 8,
        rotate: true,
        options: {
            mapTypeId: google.maps.MapTypeId.SATELLITE,
            mapTypeControl: true,
            mapTypeControlOptions: {
                style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
            },
            rotateControl: true
        }
    };
```

Is this supported? 

Thank you so much!

**Comment by nmccready** [comment]
I have no idea what tilt is so no. But if you want to champion getting it to work by all means start digging into the code and submit P(change requests).

**Comment by mohsinkerai** [comment]
I think this means rotating map through some degree

lets us say tilt the map **90 Degree** 

this means rotate the map

**Comment by nmccready** [comment]
@mohsinkerai are you indicating you want to work on this?
