### ISSUE TITLE
Unable to disable autocomplete for searchbox

### ISSUE THREAD

**Issue by bobbyziom** [angular-ui/angular-google-maps#1529]
Maybe I'm doing this all wrong, but I want the search box to just filter markers as a function of a ng-model. Therefore I'm aiming to disable the autocompletion of the searchbox, as I'm not searching for places, but filtering map content based on the model. I've tried with the autocomplete: false option, but it doesn't work. Been searching for similar issues, but it seems to me that every issue regarding autocompletion is that the autocompletion doesn't work, which is actually what I'm trying to achieve.

My searchbox object:
``` javascript
$scope.searchbox = {
			template:'searchbox.tpl.html',
			position:'top-center',
			options: {
				autocomplete: false,
				bounds: {}
			},
			events: {
				places_changed: function (searchBox) {
					console.log(searchBox);
				}
			}
		};
```

HTML:
``` html
	<ui-gmap-google-map center="map.center" zoom="map.zoom" options="mapOptions">

		
		<ui-gmap-markers 
			models="markers" 
			coords="'self'" 
			icon="'icon'" 
			click="markerClick">
    	</ui-gmap-markers>

    	<ui-gmap-search-box options="searchbox.options" template="searchbox.template"
                            events="searchbox.events" position="searchbox.position" ng-model="search"></ui-gmap-search-box>

	</ui-gmap-google-map>	
```

Is it possible to disable autocomplete in the searchbox?

Thanks

**Comment by kandizzy** [comment]
@bobbyziom The autocomplete boolean when true makes the directive instantiate a Place Autocomplete, when false or undefined it instantiates a Places search box. There's a link in the [api docs](http://angular-ui.github.io/angular-google-maps/#!/api/search-box) that explains the difference between the two.

The results view is part of the default functionality for both of those Google APIs and there isn't a way to toggle them off. 

Maybe a custom control that is just an input field would work for filtering your markers?

**Comment by bobbyziom** [comment]
@kandizzy thanks alot. I think custom control is the solution. Implemented it like this using $rootScope, if anyone should be interested:

``` javascript
		$scope.$watch('search', function() {
			var devicesFiltered = $filter('filter')($scope.devices, $rootScope.search);
			createMarkers(devicesFiltered);
		});
```

Where the createMarkers function handle the logic for creating the markers, obviously :)

**Comment by kandizzy** [comment]
@bobbyziom awesome! and thanks for posting your solution :+1:
