### ISSUE TITLE
Fixes for some memory leaks but i'm unable to implement them correctly.

### ISSUE THREAD

**Issue by spyridonas** [angular-ui/angular-google-maps#1531]
I don't know how to correctly implement them , since i don't know how coffeescipt works, maybe someone more experienced can help out. The problem i had was that when i refreshed the markers from ui-gmap-markers the watchers count was growing and growing. A fix was provided by @nmccready on #1524 (pr #1528) but not everything was fixed. After looking around at the code i noticed on window-child-model.coffee (src\coffee\directives\api\models\child) there where more commands on the "remove" than on the "destroy" . After copying the commands from remove to copy one of my issues where fixed ( the problem is i don't know exactly what fixed it). Then on src\coffee\directives\api\managers\marker-manager.coffee i copied over the same commands to the "destroy" and "clear" and more issues where fixed with this. Can somebody implement this fix properly and pr it ? Also i think that all of remove/destroy functions should be looked at, that two affect my implementation of angular-google-maps. Thanks.

**Comment by nmccready** [comment]
Heck I guess I'll leave the other ticket open this is way to terse with no code and code lines. If I could make subtasks I would. As for properly the fix was proper, will there possibly be more problems yes, its software. Lastly learn coffee as it is just javascript anyhow.
