### ISSUE TITLE
Ability to limit number of markers shown while spiderfied

### ISSUE THREAD

**Issue by MattDionis** [angular-ui/angular-google-maps#1532]
I'm trying to find a way to limit the number of markers shown when spiderfying. This feature works great, but in some instances I have 50-100+ markers spiraled out which makes the screen very cluttered. Is there a way to set an option so that say 20 markers max are spiderfied?

**Comment by nmccready** [comment]
I really don't know; you'll have to dig into MarkerSpiderfier itself to see if it has those options. If not then it will need to be added.

**Comment by nmccready** [comment]
@MattDionis any luck?

**Comment by nmccready** [comment]
Will rep-open on response.
