### ISSUE TITLE
Issue when toggling back and forth from 'cluster' to 'spider'

### ISSUE THREAD

**Issue by MattDionis** [angular-ui/angular-google-maps#1533]
I have created a map with both 'cluster' and 'spider' options. If I use a toggle I set up to flip back and forth between these settings everything works great. Also, if my first click is on a cluster the 'spider' type is triggered which is how I've designed it. The issue comes when I toggle to 'spider', then toggle back to 'cluster', then click a 'cluster'. My map should flip back to 'spider', but in this scenario it does not.

My html:

```
<ui-gmap-google-map center="userMap.center" zoom="userMap.zoom" options="userMap.options">
  <ui-gmap-markers
    ng-if="!userMap.doSpider"
    models="userMap.markers"
    coords="'self'"
    icon="'icon'"
    fit="userMap.fit"
    options="'options'"
    click="userMap.showWindow()"
    events="userMap.markersEvents"
    type="'cluster'"
    typeOptions="userMap.clusterOptions"
    typeEvents="userMap.clusterEvents">
    <ui-gmap-window
      show="userMap.window.show"
      coords="userMap.window.model"
      options="userMap.window.options"
      closeclick="userMap.window.closeClick()"
      templateUrl="'/app/gmUserMap/infoWindow.html'"
      templateParameter="userMap.window">
    </ui-gmap-window>
  </ui-gmap-markers>
  <ui-gmap-markers
    ng-if="userMap.doSpider"
    models="userMap.markers"
    coords="'self'"
    icon="'icon'"
    fit="userMap.fit"
    options="'options'"
    click="userMap.showWindow()"
    events="userMap.markersEvents"
    type="'spider'"
    typeOptions="userMap.spiderOptions"
    typeEvents="userMap.spiderEvents">
    <ui-gmap-window
      show="userMap.window.show"
      coords="userMap.window.model"
      options="userMap.window.options"
      closeclick="userMap.window.closeClick()"
      templateUrl="'/app/gmUserMap/infoWindow.html'"
      templateParameter="userMap.window">
    </ui-gmap-window>
  </ui-gmap-markers>
</ui-gmap-google-map>

Angular controller:
vm.clusterEvents = {
    click: function() {
      vm.doSpider = true;
      vm.fit = false;
    }
};

vm.clusterToggle = function(state) {
    vm.doSpider = state;
};
```

After triggering `vm.clusterToggle` the `click` handler in `vm.clusterEvents` no longer seems to work.

**Comment by nmccready** [comment]
Well I am not sure exactly why your ng-if is not working, but you can just use one markers directive and switch the type from 'spider' to 'cluster' and vice versa and it should work. It is also less html that way.

**Comment by nmccready** [comment]
Here is an example with it working the way u have it above. http://plnkr.co/edit/7OgXrZ?p=preview

**Comment by nmccready** [comment]
One downside of combining the directive into one ui-gmap-markers is possible event collision on the handles. So keeping them sep may be ideal.

**Comment by MattDionis** [comment]
Yeah, that was my issue. If I want to have a 'click' handler for 'spider' and a different 'click' handler for 'cluster' the single directive obviously breaks. Thanks for that example.

**Comment by JosepAlacid** [comment]
Plunker not working!
