### ISSUE TITLE
Configuring markers without changing the models

### ISSUE THREAD

**Issue by jaufgang** [angular-ui/angular-google-maps#1536]
Is there a way I can set marker icons and labels based on existing model properties without changing the models themselves?  It seems that to set icons and labels, each model needs to have an "options"  property containing an options config object and an "icon" property containing a path to an icon image.  
This seems to violate the separations of concerns of the MVC pattern, by forcing the models to be modified because of how its viewed.    

For example, if the models collection looks something like this
```javascript
[{ 
      route: 27,
      type:='bus' , 
      location:{latitude: 37.799916, longitude:-122.413663}
   }, {
      route: 49,
      type:'bus',  
      location:{latitude:37.785304, longitude: -122.417225}
}, {
     route: 72,
      type:'streetcar',
      location:{latitude:37.807685, longitude: -122.407732}
}...]
```
The models don't each have their own 'icon' or 'options' properties.  I would hope to be able to be able to pass the models directive a set of functions or a config object like this:
 
```javascript
{
labelContent: function(model) {return "Route " + model.route}
labelClass: function(model) {return model.type=='streetcar'? 'streetcar-label': 'bus-label'}
icon: function(model) {return model.type=='streetcar'? 'img/streetcarIcon.png': 'img/busIcon.png'}
}
```
This would allow me to keep my models structured the way the rest of the app uses them without adding additional  properties or copying the models into a separate collection just for the map markers.  This would be especially valuable for real-time apps  where the model data is being synchronized and constantly updated using a service such as Firebase

Is there something I'm missing?  Is there any way to do something like this using the existing directives?  If not, could something like this be added?  I think it would improve the API.

Thanks.

**Comment by nmccready** [comment]
You can add a function like getOptions .

```html
<ui-gmap-markers options="getOptions" ></ui-gmap-markers>
```

```js
\\some controller
$scope.getOptions =  function(model){
//create your options object based of your model's state
return derrivedOptions;
}
```

**Comment by nmccready** [comment]
Also if need be you can modify the gMarker independent of the model's state by using `control.getPlurals` .

https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/plural.coffee#L17

**Comment by jaufgang** [comment]
Ok that's fantastic.  Your first solution worked right away and was exactly what I was looking for.

Perhaps your documentation could be more clear on this.  All of the examples I have seen just give a property name and I haven't seen anything that lets you know that you can pass in a function, that the function will be passed the model as an argument, and that the return value of that function will be used as the options object.   Does the same option exist for other parts of the API?    Marker cluster options?  Window options?  The documentation should be clear on any parameters that can accept either a property name or function, and what arguments are passed to the function.

Thanks for your help.


Thank you very much. O

**Comment by nmccready** [comment]
Yeah that feature is new as of 2.1 I think. If someone could add the doc I'll accept it.

**Comment by dnasir** [comment]
@nmccready I have a related question. Using your first solution, is it possible to change the marker when a model property changes? i.e. I have a model with a list of items, and I would like the marker icon to change when my item property changes.

**Comment by nmccready** [comment]
@dnasir I am pretty sure the icon issue was reported and possibly fixed. It might only be on master though as I have not put a release out in forever. I probably should just cut the scope of this milestone and cut a release. I'll try and find the ticket. If I don't and you do find it; please post it here.

**Comment by nmccready** [comment]
This might be what I am thinking about; https://github.com/angular-ui/angular-google-maps/pull/1358 but it is a RichMarker. Anyway if you want the maker icon to change to be unique to the function in your directive instance do this.

`<ui-gmap-markers options="getMarkerOptions"></ui-gmap-markers>`

```coffee
#controller setup prior
$scope.getMarkerOptions = (model) ->
  $log.debug(arguments)# to see other args avail
 #handle model dynamically and set the icon based on its props
 model.icon = blah blah...
```

**Comment by nmccready** [comment]
@jaufgang please feel free to add to the docs and make it as clear as you want. I can't keep up with this anymore as I have too much going on. Other people need to support this directive or it will die.
