### ISSUE TITLE
Google Map instance leaks when directive used on different ui-router states

### ISSUE THREAD

**Issue by chris-armstrong** [angular-ui/angular-google-maps#1538]
## Problem

We have a angular SPA that uses ui-router to navigate between different screens in the application. Two of our screens use a ui-gmap-google-map directive. We've noticed that the amount of memory that the application consumes continues to increase if we switch between these two views. We embed our application in a native wrapper using PhoneGap, and it can crash with the increasing memory usage.

## Investigation 
Digging a bit further using Chrome DevTools, it seems that several event listeners remain attached to the DOM when switching states.

The next logical step would be to investigate why the Google Maps instances are not being "destroyed" between ui-view state changes. The [consensus](http://stackoverflow.com/questions/10485582/what-is-the-proper-way-to-destroy-a-map-instance) seems to be that Google Maps instances (i.e. google.maps.Map) cannot be cleaned up, and that the implicit approach for SPAs is to reuse the Google Map instances.

## Solutions

I've put together a quick hack that reuses the google.maps.Map instance from the directive (see [this branch](https://github.com/chris-armstrong/angular-google-maps/tree/2.2.1-map_reuse_hack) ), but it will only work for one Google Map instance on the screen at a time.

Does anyone have this issue in their state-based/view-based angular application? This solution could be extended out to maintain a pool of google map instances that are recycled when the scope of the directive is destroyed, reducing the amount of memory leakage from constantly creating Map instances.

**Comment by nmccready** [comment]
Your resolution looks good to me. I would PR it. Also this would resolve having more than one google maps script in the dom.

**Comment by chris-armstrong** [comment]
Sounds good. I'll add a configuration option then to trigger my "one map shared" solution, and get a long term "recycling pool" for those with more maps.

**Comment by nmccready** [comment]
Also another possible problem to this is the loader. https://github.com/chris-armstrong/angular-google-maps/blob/master/src/coffee/providers/map-loader.coffee

IE we need to make sure google maps the api is loaded once. This might be part of your problem.

**Comment by chris-armstrong** [comment]
I'm not seeing the <script> tags being inserted multiple times, and I think the factory you point to protects itself from loading the Google Maps API multiple times with this code:

```        # Early-resolve if google-maps-api is already in global-scope
        if isGoogleMapsLoaded()
          deferred.resolve window.google.maps
          return deferred.promise
```

I've created a pull request [https://github.com/angular-ui/angular-google-maps/pull/1539] with the pooling code (and an attribute to turn it on on the directive).

**Comment by nmccready** [comment]
Awesome thanks for double checking

**Comment by chris-armstrong** [comment]
Thanks for the merge
