### ISSUE TITLE
Errors when using CartoDBLayer (cartodb.js)

### ISSUE THREAD

**Issue by eczajk1** [angular-ui/angular-google-maps#1542]
I've been trying to add cartodb layers with queries that are generated at run-time to my map.  But when I try to leverage the MapType directive, I get infinite digest errors.  Has anyone experienced this?

http://jsfiddle.net/eczajk1/8edzohv8/ (see console for errors)

I have only been able to get it to work by leveraging overlayMapTypes directly: http://jsfiddle.net/eczajk1/9manxepe/

**Comment by nmccready** [comment]
I have never tried doing this with google maps sdk and this is one of the primary reasons why I mainly use leaflet now. But since you have a native example this has me intrigued.

**Comment by nmccready** [comment]
Nice example; this is probably something that is not too hard to fix.

**Comment by eczajk1** [comment]
That's good to hear.  I'm somewhat new to this repo as well as the cartodb stuff for google maps, so i'm not sure how much help I can be.

Glad you're on the case :+1:

**Comment by nmccready** [comment]
You also get props as I am from MD originally :)

**Comment by nmccready** [comment]
BTW I see you have put the google sdk script into the dom. You can async load the cartodb script after the isReady then you won't need either in the dom.

**Comment by eczajk1** [comment]
Not sure I understand how to async load cartodb.  Got an example?

**Comment by nmccready** [comment]
This is what I mean, http://jsfiddle.net/kyy1vLv0/1/

**Comment by nmccready** [comment]
```js
.service('cartodbLoader', function($q, $timeout){
    var d = $q.defer();
    var script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = '//cdn.rawgit.com/CartoDB/cartodb.js-bower/master/cartodb.js';

    function checkIfCartoDbIsReady() {
      $timeout(function(){
        if(window.cartodb)
          return d.resolve(window.cartodb);
        checkIfCartoDbIsReady();
      }, 500);
    }

    this.load = function(){
      document.body.appendChild(script);
      checkIfCartoDbIsReady();
    };

    this.promise = d.promise;
    return this;

  })
```
was added

**Comment by nmccready** [comment]
Seemed like this had to happen after the google api was loaded.

**Comment by eczajk1** [comment]
Nice - will definitely incorporate that as a best practice.  So is that related to this issue?

**Comment by nmccready** [comment]
No, just noticed your code.

**Comment by nmccready** [comment]
So I am stumped so far as nothing is throwing in the directive. It is in angular some where. 
Error does not occur until after https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/parent/map-type-parent-model.coffee#L63.

**Comment by nmccready** [comment]
Ok disabling the deep watches seems to resolve it. So let me see if I can still do watchColleciton.

**Comment by nmccready** [comment]
fixed here https://github.com/angular-ui/angular-google-maps/pull/1544

**Comment by eczajk1** [comment]
![thumbs-up](https://cloud.githubusercontent.com/assets/2584923/10230782/003b83d6-684d-11e5-9c0b-692fb5dea8b7.gif)

You are the man.  Thanks for all your work on this and the leaflet-directive

**Comment by nmccready** [comment]
:+1: np

**Comment by eczajk1** [comment]
@nmccready New issue, but related to the one opened here ...

I am now adding multiple cartodb layers, but when I do I get this flickering.  The problem seems to go away when I add the layers directly to map.overlayMapTypes.

Should I open a new issue for this?

![flickering](https://cloud.githubusercontent.com/assets/2584923/10312920/2b3cedd2-6c1b-11e5-9e3d-564acbf61285.gif)

**Comment by nmccready** [comment]
I am swamped right now; please dig in. This is likley an angular digest / watch issue. IE clearing existing items and the redrawing them all.
