### ISSUE TITLE
Set pixelOffset option on InfoWindow

### ISSUE THREAD

**Issue by arachnotron** [angular-ui/angular-google-maps#1551]
Hello!

This is a question I'm having, because it's something I just can't figure out. I would like to pass options including pixelOffset to InfoWindow.

I see that I can give an options object to the ui-gmap-window directive, but unless it's inside of a gmap event I can't access the google.maps api -- so I can't instantiate a Size to give the pixelOffset property for the options object that I want to pass in.

Would it be possible to just set up an object with width and height, to give to pixelOffset? Certain aspects of the documentation are confusing, and linking to the Maps API reference isn't entirely helpful (at least in my case), since, like I said, I'm unable to access the API wrapper when I want to set this up.

**Comment by nmccready** [comment]
Why can you not access google.maps.Size? Just try to access it when the API is loaded. You need to use the isReady or GoogleMapsAPi service.
