### ISSUE TITLE
Get the center of a Polyline by clicking on it

### ISSUE THREAD

**Issue by asso1985** [angular-ui/angular-google-maps#1561]
Having said i have : 

        linksEvents : {
          
            click : function(a, b ,model, d) {

                var bounds = new google.maps.LatLngBounds();
                    a.getPath().forEach(function(e){
                        bounds.extend(e);
                    })         
                    
                var center = bounds.getCenter();        
                

                var position = {
                  latitude : center.J,
                  longitude : center.M
                }
             }
        }

This used to work, now it doesn't.

**Comment by eczajk1** [comment]
I don't think you can depend on the "J" and "M" properties representing latitude and longitude (respectively).  Google sometimes uses different properties (different letters) for some reason.

**Comment by nmccready** [comment]
The reason is probably minification; so hell no don't rely on it.

**Comment by eczajk1** [comment]
not sure if there is a better way ... this has worked for me so far:

```
var position = {
    latitude: boundsTopRight.G || boundsTopRight.H || boundsTopRight.J,
    longitude: boundsTopRight.K || boundsTopRight.L || boundsTopRight.M
};
```

**Comment by asso1985** [comment]
That's my problem : 

If I an rely on google obj, how can I get the center ?

The model from angular google map gives me the path object :

      path: Array[2]
      0: Object
           latitude: 45.483716
           longitude: 9.181642
      1: Object
           latitude: 45.487083
           longitude: 9.204435

Ho can I find the center of the polyline from this ?

**Comment by eczajk1** [comment]
This isn't an angular-maps issue, and I doubt Google Maps itself can help you with this.  Try [Turf](http://turfjs.org/)

**Comment by asso1985** [comment]
Anyway I'm having the same problem after dragging a marker, I have to rely on the google data since the angular marker model don't always update position after dragging

**Comment by nmccready** [comment]
So I know I have done something like this recently with this branch I am working on (can't find the exact code yet). Anyway the gist of it is you need to iterate all the paths into [LatLngBounds](https://developers.google.com/maps/documentation/javascript/3.exp/reference#LatLngBounds) object. This has getCenter built in. You can do this by basically coping [fit-helper](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/utils/fit-helper.coffee#L5-L11) itself. But instead of calling fit call getCenter. 

This all has spawned from a PR I have not finished which is for making fit work with marker, polyline, and circle.

**Comment by asso1985** [comment]
I sorted out like this : 

        var toRadians = function(a) {
          return (a * Math.PI) / 180;
        }

        var toDegrees = function(a) {
          return (a * 180) / Math.PI;
        }        
      


      var getCenterPointOFLine = function(lat1, lon1, lat2, lon2) {
        var dLon = toRadians(lon2 - lon1);

        //convert to radians
        lat1 = toRadians(lat1);
        lat2 = toRadians(lat2);
        lon1 = toRadians(lon1);

        var Bx = Math.cos(lat2) * Math.cos(dLon);
        var By = Math.cos(lat2) * Math.sin(dLon);
        var lat3 = Math.atan2(Math.sin(lat1) + Math.sin(lat2), Math.sqrt((Math.cos(lat1) + Bx) * (Math.cos(lat1) + Bx) + By * By));
        var lon3 = lon1 + Math.atan2(By, Math.cos(lat1) + Bx);

        return {
          lat : toDegrees(lat3),
          long : toDegrees(lon3)
        }
      }

Thanks everyone, sorry for bothering

**Comment by nmccready** [comment]
It use google LatLngBounds less code to need and less testing to worry about.

**Comment by asso1985** [comment]
Thanks @nmccready  i'll try that!

**Comment by nmccready** [comment]
Closing as I think everyone seems to be satisfied.

**Comment by asso1985** [comment]
Great
Il 14/ott/2015 06:47 PM, "nmccready" <notifications@github.com> ha scritto:
