### ISSUE TITLE
Quickstart page points to wrong angular-simple-logger file

### ISSUE THREAD

**Issue by mattdawson** [angular-ui/angular-google-maps#1563]
At step 1 under "If not using Bower, you'll also need to fetch:"

angular-simple-logger/dist/index.js should be angular-simple-logger/dist/angular-simple-logger.js

index.js is the nodejs version, not browser.

Also needs adjusting in step 2 script import.

**Comment by nmccready** [comment]
Yes correct; please submit a PR to the website branch and it should auto deploy the update.

**Comment by nmccready** [comment]
I am working on it now

**Comment by nmccready** [comment]
Fixed https://github.com/angular-ui/angular-google-maps/commit/383e671a09ee30174aebdc139e394eba464c710c
