### ISSUE TITLE
Explicit dependency annotations in API documentation

### ISSUE THREAD

**Issue by BeLi4L** [angular-ui/angular-google-maps#1568]
On the page http://angular-ui.github.io/angular-google-maps/#!/api/GoogleMapApi, in the 2 code samples, the dependencies are not explicit and give errors when minifying code. The solution is to use **explicit dependency annotations** to prevent that.

**Comment by cthrax** [comment]
That's only an issue if you're not using something like ng-min. The code examples are much easier to read without array notation. It's up to the developer to add explicit annotations if they need it.
