### ISSUE TITLE
remove markers (ui-gmap-markers) or polygons (ui-gmap-polygons) from maps 

### ISSUE THREAD

**Issue by gameover-fwk** [angular-ui/angular-google-maps#1569]
Hello

In one of my use case i have to switch to different sources of data for markers and polygons,
when using the display button which select the source, i try to clean the map and put the new markers and polygons from this source. 
I dont know why but some markers (always the same) and some polygons (always the same) are not cleaned.

In the HTML:
```
        <ui-gmap-google-map center='map.center' zoom='map.zoom' options='map.options' events="map.events" control="map.control">
            <ui-gmap-markers models="map.markers" coords="'location'" icon="'icon'" idkey="'id'" events="markersEvents" options="'options'"></ui-gmap-markers>
            <ui-gmap-polygons models="map.polygons" path="'path'" stroke="'stroke'" fill="'fill'" idkey="'id'" clickable="true" events="markersEventsOnPolygon" draggable="false" visible="true"></ui-gmap-polygons>
        </ui-gmap-google-map>
```

to clean things on the controller: i just set the array variable to []
```
function clearMap($scope) {
    $scope.map.markers = [];
    $scope.map.polygons = [];
}
```

If i use single directives ui-gmap-marker and ui-gmap-polygon, eveything is cleaned correctly but for performances reason i need to use ui-gmap-markers ui-gmap-polygons

**Comment by gameover-fwk** [comment]
Just found the issue: clear the array and refill it immediately make some features kept on google map.

**Comment by nmccready** [comment]
ty for closing and replying with resolution
