### ISSUE TITLE
Responsive Maps

### ISSUE THREAD

**Issue by suryaiiit** [angular-ui/angular-google-maps#1571]
Any idea/suggestions on how to make the map responsive.
Please note, I'm using this in Meteor-Angular (http://angular-meteor.com/tutorials/angular1/google-maps).

Thank you.

**Comment by nmccready** [comment]
Your question is extremely vague and broad, care to be a little more explicit?

**Comment by cristianhoyos66** [comment]
I think that he refers to this:

    .angular-google-map-container {
       height: 400px;
       width: 400px;
    }

it's height and width with pixels (px). I've tried with percentages (%) and the map does not recognize and i'ts not shown. Only with pixels and it's not responsive.

I've not tried this, but it could work using css' calc function.

Here some examples: 

http://www.sitepoint.com/css3-calc-function/

pd: I'm sorry with my english, but I'm learning xD

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/stylesheets/dynamic-height.css#L11-L15

https://github.com/angular-ui/angular-google-maps/blob/master/example/dynamic-map-height.html

**Comment by suryaiiit** [comment]
Yes, thats what I'm looking for. Thank you.
