### ISSUE TITLE
[Develop] Overlapping Markers Issue

### ISSUE THREAD

**Issue by niftylettuce** [angular-ui/angular-google-maps#158]
Can you guys add this in?

https://github.com/jawj/OverlappingMarkerSpiderfier

**Comment by charanm** [comment]
Is this feature available now?

**Comment by gino8080** [comment]
yes please it this feature avaialable how?

**Comment by codeback** [comment]
@nmccready, how can we check if this feature is available? is there a parameter/attribute to enable it?

Thanks a lot!

**Comment by nmccready** [comment]
Marker Spiderfire is not in there. However someone just PR'ed rich marker. The changes to add Spiderfire are virtually the same.
