### ISSUE TITLE
Map cannot load completely

### ISSUE THREAD

**Issue by Nekle** [angular-ui/angular-google-maps#1582]
When I use it like below, google map cannot load completely.
```
<ui-gmap-google-map zoom='Map.zoom' center="Map.center"></ui-gmap-google-map>
```

![snip20151026_1](https://cloud.githubusercontent.com/assets/1272353/10731172/0f95cb70-7c2f-11e5-9fe5-973ffcc1e678.png)

When I resize browser, it can load completely.

**Comment by nmccready** [comment]
This has been discussed over and over many times in closed issues and in http://angular-ui.github.io/angular-google-maps/#!/faq "partially rendering" . Please search.
