### ISSUE TITLE
Question: Is it possible to use window and rectangle directives together?

### ISSUE THREAD

**Issue by SamuelToh** [angular-ui/angular-google-maps#1592]
Hi, I'm just trying to associate a rectangle with a window directive to draw popups like what most demo do for markers.

I'm wondering whether is it possible for rectangles to have popup like markers? I have tried nesting the window directive within a rectangle but didn't have much luck with it.

Any idea whether is it possible for now, if yes any demo or examples that I can follow?

Thanks!
Sam

**Comment by nmccready** [comment]
You can use them together but you need to make the magic happen. There is no nesting support for windows under rectangle.

**Comment by SamuelToh** [comment]
Hey thanks for the reply.

Any hints on what the magic could be? Just throw in some key words here and I will do the remaining research myself.

Any other pointers will be greatly appreciated!!

**Comment by nmccready** [comment]
Look up some examples on how to use ui-gmap-window with ui-gmap-markers , it is basically the same. It should be in many closed issues as well.

**Comment by SamuelToh** [comment]
@nmccready 
Hey thanks a lot for your hint. I have got it working using an example found in the FAQ section where it had the window directive declared outside of a marker, and the marker was wired to an onClick event to control the window directive's coordinates and visibility.

It works like a charm.

**Comment by nmccready** [comment]
cool thanks for figuring it out
