### ISSUE TITLE
Simple DragEnd Event end with TypeError: a[Ec] is not a function

### ISSUE THREAD

**Issue by marceloch2** [angular-ui/angular-google-maps#1598]
Related to Makers Directive, but happening with another directives also, to keep simple and maybe close this poor issue (sorry, just saw how poor it was described now), do you know or can explain for me this error message?

"error within chunking iterator: TypeError: a[Ec] is not a function"

Version: angular-google-maps 2.2.1 2015-10-23
Version: angularjs/1.4.7

Now it's happening when click in Windows Directive, i'm doing something very wrong, i was suspecting about the ID, but checked here and i'm populating with unique ID for sure.

My Directives code bellow,

https://gist.github.com/marceloch2/c36cebe23b74dead065c

Thanks in advance buddy.

All events work except dragend.

dragend: function(marker) {
    console.log(marker);
},

**Comment by nmccready** [comment]
Be nice if your error above was more explicit that this is a marker, or markers problem. Which version and what directive?

**Comment by nmccready** [comment]
Please make a solid example and not the snippet above.

**Comment by marceloch2** [comment]
Sure, sorry, it's related to Makers Directive, but seeing this is happening with frequency and with another directives also, to keep simple and maybe close this poor issue (sorry, just saw how poor it was described now), do you know or can explain for me this error message? 

 - "TypeError: a[Ec] is not a function"

Version: angular-google-maps 2.2.1 2015-10-23

Now it's happening when click in Windows Directive, i'm doing something very wrong, i was suspecting about the ID, but checked here and i'm populating with unique ID for sure.

My Directives code bellow, 

<ui-gmap-google-map center="map.center" zoom="map.zoom" draggable="true" options="options" bounds="map.bounds">
                <ui-gmap-markers models="coordsWeldsWithConnection" coords="'self'" icon="'icon'" options="'options'" idKey="'id'" doRebuildAll="true" events="'events'">
                    <ui-gmap-windows show="true">
                        <div ng-non-bindable>LOREM</div>
                    </ui-gmap-windows>
                </ui-gmap-markers>
                <ui-gmap-markers models="coordsWeldsWithOutConnection" coords="'self'" icon="'icon'" options="'options'" idKey="'id'" doRebuildAll="true" events="'events'"></ui-gmap-markers>
                <ui-gmap-markers models="lagers" coords="'self'" icon="'icon'" options="'options'" idKey="'id'"></ui-gmap-markers>
                <ui-gmap-markers models="externalLagers" coords="'self'" icon="'icon'" options="'options'" idKey="'id'"></ui-gmap-markers>

                <ui-gmap-polyline ng-repeat="p in polylines" path="p.path" stroke="p.stroke" visible='p.visible' editable="p.editable" draggable="p.draggable"></ui-gmap-polyline>
            </ui-gmap-google-map>


Thanks in advance buddy.

**Comment by marceloch2** [comment]
Using angular-google-maps 2..0.x the error disappear.
