### ISSUE TITLE
center position is displayed at top left corner in ionic modals

### ISSUE THREAD

**Issue by AndreasMaier** [angular-ui/angular-google-maps#1599]
Hey, I ran into an issue where angular-google-maps would not display maps correctly in ionic modals.

I created a [little sample repo](https://github.com/AndreasMaier/ng-gmaps-top-left-center) to describe and reproduce this issue. It basically has a tab with a google map that on load displays the map centered correctly. It also provides a possibility to show a modal overlaid on the same page which has the same map, but moves the same center/location to the top left. 

The app basically just consists of one tab whose controller is serving the static centerlocation to both the map on the tab view and the modal. Does anybody have an idea what could create this behavior?

### controller 
```javascript
angular.module('starter').controller('ModalTabCtrl', function ($ionicModal, $scope) {
    ...
    $scope.map = {
        center: {
            latitude: 37.778414,
            longitude: -122.389212
        },
        zoom: 8
    };
});
```

### tab
```html
<ion-view view-title="Tab">
    <ion-content class="padding">
        <ui-gmap-google-map center='map.center' zoom='map.zoom'>
        </ui-gmap-google-map>
    </ion-content>
    ...
</ion-view>
```

### modal
```html
<ion-modal-view>
    ...
    <ion-content>
        <ui-gmap-google-map center='map.center' zoom='map.zoom'>
        </ui-gmap-google-map>
    </ion-content>
</ion-modal-view>
```

Here are two images showcasing the shift of the center:

<img width="239" alt="map centered correct" src="https://cloud.githubusercontent.com/assets/3517534/10902439/c47aee20-81b2-11e5-8ccb-17567d929e10.png">
<img width="243" alt="map center on top left" src="https://cloud.githubusercontent.com/assets/3517534/10902440/c7db79b8-81b2-11e5-82be-1ebb3d993568.png">

**Comment by nmccready** [comment]
See #1395 , probably same issue.

**Comment by AndreasMaier** [comment]
Ok got it. I updated the code to use a control and refresh it when the modal gets shown. This works so far for me and was totally already in the api doc. 

```javascript
    $scope.openModal = function () {
        $scope.modal.show();
        $scope.modalControl.refresh({
            latitude: 37.778414,
            longitude: -122.389212
        });
    };
```
