### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hale** [angular-ui/angular-google-maps#16]
I get this with the following default values:

``` javascript
    angular.extend($scope, {
      center: {
        lat: 45,
        lng: -73
      },
      zoom: 4,
      markers: []
    });
```

``` javascript
    <google-map center="center" draggable="true" zoom="zoom" markers="markers" mark-click="true" style="height: 400px"></google-map>
```

**Comment by cto-oneva** [comment]
having the same problem on Ubuntu 14.04/chrome, with just this code:
`
<!DOCTYPE html>
<html lang="en">
  <head>
  <body >
    <script src="vendor/angular/angular.js"></script>
  </body>
</html>
`

**Comment by cthrax** [comment]
@cto-oneva if that's really all you have then the problem is not with agm, as agm is not included. If you would like further help, please open a new issue that includes an MCVE https://github.com/angular-ui/angular-google-maps/wiki/MCVE
