### ISSUE TITLE
No click event on ui-gmap-markers

### ISSUE THREAD

**Issue by werdnanoslen** [angular-ui/angular-google-maps#1600]
I don't understand why the markers on [my map](http://andyhub.com/demos/mobile-map-io/www/#/map) are not using the [click event](https://github.com/werdnanoslen/mobile-map-io/blob//dc375b6db0294999acad2348ffeb07a3d56e7c6d/www/js/controllers.js#L52) applied to them as [events](https://github.com/werdnanoslen/mobile-map-io/blob/dc375b6db0294999acad2348ffeb07a3d56e7c6d/www/templates/map.html#L50). I think I'm just not following the documentation properly, but I'm not sure where it's going wrong. Could someone help me out?

**Comment by nmccready** [comment]
Not sure what your talking about. Just looked at the app and the click fired fine with the alert you created. Anyway make a small example as I am not debugging full blown applications.
