### ISSUE TITLE
ng-click doesn't work inside a window (infowindow)

### ISSUE THREAD

**Issue by nelson687** [angular-ui/angular-google-maps#1601]
Hi, I have this:
```
<ui-gmap-windows show="show">
            <div class="infoWindow" ng-non-bindable>
                <a ng-click="showStats()" class="location" href="#">Test</a>
            </div>
</ui-gmap-windows>

```
but the ng-click event is not firing. Am I missing something ?

**Comment by nmccready** [comment]
#1596  just closed same problem. This is also in examples and shows it working with a template.

**Comment by nelson687** [comment]
So is using a template the only way to make it work? After a few hours I could make the template work, but still having the same problem with ng-click, it doesn't work

**Comment by nmccready** [comment]
Currently yes; but someone in another thread thinks the other way can be fixed. I do not have time to fix it. So unless someone else does template is your best bet. You need to make an example and play with the existing examples. There are quite a few in there showing a button click working with ng-click in a window.
