### ISSUE TITLE
Marker pin is not centered and address is not updated when marker pin is dragged

### ISSUE THREAD

**Issue by abutuffah** [angular-ui/angular-google-maps#1603]
Hi, I implement your plugin in my ionic project. and I've found issue that I'm stuck on. 

I can't get the marker centered in my map view. and when I dragged the pin , I want to show the address right away, but it is showed when I dragged the map again. When I just dragged the pin, the address is not refresh. Please help , your help is really appreciated

**Comment by nmccready** [comment]
An reproducible example is appreciated.

**Comment by abutuffah** [comment]
//begin map
  $scope.map = {
    center: {
      latitude: market.latitude,
      longitude: market.longitude
    },
    zoom: 13
  };
  
  $scope.marker = {
    id: 0,
    coords: {
      latitude: market.latitude,
      longitude: market.longitude
    },
    options: { draggable: true },
    events: {
      dragend: function (marker, eventName, args) {
        $scope.getDistance(marker.getPosition().lat(), marker.getPosition().lng());
      }
    }
  };
  
  $scope.$watchCollection("marker.coords", function (newVal, oldVal) {
    if (_.isEqual(newVal, oldVal)) return;
    $scope.mapAddress = $scope.mapAddress;
  });

the $scope.mapAddress cannot updated automatically.

I'm doing to write it on codepen so that we can see it :)

**Comment by abutuffah** [comment]
I solved it, it is a typical angular problem, solved by adding $scope.$apply(); thanks for your concern :)
