### ISSUE TITLE
load app, then ... if the data needs it ... load the googlemapApi at a later time, on demand. 

### ISSUE THREAD

**Issue by webnerdlw** [angular-ui/angular-google-maps#1604]
Lazy loading of angular-google-maps with: key, version, libraries configuration info being passed in. Are there any examples anywhere of this?
I need to be able to lazy load the angular-google-maps api based upon program logic when a particular template is used. I don't want to load it when the app loads, because of the usage limits/costs associated with google maps licensing ... only when I need it. Does anyone know of a way to do this? I seem to be hung up on passing in the key, version, and libraries config info at lazy load time.

nmccready Oct 01 21:45
It is right here for lazy loading http://angular-ui.github.io/angular-google-maps/#!/api/GoogleMapApi it is lazy loaded by default, you just need to set the options.

webnerdlw Oct 02 10:37
Hi Nick. I want to load my app and then ... if the data needs it ... load the googlemapApi at a later time, on demand. I may not be understanding this completely, but because this setup is part of the app config, it loads immediately whether or not I need it. I want to avoid that because I want to reduce my usage/count with GoogleMaps. How can I do that?

nmccready Oct 22 23:45
@webnerdlw thats a good question and currently the way it is the main map directive needs google maps to be loaded. Anyway I would need to think about it some; but it is a good idea. Make an issue please.

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/scripts/controllers/example.js#L7-L13

**Comment by ralphsaunders** [comment]
+1 for this feature.

As the uiGmapGoogleMapApiProvider has to be set in a config block (lest the library load a default), the Google Maps API is fetched as soon as the JavaScript on the page is executed.

This isn't ideal for high-traffic pages where maps functionality is hidden away until the user interacts with a page (e.g. changes a tab, or uses an input field) – especially for Google Maps for Work customers.

**Comment by webnerdlw** [comment]
#1630's fix resolved this issue for me also.  Closing
