### ISSUE TITLE
How to get google.maps.Map instance when map is ready?

### ISSUE THREAD

**Issue by diogodomanski** [angular-ui/angular-google-maps#1607]
I would like to know how to get the google.maps.Map instance inside the callback function for map ready.
```javascript
uiGmapGoogleMapApi.then(function(maps) {
   // here...
});
```

Thanks in advance

**Comment by nmccready** [comment]
Its not there that is in the isReady svc.

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/map.coffee#L74-L78

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/abce610a29649159363ce071829d7d1d9c8ec4d3/example/assets/scripts/controllers/issue-147-ng-show-map-refresh.js#L11-L12
