### ISSUE TITLE
attribution mapdata and terms of use links open in app with cordova application

### ISSUE THREAD

**Issue by Freundschaft** [angular-ui/angular-google-maps#1611]
Hi!

I have the angular mapdata and terms of use links in my google maps control but now I have the issue that the attribution links on the google maps control dont open in a browser but in the application itself instead.
Is there any way I can control or alter this behavior? Thanks!

**Comment by nmccready** [comment]
I am not following.

**Comment by Freundschaft** [comment]
the links in the lower right corner when showing google maps, when clicking on them in a cordova application, they are not opened in the system browser but in the app itself instead:

http://data.linkededucation.org/linkedup/devtalk/05/google-map-attribution.png

**Comment by nmccready** [comment]
I have no control over that. That is straight google.
