### ISSUE TITLE
get cluster markers

### ISSUE THREAD

**Issue by siddharthbhavsar** [angular-ui/angular-google-maps#1614]
How do i get markers from a cluster when clustering is enabled

**Comment by nmccready** [comment]
You need them on an event correct? If so it is in the documentation see typeEvents attribute in markers.

**Comment by siddharthbhavsar** [comment]
No, I need to set the cluster icon based on the marker contents. Also is there a way I can enable or disable clustering through code?
The documentation says the 'doCluster' is not bindable.

**Comment by nmccready** [comment]
I'll have to double check the code later. But I think through plural you have access to the manager which has the clusterer wrapped in that.  So look at the code for getManager or get MarkerManager.  Anyway I'm done looking at code for  the evening.

**Comment by siddharthbhavsar** [comment]
ok, thanks for the direction

**Comment by siddharthbhavsar** [comment]
How can I get access to the manager?

**Comment by nmccready** [comment]
By looking at the code https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/plural.coffee#L20-L25

**Comment by tianxu0836** [comment]
the problem for plural and control is they don't work for multiple dynamic clusters....
you can't create a plural or control for each dynamic cluster.
