### ISSUE TITLE
Adding a custom overlay

### ISSUE THREAD

**Issue by ksmolicz** [angular-ui/angular-google-maps#1621]
Is it possible to implement custom overlay similar to https://developers.google.com/maps/documentation/javascript/examples/overlay-simple ?

**Comment by SNTRwa** [comment]
I have tried to combine example from google:
```
    uiGmapIsReady.promise(1).then(function(instances) {
      instances.forEach(function(inst) {
        var map = inst.map;

        var imageBounds = {
          north: 52.229676,
          south: 52.169676,
          east: 21.012229,
          west: 21.112229
        };

        var historicalOverlay = new google.maps.GroundOverlay(
          'https://www.lib.utexas.edu/maps/historical/newark_nj_1922.jpg',
          imageBounds);
        historicalOverlay.setMap(map);
      });
    });
```
but have lot of errors and whole thing doesn't work as expected:
```
Uncaught TypeError: b[cd] is not a function
```

**Comment by nmccready** [comment]
The example you want to look at is https://github.com/angular-ui/angular-google-maps/blob/master/example/overlay-map-type.html using map-type. Anyway I know someone made a comment a while back using a cartodb layer. I think it was done with this. So far I can not find it.

**Comment by nmccready** [comment]
Yes here it is #1542 I think this is what you need.

**Comment by ksmolicz** [comment]
SNTRwa solution is working. Issue resolved.

**Comment by sasincj** [comment]
@SNTRwa : 

    "Alright, I just messed up with east and west longitude :) "

Where did u messed up, i am using the same code as yours, i am still getting that error:

    TypeError: b[cd] is not a function

**Comment by sasincj** [comment]
Worked it .. used the v3.20 of google maps.

**Comment by evanjmg** [comment]
I don't quite understand how to do a custom map with map-type with this documentation- https://github.com/angular-ui/angular-google-maps/blob/master/example/overlay-map-type.html - it just shows objects and tiles - I know how to do the constructor, but how would I load it and add a click event like so -  http://stackoverflow.com/questions/3361823/make-custom-overlay-clickable-google-maps-api-v3
