### ISSUE TITLE
Doesn't works on cordova

### ISSUE THREAD

**Issue by cperezvinsite** [angular-ui/angular-google-maps#1622]
I'm creating a cordova app, the angular google maps works great on web browser, but when i tried to run it on xcode emulator, the angular-google-map-container is empty, in other words the map never loads. But the same code works great in web browser, I already add the permission for import libraries from web, actually in can create a map with the google api indications.

**Comment by nmccready** [comment]
#1595

**Comment by nmccready** [comment]
dupe
