### ISSUE TITLE
Question: Is there a way to get all of the gMarker instances from the ui-gmap-google-map directive?

### ISSUE THREAD

**Issue by SamuelToh** [angular-ui/angular-google-maps#1626]
Hi all, 

I'm just wondering whether is it possible to get all of my Google map marker instances from the google map directive?

According to the API documentation it is possible to get marker instances through using the control attribute's getGMarkers() API for both marker and markers directives. Trouble here is that I am rendering my markers using the Marker directive through the ng-repeat loop, and I suspect that when the marker directive was repeated by ng-repeat, the control attribute is continously getting overridenhence when I call $scope.markerControl.getGMarkers(), it is returning only 1 object. : ( 

I'm thinking this behaviour is correct as the API cleanly stats that 
"getGMarkers() - Array of all the google.markers associated with this directive" So for my ng-repeat + marker case, it will probably not  work for me, unless I am doing something wrong :P

Therefore I'm trying to see if there is an easy way for me to get all markers on the map, so that I can do marker clustering easily?

**Comment by nmccready** [comment]
So yes this is a bug which I was in progress in fixing. It comes with a new concept of groups though. But I advise using `ui-gmap-markers` .

Anyway if u want to see what I am talking about see marker.coffee in this temp PR.

https://github.com/angular-ui/angular-google-maps/compare/master...nmccready:dev/nmccready/issue_1458_polyline_fit#diff-95f10309e3c87d8fc935aa7b0f1b8504R24

**Comment by nmccready** [comment]
I think I do need to add the grouping to getGMarkers though. But honestly the singular directives need to die. But I am not working on another major release so.. I guess they shall live.

**Comment by SamuelToh** [comment]
@nmccready 
Thanks for the swift reply. Given that the singular marker might die 1 day, I guess it would be better for me to update my code to use Markers as a long term solution. 

Also for scenario where each marker has an info-window attached, am I correct to say that the Markers directive is more efficient than the singular Marker? Since the code is expected to generate an ui-gmap-window for each singular marker whereas for Markers, there is only 1 window generated because it is shared?

**Comment by nmccready** [comment]
This is also a question asked many times.

> Also for scenario where each marker has an info-window attached, am I correct to say that the Markers directive is more efficient than the singular Marker? Since the code is expected to generate an ui-gmap-window for each singular marker whereas for Markers, there is only 1 window generated because it is shared?

This is up to you. If you nest it you will have a window for each marker in `ui-gmap-markers`, if you don't then you will have one window which you can manage with the controller. Which is what I recommend.

**Comment by SamuelToh** [comment]
@nmccready  Thanks for the clarification!  

Since this is a known issue and the fix is in in progress, do you mind if I close this?
