### ISSUE TITLE
Search Box examples - click on marker broken

### ISSUE THREAD

**Issue by vip9** [angular-ui/angular-google-maps#1629]
When clicking on marker at http://localhost:3100/example/search-box.html example, the "Uncaught TypeError: click is not a function" error shows.

Also, clicking at other search-box examples results same error. I'm on master.

**Comment by wbreza** [comment]
+1 - I'm also having an issue with click events not firing on markers

**Comment by kandizzy** [comment]
I'll look at this today

**Comment by DzmitryU** [comment]
Would you provide plnkr link?

**Comment by kandizzy** [comment]
Finally fixed these examples in this PR #1742

**Comment by kandizzy** [comment]
fixed on master
