### ISSUE TITLE
Problem loading the map

### ISSUE THREAD

**Issue by alechirsch** [angular-ui/angular-google-maps#1632]
We have been working on an app that uses angular google maps and suddenly, in the past two days, the map no longer loads. We have reverted to code the we are 100% worked in the past and get the same error.

The two errors below are copied from the Google Chrome console.
```
GET http://maps.googleapis.com/maps/api/js/ViewportInfoService.GetViewportInfo?…sen-US&5e0&6sm%40329000000&7b0&8e0&9b0&callback=_xdc_._dy27xm&token=12475

GET http://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1shttp%3A%2F%2Flocalhost%3A8000%2F&callback=_xdc_._synw83&token=71850 
```
Any ideas?

**Comment by nmccready** [comment]
No can u get a reproducible example? Google produced this. http://stackoverflow.com/questions/30980482/google-maps-api-fails-to-load-map-tiles

http://bfy.tw/2tz9
