### ISSUE TITLE
Working with ES6 and Webpack

### ISSUE THREAD

**Issue by Tallyb** [angular-ui/angular-google-maps#1633]
I am trying to use angular google maps with a webpack project. when trying to load google maps angular fails to load 

     Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
     Error: [$injector:modulerr] Failed to instantiate module {} due to:
     Error: [ng:areq] Argument 'module' is not a function, got Object

I have installed via npm `angular-google-maps`

My app.js (main file) contains the following code: 

    import angular from 'angular';
    import uiGmapgoogleMaps from 'angular-google-maps';
    import home from './features/home/index';
    import mapping from  './app.maps.config.js';
    angular.module('app', [home,  uiGmapgoogleMaps])
      .config (mapping)  ;

and my config mapping file contains: 

    export default function mapping(uiGmapGoogleMapApiProvider) {
           uiGmapGoogleMapApiProvider.configure({
               //    key: 'your api key',
               v: '3.20', //defaults to latest 3.X anyhow
               libraries: 'weather,geometry,visualization,drawing'
           });
     };

Any suggestions?

**Comment by nmccready** [comment]
Do you get the same error when this project is not imported?

**Comment by nmccready** [comment]
Probably would be easiest if you a make a template with this error occuring on a repo I can fork and play with.

**Comment by dmackerman** [comment]
Running into the same issue. Basically `import uiGmapgoogleMaps from 'angular-google-maps';` exports an empty object. Still digging into it.

**Comment by konpa** [comment]
Same here

**Comment by nmccready** [comment]
`uiGmapgoogleMaps` is never exported as a module. It is only a angular module.

**Comment by dmackerman** [comment]
So, to get this to work we'll have to fork it and create some sort of shim?

**Comment by nmccready** [comment]
I've had this working with webpack in the past and I am using ui-leaflet (same dependencies) with browserify with no issues. Anyway I will try to come up with an example.

**Comment by manuelfc1** [comment]
I have the same issue using JSPM.

**Comment by samlawrencejones** [comment]
Thanks, @dmackerman! That worked for me!

**Comment by TWKDreamState** [comment]
Thank you @dmackerman! It's works following your guide. However, I'm now getting a WARNING: Tried to load angular more than once. Is there a way to remedy this? I don't get this error if I add angular-google-maps via atmosphere.

**Comment by jsantana90** [comment]
@dmackerman guide work, but I get a warning from google in the console `Google Maps API warning: NoApiKeys` what does this means?

**Comment by donedgardo** [comment]
@jsantana90 
Try this:
```
.config(function(uiGmapGoogleMapApiProvider) {
    uiGmapGoogleMapApiProvider.configure({
        //    key: 'your api key'
    });
})
```
You can get a key [here](https://developers.google.com/maps/documentation/javascript/get-api-key)

**Comment by davidpelayo** [comment]
I'm closing this issue for now.

If the issue persists, please proceed informing according to the [ISSUE_TEMPLATE](https://github.com/angular-ui/angular-google-maps/blob/master/ISSUE_TEMPLATE.md) providing examples we can fork and play with.

Thanks.

**Comment by mbrooks** [comment]
I had to make sure I injected the function to get this working. Lost many hours on this!

```
export default function mapping(uiGmapGoogleMapApiProvider) {
       uiGmapGoogleMapApiProvider.configure({
           //    key: 'your api key',
           v: '3.20', //defaults to latest 3.X anyhow
           libraries: 'weather,geometry,visualization,drawing'
       });
 };

mapping.$inject = ['uiGmapGoogleMapApiProvider'];
```

**Comment by stephengardner** [comment]
Thanks @dmackerman, your solution works.

The angular google maps module requires you to also import the angular-simple-logger.

Also, if using webpack and you'd like `_` to be registered globally for `angular-google-maps`, use the `ProviderPlugin` plugin, like so:
```javascript
	config.plugins = [
		new webpack.ProvidePlugin({
			"_" : "lodash"
		}),
```

**Comment by charlieanstey** [comment]
Thanks @dmackerman, your solution to include `angular-simple-logger` separately worked a treat.
