### ISSUE TITLE
Ground Overlay Support

### ISSUE THREAD

**Issue by sasincj** [angular-ui/angular-google-maps#1636]
Hi, i have been searching the ground -overlay support, for putting an image on the map, which will respond like a map when u zoom out and zoom in.

I was not able to find ground - overlay related directive or anything in the documentation. Do you guys support ground-overlay functionality, if not, do we have any other way around to get this done ??

**Comment by nmccready** [comment]
Look into map-type

**Comment by nmccready** [comment]
#1542

**Comment by sasincj** [comment]
Ahh .. let me try this .. Thanks man ! ..

**Comment by sasincj** [comment]
Not sure how we can use this, i want something like: 
https://developers.google.com/maps/documentation/javascript/examples/groundoverlay-simple
How do i use map-type, the example in Api-Documentation doesn't work. I am doing like this:
HTML:

    <ui-gmap-map....
        <ui-gmap-map-type options='imageMapType'>
        </ui-gmap-map-type>
    </ui-gmap-map>
        

Javascript:
???? 
I am trying to do something like this, but this is not working, the example in API-documentation doesn't work. Can you create a sample example for me to followup or tell me how to use map-type by giving some example:

    $scope.imageMapType = new google.maps.ImageMapType({
    
    });

What i really want to do is something like (simply) : 
    
    var imageBounds = { north: 40.773941,south: 40.712216, east: -74.12544,west: -74.22655 };
    $scope.historicalOverlay = new google.maps.GroundOverlay( 'https://www.lib.utexas.edu/maps/historical /newark_nj_1922.jpg',imageBounds);
    uiGmapIsReady.promise().then(function (maps) {
    			
                $scope.currentMap = maps[0].map;
                
                $scope.historicalOverlay.setMap($scope.currentMap); 
            });

When i do this, I get this error:

    TypeError: b[ub] is not a function
    TypeError: b[cd] is not a function

**Comment by sasincj** [comment]
Hi, i got this map-type working.
My scenario is, i have a 
But i stils need something to be working like Ground-Overlay inside uiGmapIsReady.promise(). Its give me the same error as above.

**Comment by neerajkumarnj** [comment]
Make sure you are using the latest version of google maps. I had a similar problem with ground overlays. That fixed it for me.

**Comment by tianxu0836** [comment]
@nmccready I don't understand why this issue was closed, what if I don't want to use tiles, I just want to display a simple entire image
