### ISSUE TITLE
tilesloaded event returns undefined

### ISSUE THREAD

**Issue by MHDMAM** [angular-ui/angular-google-maps#1641]
Console log:
```
loaded undefined undefined undefined
```
Code:
```
    $scope.map = {
      center: {
        latitude: 3,
        longitude: 101
      },
      zoom: 5,
      events: {
        tilesloaded: function(map, eventName, originalEventArgs) {
          console.log('loaded', map, eventName, originalEventArgs);
          try {
            $scope.$digest(function() {
              google.maps.event.trigger(map, "resize");
            });
          } catch (_ee) {}
        },
      }
    };
```
Jade:
```
ui-gmap-google-map(center='map.center', zoom='map.zoom', events='map.events', ng-if='randomMarkers')
     ui-gmap-markers(models="randomMarkers", coords="'self'")
```
As you can see `tilesloaded` always return `undefined` did I missed something?

**Comment by nmccready** [comment]
Make a plnkr where I can see it always happening.

**Comment by MHDMAM** [comment]
Weird, plnkr works fine, it's just my local/server!
http://plnkr.co/Igo0t5rYwuli9UkRmd76

**Comment by nmccready** [comment]
Maybe bad API key?

**Comment by MHDMAM** [comment]
Ohh here's the problem!
when I put the Map inside a [accordion] (http://angular-ui.github.io/bootstrap/#/accordion) it doesn't  works. I just removed the `accordion` directive and everything works fine!

Any idea how to work around it

**Comment by nmccready** [comment]
Track when accordion is open and use ng-if to show the map.

**Comment by MHDMAM** [comment]
I'm already using ng-if. but i guess accordion use internally ngHide/ngShow -- yeah it's works when map section is open.
I think the only way is to load markers when user opens map section. is there another work around?

Thanks
