### ISSUE TITLE
Getting marker objects via 'idKey'

### ISSUE THREAD

**Issue by neerajkumarnj** [angular-ui/angular-google-maps#1644]
I wanted to fetch marker object using idKey. Saw this issue, #1626

Can't we have a markerControl[i] passed to control attribute, in ng-repeat, where i will be the '$index' and then i will have object array of markers, and i can do $scope.markerControl[i].getGMarkers()
I have not tried it. Will that work, theoretically?

**Comment by nmccready** [comment]
Not sure what your getting at; but if you want to get something by the key that it iterated over then use this.

```
<ui-gmap-markers control="markerControl" ....>
```
```
$scope.,markerControl.getPlurals()[THE_ID]
```

If your using `<ui-gmap-marker>` it doesnt work as stated in #1625. I was in the middle of working on a PR that was about 75% complete. But I currently am busy with work and have lost motivation on this project.

**Comment by neerajkumarnj** [comment]
I figured out the solution. I don't need to use the control object, i can directly access the "marker" from scope via the idKey, and any changes that i make gets reflected. So, thanks anyways.
