### ISSUE TITLE
error within chunking iterator: TypeError: a.remove is not a function 

### ISSUE THREAD

**Issue by maeishoj** [angular-ui/angular-google-maps#1652]
Hello everyone,

I am having a strange issue and i don't know what to make of it (see title).

That happen when I drop the a 2nd marker on the map, and if I drop say 5 and I try to click on each marker to open the InfoWindow, it only opens it for the first 2 markers and not the other ones.

<img width="1506" alt="screen shot 2015-12-13 at 15 02 43" src="https://cloud.githubusercontent.com/assets/1631903/11767344/e287274a-a1aa-11e5-81bc-54c750078dc1.png">

I tried to reproduce it on plunkr, but wasn't able, as there it works just fine. I copied the whole code (relevant parts) and on my machine the same doesn't work properly.

http://plnkr.co/edit/qboJnHGORg4EQWZ6WG9B?p=preview

I am using 2.2.1 and if load 2.1.5 instead, i don't get that error! 

DOes anyone have an idea what's going on?

**Comment by nmccready** [comment]
Need an example where this is happening; but you would probably get better error information if you are not using minified code. (This is assumed, so if I am wrong apologies up front.)

**Comment by maeishoj** [comment]
not sure why it said : angular-google-maps.min.js cause im not using minified and I checked again now and the error is the same, just without .min.

as I wrote above, unfortunately i tried to reproduce the error in plnkr, but i couldn't :/ IT is the same code and libraries i have locally, except a whole other bunch of libraries I have for my project that are not related but not sure whether they would cause incompatibility problems :/ 

From the error do you have any idea of what would be going wrong with the 2.2.1 that didn't with the 2.1.5 when I drop markers on the map (again, the error happens as I drop the 2nd marker on the map :( )

**Comment by nmccready** [comment]
I don't know if it is an error per-say in the library. It means that some object a (which I do not see anywhere) is calling a function `remove` while iterating through the code. This error could be happening as high as the application level and just being caught in the iterator itself. Remove is called [here](https://github.com/angular-ui/angular-google-maps/blob/abce610a29649159363ce071829d7d1d9c8ec4d3/src/coffee/directives/api/models/parent/markers-parent-model.coffee#L168) and [here](https://github.com/angular-ui/angular-google-maps/blob/abce610a29649159363ce071829d7d1d9c8ec4d3/src/coffee/directives/api/models/parent/windows-parent-model.coffee#L165)

**Comment by nmccready** [comment]
But bottom line is I can't really help without an example that actually produces the problem.

**Comment by maeishoj** [comment]
I understand. I will try to see how i can reproduce this, else I will keep 2.1.5 unitll i can figure out how to reproduce it.

**Comment by nmccready** [comment]
You don't have anything that is expected to be bound to remove do u? IE an attribute that is `someAttr="remove"` .

**Comment by nmccready** [comment]
Also disable chunking with `chunk=false` and you might get a better stack trace.

**Comment by maeishoj** [comment]
no remove. I am dropping marker from outside to the map, by adding the selected img to the array that is binded to the markers in the map and then do $scope.$apply(); else the markers are not shown on map. If I remove $scope.$apply() and drag and drop them, i get no error (right away), but no marker visible, but if then I move the map, so that its "refreshed" then i get the same error.

Also chunck =false didnt really help :/

<img width="1431" alt="screen shot 2015-12-14 at 17 25 00" src="https://cloud.githubusercontent.com/assets/1631903/11786664/0d7c6ff4-a288-11e5-9467-61f3b24c7255.png">

**Comment by maeishoj** [comment]
Safari gives a little more info:

<img width="1432" alt="screen shot 2015-12-14 at 17 37 12" src="https://cloud.githubusercontent.com/assets/1631903/11786887/5d0e15ee-a289-11e5-9290-052d32eb3441.png">

**Comment by maeishoj** [comment]
similar error but more descriptive happen in another page of my app (with 2.2.1 but no 2.1.5) and seems to relate to same issue, except it gives a little more details

<img width="1432" alt="screen shot 2015-12-14 at 17 37 12" src="https://cloud.githubusercontent.com/assets/1631903/11786977/cd34ec12-a289-11e5-8476-1f3333400eed.png">

**Comment by nmccready** [comment]
Much better then it is a bug or something with an event listener being removed.

**Comment by maeishoj** [comment]
you are right, i think.

I have the following:

    <ui-gmap-windows show="'show'">
                            <div ng-non-bindable>{{code}} - {{description}}<br/><strong>Location:</strong> {{latitude}} - {{longitude}} </div>
                            </ui-gmap-windows>

and I i remove the code above, not having a window, it works fine without throwing that error :/

**Comment by nmccready** [comment]
Probably this `for in` is the problem.

https://github.com/angular-ui/angular-google-maps/blob/2.2.1/dist/angular-google-maps.js#L939

Are you extending `Array.prototype` ?

**Comment by nmccready** [comment]
Anyway using `_.each`, `angular.each` or `[].each` might fix the problem but they are all slower. Also checking for hasOwnProperty would help as well.

**Comment by maeishoj** [comment]
I do extend it but i can remove that. however i have a library bluebird.js from the template i am using, which i saw extends Array.prototype.

About the _.each, angular.each, [].each, how did you suggest me to use them (meaning, where)?

Also the last screenshot i posted where you said "much better" was from safari. Chrome (in the same page) doesn't throw that same error.

**Comment by nmccready** [comment]
It is just me making notes on what I need to change in the code base. Nothing you can do. Its a bug and all of those are fixes. But you can test and confirm my assumptions by trying those changes directly in your angular-google-maps.js verison modified with one of those ideas.

**Comment by maeishoj** [comment]
hey there. so removing my custom method of "array.prototype" fixed all issues so far for what i have seen. :)

**Comment by nmccready** [comment]
Cool, yeah so whatever that prototype was was being passed to google as an object to remove which.. does not have the function `remove`. Make sense.. mucking with Array.prototype is a big no no.. but my `for in` loop should check for hasOwnProperty anyway.

**Comment by nmccready** [comment]
So its kinda bug on two fronts.. one I need a better iterator or saftey check .. 2 (your side) you should be more careful with your prototypes :) .

**Comment by maeishoj** [comment]
You right :) will keep that in mind :) I guess I can close the issue now! :) 

Thanks again for the help! was useful to pinpoint the issue! :)

**Comment by nmccready** [comment]
Going to keep it open as I won't remember to make that fix without this existing.

**Comment by maeishoj** [comment]
ok ill reopen it!

**Comment by nmccready** [comment]
resolved

**Comment by getglad** [comment]
Can you package this as part of release so it is available on NPM?

**Comment by nmccready** [comment]
Yes I'll get this started. I think it will be 2.3.0 as there were possible breaking changes in `uiGmapGoogleMapApi` . Its better to bump to 2.3.X and be safe.

**Comment by nmccready** [comment]
@getglad https://github.com/angular-ui/angular-google-maps/releases/tag/2.3.0 , on npm

**Comment by getglad** [comment]
@nmccready great - thanks so much!

**Comment by svaponi** [comment]
Hi, I updated to 2.3.4 but the problem stays.

    "angular": "1.4.3",
    "angular-block-ui": "0.2.0",
    "angular-breadcrumb": "0.3.2",
    "angular-google-maps": "2.3.x",
    "angular-ui-router": "0.2.15",
    "angular-ui-bootstrap-bower": "0.8.0",
    "bootstrap": "3.3.5",
    "jquery": "2.1.4",
    "moment": "2.11.1",
    "underscore": "1.5.2",

It seems like BasePolyChildModel.create() [line 2736] invokes convertPathPoints(_this.scope.path) but path is undefined within _this.scope. Then convertPathPoints has conditions on path.type without handle path === undefined.

Hope this makes sense :)

Any advice?
