### ISSUE TITLE
Make a marker not being clustered

### ISSUE THREAD

**Issue by AGALDEANO** [angular-ui/angular-google-maps#1668]
Hello,
I'm have a lot of markers on my map so I've decided to use clustering. It works great! 
However there is one marker that I want to be always visible and not clustered.
I tried something like the following but it didn't work:

```
<ui-gmap-google-map>
  <ui-gmap-markers></ui-gmap-markers>
  <ui-gmap-marker></ui-gmap-marker>
</ui-gmap-google-map>
```
Is there any way I could do that?
If not, that might be a useful feature.
Thanks a lot.

**Comment by nmccready** [comment]
That should work fine. Can you make a jsbin, plnkr or fiddle?

**Comment by AGALDEANO** [comment]
I've never used any of those, maybe I'll take some time to do it in a week or two. Anyway, I trust you if you say that it should work (the "owner" label is pretty persuasive). I must've miss something in my code, I'll look it up. 
This version is not up-to-date but if you want to see how I'm using your library: http://lyonvelov.info
Many thanks, and great job by the way!
