### ISSUE TITLE
Add Autocomplete to Parent Div Does not Work With Ui-Router

### ISSUE THREAD

**Issue by 360disrupt** [angular-ui/angular-google-maps#1674]
If I have two views e.g.
`root.a`
`root.b`
when in `b` there is the parent div but `a` is loaded first, then the parent div is not appended. 

I think this is related to, that the function is called during the init process:
`search-box-parent-model.coffee line 43`:

```
init: =>
  if @attrs.parentdiv?
    @addToParentDiv()
```

Adding this to line 60 could help:
```
@scope.$on '$stateChangeSuccess', =>
   if @attrs.parentdiv?
      @addToParentDiv()
   else
     @addAsMapControl()
```
Maybe it needs to be checked if it was already added. I can create a pull request on it.

**Comment by kandizzy** [comment]
@360disrupt a pull request would be much appreciated. Thank you!

**Comment by 360disrupt** [comment]
I did some changes, when compiling them with `grunt` it aborts due to errors, `grunt --force` works but it seems to change too much, I only modified one file:

This is `git status` after the built.
```
	modified:   dist/angular-google-maps-street-view.js
	modified:   dist/angular-google-maps-street-view.min.js
	deleted:    dist/angular-google-maps-street-view_dev_mapped.js
	deleted:    dist/angular-google-maps-street-view_dev_mapped.js.map
	deleted:    dist/angular-google-maps-street-view_dev_mapped.min.js
	deleted:    dist/angular-google-maps-street-view_dev_mapped.min.js.map
	modified:   dist/angular-google-maps.js
	modified:   dist/angular-google-maps.min.js
	deleted:    dist/angular-google-maps_dev_mapped.js
	deleted:    dist/angular-google-maps_dev_mapped.js.map
	deleted:    dist/angular-google-maps_dev_mapped.min.js
	deleted:    dist/angular-google-maps_dev_mapped.min.js.map
	deleted:    dist/architecture/dot/all.dot
	deleted:    dist/architecture/dot/legend.dot
	deleted:    dist/architecture/dot/modules.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.directives.api.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.directives.api.managers.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.directives.api.models.child.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.directives.api.models.parent.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.directives.api.options.builders.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.directives.api.options.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.directives.api.utils.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.extensions.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.providers.dot
	deleted:    dist/architecture/dot/modules/uiGmapgoogle-maps.wrapped.dot
	deleted:    dist/architecture/png/all.png
	deleted:    dist/architecture/png/legend.png
	deleted:    dist/architecture/png/modules.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.directives.api.managers.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.directives.api.models.child.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.directives.api.models.parent.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.directives.api.options.builders.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.directives.api.options.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.directives.api.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.directives.api.utils.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.extensions.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.providers.png
	deleted:    dist/architecture/png/modules/uiGmapgoogle-maps.wrapped.png
	modified:   src/coffee/directives/api/models/parent/search-box-parent-model.coffee
```
Shall I add all the modified files to my commit and ignore the deleted? 

Is this commit message correct:
```
fixes(1674): appends autocomplete on state change

appends autocomplete on state change if it does not exist already

closes(1674)
```

**Comment by kandizzy** [comment]
Hi @360disrupt, here are some answers.

1. Did you also run `grunt buildAll`? This will compile your changes into the dist files.

2. Yes the date change can be added.

3. Commit message is perfect.

**Comment by nmccready** [comment]
He can Shane the one file and not build all as karma will run against the new code for specs on Travis. However to test it locally he needs at a minimum to do a basic 'grunt default' or just 'grunt'

**Comment by kandizzy** [comment]
@360disrupt hi, just wanted to see if you are still working on this? I think @nmccready means you can just add the one modified file in `src` and karma will do the rest.

**Comment by 360disrupt** [comment]
Oh sorry, I made it ready but didn't emit the pull request. I hope it is okay with the changes I made, I did commit more than the src file. Maybe take a look and tell me what to do. I may could do an interactive rebase on it, but I'm not so sure how to do it when already pushed to my origin fork. Just let me know.
https://github.com/angular-ui/angular-google-maps/pull/1692

**Comment by kandizzy** [comment]
@360disrupt to keep your changes and grab the latest this command may be the best option:
 `git reset upstream/master --soft`

and then push again to your `origin master`.

@nmccready do you have any suggestions here? I always run into this problem with my PRs containing old commits from upstream.

**Comment by nmccready** [comment]
Rebase or merge. All you need to do is set and fetch upstream (our git url). Then merge in the latest. Rebuild, commit and push changes. Then it should say it is mergable on github. If you want to rebase you can (only if you know what your doing). But merging is simpler for the unexperienced.

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/commit/287358d8360bf2ae531cdd41842181e7c3c20e42
