### ISSUE TITLE
Prefill searchbox

### ISSUE THREAD

**Issue by DaSchTour** [angular-ui/angular-google-maps#1677]
In certain cases I need to prefill a value into the searchbox but as ng-model doesn't work on the searchbox and there is no possibility to know when the searchbox is added to the DOM it is not possible to insert a value into the searchbox. So it would be great if there where an option for this.
Thanks

**Comment by nmccready** [comment]
@kandizzy ?

**Comment by kandizzy** [comment]
@DaSchTour there is a example of how to use ng-model on the searchbox here: 
https://github.com/angular-ui/angular-google-maps/blob/master/example/search-box-ngmodel.html

Let me know if this works for you.

**Comment by DaSchTour** [comment]
Well somehow the way the searchbox works is against all intuition. I would never think about adding ng-model to the searchbox directive as by adding a label and input through the template. But I also have seen that the template doesn't replace what is inside the directive but is jut added and, so that I have an ugly jumping DOM when having elements below my searchbox.

**Comment by kandizzy** [comment]
I am interested to know what way would be intuitive to you. Can you walk me through how you thought it would work? That would be helpful.

Also, this is first time I've heard the ugly jumping DOM problem, would you make an MVCE of that so I can take a look?

**Comment by DaSchTour** [comment]
Well the jumping do is very easy to create. Just insert an input below the element where the searchbox is inserted. Something like this (with the needed data added).
```html
<div class="col-md-6">
 <div id="searchboxWrapper">
 </div>
 <div id="Additional Input">
   <input type="text">
 </div>
</div>
<div class="col-md-6">
 <ui-gmap-google-map center='vm.map.center' zoom='vm.map.zoom'>
	<ui-gmap-search-box parentdiv="''searchboxWrapper" />
  </ui-gmap-google-map>
</div>
```

**Comment by DaSchTour** [comment]
Well and the ng-model has no effect. I now get with a dirty jQuery solution :( the worst is that's the only thing I need jQuery for.

**Comment by kandizzy** [comment]
@DaSchTour I'm not following. What do you mean the ng-model has no effect?

**Comment by kandizzy** [comment]
You shouldn't need jquery for this. Here's an example that works.
http://plnkr.co/edit/SnNLK2Vjzx7a4ZPf6HTe?p=preview

Also, I provided the `parentdiv` option because that's how the project I was working on at the time was designed but it's not something directly from Google. You would likely be able to prevent any jumping with CSS, if you come up with a better solution open a PR.

**Comment by DaSchTour** [comment]
Well, to most important thing about ng-model is very easy to overlook. After hours of comparing my code with the plnkr I discovered that ng-model is bound twice. Once to the searchbox directive and once inside the template.
