### ISSUE TITLE
Get OverlappingMarkerSpiderfier instance

### ISSUE THREAD

**Issue by t8g** [angular-ui/angular-google-maps#1678]
How can I retrieve OverlappingMarkerSpiderfier instance.
My need is to use instance methods like oms.markersNearMarker()

Thanks ;)

**Comment by nmccready** [comment]
[control.getManager](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/plural.coffee#L20)

Then look at the manager or spider fire.
[instance](https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/managers/spiderfier-marker-manager.coffee#L8)

**Comment by t8g** [comment]
So easy !
Thanks ;)

**Comment by nmccready** [comment]
np
