### ISSUE TITLE
Lodash 4.0 release breaks some functions

### ISSUE THREAD

**Issue by david-meza** [angular-ui/angular-google-maps#1682]

**Comment by david-meza** [comment]
From backtrace:

TypeError: _.contains is not a function
    at angular-google-maps.js:6538

TypeError: _.object is not a function
    at angular-google-maps.js:6771

**Comment by armyofda12mnkeys** [comment]
Just noticed this myself. angular-google-maps 2.2.1 depends on lodash 4... but lodash 4 repaced _.contains w/ _.includes i think i read.

**Comment by nmccready** [comment]
Well crap the versioning should have been 3.X . Any suggestions on dealing with both 3 and 4 ?

**Comment by armyofda12mnkeys** [comment]
Can you maybe define the alias yourself if it doesn't exist before rest of angular-google-maps runs? 
Dunno something simple like so:
```
if( typeof _.contains === 'undefined' ) {
  _.contains = _.includes;
} //else it exists and we good for lodash3 without doing anything else
```

**Comment by david-meza** [comment]
It seems `_.object`was also replaced with `_.zipObject` but the functionality is the same. I agree that aliasing would be a good solution to deal with both versions.

**Comment by nmccready** [comment]
##1683

**Comment by nmccready** [comment]
So it is locked down on master and on 2.2.X , as for a solid fix to use 4.0. That will have to come later or by some other soul (PR). I am currently not using this library for work anymore and can only work on it in my spare time (which is not much work and 5 month old).

**Comment by armyofda12mnkeys** [comment]
I can maybe take a look later (since im using other projects that use lodash 4). Will let u know if a PR happens.

**Comment by armyofda12mnkeys** [comment]
Might need a little help nmccready... 
Where would be a good place to put the lodash alias code (before lodash is referenced/used in angular-google-maps)? I can start playing with throwing some code in there and seeing if any more lodash methods (like _.object above) need to get re-aliased. 

Maybe an init/load area or wasnt sure if uiGmapLodash is the definite optimal place (since i see below code does something similar... looks like if _.get isn't available for lodash2? users maybe, it creates it):

```
if (_.get == null) {
      //...code...
      _.get = get;
}
```

**Comment by eliely** [comment]
There is solution:
```
if( typeof _.contains === 'undefined' ) {
    _.contains = _.includes;
    _.prototype.contains = _.includes;
}
if( typeof _.object === 'undefined' ) {
    _.object = _.zipObject;
}
```
We write it on Main.js file
``` _.prototype.contains = _.includes;``` - because `ui-gmap-marker` used `_(someName).contains` construction

**Comment by armyofda12mnkeys** [comment]
>ui-gmap-marker used _(someName).contains
Hey eliely, 
Why would they create an instance of lodash?
Are you sure its not the googlemapbounds.contains or string.contains methods and definitely lodash's contains?

**Comment by nmccready** [comment]
@armyofda12mnkeys what file and line please via github urls.

**Comment by eliely** [comment]
They use lodash "Chain" methods https://github.com/lodash/lodash/blob/3.10.1/doc/README.md
There is they code 
```
var doIgnore;
     if (ignores) {
          doIgnore = _(ignores).contains(eventName);
     }
```
https://github.com/angular-ui/angular-google-maps/blob/master/dist/angular-google-maps.js
line 945

**Comment by nmccready** [comment]
Yeah its here so it is in events-helper.coffee 
https://github.com/angular-ui/angular-google-maps/blob/master/dist/angular-google-maps.js#L947

That chain can easily be removed. Using `_.contains(ignores, eventName)` or just using `array.indexOf`

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/utils/events-helper.coffee#L19 

PR merged changed it to includes, but still the chain is not needed.

**Comment by armyofda12mnkeys** [comment]
This added to line 99 in lodash.coffee (https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/extensions/lodash.coffee) might work: but haven't really tested it (I couldn't compile the full coffeescript via grunt ... but it might be something else if you can take a look):


	###
			For Lodash 4 compatibility (some aliases are removed)
	###
	
	if typeof _.contains == undefined
		_.contains = _.includes;
		_.prototype.contains = _.includes;	
	if typeof _.object == undefined
		_.object = _.zipObject;
	if typeof _.all == undefined
		_.all = _.every;
	if typeof _.any == undefined
		_.any = _.some;

**Comment by tucq88** [comment]
using temporary solution for now. But I'm looking forward for a proper fix :D Thanks you guys for your hard works.

**Comment by nmccready** [comment]
This does not fix a lot of things. Many specs are broken on using lodash 4.0 . Still having a tough time figuring out a few of them.

Here is the branch with progress. https://github.com/angular-ui/angular-google-maps/tree/dev/nmccready/tryingToMakeLodash4Wurk

**Comment by nmccready** [comment]
Anyone feel free to help work on that branch and PR to it. I can only work on it once in a while. I put too much time into it last night anyhow.

**Comment by armyofda12mnkeys** [comment]
>Many specs are broken on using lodash 4.0 .

I can take a look...
Any errors/line#'s in particular (I was able to get a map with that 2.2.x build w/ no errors)?
I wasn't sure if you using some special map options that I wasn't using.

**Comment by nmccready** [comment]
You should be seeing errors.

Pull down the code and run `grunt` or `grunt buildAll` the specs will blow up. Just because and example or the library can be loaded means nothing. The specs are the spoken gospel and they must pass.

**Comment by nmccready** [comment]
Tests that are broken:

```
uiGmapMarkers (directive creation)
    object models
      should add markers for each object in model
        ✖ from start
        ✖ from start
    array models
      should add markers for each object in model
        ✔ from start
      dynamic
        ✔ delayed creation
        update an existing marker should modify an existing gObject (gMarker)
          ✖ by reference
          ✖ by position (model)
      can eval key function
        ✔ handles click function in model
      can eval expressions
        ✔ handles click expression to function
      ✔ exists
```

```
ModelKey Tests
    ✔ should eval model handle correctly
    ✖ should properly compare models
    ✔ should properly set id key
```

**Comment by nmccready** [comment]
#1711 resolves this

**Comment by armyofda12mnkeys** [comment]
I couldn't figure it out. Thanks for fixing @nmccready  ... 
What was the main fix for this?
I thought maybe looking at your updates that it wasn't a lodash fix needed, but possibly the way to handle objects in getArrayAndKeys and maybe thats why those tests were failing?

**Comment by nmccready** [comment]
Alot of the problem was in _async.coffee and I just removed lodash from that part.

**Comment by nmccready** [comment]
This part

https://github.com/angular-ui/angular-google-maps/blob/9419a4c7fe3a03f30c34eedc546f95193e17dd8f/src/coffee/directives/api/utils/_async.coffee#L152-L155

became

https://github.com/angular-ui/angular-google-maps/blob/f37e1b57af16b1d825ddd90d4abd8afe81976e79/src/coffee/directives/api/utils/_async.coffee#L158-L164

**Comment by nmccready** [comment]
More patching https://github.com/angular-ui/angular-google-maps/blob/f37e1b57af16b1d825ddd90d4abd8afe81976e79/src/coffee/extensions/lodash.coffee#L12-L29

**Comment by jrencz** [comment]
@nmccready correct me if I'm wrong (I've never written a line of coffee script) but as long as I can tell `lodash.coffee` modifies the `_` global?

**Comment by nmccready** [comment]
Sure, there are several ways to do a lot of things.

**Comment by amak07** [comment]
@nmccready Hey sir, I am having this problem when trying to use angular-ui-map in my MEAN stack application for a course in college. From what I understand, the "aliasing" code bit should fix this problem for me? If so, I am completely unsure of where to add this line of code. I am using the current version of the MEAN.js boilerplate template for this application and have done the bower install <angular map lib> --save. Could you please advise on where to implement the code bit to solve this problem, thanks!

**Comment by shabana-parveen** [comment]
@nmccready , I am getting below for running appium command from terminal, Please provide solution for same:

$ npm ls lodash
bin@1.0.0 /Users/f2849
└── lodash@4.17.4

npm version : 5.3.0
node version : v8.6.0
appium version : 1.7.0 beta

TypeError: _lodash2.default.toPairs is not a function
    at Object.<anonymous> (../../lib/adb.js:74:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/appium/node_modules/appium-android-driver/node_modules/appium-adb/build/index.js:11:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (../../lib/android-helpers.js:10:49)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (../../../lib/commands/general.js:1:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (../../../lib/commands/index.js:1:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
