### ISSUE TITLE
Wrapper in autocomplete's template

### ISSUE THREAD

**Issue by hatemzidi** [angular-ui/angular-google-maps#1693]
hi,
I just noticed that https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/parent/search-box-parent-model.coffee#L27 is deleting any wrapper (div, span ... etc) in my searchbox.tpl.html

here's a snippet of my code : 

```javascript
angular.module('traffc')
    .run(['$templateCache', function ($templateCache) {
        $templateCache.put('searchbox.tpl.html', '<div><i class="glyphicon glyphicon-search"></i><input type="text" class="form-control clearable" id="map-location-search" placeholder="Search for a location..." autocomplete="off"></div>');
    }])
...
```
and inside my controler : 
```javascript
 $scope.searchbox = {
            template: 'searchbox.tpl.html',
            position: 'top-right',
            parentdiv: 'container-map-location-search',
            options: {
                autocomplete: true,
                types: ['(cities)'],
                visible: true
            }
...
}
```

my html : 
```html
 <div class="view" ng-controller="MapCtrl">
        <div id="map_canvas" class="col-lg-10 col-md-8 col-sm-8 col-xs-9 col-centered">
            <div id="map">
                <ui-gmap-google-map center='map.center' zoom='map.zoom' options="map.options">
                    <ui-gmap-layer type="TrafficLayer" show="true"></ui-gmap-layer>

                    <ui-gmap-search-box options="searchbox.options" template="searchbox.template"
                                        events="searchbox.events" parentdiv="searchbox.parentdiv"></ui-gmap-search-box>

                </ui-gmap-google-map>
            </div>
        </div>

        <div id="container-map-location-search">
        </div>
    </div>
```

but I keep getting : 
<img width="929" alt="screen shot 2016-01-19 at 00 07 29" src="https://cloud.githubusercontent.com/assets/926142/12405007/bb15a4f4-be40-11e5-9344-61cfe3831f1f.png">

what are the possible fixes ?
thank you ...

**Comment by kandizzy** [comment]
hi @hatemzidi 

Will you try changing your parentdiv container code to something like this:
`<div><i class="glyphicon glyphicon-search"></i><div id="container-map-location-search"></div></div>`

And your template code to:
`$templateCache.put('searchbox.tpl.html', '<input type="text" class="form-control clearable" id="map-location-search" placeholder="Search for a location...">');`

The Google Places Autocomplete class expects `inputField:HTMLInputElement` as the first argument so anything other than the input element in your template will be ignored to avoid an error from the Google API.

**Comment by hatemzidi** [comment]
hi @kandizzy,

indeed, and thanks to your explanation about the API, I changed my container to : 

```html
<div id="container-map-location-search">
            <i class="glyphicon glyphicon-search"></i><div id="container-location-search"></div>
</div> 
```
I changed the name of the wrapper and the parentdiv container, and updated the parentdiv item inside my $scope.searchbox.

... and it works ^^
many thanks :+1:
