### ISSUE TITLE
Remove the sensor param

### ISSUE THREAD

**Issue by andrewcashmore** [angular-ui/angular-google-maps#1698]
The sensor parameter is no longer required for the Google Maps JavaScript API. It won't prevent the Google Maps JavaScript API from working correctly, but we recommend that you remove the sensor parameter from the script element.

**Comment by nmccready** [comment]
Its gone on master.

https://github.com/angular-ui/angular-google-maps/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+sensor+

#1689 #1662

**Comment by andrewcashmore** [comment]
:+1:
