### ISSUE TITLE
uiGmapIsReady not resolving

### ISSUE THREAD

**Issue by napcat** [angular-ui/angular-google-maps#1699]
I cant get the map instance. The uiGmapIsReady is not resolving at all, or at least when I'm trying to get the map. I tried to change the number of times to retry the map check, but with no luck...

I get this message: 'Your maps are not found we have checked the maximum amount of times. :)'.

I'm I missing something?

        uiGmapGoogleMapApi.then(function (api)
        {
            //Google maps API reference
            GMapsLocationVM.GoogleMapAPI = api;

            GMapsLocationService.GetMapData().then(function (model)
            {
                //map object binded in the scope
                GMapsLocationVM.Map = model;

                uiGmapIsReady.promise(1, 3000).then(function (maps)
                {
                    GMapsLocationVM.MapControl = maps[0];
                });
            });
        });

I have version 2.2.1.

**Comment by nmccready** [comment]
plnkr, jsbin, fiddle please

**Comment by napcat** [comment]
I made a few tests... Can it be related with the ng-if / ng-show?

If I'm using ng-if the map appears but the uiGmapIsReady  does not resolve.

If i use ng-show the uiGmapIsReady, resolves, but the map does not show. The map area is filled with grey color and i can onlye see the google maps logo ate the bottom.

**Comment by napcat** [comment]
Ohh god... I'm so sorry! *_*

It makes sense... (I think) the promise was not resolving because the GMapsLocationVM.IsLoading was only set after the uiGmapIsReady resolve.

There was no directive on the html, at that time...

But the strange thing is the grey screen if I use ng-show instead of the ng-if... Can it be related to css rendering or a js bug?

**Comment by david-meza** [comment]
The grey screen is caused because the map initially loads while the map-container has a `display: none;` from the `ng-show`. If you think about it, how would it know how many tiles to load if it isn't based on the parent's container? So, to fix it you should trigger a map refresh when your `ng-show` expression changes.

**Comment by nmccready** [comment]
This sounds resolved; thank you @david-meza

**Comment by lfreneda** [comment]
@david-meza, how to trigger a map refresh?
