### ISSUE TITLE
How to Disable All Controls and Click-Dragging

### ISSUE THREAD

**Issue by TimeTravelersHackedMe** [angular-ui/angular-google-maps#1705]
How can I disable all the controls (e.g. zoom) and disable click-dragging?

Sorry if this is the wrong place to post this - if so can you please direct me to the appropriate place?

**Comment by nmccready** [comment]
http://angular-ui.github.io/angular-google-maps/#!/api/google-map

Its all right there.

**Comment by guaxy** [comment]
i tried remove the controls, how you did?
