### ISSUE TITLE
marker change every time. On map is move or scroll mouse. position can't lock

### ISSUE THREAD

**Issue by avatarr** [angular-ui/angular-google-maps#1706]
Hi, I have a problem with maker on scroll or move a map , For example I have set a marker.coords to my country. after that I scroll mouse then my maker not point to old point , What happen and why 

It's a full code that I copied from official site of lib
```
  var vm = this;

    vm.default_point = {
        latitude: 13.7563,
        longitude: 100.5018
    }
    $scope.map = {
        center: vm.default_point,
        zoom: 4
    };
    $scope.options = {
        scrollwheel: true
    };
    var events = {
        places_changed: function(searchBox) {
            vm.default_point.latitude = searchBox.getPlaces()[0].geometry.location.lat();
            vm.default_point.longitude = searchBox.getPlaces()[0].geometry.location.lng();
        }
    }
    $scope.searchbox = {
        template: 'searchbox.tpl.html',
        events: events
    };

    $scope.marker = {
        id: 0,
        coords: vm.default_point,
        options: {
            draggable: true
        },
        events: {
            dragend: function(marker, eventName, args) {
                var lat = marker.getPosition().lat();
                var lon = marker.getPosition().lng();
                $scope.marker.options = {
                    draggable: true
                };
            }
        }
    };
```

**Comment by nmccready** [comment]
Need a full example that runs.

**Comment by david-meza** [comment]
Your marker is using a ***reference*** to the same object that the center of the map uses. This means that when the center of the map changes, your marker will too, because they are in essence the same object. If you want to separate them, I suggest making a new object with the same lat and long. So instead of using:

    $scope.marker = {
        coords: vm.default_point
    }

You should define it as:

    $scope.marker = {
        coords: {
          latitude: vm.default_point.latitude,
          longitude: vm.default_point.longitude
        }
    }

**Comment by nmccready** [comment]
@david-meza is correct, sorry I don't usually dig into the code unless there is a working example.

**Comment by avatarr** [comment]
Thank you @david-meza  @nmccready , My bad and now google map run as example.
