### ISSUE TITLE
Using directives withing either ui-gmap-window or ui-gmap-windows does not work

### ISSUE THREAD

**Issue by bjornharvold** [angular-ui/angular-google-maps#1708]
I can imagine the complexities and timings to get this to work. What are the possible workaround(s) to this?

**Comment by nmccready** [comment]
You not providing enough information or context. Are you referring to using them with markers nesting. If so this question has been brought up many times before.

**Comment by bjornharvold** [comment]
Never mind. Figured how to do it using the templateUrl and
templateParameter.

Have a great day!

On Wednesday, January 27, 2016, nmccready <notifications@github.com> wrote:

> You not providing enough information or context. Are you referring to
> using them with markers nesting. If so this question has been brought up
> many times before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular-ui/angular-google-maps/issues/1708#issuecomment-175654021>
> .
>


-- 

Cheers,
Bjorn

-----------
*Bjorn Harvold*
*E-mail*: bjorn@harvold.com
*U.S. Mobile*: +1-917-494-6357
*Google Voice*: +1-917-934-3912
*Skype*: +1-917-720-3351 / bjornharvold
*Thai Mobile*: +66-85151-0325
*Facebook*: bjornharvold
*Twitter*: @bjornharvold
*LinkedIn*: bjornharvold
