### ISSUE TITLE
lodash 4 not compatible: _.contains() is not a function

### ISSUE THREAD

**Issue by c00** [angular-ui/angular-google-maps#1709]
When updating to the latest version of lodash (4.0.1 atm) there will be some errors. Namely `_contains() is not a function`. 

To others experiencing this problem: A workaround is to manually add the following to the project:

    _.contains = _.includes;

Workaround found in comments [here](https://github.com/mgonto/restangular/issues/1225).

**Comment by nmccready** [comment]
#1682
