### ISSUE TITLE
Generating maps in ng-repeat issue

### ISSUE THREAD

**Issue by Klapsa2503** [angular-ui/angular-google-maps#1714]
Recently I have discovered that creating maps in ng-repeat is very laggy and slow, but only if you add a markers to the map. I have created two jsfiddles to show you an example:

1. Example with a loop without any markers - fast
http://jsfiddle.net/duabubeo/58/

2. Example with a loop with single marker - slow and laggy, page is loading very slow
http://jsfiddle.net/duabubeo/57/

I had to use regular google maps in order to create maps in a loop without lags.

**Comment by nmccready** [comment]
This is probably due to angular watches. Anyway.. both markers and marker use the same underlying marker-child-object, but the speed is issue is not there for markers.

http://jsfiddle.net/nmccready/qzjtjwoc/

**Comment by nmccready** [comment]
So I found the problem https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/models/child/marker-child-model.coffee#L26 . This is pretty awful slow in lodash 3.X . http://jsfiddle.net/nmccready/9xa60d11/

In lodash 4.X it is drastically improved

http://jsfiddle.net/nmccready/7a5q8nt8/

**Comment by nmccready** [comment]
The cloning can be skipped for all child models if the model itself is a scope object. Which an singular directive the model is a scope object. So this would help as well.

**Comment by nmccready** [comment]
old lodash fire
![screen shot 2016-01-30 at 4 02 10 pm](https://cloud.githubusercontent.com/assets/583593/12699855/19c5416e-c79a-11e5-8e62-7e42d36ec73f.png)

**Comment by nmccready** [comment]
Here is the fixed branch making 3.X of lodash irrelevant http://jsfiddle.net/nmccready/vcmL1e8d/1/
