### ISSUE TITLE
Bad configuration Example

### ISSUE THREAD

**Issue by DaSchTour** [angular-ui/angular-google-maps#1721]
The Example for configuration that is published on your page is very bad, as it doesn't work after minification.
Please change
```javascript
.config(function(uiGmapGoogleMapApiProvider) {
    uiGmapGoogleMapApiProvider.configure({
        //    key: 'your api key',
        v: '3.20', //defaults to latest 3.X anyhow
        libraries: 'weather,geometry,visualization'
    });
})
```

to

```javascript
.config(['uiGmapGoogleMapApiProvider', function(uiGmapGoogleMapApiProvider) {
    uiGmapGoogleMapApiProvider.configure({
        //    key: 'your api key',
        v: '3.20', //defaults to latest 3.X anyhow
        libraries: 'weather,geometry,visualization'
    });
}])
```

**Comment by nmccready** [comment]
If anyone know anything about angular then they should know this off the bat. It is perfectly valid and it would require ngAnnotate. There is nothing wrong with the way it is.

**Comment by DaSchTour** [comment]
Well but in an normal environment your example just doesn't work. And I know about angular, but it just didn't came to my mind, that people working with angular would publish such a bad example on the internet, that looks like the did never use minification.
