### ISSUE TITLE
Using streetview with the address detail rather than lat/lang values

### ISSUE THREAD

**Issue by rcadhikari** [angular-ui/angular-google-maps#1726]
Hi Guys,

could you please confirm whether we could be able to display the street view from the address out of the box. If not what would be the wayout for that.

Any help would be really appreciated.

Cheers!

**Comment by nmccready** [comment]
Currently it only accepts a LatLng object (I think the google one). 
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/street-view-panorama.coffee#L92-L94

If you want it to support the address all you need to do is use [googles geocoding](https://developers.google.com/maps/documentation/javascript/examples/geocoding-simple). Get the Latlng from that and then send it to the directive. 

I don't think the directive should have this added to make it more complicated but convenient.
