### ISSUE TITLE
With angular 1.4.9: TypeError: Cannot read property 'exp' of undefined

### ISSUE THREAD

**Issue by kheaactua** [angular-ui/angular-google-maps#1728]
With Angular 1.4.9, I'm getting the error:

```
TypeError: Cannot read property 'exp' of undefined
    at angular-google-maps.js:6874
    at m.$digest (angular.js:16664)
    at angular.js:16859
    at e (angular.js:5804)
    at angular.js:6081
```

I load the maps with:
```javascript
.config(['$routeProvider', 'uiGmapGoogleMapApiProvider',
  function($routeProvider, uiGmapGoogleMapApiProvider) {
     // ...
		uiGmapGoogleMapApiProvider.configure({
			//    key: 'your api key',
			v: '3.20', //defaults to latest 3.X anyhow
			libraries: 'weather,geometry,visualization'
		});
  }])
```

Then in my controller I have:
```javascript
$scope.map = { 'center': { 'latitude': 45, 'longitude': 73 }, 'zoom': 15 };
uiGmapGoogleMapApi.then(function(maps) { });
```

And in my view I have:
```html
<ui-gmap-google-map center="map.center" zoom="map.zoom" options="map.options"></ui-gmap-google-map>
```

Pretty basic.  Google shows me similar issues with other libs that are based on version discrepancies.  My bower file has:
```json
  "dependencies": {
    "lovefield": "^2.1.6",
    "jQuery": "1.12.0",
    "angular-route": "^1.4.9",
    "angular-moment": "^0.10.3",
    "moment": "^2.11.1",
    "d3": "^3.5.14",
    "angular-simple-logger": "^0.1.7",
    "angular-google-maps": "^2.3.1",
    "angular": "^1.4.9",
    "bootstrap": "^3.3.6",
    "nouislider": "^8.2.1",
    "reset-css": "^2.0.2011012603"
  }
```

With Angular ^1.2, this problem doesn't occur.  Is there a way to get this working with Angular 1.4.9?

**Comment by R0bson** [comment]
Similar problem with Angular 1.5.0 also in $digest cycle.

Working example with angular 1.5.0-rc.2 (tested with previous versions down to 1.4.7 - including mentioned before 1.4.9) - [http://plnkr.co/edit/ZZIGVW63DpeAXGX0wuvP?p=preview](http://plnkr.co/edit/ZZIGVW63DpeAXGX0wuvP?p=preview)
Broken example with angular 1.5.0 [http://plnkr.co/edit/yxnvA4IelHHC8VuJg7K5?p=preview](http://plnkr.co/edit/yxnvA4IelHHC8VuJg7K5?p=preview)
In broken example map and marker show up, but the marker doesn't respond to clicking on map anymore.

Error for map:
```
TypeError: Cannot read property 'exp' of undefined
    at angular-google-maps.js:6911
    at Scope.$digest (angular.js:16664)
    at angular.js:16859
    at completeOutstandingRequest (angular.js:5804)
    at angular.js:6081
```

Error for marker (placing and relocating on click)
```
TypeError: Cannot read property 'exp' of undefined
    at setIfChange (angular-google-maps.js:1990)
    at Scope.$digest (angular.js:16664)
    at angular.js:16859
    at completeOutstandingRequest (angular.js:5804)
    at angular.js:6081
```
[Angular 1.5.0 changelog from last RC](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#150-ennoblement-facilitation-2016-02-05)

**Comment by katagaStyle** [comment]
Same issue here with angular 1.5.

**Comment by robost** [comment]
I'm also experiencing this issue. Angular 1.5, Angular Google Maps 2.3.1.

**Comment by red2678** [comment]
Same here

**Comment by bogusugob** [comment]
+1

**Comment by nmccready** [comment]
Looking into it.
