### ISSUE TITLE
With angular 1.5.0: Error: this.exp undefined

### ISSUE THREAD

**Issue by attilacsanyi** [angular-ui/angular-google-maps#1729]
After upgrading to angular 1.5.0 I got the following error:

`this is undefined Map</Map.prototype.link/</</</<@http://localhost:3000/bower_components/angular-google-maps/dist/angular-google-maps.js:6874:19`

I just use the simplest angular google maps directive:
`<ui-gmap-google-map center="map" zoom="14"></ui-gmap-google-map>`

Thanks

**Comment by nmccready** [comment]
What version ? master or tagged release?

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/2.3.1/dist/angular-google-maps.js#L6874

If this is the real spot then yes this is a broken / removed part of angular that will need to be fixed.

**Comment by nmccready** [comment]
this.exp was a field passed into a watch function letting you know the field of the actual changed values. This was useful if you were using multiple handlers for many watches.

**Comment by mikhail-eremin** [comment]
Got same error, **this** is undefined after upgrading to angular 1.5.0 stable (angular-google-maps  2.3.1)
works with angular 1.5.0-rc.2

**Comment by attilacsanyi** [comment]
Thanks @nmccready I use the latest **1.5.0 angular** an **2.3.1 angular-ggogle-maps** as @mikhail-eremin. Thanks pointing to this.

**Comment by hatemzidi** [comment]
same problem here about 'exp' with angular 1.5.0 :/

**Comment by nmccready** [comment]
Please no more +1 or same heres we know it is a problem. If you want to voice opinions; voice resolutions or a PR. TY

**Comment by nmccready** [comment]
#1728

**Comment by nmccready** [comment]
This is where it broke https://github.com/angular/angular.js/pull/13909

**Comment by nmccready** [comment]
https://github.com/angular/angular.js/commit/1c6edd416b4baad0c8b01148f429eb78e0ad7eaa#diff-44d3307b66bf51b52e110307fa57e196

**Comment by nmccready** [comment]
Anyone else having issues with ngMock /  angular-mocks.js ? Since 1.5 non of the modules of this project can be found.

**Comment by nmccready** [comment]
So specs are borking due to PhantomJS and karma with angular 1.5. I changed the karma config to Chrome and bam specs started working.

**Comment by nmccready** [comment]
https://github.com/angular/angular.js/issues/13794

**Comment by nmccready** [comment]
#1734

**Comment by mikhail-eremin** [comment]
thanks!

**Comment by hatemzidi** [comment]
+1
