### ISSUE TITLE
What is the syntax to trigger searchbox 'places_changed' event programmatically via angular-google-maps?

### ISSUE THREAD

**Issue by RohitRane** [angular-ui/angular-google-maps#1735]
I need to trigger the `places_changed` event of angular-google-maps searchbox programmatically, instead of manually pressing enter. How do I accomplish this?

I tried using the vanilla js solution :

`google.maps.event.trigger(searchbox, 'places_changed');`
But I am unsure of what to send as the first parameter.

This is my markup :

```
<ui-gmap-google-map center='map.center' zoom='map.zoom' draggable="true" options="map.options" control="map.control">
    <ui-gmap-search-box template="searchbox.template" events="searchbox.events" position="'TOP_LEFT'">
    </ui-gmap-search-box>
</ui-gmap-google-map>
```
This is my controller code :

```
$scope.map = { center: { latitude: 45, longitude: -73 }, zoom: 8 }; $scope.map.control = {}; $scope.map.options = { scrollwheel: true };

    var events = {
        places_changed: function(searchBox) {
            console.log("Search Box :", searchBox.getPlaces());
            var location = searchBox.getPlaces();
            console.log("Location :", location[0].geometry.location["G"]);
            var geoKeys = Object.keys(location[0].geometry.location);
            console.log("Keys :", geoKeys);
            $scope.map["center"]["latitude"] = location[0]["geometry"]["location"][geoKeys[0]];
            $scope.map["center"]["longitude"] = location[0]["geometry"]["location"][geoKeys[1]];
            uiGmapIsReady.promise(1).then(function(maps) {
                $timeout(function() {
                    console.log("Map :", $scope.map.control.getGMap());
                    console.log("Bounds :", $scope.map.control.getGMap().getBounds());
                    if (location[0].geometry.viewport) {
                        $scope.map.control.getGMap().fitBounds(location[0].geometry.viewport);
                    } else {
                        $scope.map["zoom"] = 15;
                    }
                    var marker = [{
                        coordinates: {
                            latitude: $scope.map["center"]["latitude"],
                            longitude: $scope.map["center"]["longitude"]
                        },
                        title: location[0]["name"],
                        id: location[0]["id"],
                        icon: location[0]["icon"]
                    }];
                    $scope.randomMarkers = marker;
                    console.log("Random Markers :", $scope.randomMarkers);
                });
                console.info("Google Maps ready", $scope.map);

            });
            //$scope.map.fitBounds(location[0].geometry.viewport);
        }
    }

    $scope.searchbox = {
        template: 'app/user/editProfile/map-search.html',
        events: events
    };
```
Now I need to trigger the "places_changed" event by an` ng-click `from somewhere else in the page. How do I accomplish this?

Thanks in advance.

**Comment by nmccready** [comment]
It is using EventsHelper and you can look at `arguments` to see all that is sent.

https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/api/utils/events-helper.coffee#L26

So it is the originating gObject (searchBox), eventName, model (angular model which is bound to the gObject), aguments (all the original arguments from the original places_changed event)

**Comment by nmccready** [comment]
The click part of the code you ask for is standard angular and you can find that out on google. All you have to do is tie `ng-click="searchbox.events.placesChanged(someArgs)"`

**Comment by RohitRane** [comment]
How do I get this "searchbox" object ?

**Comment by RohitRane** [comment]
I am getting : TypeError: searchbox.events.placesChanged is not a function

**Comment by nmccready** [comment]
Your $scope.events.placesChanged function needs to be in the same scope in which the click event is being called. If you want more specific help you need to make a plnkr.

**Comment by RohitRane** [comment]
ok. Give me some time I'll make a plnkr and share.

**Comment by tharrington** [comment]
did something change with the API? My searchbox no longer returns location coordinates

"geometry": {
      "location": {}
    },
