### ISSUE TITLE
Error: this.j is null while using angular-google-maps Places service

### ISSUE THREAD

**Issue by zapphyre** [angular-ui/angular-google-maps#1740]
please, if you could advice, Ill be thankful :
http://stackoverflow.com/questions/35486972/error-this-j-is-null-while-using-angular-google-maps-places-service

**Comment by nmccready** [comment]
Are you using the minified version. If so don't and get me the error un-minified. Otherwise you might be looking at a google problem.

**Comment by zapphyre** [comment]
not minified:

```
<script src="bower_components/angular-simple-logger/dist/angular-simple-logger.js"></script>
<script src="bower_components/lodash/lodash.js"></script>
<script src="bower_components/angular-google-maps/dist/angular-google-maps.js"></script>
```

but I googled out an example in which the guy is using it so that would support some my local inconsistency

**Comment by nmccready** [comment]
Is there a process to getting the error to occur? I went to the example and saw no such error.

**Comment by zapphyre** [comment]
not in the example... I giving it to you just to demonstrate a contradiction to my case, but I am not aware of any misuses on my side through...

**Comment by nmccready** [comment]
Please make something that is reproducible otherwise I can not help.

**Comment by zapphyre** [comment]
while I was scaffolding an application for you, some good guy has resolved the issue for me. see the SO link in the first post.
Now, I would strongly suggest you to update the documentation to not let anyone run into my track. There is not that much information&usage of this library on net yet.

**Comment by nmccready** [comment]
The project is open source so feel free to PR to the website branch to update the docs.
