### ISSUE TITLE
lodash 4.5

### ISSUE THREAD

**Issue by david-hollifield** [angular-ui/angular-google-maps#1741]
I just went through the process of upgrading to lodash 4.5 and went through the migration guide looking for obsolete functions. Based on lodash's changelog, they removed the isDeep from _.clone (_.cloneDeep) and removed _.object in favor of _.fromPairs. angular-google-maps is still using the old functions. Is this intentional or is this something that needs updated (PR)?

**Comment by nmccready** [comment]
It's intentional as not everyone wants to always jump to the latest versions of everything.  Right now it supports 3.X and 4.X. There is a compatibility file which detects what's missing and polyfills both directions.

**Comment by david-hollifield** [comment]
Are you talking about lodash-migrate as the compatibility file?

**Comment by nmccready** [comment]
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/extensions/lodash.coffee#L18

**Comment by nmccready** [comment]
This swap array.

**Comment by david-hollifield** [comment]
I'm not seeing _.clone in your swap array

**Comment by nmccready** [comment]
Correct I'm pointing you to the code so you can make a PR and add what
needs adding.

**Comment by david-hollifield** [comment]
Ah, gotcha, Consider it done. Thanks!

**Comment by david-hollifield** [comment]
OK, just forked and realized all this is in coffee. This will be a while, if at all, since in these immortal words, "Ain't nobody got time fo dat". It's easier for me to fork and update the js to replace all _.clone(obj, true) with _.cloneDeep(obj) and _.object(kv1, kv2) to _.fromPairs(kv1, kv2). Thanks for your help.
