### ISSUE TITLE
markers with different icons

### ISSUE THREAD

**Issue by fpaboim** [angular-ui/angular-google-maps#1745]
Is it possible to associate different icons with the markers directive? I only managed to find documentation to set the same icon for all markers via the 'options'. The other option would be using ng-repeat with the performance hit..

**Comment by markmssd** [comment]
Assume each of your models have an ```icon``` attribute, you can set the attribute ```icon="'icon'"``` in your html and it should work.

**Comment by fpaboim** [comment]
Worked, thanks a bunch!

**Comment by AnilGoudar** [comment]
@fpaboim Can you please give some examples for the use case?
