### ISSUE TITLE
the best way/timing to call getDrawingManager() function

### ISSUE THREAD

**Issue by nobukichi** [angular-ui/angular-google-maps#1747]
I am going to use ui-gmap-drawing-manager directive for drawing a polygon on the map.
In order to get the event when the polygon is drawn, I need to code something like this:
`
    google.maps.event.addListener($scope.drawingManagerProxy.getDrawingManager(), 'polygoncomplete', function(polygon) {
        console.log( "received polygoncomplete event" );
    });
`
where drawingManagerProxy is given to control attribute of ui-gmap-drawing-manager directive. 
It works fine if I run this code from a button on a page, when everything is fully loaded, but ideally I want to register the event listener without user operation. 

I tried calling this from $scope.$on('$viewContentLoaded', function() {}), but it did not work. I assume the ui-gmap-drawing-manager directive had not set the getDrawingManager function to $scope.drawingManagerProxy object at this timing. Is there any elegant way/timing to register the google maps event listener, other than spinning a timer to keep trying until succeed?

**Comment by nmccready** [comment]
DrawingManagerParentModel is really incomplete/bare and needs to be redesigned. Feel free to rewrite the implementation and make a PR.

**Comment by nobukichi** [comment]
I found the API somewhat strange looking and now fully understand that it is an ad-hoc solution to give us the access to drawing manager. I will have to look into the code and try come up with better API in that area.

**Comment by nmccready** [comment]
:+1:
