### ISSUE TITLE
UI-Router issue on changing routes

### ISSUE THREAD

**Issue by whittssg** [angular-ui/angular-google-maps#1751]
I am having an issue when changing routes with angular ui-router. The map works perfectly when first going to the route with maps but if i change my route (say the homepage) and then go back to the route with the Map, the map is just gray - the mouse still turns to a hand grab icon when you hove over it but the whole thing is gray. If i go to the map, go to homepage then go back to the map and hit the browser refresh then the map will work.. I read a few related issues and most of them said fixed in 2.2 but i am on 2.3. I am using ng-if to show the map when its ready and ng-cloak so that the screen doesnt flash when i first populate it with data (for some reason if i didnt ng-cloak it, the whole screen would sort of flicker when i first provided it with some data).. Any pointer would be appreciated..

Thanks,

**Comment by whittssg** [comment]
Just noticed that if i re size the browser window (once its gone gray) it will start to work again

**Comment by nmccready** [comment]
Yes you must call resize explicitly when you come back to it. This is documented in FAQ and in many common issues similar to this one. In the end it comes down to a google maps issue.

**Comment by whittssg** [comment]
Thanks...

I tried this as suggested in the FAQ:
    $scope.$on('$viewContentLoaded', function () {
            var mapHeight = 500; // or any other calculated value
            $("#my-map .angular-google-map-container").height(mapHeight);
            });
but it just reszies the gray box.. doesnt show the actual map :( 

If this is not a bug do you have a forum or google groups where i can get help please?

Thanks,

**Comment by nmccready** [comment]
Can u make a simple example which anyone can look at to fix? jsfiddle , plnkr etc?

**Comment by whittssg** [comment]
Got it working... 
I had to add a timeout to the scope:

setTimeout(function () {

            $scope.map = {
                center: {
                    latitude: 45,
                    longitude: -73
                },
                pan: true,
                zoom: 2
            };
        }, 100);

Thanks
