### ISSUE TITLE
Custom infowindow on marker click using angularjs google maps

### ISSUE THREAD

**Issue by nitinraodeo** [angular-ui/angular-google-maps#1753]
I am using angularjs google maps and i would like to custom style the infoWindow which is displayed on a marker click. The ui-gmap-window tag does have custom options and it works fine standalone. However when i try to use it inside the markers tag (ui-gmap-markers) - it does not display the custom styled infoWindow on marker click. The plunkr explains the problem clearly.

http://plnkr.co/edit/Mif7wX1eEkwtfAQ93BCI?p=info

**Comment by nmccready** [comment]
As discussed in a few tickets about windows; it is usually not necessary and overkill. Only use it if you really need many windows in memory at once. Otherwise do this simpler approach.

http://plnkr.co/edit/rBP9yAyVn71cw8kcIgdT?p=preview
