### ISSUE TITLE
load function in uiGmapMapScriptLoader factory is never called

### ISSUE THREAD

**Issue by eroak** [angular-ui/angular-google-maps#1754]
I created a project with `angular-google-map` and everything works when i run `grunt serve` but it doesn't work when i run `grunt build` and i don't have any error in the console.

Here is what my `build` task does : `[ 'dom_munger', 'ngtemplates', 'cssmin', 'concat', 'copy', 'htmlmin']`

It seems that the function
```
return function(loader) {
  return loader.load(_this.options);
};
```
https://github.com/angular-ui/angular-google-maps/blob/master/dist/angular-google-maps.js#L158-L160

is never called when i build my project.

**Comment by nmccready** [comment]
Sorry but that is a ton of unknowns. I don't know all the in's and outs of your build tasks. All I can think of is there could be a js minification problem where something is not getting annotated correctly.
