### ISSUE TITLE
what are the default units of radius of circle? and how can it be changed?

### ISSUE THREAD

**Issue by anatlerner** [angular-ui/angular-google-maps#1758]
hi
when setting a circle
 $scope.circle= 
            {
                id: 1,
                center: {
                    latitude: 44,
                    longitude: -108
                },
                radius: 500000,
                stroke: {
                    color: '#08B21F',
                    weight: 2,
                    opacity: 1
                },
                fill: {
                    color: '#08B21F',
                    opacity: 0.5
                },
                geodesic: true, // optional: defaults to false
                draggable: true, // optional: defaults to false
                clickable: true, // optional: defaults to true
                editable: true, // optional: defaults to false
                visible: true, // optional: defaults to true
                control: {}
            }
        

what are the units of radius?

**Comment by nmccready** [comment]
Meters I believe

**Comment by anatlerner** [comment]
is there a way to change the unit?

**Comment by nmccready** [comment]
Look at googles sdk.
