### ISSUE TITLE
Dynamically update and delete markers

### ISSUE THREAD

**Issue by nickgamie** [angular-ui/angular-google-maps#1766]
Hello,

I am working on creating a map with dynamic markers, where the coords are retrieved from a database. I don't have any experience with angularjs. Can anyone provide me with a code example to set me to the right direction.

I currently have a map with one hard coded marker.

Html:

<ui-gmap-google-map
         center='map.center'
         zoom='map.zoom'
         draggable="true"
         options="options">
     <ui-gmap-marker
             coords="marker.coords"
             options="marker.options"
             idkey="marker.id">
     </ui-gmap-marker>
 </ui-gmap-google-map>

Script: 

angular.module('appMaps', ['uiGmapgoogle-maps']).config(function(uiGmapGoogleMapApiProvider) {
  uiGmapGoogleMapApiProvider.configure({
      key: '',
      v: '3.20', //defaults to latest 3.X anyhow
      libraries: 'weather,geometry,visualization'
  });
}).controller('mainCtrl', function($scope) {
      $scope.map = {center: {latitude: 51.219053, longitude: 4.404418 }, zoom: 14 };
      $scope.options = {scrollwheel: false};
  
  $scope.marker = {
    id: 0,
    coords: {
        latitude:  51.219053,
        longitude: 4.404418
    },
    options: {
        draggable: false,
        title: 'The KVK Blog',
        animation: 1 // 1: BOUNCE, 2: DROP

--------------------------------------------------------

Thank you very much

**Comment by markmssd** [comment]
``` angular-google-maps ```'s directives are already "dynamic".

You can have an array, e.g. ```$scope.markers``` with all your markers into it.
Then, use [ui-gmap-markers](http://angular-ui.github.io/angular-google-maps/#!/api/markers) to display them on the map.

Now, whenever you modify elements in your ```$scope.markers``` array, add, update, or delete, it will be reflected on the map automatically.

Hope it helps!
