### ISSUE TITLE
angular-ui.github.io - broken links

### ISSUE THREAD

**Issue by riki343** [angular-ui/angular-google-maps#1771]
On this page http://angular-ui.github.io/angular-google-maps/#!/api/marker-label you have 2 links "marker" and "markers". 
For now links
http://angular-ui.github.io/angular-google-maps/#marker 
and 
http://angular-ui.github.io/angular-google-maps/#markers 
but it should be 
http://angular-ui.github.io/angular-google-maps/#!/api/marker 
and 
http://angular-ui.github.io/angular-google-maps/#!/api/markers

**Comment by nmccready** [comment]
confirmed

**Comment by nmccready** [comment]
Wherever the problem is it begins here [view](https://github.com/angular-ui/angular-google-maps/blob/website/app/views/directive/marker-label.html#L5). Actually I think only the hrefs need to be removed as `ui-sref` is already there. Feel free to PR the fix to the website branch.

**Comment by miparnisari** [comment]
This seems to be fixed, shouldn't it be closed?
