### ISSUE TITLE
Is there a way to use address instead of coordinates.

### ISSUE THREAD

**Issue by arsinawaz** [angular-ui/angular-google-maps#1779]
Is there a way to use address instead of coordinates for centering a map, drawing a circle or add a custom marker. I do not have coordindates, i want to work with addresses, city names, country names and may be postal/zip codes. 

Any help would be appreciated.

**Comment by ZachMoreno** [comment]
Good Morning @arsinawaz,

Angular Google Maps [provides access](http://angular-ui.github.io/angular-google-maps/#!/api/GoogleMapApi) to request & use the [Google Maps JS API Libraries](https://developers.google.com/maps/documentation/javascript/libraries), but does not provide access to the [Google Maps Web Services](https://developers.google.com/maps/web-services/). What you're looking to achieve, covert adresses to lat/long, is possible through use of the The [Geocoding Web Service](https://developers.google.com/maps/documentation/geocoding/intro#Geocoding). My suggestion for you moving forward is to wrap the Geocoding Web Service in an Angular factory or service that you pass an address to and it returns the lat/long. Something like...

```
.factory('GeocoderAPI', ['$scope', '$resource', function($scope, $resource) {
	var endpoint = 'https://maps.googleapis.com/maps/api/geocode/json?address=' + $scope.lookupAddress + '&key=YOUR_API_KEY';

	geocoderAPI = {
		convertToLatLong: $resource(endpoint, {}, {
			query: {
				method: 'GET',
				isArray: false,
				cache: false
			}
		})
	};

	return geocoderAPI;
}]);
```

Then you can inject the `GeocoderAPI` as a dependency of your controller & use it in the following way

```
$scope.lookupAddress = '1600+Amphitheatre+Parkway,+Mountain+View,+CA';

GeocoderAPI.convertToLatLong.query().$promise.then(function(promisedLatLong) {
	$scope.newLatLong = {
		latitude: promisedLatLong.results.geometry.location.lat,
		longitude: promisedLatLong.results.geometry.location.lng
	};
});
```

I have not tested this code, but the concept is whats important. Please let me know how this approach works for you.

**Comment by arsinawaz** [comment]
Thanks
