### ISSUE TITLE
Initial coordinates seem to round for certain numbers triggering change event

### ISSUE THREAD

**Issue by mattdawson** [angular-ui/angular-google-maps#1783]
I think Google maps is actually the cause of this.
When I create a map with certain coorinates e.g. lat=-32, lng=174.820940251555, a change event is triggered and the longitude gets changed to 174.82094025155493
I think an operation is happening in google maps causing the number to change slightly due to rounding on a double.
I work around this by hacking the code to only apply a change if it exceeds 174.820940251555-174.82094025155493=5.684341886080802e-14.  This probably isn't the best solution as it's a mantissa accuracy/rounding issue, not the whole number.

Demo plnkr: http://plnkr.co/edit/D7IwzY2QVrxNurG5oDaW?p=preview

**Comment by mattdawson** [comment]
It's just occured to me the issue may be that google maps tracks the view by bounds, not center and location.  So when it gets center and location it has to convert it to bounds, then do the reverse when you ask for center thus introducing error.  It may be possible to make this not happen by calculating a bounds in AGM that will return the correct center when passed a center.

**Comment by nmccready** [comment]
You might want to try master as this PR was merged. https://github.com/angular-ui/angular-google-maps/pull/1748

Otherwise this is out of scope for me. If you want to dig in and make a PR, I will gladly accept it.

**Comment by mattdawson** [comment]
Tracing into googles minified code I see the longitude is passed into the function below inside new google.maps.LatLng(lat,lng).  It appears to be making sure the lat lng is a bounds, but sadly it's screwing with coordinates even when it doesn't need to due to rounding errors.
```
a= 174.820940251555 (longtitude)
b=-180   (bounds left)
c= 180    (bounds right)
   
_.Ma = function(a,b,c){
  c-=b;        // c=360
  return (
  (a-b)        = 354.820940251555
  %c           = 354.820940251555
  +c)          = 714.8209402515549
  %c           = 354.82094025155493
  +b    //     = 174.82094025155493
};
```

**Comment by mattdawson** [comment]
I've raised a bug with google maps.  I don't believe there's a work around that can be done in AGM.
https://code.google.com/p/gmaps-api-issues/issues/detail?id=9550

**Comment by nmccready** [comment]
Thanks for looking into this deeper. Follow up here (even though closed) and I will re-open it if anything changes.

**Comment by mattdawson** [comment]
The google maps guys say they don't really want to fix it.  But they have told me if you pass true as the 3rd parameter of new google.maps.LatLng that they won't run the rounding function.  Which means you'd have to write/run your own rounding method in agm.

**Comment by mattdawson** [comment]
I've proxied LatLng to solve the issue in my system.
`
google.maps.LatLng_ = google.maps.LatLng;
google.maps.LatLng = function(lat, lng, boundsWrap) {
	// If bounds wrapping parameter is present then proxy arguments exactly, else if bounds will be exceeded then call internal wrapping method
	return new google.maps.LatLng_(lat, lng, boundsWrap!==undefined?boundsWrap:(lat<=180 && lat>=-180 && lng<=180 && lng>=-180));
}
`
