### ISSUE TITLE
Infowindow flickering on mouseover

### ISSUE THREAD

**Issue by leena-bhise** [angular-ui/angular-google-maps#1786]
I am using ui-gmap-google-map to implement map on my application. my code is below :

    <ui-gmap-google-map center="{ latitude: 0, longitude: 0 }" zoom="3" id="scheduler-map" bounds='map.map.bounds' control="map.gmap">
    <ui-gmap-markers ng-if="map.positions" events="markersEvents" models="map.positions" idKey="'p_id'" coords="'position'" options="'options'" click="closeClick; ">
    <ui-gmap-window closeClick="closeClick" options="windowOpt" show="windowOpt.show" templateUrl="'pos-info.html'" templateParameter="windowParams"></ui-gmap-window>
  </ui-gmap-markers>
</ui-gmap-google-map>
template code 

    <div class='popup' ng-class="{'set-width': parameter.isDataPresent}">
      <h5>{{parameter.name}}</h5>
      <b ng-if='parameter.driver'>Driven by</b>
      <div>
       {{parameter.driver.display_name}}
     </div>
     <div class='data-msg' ng-if="parameter.isDataPresent">
       This vehicle may be inactive. We have not received an updated position location from it since    <b>{{parameter.createdAt | date: 'MMM dd HH:mm'}} ({{parameter.createdAt | timeAgo}})</b>
     </div>
    </div>

css : 
     .set-width {
       width: 100px;
     }

Here I applied mouseover / mouseout events on marker to show infowindow. when I hover on marker infowindow flickered. As I noticed it is due to dynamic width (from set-width class).

Please see attached video : https://youtu.be/ag6m97rGrBA

Any suggestion on this.

Thanks in advance.

**Comment by nmccready** [comment]
You might want to look at ngShow or ngifs css animation stuff. That way you can hide the element and stretch it out. So make the element visible only when the width is finished being set in a set time.

**Comment by nmccready** [comment]
https://docs.angularjs.org/api/ng/directive/ngShow
https://docs.angularjs.org/api/ng/directive/ngIf

**Comment by leena-bhise** [comment]
@nmccready  ngShow / ngIf are not useful there. Do you have any other sollution ?

**Comment by nmccready** [comment]
Try this, https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/stylesheets/gwin-size-fix.css#L4-L15

**Comment by nmccready** [comment]
Just make it wider then you need it. If that doesn't help your going to need to make an example and search around.

**Comment by leena-bhise** [comment]
In my case infowindow size vary based on a condition so different infowindows show different content. so height / width varies in that case.

For ex. one infowindow show content of 5 paragraph and another one show a string value so your solution doesn't work.

**Comment by leena-bhise** [comment]
@nmccready  Thanks your solution worked.

**Comment by smiddela** [comment]
Removing ng-cloak from the below html worked for me.

<div layout="column" ng-cloak>
<my infowindow html here>
</div>

**Comment by smiddela** [comment]
Removing ng-cloak from the below html worked for me.

`<div layout="column" ng-cloak>
<my infowindow html here>
</div>
`
