### ISSUE TITLE
Unfocusing a marker doesn’t restore other pins on the map

### ISSUE THREAD

**Issue by madhurigr** [angular-ui/angular-google-maps#1787]
@nmccready  When I clicking a marker multiple times it removes another marker pins from the map and If I do any moment on the map, pins get visible again.

Please see video here : 
https://youtu.be/7in5dKO9eYQ

Is there any fix for this? 

Thanks in advance.

**Comment by nmccready** [comment]
Please make a small example that I can play with.

**Comment by nmccready** [comment]
Need small reproducible example. Closing until this exists.
