### ISSUE TITLE
Bind ng-model and other ng tags to dom element written inside script tag

### ISSUE THREAD

**Issue by Neha140790** [angular-ui/angular-google-maps#1789]
<script type="text/ng-template" id="searchbox.tpl.html">
                    <input type="text" placeholder="Search Box" id="searchBoxDiv" class="form-control" required autofocus />
</script>

This is my code to create a search box in angular google map but now i am not able to attach any ng- tag to this input field such as ng-model, ng-blur, ng-focus....etc

Can anyone help me out how to use compile service for it????? Controller name is 'mapController'

**Comment by kandizzy** [comment]
As of now, only `ng-model` is supported on the input field of the searchbox directive. There is an example of how to implement it in the examples folder.

There's an open issue regarding this issue- if you want to dig in and add this functionality some information can be found there.
https://github.com/angular-ui/angular-google-maps/issues/1702
