### ISSUE TITLE
Google map tiles not rendered properly while dragging

### ISSUE THREAD

**Issue by mohaideenisync** [angular-ui/angular-google-maps#1792]
I have using google map api in angularjs.

If i do dragging, most of times tiles are not loading fully. It showing grey background.

I have refereed some answers in google. They have suggested resize features.

I have tried the following code

`google.maps.event.trigger(map, "resize");`

It is not solving my issue. and i have tried one more event called tilesloaded

but this is also not working.

```
tilesloaded: function (map) {
                $scope.$apply(function () {
                    console.log("tilesloaded")
                    google.maps.event.trigger(map, "resize");
                });
            } 
```

**Comment by nmccready** [comment]
Make an example.

**Comment by nmccready** [comment]
Closing until there is something I can go on.

**Comment by whispers16** [comment]
@mohaideenisync  the same happen for me! did you find any solution??
