### ISSUE TITLE
Error: [$compile:ctreq] Controller 'uiGmapGoogleMap', required by directive 'uiGmapSearchBox', can't be found!

### ISSUE THREAD

**Issue by ermarin** [angular-ui/angular-google-maps#1794]
Hello,

I'm trying to implement the search box, but i get this error when call controller, i'm using angular 1.5.0

![error](https://cloud.githubusercontent.com/assets/8620255/14291018/0c7c3dd0-fb27-11e5-923c-1211fba0721a.PNG)

**Comment by kandizzy** [comment]
Please make an example we can take a look at to help you debug. https://github.com/angular-ui/angular-google-maps/wiki/MCVE

**Comment by nmccready** [comment]
Closing until example exist.

**Comment by TWKDreamState** [comment]
If it helps, I had this same error and it was due to the my putting the <ui-gmap-search-box> directive OUTSIDE of the <ui-gmap-google-map directive>.

**Comment by tahir-jamil** [comment]
well i am using simple map as a demo but its not working 
hear are all the information about the bug please visit
https://github.com/tahir-jamil
