### ISSUE TITLE
How to change mapTypeId ?

### ISSUE THREAD

**Issue by MinaMagdyBoshra** [angular-ui/angular-google-maps#1797]
Please help
when I change map type Id as below
 $scope.options = {scrollwheel: false,mapTypeId: google.maps.MapTypeId.SATELLITE}

throw error

 ReferenceError: google is not defined and map not loaded

**Comment by rhutchison** [comment]
Try this:

```javascript
      uiGmapGoogleMapApi
        .then(function(maps) {
          $scope.options = {
            mapTypeId: maps.MapTypeId.SATELLITE,
            scrollwheel: false
          };
        });
```

**Comment by cthrax** [comment]
@rhutchison that's the correct answer. @MinaMagdyBoshra re-open if you still have issues.
