### ISSUE TITLE
Not Loading From Bower

### ISSUE THREAD

**Issue by funzeye** [angular-ui/angular-google-maps#1800]
Getting an error when loading with bower:
bower angular-google-maps#~2.3.2          ECMDERR Failed to execute "git clone https://github.com/angular-ui/angular-google-maps.git -b 2.3.2 --progress . --depth 1", exit code of #-532462766
Not looking for answer to issue, just thought it might be of interest to you.

**Comment by runderworld** [comment]
@funzeye http://lmgtfy.com/?q=ECMDERR

**Comment by funzeye** [comment]
Ha, very uncool.
Obviously the first thing I did was google it.

**Comment by runderworld** [comment]
@funzeye   snarky remark withdrawn! apologies. 💝
