### ISSUE TITLE
change backgroundColor in options not working?

### ISSUE THREAD

**Issue by evanjmg** [angular-ui/angular-google-maps#1803]
```
<ui-gmap-google-map ng-if="map.toggle" options="map.map.options"  draggable="false"   center="map.map.center"  zoom="map.map.zoom" draggable="true"  bounds="map.map.bounds"events="map.map.events" control="map.map.control" >

vm.map.options: {
				     	backgroundColor: "#2FA799" }
```
I tried to put this in the directive, but it's not changing my background color of my canvas. No errors or anything. Any solutions?

**Comment by rhutchison** [comment]
options doesn't seem to be working at all.  Let me know if you find a solution

**Comment by cthrax** [comment]
Can you create a plnkr demonstrating the issue?

**Comment by evanjmg** [comment]
Sorry for the late reply, today I just got it working today with an !important on the container. - See my plunk -
https://plnkr.co/edit/JqimoHzMNiBO6CmVQ4bi?p=preview   

 However, this not what Google recommends -> http://googlegeodevelopers.blogspot.co.uk/2008/07/wacky-wednesday-change-background-color.html. 

I'll close it for now, but .options.backgroundColor - would work if it was included in the init call
