### ISSUE TITLE
3.0 Discussion - Support for Angular 2.0, migration to Typescript

### ISSUE THREAD

**Issue by veeprox** [angular-ui/angular-google-maps#1831]
Just a quick one to see if anyone else is currently working on a port to Typescript with a goal to support both Angular 2.0 and 1.x, provide type definitions and so on. I'm interested in taking a lead on this if not.

**Comment by nmccready** [comment]
No one in this group currently is. We would love someone to take over.

**Comment by davidpelayo** [comment]
@veeprox please keep us posted with this. I would also like to participate.

**Comment by veeprox** [comment]
@davidpelayo will do, thanks for the offer

What would be the best way to get started on this, do I just create a fork of this repository and work in there? or is there a typescript branch in this current project?

**Comment by DaSchTour** [comment]
There is already somebody working on this
https://github.com/SebastianM/angular2-google-maps

**Comment by nmccready** [comment]
> There is already somebody working on this
> https://github.com/SebastianM/angular2-google-maps
