### ISSUE TITLE
Is it possible to position the zoom +/- buttons?

### ISSUE THREAD

**Issue by derfsubterfuge** [angular-ui/angular-google-maps#1834]
Is it possible to position the zoom +/- buttons?  I would like them to be in the top-right corner, not the bottom left.

Thanks,
Nicholas

**Comment by Danscho** [comment]
Yes, it is. Pass the position in your options object e.g.:

    mapOptions = {
        center: {
            latitude: 0,
            longitude: 0
        },
        zoom: 3,
        options: {
            zoomControl: true,
            zoomControlOptions: {
                position: 3 //=RIGHT_TOP
            }
    }


Whether your map is already loaded you can use [google.maps.ControlPosition](https://developers.google.com/maps/documentation/javascript/controls#ControlPositioning)
or a numeric value:
BOTTOM:11
BOTTOM_CENTER:11
BOTTOM_LEFT:10
BOTTOM_RIGHT:12
CENTER:13
LEFT:5
LEFT_BOTTOM:6
LEFT_CENTER:4
LEFT_TOP:5
RIGHT:7
RIGHT_BOTTOM:9
RIGHT_CENTER:8
RIGHT_TOP:7
TOP:2
TOP_CENTER:2
TOP_LEFT:1
TOP_RIGHT:3
