### ISSUE TITLE
Search box outside the map?

### ISSUE THREAD

**Issue by al095660** [angular-ui/angular-google-maps#1835]
Hi guys, is there any way to have the search box outside the **ui-gmap-google-map** directive? I don't want it inside the map and after several tries i just can't make it. I'd be glad if you can bring me some help.

Thanks!

**Comment by kandizzy** [comment]
You can place the searchbox UI outside the map using `parentdiv`. However, if you just want to use the searchbox with no map at all, that is not possible at this time.

**Comment by al095660** [comment]
@kandizzy I forgot to edit the issue, i tried that a few days ago and worked perfectly. Thanks for the help, though :)

**Comment by netowp** [comment]
@kandizzy Is there a faster way to load the search box outside of the map? I'm using it in a search bar but it only loads when the map is loaded.

**Comment by kandizzy** [comment]
It instantiates when the API is ready
https://github.com/angular-ui/angular-google-maps/blob/master/src/coffee/directives/search-box.coffee#L40

There have been other requests (#1828, for example) to use the search box without the map, but currently this is not possible.
