### ISSUE TITLE
documentation site error angular-google-maps.org

### ISSUE THREAD

**Issue by pdsullivan** [angular-ui/angular-google-maps#1838]
Documentation web page is not loading.

![image](https://cloud.githubusercontent.com/assets/2042218/15199149/ebc6f96e-1790-11e6-8bb4-78d783858d37.png)

**Comment by pkiv** [comment]
Can confirm, also getting this issue.

**Comment by aulsai** [comment]
+1

**Comment by thngdude** [comment]
+1

**Comment by reydtianero** [comment]
+1

**Comment by aleixpellicer** [comment]
+1

**Comment by joele75** [comment]
+1

**Comment by vitorreis** [comment]
+1

**Comment by Wirwing** [comment]
Same problem here. We need to review some items, do you have a backup site?

**Comment by nmccready** [comment]
#1842 dupe
