### ISSUE TITLE
http://angular-google-maps.org OFFLINE

### ISSUE THREAD

**Issue by vitorreis** [angular-ui/angular-google-maps#1840]
The website is returning `ERR_TOO_MANY_REDIRECTS`
```
The angular-google-maps.org page isn’t working

angular-google-maps.org redirected you too many times.
```

**Comment by neelabhsingh** [comment]
Yes, angular-google-maps.org is down. I was also trying since morning..

**Comment by Kuckovic** [comment]
+1

**Comment by aleixpellicer** [comment]
I guess its a duplication of https://github.com/angular-ui/angular-google-maps/issues/1838

**Comment by vitorreis** [comment]
You are right @aleixpellicer I didn't noticed the #1838
