### ISSUE TITLE
Marker icons for clusters not found (404)

### ISSUE THREAD

**Issue by maumig** [angular-ui/angular-google-maps#1841]
Hi,
default url (IMAGE_PATH) of marker icons for clusters are not on the web.

i.e.
http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m1.png

Returns a page with 404 error like this: 
404. That’s an error.

The requested URL /svn/trunk/markerclustererplus/images/m1.png was not found on this server. That’s all we know.

tnx.

**Comment by aabde** [comment]
UP

**Comment by rrisch** [comment]
+1

**Comment by sdko** [comment]
This problem can be fixed by adding a new image path in the clusterOption object

`clusterOptions = {
          imagePath: 'https://raw.githubusercontent.com/googlemaps/js-marker-clusterer/gh-pages/images/m'
      };`
