### ISSUE TITLE
Curl dependencies aren't available any longer

### ISSUE THREAD

**Issue by davidpelayo** [angular-ui/angular-google-maps#1844]
@nmccready See [this issue on the moved google maps tools repo](https://github.com/googlemaps/js-marker-clusterer/issues/59).

None of the following Urls are available:

```json
{
  "devDependencies": {
    "gmap-util-keydragzoom": "http://google-maps-utility-library-v3.googlecode.com/svn/tags/keydragzoom/2.0.9/src/keydragzoom.js",
    "gmap-util-infobox": "http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.13/src/infobox.js",
    "gmap-util-markerclustererplus": "http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.1.1/src/markerclusterer.js",
    "gmap-util-markerwithlabel": "http://google-maps-utility-library-v3.googlecode.com/svn/tags/markerwithlabel/1.1.10/src/markerwithlabel.js",
    "gmap-util-richmarker": "http://google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker.js"
  }
}
```

Therefore this library won't build again, until URLs are changed to the proper ones, or downloaded and used locally.

**Comment by davidpelayo** [comment]
By the way, if you want help, @nmccready, to maintain this repo, feel free to add me in the collaborators list. Thanks.

**Comment by nmccready** [comment]
Yes I was dreading this day on the repos. They have mostly been moved to git. I'll add you to maintainers. I no longer have the time to dedicate to this project. We really need someone to take over. I can give tons of advice. But I can no longer be super active in it.

**Comment by nmccready** [comment]
BTW I will kick on a new release with your recent pulls in hot minute.

**Comment by nmccready** [comment]
That is if it can build :P

**Comment by nmccready** [comment]
@davidpelayo you have been added to write perms. If you stay active I'll make you an admin of angular-google-maps

**Comment by nmccready** [comment]
Well this is pretty darn urgent. I will work on this.

**Comment by nmccready** [comment]
Damn why were not all the projects forked? I am having a hard time tracking them all down.

**Comment by nmccready** [comment]
I will publish the ones that are not anywhere else under my personal repos. I will mark them as not under active dev though. You can still find the source for example.

https://code.google.com/p/google-maps-utility-library-v3/source/browse/tags/keydragzoom/2.0.9/src/keydragzoom.js?r=473

We just can no longer use it a resource via curl. So I will need to re-publish the missing ones (that are no where else) under bower and npm. Fun times

**Comment by nmccready** [comment]
Ok I took care of moving keydragzoom.

https://github.com/nmccready/google-maps-utility-library-v3-keydragzoom

It is published to npm and bower. This project is now a template and it will make the rest of the missing easy to relocate.

**Comment by nmccready** [comment]
infobox done
https://github.com/nmccready/google-maps-utility-library-v3-infobox

markerclusterplus might be [here](https://github.com/googlemaps/js-marker-clusterer)

**Comment by nmccready** [comment]
markerwithlabel - https://github.com/nmccready/google-maps-utility-library-v3-markerwithlabel

**Comment by nmccready** [comment]
richmarker - https://github.com/googlemaps/js-rich-marker

**Comment by nmccready** [comment]
I am not confident that markerclustrerplus was done and only markercluster was.. so onto that. such fun

**Comment by nmccready** [comment]
ok this appears to be the most followed fork of markerclusterplus
https://github.com/mahnunchik/markerclustererplus

**Comment by nmccready** [comment]
It compiles again #cb667cb7b55a607929537a2fd8250613e38e9be3

**Comment by davidpelayo** [comment]
Sorry @nmccready but wasn't available yesterday. Good job!

**Comment by nmccready** [comment]
@davidpelayo https://github.com/googlemaps/v3-utility-library looks like it was all moved here in one spot. This is kind of confusing as some (few) of them have their own repos. 

Also the down side of this repos setup there are no package.json, and bower.json .
