### ISSUE TITLE
Icon for marker clustering does not appear

### ISSUE THREAD

**Issue by DzmitryU** [angular-ui/angular-google-maps#1846]
Hello. I noticed, that recently clustering for markers doesn't work correct.
Here you can see example.
http://plnkr.co/edit/OLH3GnNLEccbOKaHuSwx?p=preview

It can be connected with fact, that MarkerClusterer has moved from https://code.google.com/p/google-maps-utility-library-v3/ to github https://github.com/googlemaps/js-marker-clusterer, but angular-google-maps still contains old link. Would you fix it?
Thanks.

**Comment by marcelo-lopes** [comment]
I'm experiencing the same issue in my website:
<img src="http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m1.png" style="position: absolute; top: 0px; left: 0px; clip: rect(0px, 53px, 53px, 0px);">

GET http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/images/m1.png 404 (Not Found)

**Comment by nmccready** [comment]
yah google is no longer hosting things

**Comment by nmccready** [comment]
see #1844

**Comment by nmccready** [comment]
use raw git and point it to here https://github.com/googlemaps/js-marker-clusterer/tree/gh-pages/images

**Comment by nmccready** [comment]
Closing in favor of #1842 workaround
