### ISSUE TITLE
Docs say "idKey", but should just say "id" 

### ISSUE THREAD

**Issue by stephengardner** [angular-ui/angular-google-maps#1847]
Doc enhancement.  For Map Markers.

http://angular-ui.github.io/angular-google-maps/#!/api/marker says the marker attribute `idKey` must be unique.  
I was setting `idKey` on my markers, and key getting the "no id found" error.  Had to sift through some other examples to finally try calling it just plain old `id`.  Docs should match this exactly, please!

Great module...  Well maintained.  Thank you!

**Comment by nmccready** [comment]
`idKey` is for the directive attribute to not collide with a dom element `id`. Now in the javascript code itself idKey is used to map models to have id's . So the documentation is correct.
