### ISSUE TITLE
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

### ISSUE THREAD

**Issue by jsantana90** [angular-ui/angular-google-maps#1851]
I'm trying to install `meteor add angularui:angular-google-maps` but when I do the command it says:

```
 => Errors while adding packages:             
                                              
While checking for angularui:angular-google-maps@2.3.3:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

I'm using `Meteor 1.3.2.4`.

**Comment by fpaboim** [comment]
Same here. +1

**Comment by rlugge** [comment]
Same here, but when I copy over a statement from another project pegging version 2.3.2, it works properly.

**Comment by jsantana90** [comment]
Hey guys, on meteor 1.3 I was able to follow this tutorial: http://www.angular-meteor.com/tutorials/socially/angular1/google-maps and was able to get google maps working with npm.

**Comment by jsantana90** [comment]
Hey @rlugge I was able to get this working by installing the atmosphere previous package version and adding the google maps api key to angular config https://github.com/angular-ui/angular-google-maps/issues/1887
