### ISSUE TITLE
Map Chopping

### ISSUE THREAD

**Issue by myGitHubForum** [angular-ui/angular-google-maps#1857]
I am using the angular google maps and initially it is rendering fine and able to do zoom, pan etc. But when I route to new view and come back to the current view, the map gets chopped off. Any help would be appreciated.

I will have map object in the scope and trying to re-render that using the center. 
Is there a way to refresh the Map with out updating the map center?

Attached is the screenshot.

![mapchoppingissue](https://cloud.githubusercontent.com/assets/8227363/15407417/588fc220-1dd0-11e6-8872-933a7da7f436.png)

**Comment by nmccready** [comment]
Please look up existing closed issues. This is a google maps resize problem. Also you should be able to find this on stackoverflow.
