### ISSUE TITLE
How to set ControlPosition?

### ISSUE THREAD

**Issue by pacozaa** [angular-ui/angular-google-maps#1883]
I try to use this form to set ControlPosition
> position: 'BOTTOM_LEFT'
 
which I came up like this.

``` 
scrollwheel: false,
zoomControl: true,
zoomControlOptions: {
    position: 'BOTTOM_LEFT'
},
mapTypeControl: true,
mapTypeControlOptions: {
    position: 'BOTTOM_LEFT'
},
streetViewControl: true,
streetViewControlOptions: {
    position: 'BOTTOM_LEFT'
}
``` 

but it make an element hide, then I have to use raw data from [example](https://jsfiddle.net/api/post/library/pure/) and print it out.

> console.log(google.maps.ControlPosition.LEFT_BOTTOM);

which print 6 and I have to do this

> position: '6'

which I came up like this.

``` 
scrollwheel: false,
zoomControl: true,
zoomControlOptions: {
    position: '6'
},
mapTypeControl: true,
mapTypeControlOptions: {
    position: '6'
},
streetViewControl: true,
streetViewControlOptions: {
    position: '6'
}
``` 

This works! but I don't think it is the right way. Please help me :+1: 

EDIT1: This is my error

> angular.js:12520ReferenceError: google is not defined
    at new controller (intro-main.js:50)
    at Object.invoke (angular.js:4523)
    at extend.instance (angular.js:9182)
    at nodeLinkFn (angular.js:8299)
    at angular.js:8572
    at processQueue (angular.js:14792)
    at angular.js:14808
    at Scope.$eval (angular.js:16052)
    at Scope.$digest (angular.js:15870)
    at Scope.$apply (angular.js:16160)

**Comment by eczajk1** [comment]
I use the google maps property directly, which works except that you need to wait for the api to load:

```
uiGmapIsReady.promise(1).then(function () {
  options = {
    mapTypeControlOptions: {
      position: google.maps.ControlPosition.BOTTOM_LEFT
    }
  };
});
```

**Comment by pacozaa** [comment]
@eczajk1 

This is my error

> angular.js:12520ReferenceError: google is not defined
    at new controller (intro-main.js:50)
    at Object.invoke (angular.js:4523)
    at extend.instance (angular.js:9182)
    at nodeLinkFn (angular.js:8299)
    at angular.js:8572
    at processQueue (angular.js:14792)
    at angular.js:14808
    at Scope.$eval (angular.js:16052)
    at Scope.$digest (angular.js:15870)
    at Scope.$apply (angular.js:16160)

**Comment by eczajk1** [comment]
maybe paste your controller code?  or try to send a link for jsfiddle or plunkr

**Comment by pacozaa** [comment]
@eczajk1 It works now. I just forgot to add an arguement `uiGmapIsReady` in controller

Thank you !
