### ISSUE TITLE
Display of Search box results is not proper.

### ISSUE THREAD

**Issue by vjayanth** [angular-ui/angular-google-maps#1886]
I am using angular-google- maps in my angular app.I have integrated successfully in my app. But the problem when i search for any place in search field the results are showing correctly but position of block of results is not proper it is changing according to scroll bar.
I attached screen shot of the issue.
[screen shot](https://drive.google.com/open?id=0B7GU9YcI7DhUTEh5NFZkdHVlQjg)

**Comment by kandizzy** [comment]
@vjayanth this is a CSS issue, the solution will likely vary based on your specific case. There is an example CSS file in `examples` which might provide some guidance https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/stylesheets/search-box-example.css
