### ISSUE TITLE
Modal ng-if not render map correctly

### ISSUE THREAD

**Issue by svkmedia** [angular-ui/angular-google-maps#1888]
I read lot of issues about putting map into modal.
It seems like best solution is to add ng-if to map. But my map is not rendered correctly. I tried also refresh but nothing helped... Any ideas?

![screen shot 2016-07-05 at 01 24 43](https://cloud.githubusercontent.com/assets/8425765/16581377/73975e4a-42a9-11e6-8d1b-cf350d527c7e.png)

`<div class="popup" ng-show="showMap = true">
        <ui-gmap-google-map ng-if="showMap" class="map" center='map.center' zoom='map.zoom' options="map.options"></ui-gmap-google-map>
        <div class="location">
            <div class="address">Columbus, Ohio, Street 21</div>
            <span class="circle">
                <i class="material-icons">place</i>
            </span>
        </div>
    </div>`

`$scope.map = {
        center: {
            latitude: 45,
            longitude: -73
        },
        zoom: 8
    };`

**Comment by eczajk1** [comment]
the idea is delay adding the map until after the modal has had a chance to load.  Set ```showMap``` to true in the next digest cycle:

```
$timeout(function () {
  $scope.showMap = true;
});
```

**Comment by Daniel-t** [comment]
I was dealing with a very similar problem, maps on modals not rendering properly after the first display.   The fix suggested by @eczajk1 work for me.

**Comment by svkmedia** [comment]
Thank you guys I just fixed it with:

`$scope.$watch($scope.mapWatch, function () {
                window.setTimeout(function(){
                    google.maps.event.trigger(map, 'resize');
                },100);

            });`

**Comment by mehanika** [comment]
@svkmedia I think you should close this issue

**Comment by Satish-Lakhani** [comment]
Thanks @eczajk1,
It worked for me.

~Satish

**Comment by victordev** [comment]
Thanks @svkmedia saved my day!!
