### ISSUE TITLE
map markers probably not working

### ISSUE THREAD

**Issue by MattiaPette** [angular-ui/angular-google-maps#1896]
Hi I was recently learning how to set a marker in the map. In the guide over [HERE](http://angular-ui.github.io/angular-google-maps/#!/api/marker) the example should be showing how to do in a proper way but it's not working (at least for me).
Also the plnkr button is not working and Chrome tells me that a popup was blocked. If I chose to unblock the popup, the plnkr page is an empty project.

I don't know if it's a bad behaving of my browser or something else but it shouldn't.
Please tell me if I'm wrong about something that i probably don't know yet (still learning)

OS: win 10 pro 64 bit
Browser: Google Chrome 51.0.2704.103

Screenshot:
![image](https://cloud.githubusercontent.com/assets/3349243/16832389/5b98f792-49aa-11e6-86bb-535881069cfb.png)

**Comment by MattiaPette** [comment]
Was a temporary problem. It's working fine now without doing anything

**Comment by mrkoch** [comment]
Hi, i have just tested map markers and are not working
<img width="1432" alt="screen shot 2016-07-20 at 20 01 55" src="https://cloud.githubusercontent.com/assets/1955615/16997256/f7cebc00-4eb4-11e6-8b03-37f00ec5cd38.png">

**Comment by kintela** [comment]
Hi, I have the same problem. In the demo page I don't see any raddom marker but I put the code in my proyect and the same.
