### ISSUE TITLE
Downloading by npm in Windows

### ISSUE THREAD

**Issue by pablobvch** [angular-ui/angular-google-maps#1923]
Dear GitHub community: 

I'm trying to download the npm package and I got these errors:

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "i" "angular-google-map" "--save"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND proxyurl proxyurl:80
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ServiceProvider\ServiceProvider_Web2\ServiceProvider_WebApp\npm-debug.log

I don't think that it was a problem with my network setting because I can download other packages without problems.. 

Any Idea?

Thank a lot,

Pablo.

**Comment by noherczeg** [comment]
"angular-google-map" is used. There is a missing "s" at the end.

**Comment by pablobvch** [comment]
Thanks, @noherczeg It was a typos, but the original error is:

npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -                                                                                                    -get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child                                                                                                    _process.js:215:5)
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child                                                                                                    _process.js:215:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori                                                                                                    gin.url' }
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config -                                                                                                    -get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child                                                                                                    _process.js:215:5)
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:202:12)
npm WARN addRemoteGit     at emitTwo (events.js:106:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:191:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:852:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child                                                                                                    _process.js:215:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.ori                                                                                                    gin.url' }

 fatal: unable to access 'https:/                                                                                                    /github.com/nmccready/google-maps-utility-library-v3-markerwithlabel.git/': Coul                                                                                                    dn't resolve proxy 'proxyUrl'
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "angular-google-maps" "--save"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code 128

npm ERR! Cloning into bare repository 'C:\Users\pablo\AppData\Roaming\npm-cache\_git-remotes\git-github-com-MikaFima-js-rich-marker-git-0383f4bbdad4ddf154772fedbdd27e464600e943-e7abb722'...
npm ERR! fatal: unable to access 'https://github.com/MikaFima/js-rich-marker.git/': Couldn't resolve proxy 'proxyUrl'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ServiceProvider\ServiceProvider_Web2\ServiceProvider_WebApp\npm-debug.log


Last Time, I did this:
https://github.com/angular-ui/angular-google-maps/issues/1854
But I had a lot of problems so, I had to re-install git bash

Cheers,

Pablo.

**Comment by noherczeg** [comment]
@pablobvch So you fixed it, or it still does not work?

**Comment by pablobvch** [comment]
it doesn't work either.

**Comment by damountie** [comment]
Try version 2.3.2. I myself can't install any later version.

**Comment by damountie** [comment]
My assumption is that this may have arisen here https://github.com/angular-ui/angular-google-maps/commit/cb667cb7b55a607929537a2fd8250613e38e9be3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R81

**Comment by pablobvch** [comment]
I didn't remember that issue, but I resolved it. Thanks for your comments.
