### ISSUE TITLE
Webpack Commonjs support

### ISSUE THREAD

**Issue by sibelius** [angular-ui/angular-google-maps#1929]
issue https://github.com/angular-ui/angular-google-maps/issues/1633 is still valid!

this package should add properly support to commonjs / webpack
- take a look on this PR - https://github.com/lorenzofox3/Smart-Table/pull/429)

``` js
require('./angular-google-maps');
module.exports = 'uiGmapgoogle-maps';
```
- and this blog post - http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support

when I try to use angular-google-maps

`import uiGmapgoogleMaps from 'angular-google-maps';`

I'm getting this error

`ReferenceError: _ is not defined`

this makes sense, as lodash (_) is not in my global scope, as I'm using webpack (import from / require)

angular-google-maps should also do not require lodash from global scope (it is bad to polute global)

it is also a good idea to move from coffescript to ES6

**Comment by tocology** [comment]
Is there any change for this issue?
I have a plan to use this angular-google-maps with webpack.

Please notify me any about that.

**Comment by stephengardner** [comment]
Any update here?

**Comment by kuhnroyal** [comment]
Also running into this, any workarounds?

**Comment by sibelius** [comment]
I've moved to React, and works fine \o/

**Comment by devotis** [comment]
I had the `_` problem too. Here my `webpack.config.js` with the parts that fixed it for me.

```javascript
const path = require('path')
const webpack = require('webpack')

module.exports = {
  entry: './app/app.module.js',
  output: {
    ...
  },
  module: {
    ...
  },
  resolve: {
      // this tells Webpack where actually to find lodash because you'll need it in the ProvidePlugin
      alias: {
          lodash: path.resolve( __dirname, './node_modules/lodash'),
      },
      ...
  },
  plugins: [
      // this tells Webpack to provide the "_" variable globally in all your app files as lodash.
      new webpack.ProvidePlugin({
          _: "lodash",
      }),
      ...
  ]
}
```

**Comment by devotis** [comment]
As for the problems with importing angular-google-maps, I've created a lightweight fix: https://github.com/angular-ui/angular-google-maps/pull/2008
