### ISSUE TITLE
Installing failed for Meteor 1.4.0.1 using meteor npm

### ISSUE THREAD

**Issue by fidelsam1992** [angular-ui/angular-google-maps#1931]
C:\Users\Fidel Kaldas\socially>**meteor npm install --save angular-google-maps**
npm ERR! git submodule -q update --init --recursive: fatal: 'submodule' appears
to be a git command, but we were not
npm ERR! git submodule -q update --init --recursive: able to execute it. Maybe g
it-submodule is broken?
npm ERR! git submodule -q update --init --recursive:
npm ERR! git submodule -q update --init --recursive: fatal: 'submodule' appears
to be a git command, but we were not
npm ERR! git submodule -q update --init --recursive: able to execute it. Maybe g
it-submodule is broken?
npm ERR! git submodule -q update --init --recursive:
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\Fidel Kaldas\\AppData\\Local\\.meteor\\packages\\meteo
r-tool\\1.4.0-1\\mt-os.windows.x86_32\\dev_bundle\\bin\\node.exe" "C:\\Users\\Fi
del Kaldas\\AppData\\Local\\.meteor\\packages\\meteor-tool\\1.4.0-1\\mt-os.windo
ws.x86_32\\dev_bundle\\lib\\node_modules\\npm\\bin\\npm-cli.js" "install" "--sav
e" "angular-google-maps"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true submodule -q update --init -
-recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Fidel Kaldas\socially\npm-debug.log

**Comment by damountie** [comment]
Try version 2.3.2. I myself can't install any later version.

**Comment by nmccready** [comment]
I haven't published meteor as it could not get it to work. I am not too knowledgeable in meteor to spend that much time in it. I will give it another shot.

**Comment by nmccready** [comment]
Publish script is here https://github.com/angular-ui/angular-google-maps/blob/master/scripts/publish

**Comment by nmccready** [comment]
I finally found my username pass combo. Anyway I am publishing 2.4.0. I will try and figure out how to pub old versions

**Comment by nmccready** [comment]
I asked the question on gitter and it seems it is not possible to back publish 2.3.4. Sorry for the problem, but take it up with meteor.

**Comment by fidelsam1992** [comment]
Thank you ! It solved my issue !

**Comment by vrfox** [comment]
Add git/bin to the path... you need sh.exe
