### ISSUE TITLE
Spider-clustered marker should be discernible from single marker

### ISSUE THREAD

**Issue by werdnanoslen** [angular-ui/angular-google-maps#1939]
## Version
2.3.4

## Test Case
[https://jsfiddle.net/twgoye6e/](https://jsfiddle.net/twgoye6e/)

## Steps to reproduce
Create a spider cluster of markers

## Expected Behavior
To be able to discern between a click/tap on an spider-clustered marker and an individual marker

## Actual Behavior
A spider-clustered marker is also itself a marker, rendering a click event on a spider-clustered marker useless/duplicated when the user intends to click on one marker within that cluster.

Issue in my project repo: https://github.com/werdnanoslen/gleanhub/issues/20

**Comment by werdnanoslen** [comment]
This might also be related to https://github.com/angular-ui/angular-google-maps/issues/1898

**Comment by skortchmark9** [comment]
if you're using spiderfy all markers become 'spiderfy' markers, even if they are not in a cluster. So if you use the `typeEvents` instead of the regular `events` you can use spiderfy's click listener, i.e.

```
<ui-gmap-markers typeEvents="events">

events = {
    click: function() {console.log('i am fired when you click an isolated marker')}
    spiderfy: function() { console.log('i am fired when you click a marker that expands into a cluster)}
}
```

**Comment by werdnanoslen** [comment]
aw man, how did I not realize this... thanks!
Here's an updated fiddle for posterity: https://jsfiddle.net/twgoye6e/2/
