### ISSUE TITLE
Getting data in/out of event click

### ISSUE THREAD

**Issue by sam-sharkey** [angular-ui/angular-google-maps#1946]
I am using a scaffolding generated by yeoman (angular-fullstack) and the setup for the webpage is different to most of the examples on this repository. I am pretty new to development so I don't really know what I am doing, but anyways I am having trouble getting data in and out of a click event on the google maps api.

Here is my javascript code : 

```
export class MapComponent {
  $http;
  socket;
  center;
  zoom;
  event;

constructor($http, $scope, socket) {
    this.$http = $http;
    this.socket = socket;
    $scope.$on('$destroy', function() {
      socket.unsyncUpdates('map');
    });
  }

  $onInit() {
    this.center= { latitude: 45, longitude: -73 };
    this.zoom= 8;
    this.event = {
       click: function(mapModel, eventName, originalEventArgs) {
            console.log("user defined event: " + eventName, mapModel, originalEventArgs);
            console.log(originalEventArgs[0]);
            var e = originalEventArgs[0];
            console.log(e);
            this.center = {e.latitude, e.longitude};
        }
     }
  }

}

export default angular.module('codeApp.map', [uiRouter,'nemLogging',
    'uiGmapgoogle-maps'])
  .config(routes)
  .component('map', {
    template: require('./map.html'),
    controller: MapComponent
  })
  .name;
```

And HTML:

```
<ui-gmap-google-map center='$ctrl.center' events = "$ctrl.event" zoom='$ctrl.zoom'>
		<ui-gmap-markers models="$ctrl.alertMap" coords="'self'" fit='true' icon="'icon'" events="$ctrl.event">
        </ui-gmap-markers> 
</ui-gmap-google-map>
```

Everything works until the "this.center = {e.latitude, e.longitude};" statement, I get an error saying that "this" is undefined. It's because "this" is only defined outside of the click function, so my question is, how can I get data out of this function so as to be able to edit the map based on the user clicking on a marker?

**Comment by markmssd** [comment]
Try this:

```
  $onInit() {
    var self = this; // <--
    this.center= { latitude: 45, longitude: -73 };
    this.zoom= 8;
    this.event = {
       click: function(mapModel, eventName, originalEventArgs) {
            console.log("user defined event: " + eventName, mapModel, originalEventArgs);
            console.log(originalEventArgs[0]);
            var e = originalEventArgs[0];
            console.log(e);
            self.center = {e.latitude, e.longitude};
        }
     }
```
Then call self.center = {e.latitude, e.longitude};

Let me know if it works!

**Comment by sam-sharkey** [comment]
You rock man! Thanks for the help! Just wondering, why does this change anything?

**Comment by davidpelayo** [comment]
@sam-sharkey "this" is being saved in a different variable so then later you can set its center values. The reason why it didn't work for you is that when the click handler function is executed, the value of "this" is different than the one you thought.

You can do either what @markmssd suggested or bind the click handler function context value to the one at the moment when its declared, like follows:

```javascript
  // without - var self = this
  this.event = {
    click: function(mapModel, eventName, originalEventArgs) {
      var e = originalEventArgs[0];
      this.center = {e.latitude, e.longitude};
     }.bind(this)
  }
```
