### ISSUE TITLE
How to turn off drawing manager?

### ISSUE THREAD

**Issue by marioscience** [angular-ui/angular-google-maps#1975]
Hello, I am using <ui-gmap-free-draw-polygons ...> directive to draw on the map. However, I can't find a way to turn off the drawing in the case that the drawing doesn't happen. 

To reproduce the issue you start the drawing by calling the function in the draw attribute and then... yeah, how do I cancel it without drawing. 

I was looking in the source code for the directive and it appears that the directive grabs the maps and directly adds mousemove and mousedown listeners for the drawing. I tried to remove the listeners from the map but no luck. 

Any ideas please?

I will try to make a plunker reproducing the issue and post it here in a little bit.

**Comment by marioscience** [comment]
I made this simple plunker. http://plnkr.co/edit/FCeTBhgnHsmlnKP8gB1c?p=preview
While doing it I realized that it is just a small drawing demo. 

@nmccready I would really appreciate a hint or if you could point me to a solution. 

Thanks for a wonderful directive by the way. you rock! 💃

**Comment by marioscience** [comment]
Nvm, solved it by turning off the 'mousedown' event on the map and restoring the dragging functionality and other options. This is my code, for anyone facing this issue:

```javascript
google.maps.event.clearListeners(this.mapInstance.getDiv(), 'mousedown');

var mapOptions = {
         draggable: true,
         disableDefaultUI: false,
         scrollwheel: true,
         disableDoubleClickZoom: true
};

this.mapInstance.setOptions(_.extend(mapOptions, this.mapOptions));
```

Basically, the answer was in the code itself, I just reverse engineered it. (dang, I'm such a hacker!(no, jk))

**Comment by nmccready** [comment]
Thanks for digging.
