### ISSUE TITLE
Problem Creating Multiple Markers.

### ISSUE THREAD

**Issue by ph3l1x** [angular-ui/angular-google-maps#1984]
I am having the hardest time getting my angular project to display multiple map markers. I have a service called retsAPI where I am querying a local MLS  database for home listings. I am trying to display these items on a google mapes. Here is my controller.

```
    function retsMapController($scope, uiGmapGoogleMapApi, uiGmapIsReady, retsAPI) {
    $scope.map = {
        center: {
            latitude: 43.6376107,
            longitude: -116.314943
        },
        zoom: 10
    };
    $scope.options = {
            scrollwheel: false,
            streetViewControl: false,
            mapTypeControl: false,
            scaleControl: false,
            rotateControl: false,
            zoomControl: false
    };

    $scope.markers = [];
    uiGmapIsReady.promise()
        .then(function (instances) {
            console.log(instances[0].map);
        })
        .then(function () {
            retsAPI.default().success(function(result) {
                $scope.results = result;
                var i = 0;
                   result.forEach(function(item) {
                       $scope.markers.push({
                          id: Date.now()+i,
                           coords: {
                               latitude: item['LMD_MP_Latitude'],
                               longitude: item['LMD_MP_Longitude']
                           }
                       });
                   i++;
                });
                console.log("MARKER: ", $scope.markers);
        });


    });
    uiGmapGoogleMapApi.then(function (maps) {
        angular.extend($scope.map, {
            options: {
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                zoomControlOptions: {
                    style: google.maps.ZoomControlStyle.LARGE,
                    position: google.maps.ControlPosition.LEFT_CENTER
                }
            }
        });
    });
```

Here is my HTML file.

```
    <div id="real_angular" ng-controller="retsMap" ng-app="real_angular">
    <div rets-search-form></div>
    {{ markers }}
    <ui-gmap-google-map
        ng-if="map.center"
        center='map.center'
        zoom='map.zoom'
        options='options'
        refresh="true">
        <ui-gmap-markers
            models="markers"
            coords="'self'"
            icon="'icon'">
        </ui-gmap-markers>
    </ui-gmap-google-map>
```

and this is the result of $scope.markers

`[{"id":1481596995980,"coords":{"latitude":"43.7335624694824","longitude":"-116.400283813477"}},{"id":1481596995981,"coords":{"latitude":"44.9327393","longitude":"-116.0692291"}},{"id":1481596995982,"coords":{"latitude":"44.846809387207","longitude":"-116.179756164551"}},{"id":1481596995983,"coords":{"latitude":"44.0762062072754","longitude":"-116.978248596191"}},{"id":1481596995984,"coords":{"latitude":"44.6780061721802","longitude":"-116.120807826519"}},{"id":1481596995985,"coords":{"latitude":"44.8671951293945","longitude":"-116.026954650879"}},{"id":1481596995986,"coords":{"latitude":"43.0574607849121","longitude":"-114.13264465332"}},{"id":1481596995987,"coords":{"latitude":"43.7259407043457","longitude":"-116.800910949707"}},{"id":1481596995988,"coords":{"latitude":"42.55171340147","longitude":"-114.460141584277"}},{"id":1481596995989,"coords":{"latitude":"44.3812294006348","longitude":"-115.982734680176"}},{"id":1481596995990,"coords":{"latitude":"42.9506072998047","longitude":"-115.298492431641"}},{"id":1481596995991,"coords":{"latitude":"42.5505142211914","longitude":"-114.454963684082"}},{"id":1481596995992,"coords":{"latitude":"43.677565","longitude":"-116.0496032"}},{"id":1481596995993,"coords":{"latitude":"44.2447853088379","longitude":"-116.953323364258"}},{"id":1481596995994,"coords":{"latitude":"43.5853805541992","longitude":"-116.189315795898"}},{"id":1481596995995,"coords":{"latitude":"43.6678466796875","longitude":"-116.680221557617"}},{"id":1481596995996,"coords":{"latitude":"43.6502661556005","longitude":"-116.251468285918"}},{"id":1481596995997,"coords":{"latitude":"43.6551094055176","longitude":"-116.685394287109"}},{"id":1481596995998,"coords":{"latitude":"44.5916213989258","longitude":"-116.669593811035"}},{"id":1481596995999,"coords":{"latitude":"42.6074829101563","longitude":"-114.768821716309"}}]`

it also appears that i have lost my google controls. I am not sure what happened to make those disappear.

**Comment by markmssd** [comment]
My guess is that in
```
<ui-gmap-markers
            models="markers"
            coords="'self'"
            icon="'icon'">
        </ui-gmap-markers>
```
```coords="'self'"``` should instead be ```coords="coords"```

'self' means the coordinates are at the "root" level of your object, but yours are in the "coords" property.

Let me know it it fixes it!

**Comment by ph3l1x** [comment]
Thanks for the response. I tried adding coords="markers" with no luck.. All of my coords are inside $scope.markers

**Comment by markmssd** [comment]
Your objects look like this:
 ```
{"id":1481596995996,
  "coords": {
    "latitude":"43.6502661556005",
    "longitude":"-116.251468285918"}
}
```
So you have your coords in "coords", try setting coords="coords"!

**Comment by ph3l1x** [comment]
When using coords="coords" I receive this.
```
MarkersParentModel: no valid coords attribute found
String {0: "U", 1: "n", 2: "a", 3: "b", 4: "l", 5: "e", 6: " ", 7: "t", 8: "o", 9: " ", 10: "c", 11: "o", 12: "n", 13: "s", 14: "t", 15: "r", 16: "u", 17: "c", 18: "t", 19: " ", 20: "I", 21: "M", 22: "a", 23: "r", 24: "k", 25: "e", 26: "r", 27: "P", 28: "a", 29: "r", 30: "e", 31: "n", 32: "t", 33: "M", 34: "o", 35: "d", 36: "e", 37: "l", 38: " ", 39: "d", 40: "u", 41: "e", 42: " ", 43: "t", 44: "o", 45: " ", 46: "i", 47: "n", 48: "v", 49: "a", 50: "l", 51: "i", 52: "d", 53: " ", 54: "s", 55: "c", 56: "o", 57: "p", 58: "e", length: 59, [[PrimitiveValue]]: "Unable to construct IMarkerParentModel due to invalid scope"}

TypeError: Cannot read property 'gManager' of undefined
    at Object.fn (angular-google-maps.js?oi3sy6:7142)
    at Scope.$digest (angular.js?v=1.3.4:14129)
    at angular.js?v=1.3.4:14325
    at completeOutstandingRequest (angular.js?v=1.3.4:4858)
    at angular.js?v=1.3.4:5231
```

Also receive same error when trying coords="markers.coords"

**Comment by ph3l1x** [comment]
Why does coords and models property need to be the same? Don't the coords and ID object get passed into the models attribute?

**Comment by ph3l1x** [comment]
ok I see that coords attribute is to point to the property in the object that contains the lat and long. However I am doing so. I have managed to fixed the error messages however I am not getting any markers on the map.

**Comment by ph3l1x** [comment]
I mis understood the documentation. I was able to get this figured out properly. Thanks markmssd

**Comment by markmssd** [comment]
Just by curiosity, what was the issue at the end? :)

**Comment by ph3l1x** [comment]
Well I didn't realize until reading the documentation closer that the 
property for coords was supposed to be the property inside your model 
that contained the coords. I was thinking it was supposed to be its own 
object. And to remove those errors that I was receiving I needed to make 
sure that

$scope.markers = [];

was above some of my code. Wasn't getting set first it seems is what 
caused those other weird error messages I was receiving.

Thank you for your help! I am a little new to Angular.
