### ISSUE TITLE
angular-google-maps fails when upgrading to Angular 1.6.x 

### ISSUE THREAD

**Issue by bjornharvold** [angular-ui/angular-google-maps#1989]
## Version
2.4.0

## Steps to reproduce
* Use Angular 1.6.x as it deprecates $http.get().success
* Load a searchbox or anything that uses the deprecated method

## Expected Behavior
* Searchbox should display

## Actual Behavior
* Stacktrace saying $http.get(...).success is not a function

Use .then() instead. Easy fix.

**Comment by bjornharvold** [comment]
@nmccready mentioned :-) Happy new year!

**Comment by anteriovieira** [comment]
Hi @bjornharvold , can you give us an example of the code you are using?

If possible add your example to the [plnkr.co](http://plnkr.co).

**Comment by nmccready** [comment]
@anteriovieira he is correct `.success` has been removed. It should be removed from the codebase on `$http`.

**Comment by anteriovieira** [comment]
ok, I'll do it as soon as possible.

**Comment by bjornharvold** [comment]
Thank you guys!

**Comment by bjornharvold** [comment]
Can you please do a 2.4.1 release for this?

**Comment by anteriovieira** [comment]
@nmccready I sent a [pull request](https://github.com/angular-ui/angular-google-maps/pull/1991/files) with the release build 2.4.1

**Comment by bjornharvold** [comment]
Thank you much!

**Comment by nmccready** [comment]
Published to npm, and bower / git. I did not publish for meteor as it is a pain in the ass.

**Comment by nmccready** [comment]
Published Meteor, found my pass 2.4.1 is on atmosphere
