### ISSUE TITLE
Can I use this in Angular 4? 

### ISSUE THREAD

**Issue by dexter-nunag** [angular-ui/angular-google-maps#2020]
Can I use this in Angular 4? If yes, I kindly need a simple guide for it. Thanks in advance.

**Comment by DaniloThiago** [comment]
I'd like to know too

**Comment by dgpoo** [comment]
i want to know also

**Comment by dgpoo** [comment]
recently i didnt find any solution for angular 4 for google street view and view direction,so i found solution to use iframe. you set map coding in seperate file and call it into iframe

**Comment by mcottingham** [comment]
Are there any updates on this?  This looks like a handy library, I would love to see it available for version 2-5 of angular.

**Comment by pbrain19** [comment]
you guys should try https://angular-maps.com

**Comment by nmccready** [comment]
i seriously doubt it
