### ISSUE TITLE
[question] Testing angular-google-maps apps: mocking the module google-maps

### ISSUE THREAD

**Issue by LeandroLovisolo** [angular-ui/angular-google-maps#270]
Hi all,

I'm trying to test a single-module application which lists `google-maps` as one of its dependencies. I'm using the Karma test runner. All the required dependencies are included in my `karma.conf.js` file.

Right now I'm getting the following error message:

```
Uncaught ReferenceError: google is not defined
    at /home/leandro/myproject/app/bower_components/angular-google-maps/dist/angular-google-maps.js:5089
```

I'm guessing this is because the google maps API code isn't being loaded in the browser.

So my question is: what is the recommended way to test a module that depends on `google-maps`? Should I mock the module `google-maps` or is there a simpler way to do this?

I'm using angular-google-maps 1.0.9.

Thanks.

**Comment by ScottieR** [comment]
Old thread, but in case someone needs it I created a more detailed mock for anyone using more parts of the Google API (placesService, etc), and reiterated the steps above that get things working: https://github.com/ScottieR/angular-google-maps-mock

**Comment by cold-gin** [comment]
@ScottieR - Bro, thank you! :+1:
