### ISSUE TITLE
Dynamic height issue + fix

### ISSUE THREAD

**Issue by ashconnell** [angular-ui/angular-google-maps#287]
Just a heads up your FAQ for dynamically setting the height of the map doesn't work as intended, it sets the div correctly but the map only renders partially to those dimensions.

If users want to they can set up a wrapper div with the right dimensions they want, and position relative it. They can then add:

`.angular-google-map-container { height:100%; width:100%; position:absolute; top:0; left:0; }`

which will make it work correctly

**Comment by marthinal** [comment]
Hi guys I'm not using angular-google-maps but using Ionic and gmaps.

I was working a little bit on it and fixed my problem with "height" by changing the height for .scroll class(ionic.css). In my case to 80%.
 By default the map inherits the height from this class when you add the map inside <ion-content>

Interesting link http://econym.org.uk/gmap/basic19.htm
Hope it helps.
Cheers!

**Comment by FrancescoMussi** [comment]
God bless you! After crashing my head against the wall to get the height work properly in my Ionic app fixing .scroll made the trick!
This is how it works for me:

 .scroll {
     height: 100%;
 }

.angular-google-map-container { 
	height:100%; 
	width:100%; 
	position:absolute; 
}

**Comment by f0ntana** [comment]
yeap in my case solution:

.scroll {
    height: 100%;
}
#map {
    width: 100%;
    height: 100%;
}

**Comment by nebulr** [comment]
This helped a lot in addition I thought I might add what I found worked : 
I had a nav bar that had 4em height and a sub nav bar with 64px height

```
.map-wrapper {
  position: relative;
  height: calc(100vh - 4em - 64px);
}

.angular-google-map-container {
  position: absolute;
  top: 0;
  bottom: 0;
  right: 0;
  left: 0;
}
```
with html

```
  <div class="map-wrapper">
      <ui-gmap-google-map> ...</ui-gmap-google-map>
  </div>
```
