### ISSUE TITLE
Click event does not seem to work with <markers>

### ISSUE THREAD

**Issue by lastzero** [angular-ui/angular-google-maps#288]
I'm working with angular-google-maps 1.0.13 and could not get the click event working with markers: 

```
<markers models="jobs"
doCluster="map.cluster"
clusterOptions="map.clusterOptions"
fit="map.fitMarkers"
click="selectJob"
coords="'self'">
</markers>
```

$scope.selectJob() was never called when clicking a marker.

Additionally, it would be good to know (didn't find that in the documentation), if the selected model is passed to the event handler.

Adding multiple markers with ng-repeat works as expected (but the cluster and fit options don't seem to be available here):

```
<marker ng-repeat="job in jobs"
coords="job"
click="selectJob(job)">
</marker>
```

**Comment by santukumar2017** [comment]
please comment 
animation/draggable = true
or animation = "DROP"

then it will work
