### ISSUE TITLE
Show label on marker hover

### ISSUE THREAD

**Issue by thetom88** [angular-ui/angular-google-maps#290]
Hello everyone and thank you for your amazing work.
I'm having a problem in setting a label each marker that appears on marker mouseover.
I tried with adding a hover property to the each marker =false, then I attached an event handler on each marker on mouseover and mouseout that should toggle this property. unfortunately the marker passed in the event handler function is not the same as my marker model, but google's marker instead. Do you know how may I create marker label that appear on marker hover? thank you!

**Comment by Renader** [comment]
I'd love to hide my label too. I need my label only to show if the users mouse is over the marker. Any ideas how to do so? I've found this but i dont know how to connect it to my icon. http://jsfiddle.net/doktormolle/m6wazLrf/
