### ISSUE TITLE
Bug with ng-show?

### ISSUE THREAD

**Issue by ghost** [angular-ui/angular-google-maps#291]
Hi! 
I want to show / hide the map with an ng-show. 
When true, the map shows up but almost all of it is gray and I can't use it...
I have set the refresh option to true as said in the doc.
![capture decran 2014-03-01 a 17 21 27](https://f.cloud.github.com/assets/6690983/2301840/0f7d4558-a15e-11e3-820d-419f7405191c.png)

Any idea?

Thanks in advance

HD.

**Comment by super-coder** [comment]
How do I trigger resize event manually?

**Comment by spacebiscuit** [comment]
ng-if only made matter worse for me:

Uncaught TypeError: Cannot read property 'firstChild' of null

You have included the Google Maps API multiple times on this page. This may cause unexpected errors.
