### ISSUE TITLE
Rotating a marker

### ISSUE THREAD

**Issue by JerryBels** [angular-ui/angular-google-maps#295]
Hello !

So I can't find a way to customize css on the marker : http://angular-google-maps.org/api#marker

I would like to be able to rotate the marker so I can use it for the user's arrow "you are here" and rotate according to compass of the device.

Is this possible ? I succeeded to do it by exploring the code in Chrome inspector and manually adding it to the final div element...

thanks !

**Comment by marcosplisboa** [comment]
I'm need rotate marker SVG in google Maps.. help me!!!

**Comment by viztastic** [comment]
@kbowerma that was really helpful, thanks. (I know this is two years later...)

**Comment by devotis** [comment]
Check out this answer: http://stackoverflow.com/a/29411992/1385429
It worked for me instantly.
