### ISSUE TITLE
Is it possible to make the maps height 100%? 

### ISSUE THREAD

**Issue by CodisRedding** [angular-ui/angular-google-maps#309]
I'd like to fit the map to the browsers height and width but 100% doesn't work. I've set html and body to 100% height no margin as well. Any ideas?

**Comment by escapedcat** [comment]
fyi you can also check the official example:
http://angular-ui.github.io/angular-google-maps/views/examples/base/base.html?example=google-map
See `<style>` tag in `<head>`:

```html
<style type="text/css">
        html, body, #map_canvas {
            height: 100%;
            width: 100%;
            margin: 0px;
        }

        #map_canvas {
            position: relative;
        }

        .angular-google-map-container {
            position: absolute;
            top: 0;
            bottom: 0;
            right: 0;
            left: 0;
        }
</style>
```

**Comment by cyrixmorten** [comment]
I got the full width/height working, but now I have problems using maps in other places of my site where I do not want fullscreen.

Is there any way of doing this without affecting .angular-google-map-container for the whole site?

**Comment by cthrax** [comment]
Instead of using a blanket .angular-google-map-container, you can use more specific selectors ".my-map1 .angular-google-map-container" ".my-map2 .angular-google-map-container" etc...

**Comment by cyrixmorten** [comment]
Arh of course! Thought I already tried that but gave it a second shot and works like a charm.

**Comment by jawadahmadd** [comment]
@escapedcat you are a life saver man. God Bless you.

**Comment by nebulr** [comment]
This helped a lot in addition I thought I might add what I found worked : 
I had a nav bar that had 4em height and a sub nav bar with 64px height

```
.map-wrapper {
  position: relative;
  height: calc(100vh - 4em - 64px);
}

.angular-google-map-container {
  position: absolute;
  top: 0;
  bottom: 0;
  right: 0;
  left: 0;
}
```
with html

```
  <div class="map-wrapper">
      <ui-gmap-google-map> ...</ui-gmap-google-map>
  </div>
```

**Comment by Cdvalencia** [comment]
.angular-google-map-container {
    height: 400px !important;
}
