### ISSUE TITLE
[post 1.1] polyline & polygon directives: add support for GeoJSON MultiLineString & MultiPolygon object types.

### ISSUE THREAD

**Issue by rickhuizinga** [angular-ui/angular-google-maps#319]
MongoDB 2.6 will introduce support for additional GeoJSON data types: MultiPoint, MultiLineString & MultiPolygon.

The polyline & polygon directives should be upgraded to support these GeoJSON types so that it continues to remain easy to dump MongoDB geospatial query results directly into angular-google-maps.

I volunteer to implement this enhancement around the time that MongoDB 2.6 is released. Please assign this issue to me.

**Comment by nmccready** [comment]
@rickhuizinga feel like adding this to 2.1?

**Comment by yadongzhu** [comment]
@rickhuizinga  hi, does the Multipolygon works now, I tried the build "angular-google-maps 2.1.0-X.10 2015-04-16" but seems still not work yet?

**Comment by yadongzhu** [comment]
@nmccready hi, does the Multipolygon works now, I tried the build "angular-google-maps 2.1.0-X.10 2015-04-16" but seems still not work yet? thanks

**Comment by nmccready** [comment]
Multipolygon works, just not the holes. But you can load geojson directly through googles map api. `loadGeoJson()` https://developers.google.com/maps/documentation/javascript/datalayer#load_geojson

**Comment by yadongzhu** [comment]
@nmccready thanks for response, can you guide me how the Multipolygon works, I checked the source code, and it seems still draw only one of the polygon:

} else if (path.type === 'MultiPolygon') {
              trackMaxVertices = {
                max: 0,
                index: 0
              };
              _.forEach(path.coordinates, function(polygon, index) {
                if (polygon[0].length > this.max) {
                  this.max = polygon[0].length;
                  return this.index = index;
                }
              }, trackMaxVertices);
              array = path.coordinates[trackMaxVertices.index][0];

**Comment by nmccready** [comment]
Ahh well if you want it to drill down into multiple then that does not work. So good point :) . Like the code says in the comments it only draws the external single polygon of MultiPolygon. So as this ticket states it needs to be completed.

**Comment by nmccready** [comment]
Basic code appears to get the polygon that is most complex (most vertices).

**Comment by yadongzhu** [comment]
@nmccready thanks for the clarify of the status. my current use case is to draw the USA on google map, the geoJson includes all parts of US land, i.e. US main land, AK state and a bunch of islands in Pacific. yes I can use loadGeoJson directly but I prefer the angular way ..., but thanks anyway!

**Comment by nmccready** [comment]
If you want to do it the angular way then create a directive called geojson. Which calls google.loadJSON. You can pretty much directly port this to here from angular-leaflet-directive. This is exactly what they do.

**Comment by yadongzhu** [comment]
@nmccready oh, cool! very informative, I will try, great thanks!

**Comment by deonclem** [comment]
What's the status on this ?

**Comment by nmccready** [comment]
no one has done anything

**Comment by pelverum** [comment]
Reading through this issue, it is unclear as to whether MultiPolygon geojson type is supported or not.  I need to handle display of geojson data that could either be a Polygon or MultiPolygon.  I have the Polygon data displaying without issue using the ui-gmap-polygon directive (using version 2.2.1), and need guidance as to how to display multipolygon data.  Should it be supported directly or do I need to convert to multiple Polygon structures and display them using the ui-gmap-polygons directive?

**Comment by nmccready** [comment]
Closing as this is pretty old and off my radar

**Comment by sime** [comment]
@yadongzhu Are you able to share how you solved your issue with drawing multiple polygons?

**Comment by nmccready** [comment]
It is not solved, just no one worked on it.

**Comment by nmccready** [comment]
It would be better to have a sep geojson directive which uses this part of google maps https://developers.google.com/maps/documentation/javascript/datalayer#simple_style_rules . This would easily handle complex geojson.

**Comment by sime** [comment]
Yes, I'm looking at the datalayer now.

Re: my initial comment, I was interested to hear about workarounds.

PS We have actually hacked MultiPolygon support in 2.0.9, though porting it is proving difficult. I can share the source if you like.

**Comment by nmccready** [comment]
👍  share away

**Comment by sime** [comment]
2.0.9 hacked to support complex MultiPolygon.
https://gist.github.com/sime/437b94e78c3fe2057b00988420f737db

2.0.9 upstream for reference: https://github.com/angular-ui/angular-google-maps/blob/664001b94be2a0f54fcf1781c3e9d8b40d9f9417/dist/angular-google-maps.js

Unfortunately the indenting seems to be different so diffing is not that helpful, I'm looking at re-indenting it.

**Comment by sime** [comment]
I have a readable patch now.

https://gist.github.com/sime/910343c7a3e9773cc2022e0565cbf7e8

I hope this is useful is potentially porting it.

**Comment by nmccready** [comment]
This is feasible to backfill, but it would be better to compare the actual source code (coffeescript). Your showing the compiled code.

**Comment by sime** [comment]
Eek, I was worried that would happen.

The hack was done JS.
