### ISSUE TITLE
[post 1.1] polygon directive, geojson mode should support displaying inner holes in the polygon

### ISSUE THREAD

**Issue by rickhuizinga** [angular-ui/angular-google-maps#321]
Currently the polygon directive code only displays the outer polygon ring of a GeoJSON Polygon object.  It should also support showing the inner holes (rings 1..n).

Supposedly the Google Maps Polygon API supports this by having polygon holes ordered in reverse direction (counter-clockwise/clockwise) as the outer shell.

**Comment by aplus01** [comment]
Is support for polygons that contain holes still being developed?

**Comment by nmccready** [comment]
Its down to be done, but I don't think anyone is actively working on it. Basically I won't get to it until I need it. @rickhuizinga is currently not totally active right now and I don't think it is a priority for @cthrax either. So if you really need it ASAP you will need to dig in and add it and please PR it to master.

**Comment by aplus01** [comment]
I started looking into it and saw this open issue and thought I'd ask before duplicating effort. If I get a solution going I'll do as you suggest and PR it to master.

**Comment by nmccready** [comment]
cool

**Comment by nmccready** [comment]
@rickhuizinga feel like adding this to 2.1?

**Comment by SemihAkar** [comment]
Anyone working on this?

**Comment by nmccready** [comment]
closing due to age
