### ISSUE TITLE
templateParameter not updating

### ISSUE THREAD

**Issue by dgavigan** [angular-ui/angular-google-maps#346]
I am using build `angular-google-maps 1.0.17 2014-03-30` and have various markers displayed on the map in the following way: 

`<markers models='components'
                          coords="'self'"
                          doCluster='true'
                          click="'getDetails'">
                        </markers>`

Im then using the window component to show details for the selected marker: 

`<window coords="windowCoords"
                        show="displayWindow"
                        templateUrl="'views/info-window.html'"
                        templateParameter="componentDetails">
                        </window>`

`getDetails()` is triggered when a marker is selected, returning the correct data for the selected `marker`. 

However, once I set `$scope.componentDetails = newData` I'm still getting the old window details, and the info window is not rendering with the updated data. It does appear to be picking up the new coords as the window displays in the correct location, but with stale data. 

Anyone ever run into something similar or am I implementing this wrong?

**Comment by jessemorton** [comment]
This was helpful to read about, as I was having the same issue. For others coming to this issue in the future, consider modifying any property that's tied to the ui-gmap-window's `options` parameter, and that'll get the `templateParameter` changes to also be appreciated.

In my case, I set a new placeholder property `windowOptions.modelId = <the_new_model's_id>` upon every click, just for the sake of triggering the watcher.
