### ISSUE TITLE
Disabling scroll based zoom

### ISSUE THREAD

**Issue by pulkitsinghal** [angular-ui/angular-google-maps#381]
https://developers.google.com/maps/documentation/javascript/reference?hl=nl specifies that the scroll wheel can be disabled.

![screen shot 2014-04-22 at 7 22 43 pm](https://cloud.githubusercontent.com/assets/821963/2772409/83b40be4-ca7d-11e3-92c1-8903adb575d6.png)

I was wondering, how do I pass this option down through a directive?

**Comment by robert-irribarren** [comment]
not dumb. i googled this and this answered showed up and it helped me out.

**Comment by tommyalvarez** [comment]
+1 help me too

**Comment by ZachMoreno** [comment]
@pulkitsinghal,
No such thing as, "Dumb questions"

@robert-irribarren & @tommyalvarez,
Happy to help explain this in more detail

In your **controller**, bind a `map` object to your `$scope` that contains an `options` object that contains the `scrollwheel` property, with the value set to `false`
```
$scope.map = {
    options: {
        scrollwheel: false
    }
};
```

Then, in your **view**, reference the `map.options` object as the value of the `<ui-gmap-google-map></ui-gmap-google-map>` element's `options` attribute.

```
<ui-gmap-google-map options="map.options">
    ...
</ui-gmap-google-map>
``` 

Please let me know how this works for you.
