### ISSUE TITLE
[develop] ng-show within window not working

### ISSUE THREAD

**Issue by ghost** [angular-ui/angular-google-maps#382]
When I use ng-show within the window directive, my strong-tag won't show although the expression is true. I put the expression I'm using outside the ng-show and then it says "true", so the expression is indeed true.
This is only an issue on the development version, as it does work on the release version.

I created a plunker to show my problem. 
http://plnkr.co/edit/A6eDExMqECldHAOLcVGP

**Comment by knapeto** [comment]
Hey all,

I have still problem with ng-show..

I have dynamic selected.

```js
<ui-gmap-window coords="selected" show="selected.show" closeClick='selected.onMarkerClose()' ng-cloak>

    <div style="min-width: 230px;">

        <div ng-show="selected.atest">aaa</div>

        <div ng-show="selected.btest">bbb</div>

    </div>

</ui-gmap-window>
```

**Comment by abdellah-neo** [comment]
For people still experiencing this issue: you can use :
`ng-show="{{boolean}}`
It works just fine

**Comment by nmccready** [comment]
Thanks @abdellah-neo
