### ISSUE TITLE
fit=true + single marker = too high zoom

### ISSUE THREAD

**Issue by amit777** [angular-ui/angular-google-maps#414]
Hi, when I have a variable number of markers, fit to zoom works great except for the instance where you have 1 map marker.  Then the map zooms into too close and is useless.  I found some other people having a similar issue here:

http://stackoverflow.com/questions/3334729/google-maps-v3-fitbounds-zoom-too-close-for-single-marker

Could we add a directive option for "single-marker-zoom=8" or something like that?

**Comment by DanUnderwood** [comment]
Here is a plnkr demoing the issue:
http://plnkr.co/edit/eMgC6SnQuFPB9cx8kpP5

**Comment by nmccready** [comment]
I started reworking this functionality in another ticket. Anyway new issue #449 which is related.
