### ISSUE TITLE
Window click/ touch events not firing (Mobile)

### ISSUE THREAD

**Issue by pbrain19** [angular-ui/angular-google-maps#428]
It appears that anything touch / click does not fire at all.

Here is an example of the issue. Currently testing in Moto X chrome browser. 

http://shielded-hamlet-4180.herokuapp.com/

Events/markers are location driven so register and make a dummy event to if not in NY

**Comment by DavidePastore** [comment]
My solution here is to wrap your `ui-gmap-google-map` tag with a container and add `data-tap-disabled="true"` attribute.

```
<div data-tap-disabled="true">
  <ui-gmap-google-map center="center" zoom="map.zoom">
    <!-- Your markers -->
  </ui-gmap-google-map>
</div>
```

**Comment by nmccready** [comment]
@DavidePastore thank you!

**Comment by ev-tt** [comment]
@DavidePastore thanks, it helped!
