### ISSUE TITLE
how to make  map appear full screen width/height

### ISSUE THREAD

**Issue by abbood** [angular-ui/angular-google-maps#429]
I included google maps sdk into my project and was able to make it appear 100% screen width/height by doing the following:

first i made sure the `html` tag was 100% height

```
html { height: 100% }
```

in the html file holding the google map, I just made the holding div 100% height/width as well:

```
#map {
  height: 100%
  width: 100%
}
```

and I basically load the map using javascript:

```
$(document).ready(function() {
    var handler;
    handler = Gmaps.build("Google");
    return handler.buildMap({
      internal: {
        id: "map"
      }
    }, function() {
      handler.fitMapToBounds();
    });
  });
```

with **angular-google-maps**, i simply followed the [instructions](http://angular-google-maps.org/use).. which specifically asks to set a height for the map like so:

```
.angular-google-map-container { height: 400px; }
```

trying to set that to 100% results in nothing showing up in the page. I spent all morning messing with css, with no clear win. The closest I got was doing this

```
.angular-google-map-container { 
  height: 100%;
  position: absolute;
}
```

but then that made the map non-draggable.. 

any ideas?

**Comment by escapedcat** [comment]
Also see https://github.com/angular-ui/angular-google-maps/issues/309

**Comment by weslley39** [comment]
@gitnik +1

**Comment by nebulr** [comment]
This helped a lot in addition I thought I might add what I found worked : 
I had a nav bar that had 4em height and a sub nav bar with 64px height

```
.map-wrapper {
  position: relative;
  height: calc(100vh - 4em - 64px);
}

.angular-google-map-container {
  position: absolute;
  top: 0;
  bottom: 0;
  right: 0;
  left: 0;
}
```
with html

```
  <div class="map-wrapper">
      <ui-gmap-google-map> ...</ui-gmap-google-map>
  </div>
```
