### ISSUE TITLE
Close other windows when I click marker

### ISSUE THREAD

**Issue by gorkaeff** [angular-ui/angular-google-maps#434]
Hi!
I'm using angular-google-maps 1.0.15, and I have created a map with <markers> and inside this tag I have <windows> tag. 

There are lot of markers, but when I click this show his window but if I click another marker, I want to close first window and show last clicked marker, but now I have many open window at the same time.

What is the solution to fix that?

Thanks and sorry for my english.

**Comment by rvanbaalen** [comment]
It's unfortunate that Plunkr doesnt seem to be working (at this moment?)

Could you guys please post the example code of your solution here as a snippet instead of referring to an external source?

**Comment by gitnik** [comment]
There's no real solution, it was a bug that has been fixed. Everything should work as expected

**Comment by rvanbaalen** [comment]
Interesting. Im experiencing the same 'bug' andjust recently installed angular-google-maps with bower. Should be the latest version 

---
This email was sent from my iPhone and therefore subject to typos and other inaccuracies.

**Comment by nmccready** [comment]
Make sure your using dot notation when binding against primitives. see https://github.com/angular/angular.js/wiki/Understanding-Scopes and search primitives.

**Comment by rvanbaalen** [comment]
I will double check that tonight and get back to you if it helped. Thanks for the reference.
