### ISSUE TITLE
[Freature request] Add address picker 

### ISSUE THREAD

**Issue by programming-kid** [angular-ui/angular-google-maps#459]
@nlaplante  this is amazing directive and thanks for prompt response on issues . I have a feature request , do you have plans to include address picker to this directive ?? Adding address picker to this directive will be great addition to this plug-in . Adding something like this [typeahead-addresspicker ](https://github.com/sgruhier/typeahead-addresspicker) will be great . Currently i am using both this plugin in my project but having something like this built in angular-google-maps will be great .

**Comment by nmccready** [comment]
I have no plans to work on this until I myself need it. So if someone wants this they need to dig in.

**Comment by morettimatheus** [comment]
@programming-kid would you mind posting a plunker with your map working along with the typeahead? Or pointing me out on which repo of yours you have this snippet once I tried to find but couldn't.

**Comment by kandizzy** [comment]
@morettimatheus You can use Autocomplete by setting the search-box directive's `options.autocomplete` parameter to true. Here is a plunkr and there's more information and links to Google's documentation in the [api docs](http://angular-ui.github.io/angular-google-maps/#!/api)

http://plnkr.co/edit/PIvhQQYTtE8fhzhU4lax?p=preview

**Comment by morettimatheus** [comment]
@kandizzy Carrie, clicking on any search suggestion won't center the map or place the icon at this suggestion point. Is this the normal behaviour?  Should I just use Maps API from now on?

Thank you very much for the plunker. And for all the support :+1: :smile:

**Comment by kandizzy** [comment]
This directive supports all of that functionality, but you need to add that to your own code. There are [examples](https://github.com/angular-ui/angular-google-maps/tree/master/example) provided on how to use everything. The specific example you'll want to look at is [search-box-autocomplete](https://github.com/angular-ui/angular-google-maps/blob/master/example/search-box-autocomplete.html)

Take a look at the [javascript file](https://github.com/angular-ui/angular-google-maps/blob/master/example/assets/scripts/controllers/search-box-autocomplete.js) for that example on how to add markers from the search results.

You can clone this repo and run `grunt example` and work on this locally- or you can add the marker code to that plunkr.

**Comment by morettimatheus** [comment]
Thank you very very much! This example you have shown works perfectly! Sorry for not looking through examples before commenting here. 

After I finish this task I will create a plunker and paste it here so other people with the same issue can see the solution easier. 

Thank you very much once again :smile:

**Comment by kandizzy** [comment]
@morettimatheus cool! thank you :+1:

**Comment by intellix** [comment]
I was previously using AngularGm and ngAutocomplete. I suppose my only problem with the current `<ui-gmap-search-box>` directive is that it requires wrapping in a `<ui-gmap-google-map>`, which it really shouldn't depend on. 

I have something similar to what you see on AirBnb homepage, where you search for something (without a map), get the result and then redirect them to a page containing the map, using the center location.

Using the current search-box, I'll have to hide the map, but it's a waste of resources to have to create an unneeded map instance.

I'll attempt to use ngAutocomplete, but not sure how it'll play with the async loading of this library. If I fail at that, I'll try to manually integrate something into this lib. Probably not too difficult :)
