### ISSUE TITLE
Does this module require Lodash and not underscore

### ISSUE THREAD

**Issue by paulsheldrake** [angular-ui/angular-google-maps#463]
I haven't been able to get the my Markers to work after upgrading from 1.0.18 to 1.1.0 and I notice that you don't have underscore in the example.html anymore and now have lodash.  Just wondering if there is something simple I may be missing.

If you do need lodash you should probably update this page 
http://angular-google-maps.org/use

Cheers,
Paul

**Comment by FlavorScape** [comment]
So bizarre. I was getting errors in a dev environment (not local) that _ is not defined. I already had lodash loaded from bower deps... then... I added underscore for fun and then maps worked fine. This is using the latest 2.3.2. I even answered this question on SO and it was the correct solution.

http://stackoverflow.com/questions/33530717/referenceerror-is-not-defined-while-using-angular-google-maps/35731082#35731082
