### ISSUE TITLE
Marker animation in markers directive

### ISSUE THREAD

**Issue by andrius-kulbis** [angular-ui/angular-google-maps#482]
Hello,

How can I enable marker BOUNCE animation for selected marker, while using `<markers>` directive?
Tryed:

```
var marker = {
    latitude: loc.lat(),
    longitude: loc.lng(), 
    options: {
        animation: google.maps.Animation.BOUNCE
    }
}
$scope.map.markers.push(marker);

...

<markers models="map.markers" coords="'self'" doCluster="true" 
        click="'onClicked'" doRebuildAll="false">
```

But this doesn't work.

**Comment by iwiszhou** [comment]
Hello,
It doesn't work
I just try to modify the example under API doc page -> Edit in Plnkr. 
I modified
var ret = {
        latitude: latitude,
        longitude: longitude,
        title: 'm' + i
      };

to 

var ret = {
        latitude: latitude,
        longitude: longitude,
        title: 'm' + i,
        options : { animation: google.maps.Animation.BOUNCE }
      };

It doesn't make the markers bounce..
Any ideas ?  @nmccready

**Comment by cthrax** [comment]
You didn't modify your HTML to point the markers at your options property. http://plnkr.co/edit/y43YivR0B2Yce4J5HMqU?p=preview

**Comment by iwiszhou** [comment]
Hum....Yea.
I think the only different is I am not using Watch function to populate my marker. I am still not able to see the marker bounce.

But after I debug the source code, I found out an issue, on function:  "MarkerChildModel.prototype.setOptions",  when they try to access the options, the key for options is null.
_this.optionsKey -> always return null. That is the reason why the marker animation is not working.
"_options = _this.getProp(_this.optionsKey, _this.model); "

@cthrax  @nmccready

**Comment by cthrax** [comment]
It sounds like you need to use a watch to populate your markers then. Likely, you are running into a race condition where you are trying to use something too early. The fact that my plnkr works really demonstrates this is a problem in how you're using the library and not a problem in the library itself. Spend some time isolating what the difference is and if you can give us a succinct example of what is not working, we might be able to help you, but with this broad of a scope, we're not able to provide much in the way of feedback.

**Comment by pawantiwari1** [comment]
how to animate if using AGM (Angular google Map ) because here some tag are used to as agm-marker so how to animate here marker ..?
