### ISSUE TITLE
Marker moves with map.

### ISSUE THREAD

**Issue by jbravar** [angular-ui/angular-google-maps#498]
![ng-gmap-issue](https://cloud.githubusercontent.com/assets/160371/3288376/155fcc90-f562-11e3-9474-e1fddcc9ddf6.gif)

Can't seem to find any other issues like this, maybe I'm not sure what to search for.

**Comment by uiktiomasfeliz** [comment]
With this solution i got working.
http://stackoverflow.com/a/30572501

**Comment by nicolae-olariu** [comment]
You can bypass this bug by indeed creating a fresh new object (different than map's center) and bind the marker's `coords` to it. [Read more.](http://stackoverflow.com/a/29763312/2674883)

**Comment by nmccready** [comment]
There is no bug they need to be two independent references. Look at the code and it's pretty clear.

**Comment by nmccready** [comment]
Here is why:

scope.center is used both to set the map and to receive the map's current position. Therefore if you bind marker to the scope.center the marker will always be i in the center. I don't know how to make this any clearer.

**Comment by nmccready** [comment]
@nicolae-olariu
