### ISSUE TITLE
Ng-repeat not rendering properly within InfoWindow

### ISSUE THREAD

**Issue by sanketch** [angular-ui/angular-google-maps#511]
Not sure if this is a bug or I am doing something wrong but for some reason ng-repeat isn't functioning like it's supposed to when used inside an info window. 

Here is the Plunker : http://plnkr.co/edit/BmUp9x?p=preview

I noticed two things:
1) Elements are repeated more than once, depending on the array size which is weird (as shown in plunkr, the array 1,2 is printed twice.
2) My result array has more elements in it and I am using ng-repeat to display them, but it wouldn't display them. Even though {{result}} immediately following <window> tag will print out the result array. 

I read @nmccready 's comment here about infowindow: https://github.com/nlaplante/angular-google-maps/issues/473#issuecomment-45642400 but it seems that the scope has the results array as it prints it out, but when used with ng-repeat it doesn't work properly.

**Comment by Jatik** [comment]
Hey guys,
did you solve the problem? I'm struggling with it right now. Angular version is 1.4.7. I don't know if ng-non-bindable helps because as soon as I add it it prevents the following ng-repeat from being rendered at all. Thanks
