### ISSUE TITLE
how to make completely custom InfoWindows 

### ISSUE THREAD

**Issue by abbood** [angular-ui/angular-google-maps#520]
Is there a way to make completely custom info windows? i looked around and just saw this add-on [library](https://code.google.com/p/google-maps-utility-library-v3/wiki/Libraries) for google maps .. but it gives you limited styling options (ie color, size etc).. i want it to be completely autonomous (ie i can do whichever css styling i want).

![screen shot 2014-06-21 at 10 42 18 am](https://cloud.githubusercontent.com/assets/774379/3348159/0f9e2cc0-f918-11e3-854e-69834ae848d0.png)

**Comment by merlihan** [comment]
Hey @nmccready - I am trying to accomplish this as well but can't seem to hook into infobox. I had tried adding the infobox options to $scope.infoWindow but that didn't do the trick. Whereabouts do we get access to infobox options?

Thanks in advance.

**Comment by merlihan** [comment]
Ah - ok found it here: [master] Support for google-maps-utility-library-v3 InfoBubble #110

Thanks.
