### ISSUE TITLE
panBox does not work correctly when using custom Window of a marker

### ISSUE THREAD

**Issue by kikoanis** [angular-ui/angular-google-maps#524]
Unless I am missing something, it seems that the custom function "panBox_" does not work as intended if the top of the marker is too close to the top of the map or too close to the left of the map.
Here is a plnkr to test:
http://plnkr.co/edit/xlzAncyUP2oAP3ym4K5v?p=preview

**Comment by intellix** [comment]
Also having this issue. I've got it to pan around the new infoBox exactly without any margin. One annoyance is I had to reference `google` directly within my controller:

```js
vm.infoWindow = {
    show: false,
    options: {
        boxClass: 'map-info-window',
        // @todo: Remove all this jazz
        pixelOffset: new google.maps.Size(-130, -53),
        boxStyle: {
            width: '260px',
            height: '246px'
        },
        closeBoxURL: '',
        alignBottom: true,
        disableAutoPan: false
    }
};
```

One additional thing, I'm not closing the infoBox if you click on another marker, it just animates to the marker, which doesn't call panTo unless I hide and reopen it.
