### ISSUE TITLE
Expose GMaps setDirections() method

### ISSUE THREAD

**Issue by anoopsinghbayes** [angular-ui/angular-google-maps#533]
drawing polylines on map is cumbersome ,
expose inbuilt setDirections() method of the underling map to user so that they can directly pass the respose from the google.maps.DirectionsService() routes methods

**Comment by webnerdlw** [comment]
Is there a plan to add this functionality to angular-ui/angular-google-maps ... OR do I need to use UI map if I need/want this functionality?

**Comment by nmccready** [comment]
You could copy and or implement this so it is in this library. Sometimes people need to step up and contribute. As for others it is not on our radar. If you want it please add it and take credit.

**Comment by sariyu** [comment]
Hi @anoopsinghbayes, I'm looking for similar solution as in the image you attached. I managed to display two locations on the map using angular-google-maps now i have to calculate the route between those two paths. Any Help ?
