### ISSUE TITLE
Always zoom at the center of the map

### ISSUE THREAD

**Issue by dbaq** [angular-ui/angular-google-maps#541]
Hey guys,

I can't achieve something, I tried to keep the map centered on the center location even when the user double-tap or pinch-to-zoom.

So far when you double tap, the map is re-centered near by the double-tap.

Is it possible to keep the map centered at the same location when a user zoom in/out. You can find this can of behavior on the Uber/Lyft app when you a marker at the center of the map, if you zoom in (by double typing anywhere), the map is zoomed and stays centered at the same location.

Thank you for your help.

**Comment by nmccready** [comment]
@dbaq ever figure out a way?
