### ISSUE TITLE
Polyline change path to empty path not destroying PolylineChildModel

### ISSUE THREAD

**Issue by Roycohen** [angular-ui/angular-google-maps#543]
I have polyline path which is working but if I change the path to be empty array or null the polyline is still shown on the map.
I have also tried to add ng-if to the polyline directive and after I've added it I can see that the "$destroy" is being executed but the polyline is still shown on the map.

I really need help in this one.

**Comment by anteriovieira** [comment]
Hi @Roycohen , did you have any progress with this issue? 

If possible give us an example so we can help you.

This is a beginning of a task force for closing old issues.

**Comment by anteriovieira** [comment]
@nmccready It may be that some update has corrected this problem, I have tested and investigated but I have not found anything.

Everything is working well for me.

[See the code used in the example here](https://github.com/to-know/issues-angular-google-maps/blob/master/src/issues/543/map-ctrl.js#L85)

![polylines](https://cloud.githubusercontent.com/assets/1490347/21534078/f9f5c90c-cd48-11e6-8224-fbfd321240f3.gif)
