### ISSUE TITLE
Setting Map Styles

### ISSUE THREAD

**Issue by s10mcow** [angular-ui/angular-google-maps#550]
I can seem to figure out how to set the styles through the options attribute. Any documentation out there about this? All I see is that these styles are available with a link to the map options. 

Controller:
![controller](https://cloud.githubusercontent.com/assets/3219270/3520783/3a257594-0736-11e4-8fc8-7e423e2b9b63.png)

HTML:
![html](https://cloud.githubusercontent.com/assets/3219270/3520795/6439a076-0736-11e4-821f-d751ffd5cc29.png)

**Comment by luillyfe** [comment]
Hi, this solution isn't working for me, because Angular throws the following error: Can't find variable Google.

Greetings from Colombia.
