### ISSUE TITLE
Expose loadGeoJson()

### ISSUE THREAD

**Issue by martinlindhe** [angular-ui/angular-google-maps#551]
Please expose a way to easily load geojson files.

https://developers.google.com/maps/documentation/javascript/datalayer#load_geojson

**Comment by nmccready** [comment]
Using isReady or the uiGmapGoogleMapApi will give you the map reference. I don't see a need to do anything else angular with this.

**Comment by nmccready** [comment]
Is it expected that there should be a geoJsonUrl attribute?

**Comment by nmccready** [comment]
Closing unless there is feedback and interest.
