### ISSUE TITLE
how to retrieve gMarkers from google maps object 

### ISSUE THREAD

**Issue by abbood** [angular-ui/angular-google-maps#561]
[angular-google-maps](http://angular-google-maps.org/) abstracts the process of creating google markers (ie we don't do it directly via `new google.maps.Marker({...});`).. that said, there isn't a way for us to simply retrieve the markers pertaining to a google map object nor can we create our own array to store a reference to these markers for later usage (see [here](http://stackoverflow.com/a/6662514/766570))

Is there a way for us to retrieve the gMarkers pertaining to the google map object? @nmccready

**Comment by flyer1** [comment]
This update was extremely useful to me. 
FYI, to those who use it, when you retrieve the list of markers via map.markersControl.getGMarkers(), it orders the array by id. My list was sorted by distance from a given geopoint and I had expected the gMarkers array to come out the same order as it went in. No big deal, but worth being aware of.
