### ISSUE TITLE
How do I pass other parameters to the google polygon events object using the directive?

### ISSUE THREAD

**Issue by DanielDeLaGarza** [angular-ui/angular-google-maps#570]
I have been trying to pass down another parameter to the polygon event handler 'click' function, I'm not sure how to do it. 

currently I have this code:

in the controller I have this to debug the arguments

$scope.map.clickFunction = function(arg0, arg1, arg2, arg3){console.log(arg0); console.log(arg1); console.log(arg2); console.log(arg3);}; 

HTML code

```
        <polygon
              ng-repeat='poly in map.polygons'
              path='poly.path'
              fill='{color: "#CCFFCC", opacity: .5}'
              stroke='{color: red, weight: 0.1, opacity: 1}' 
              events = '{click: map.clickFunction}'>
        </polygon>
```

I want to be able to access the data in "poly" for each polygon when they are clicked so that I can display it.

**Comment by maimaipa357** [comment]
Is there no 'simple' solution to add parameters on those polygons.
I'm searching to  store some information but I can't find a simple way to do it.

Thanks in advance.
