### ISSUE TITLE
can't hide previous window before showing next.

### ISSUE THREAD

**Issue by carlosrojaso** [angular-ui/angular-google-maps#599]
I'm using the window directive inside a marker.

When I click on the marker the window that's under it shows.

If I click in a second marker the previous window doesn't hide.

The show attribute doesn't seem to combine with the isIconVisibleOnClick so I can't find how to hide all the other windows when displaying a new one.

**Comment by anteriovieira** [comment]
Hi @nmccready , the code below worked well for me. I believe that this issue can be closed.

```html
<ui-gmap-google-map  center='map.center' ...>
    <ui-gmap-layer type='TransitLayer'>
		<ui-gmap-marker click='showWindow(m)' coords='m.coords' fit='true' idkey='m.id' ng-repeat='m in markers'>
			<ui-gmap-window isIconVisibleOnClick='true' options='m.options' show='m.show'>
				{{m.message}}
			</ui-gmap-window>
		</ui-gmap-marker>
    </ui-gmap-layer>
</ui-gmap-google-map >
```

```js
// ...

$scope.showWindow = function(selected){

	_.map($scope.markers, (marker) => {
		marker.show = (selected.id === marker.id);
	});

};

// ...
```

![untitled project](https://cloud.githubusercontent.com/assets/1490347/21469234/188ec31c-ca26-11e6-8459-f2257e68c4be.gif)

**Comment by anteriovieira** [comment]
I have not found anything that might consider a bug
