### ISSUE TITLE
Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by kalvish21** [angular-ui/angular-google-maps#600]
I'm using 1.2 version and on line 3225 I get the error in Google Chrome:

Uncaught ReferenceError: _ is not defined

Is there something i'm possibly missing? I'm using latest version of angular stable (AngularJS v1.3.0-build.3009+sha.0107bfc).

**Comment by codymikol** [comment]
I'm actually having this issue in karma-jasmine, I am listing the dependencies in the correct order but get this error regardless.
