### ISSUE TITLE
RichMarker

### ISSUE THREAD

**Issue by AliAkbarLatifi** [angular-ui/angular-google-maps#607]
How to use RichMarker class in markers directive?

**Comment by 23tux** [comment]
+1 Anything new on this? I would love to use RichMarkers with angular google maps

**Comment by nmccready** [comment]
No   Not that I know of. I'm trying to give advice so someone else can complete this. I don't have time for this currently. The community needs to step up.

**Comment by xfreakx** [comment]
nmccready if you help me i can try to do it, because i really need it.

**Comment by nmccready** [comment]
@xfreakx sure

**Comment by madvas** [comment]
+1

**Comment by xfreakx** [comment]
Is it possible to load them via kml file, which will be generated by backed? That will be nice workaround...

**Comment by madvas** [comment]
For my purposes workaround with SVG works pretty well. It can be done something like this:
```
myMarker.icon = 'data:image/svg+xml;charset=UTF-8;base64,' + 
    btoa('<svg>You can put here dynamically generated SVG</svg>')
```

**Comment by nmccready** [comment]
In all honesty to add RichMarker to the codebase it will probably be pretty easy. But the bottom line is I want someone else to try it.

**Comment by xfreakx** [comment]
madvas the problem is that i need to add an arrow and rotate it with css ...

**Comment by philttz** [comment]
+1.. waiting for this also

**Comment by caioiglesias** [comment]
Is the goal of following ClusterMarkerManager's interface to enable clustering of the rich markers?

**Comment by caioiglesias** [comment]
I started working on this without adding type, just by adding "content" to options which is what RichMarker expects to be HTML. Working on <marker> for now. I'll wait for a reply regarding a manager.
