### ISSUE TITLE
Add angular-ui links to website

### ISSUE THREAD

**Issue by cthrax** [angular-ui/angular-google-maps#613]
To make the angular-ui integration more consistent with the rest of angular-ui, get some links to at least the angular-ui team, but probably the list of projects, similar to what http://angular-ui.github.io/ng-grid/ has.

**Comment by nmccready** [comment]
@cthrax did you fix this?

**Comment by cthrax** [comment]
@nmccready no, it's not been done. I might even question whether it does need to be done.
