### ISSUE TITLE
how to destroy the map instance?

### ISSUE THREAD

**Issue by ms88privat** [angular-ui/angular-google-maps#638]
Hello,
I am really confused.. I got the google-map directive in one of my ui-views. The map is centered correctly of the specific city coordinates. Now i can change the center of the map through touch input.

However if i transition back $ forth, the map remains on the position i left it and not on city-center. That is really confusing if the city meanwhile has changed though $stateParams.

Normally the map should be completely re-initialized if the controller is called again on view-transition?

What can i do to reset the map completely after $destroy ?

Thank you very much.

**Comment by czalexpic** [comment]
What about memory? If you repeatedly show and hide the map, in the DevTools -> memory -> Heap snapshot, memory consumption is always growing.
