### ISSUE TITLE
Map in Modal Dialog Doesn't Render Correctly If Page Has a Map

### ISSUE THREAD

**Issue by adblockist** [angular-ui/angular-google-maps#639]
![screen shot 2014-08-16 at 2 53 23 pm](https://cloud.githubusercontent.com/assets/826383/3943214/cb4735b8-258f-11e4-81f0-a4c5bc6da712.png)

As you can see from the picture, the map in the modal dialog doesn't render correctly.  If I disable the one of the page (the one in the background), it works fine.

I'm using angular-ui to generate the modal dialog and using angular-google-maps 1.2.0.

Thanks.

**Comment by emadd** [comment]
hangongithub's solution should be featured on the FAQ
