### ISSUE TITLE
Polygon contains point

### ISSUE THREAD

**Issue by MauritzKruger** [angular-ui/angular-google-maps#649]
Hi guys

I would like to know if you can by any chance add the functionality in controller to determine if point is inside the newly created polygon.  Example code by other developer: http://www.counsellingbyabhi.com/2013/01/google-map-check-whether-point-latlong.html

**Comment by sefsinalas** [comment]
I need this functionality too.

**Comment by nmccready** [comment]
This is pretty easy to implement yourself as long as you get the reference of the real poly.

**Comment by sefsinalas** [comment]
I don't understand. Can you help me to understand? This is what i have: http://plnkr.co/edit/qaN9Ui5sBbZMQmC7vKeL?p=preview

**Comment by nmccready** [comment]
See https://developers.google.com/maps/documentation/javascript/3.exp/reference#LatLngBounds , method contains . Are you using polygons or polygon. I suggest polygons as getting the gObjects is already supported by control.getPlurals . You need to read the docs and search through examples. If someone else wants to go into more detail by all means do it.
