### ISSUE TITLE
Text in infoWindow can't be highlighted/selected

### ISSUE THREAD

**Issue by gitnik** [angular-ui/angular-google-maps#697]
Not sure if this is some option I'm missing or a restriction by the GMaps API, but text/content in infoWindows can never be selected/highlighted via the mouse

**Comment by nmccready** [comment]
@gitnik ever figure this out? Did you try using templateUrl?

**Comment by nadafigment** [comment]
I'm seeing this also; I guess gitnik didn't figure it out, I would like to. I am getting this even when using native infoWindows but with angular-google-maps handling the map itself -- eg var infoWindow = new google.maps.InfoWindow({content:contentString});
and using the exact content from maps api docs: https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple

So I suspect it is something to do with how the map is being initialized. I tried with multiple versions of maps api, 3.exp, 3.18, 3.20, 3.21..

**Comment by wrummler** [comment]
I'm not seeing this in Google's samples or in my own app. I'm using agm's `window` and the `templateUrl` attribute fwiw. With agm 2.1.4, gm 3.20, ng 1.4.1 in Chrome 43.0.2357.124 on Win7 Pro 64-bit.

**Comment by nadafigment** [comment]
@wrummler do you mean you can't select infoWindow text from 
https://developers.google.com/maps/documentation/javascript/examples/infowindow-simple
?

I can do so in Chromium Version 43.0.2357.81 Ubuntu 14.04 (64-bit) and Firefox 38.0 for canonical Ubuntu, will see if i can try on a windows machine somewhere. Are the local/latest agm examples hosted anywhere so I can try with those, or do I need to set up locally?

**Comment by wrummler** [comment]
@nadafigment In my comment "this" === the issue itself. Selection of text in infowindows is working fine for me.

Beyond the plunker examples at the agm API doc pages, I'm only aware of the examples in the master branch's example directory. The most straightforward way to check the latter is to set up locally. To avoid browsers' file:// protocol restrictions, you'll need to serve the example HTML with an HTTP server (like node's http-server if you've got node installed).

**Comment by nadafigment** [comment]
Thanks @wrummler, works for me with the examples from master, I must either be setting up something wrong or the problem is specific to using new google.maps.InfoWindow() instead of using the directives as designed (unfortunately can not change to use those easily).
