### ISSUE TITLE
markersControl.getGMarkers does not contain all markers (?) 

### ISSUE THREAD

**Issue by gitnik** [angular-ui/angular-google-maps#707]
Sorry for the super vague title, but I'm not sure what's causing the issue. Might as well be a GC bug on the google maps API. Anyway here's the bug description:

I have a map with roughly 400 markers. A certain click event triggers the following code:
```javascript
$scope.map.markersControl.getGMarkers().forEach(function(marker) {
    marker.setMap(null);
});
```

I would expect this to properly remove all markers from the map. What happens however is that some markers (they're always the same ones) actually stay on the map as you can see in the screenshot.

![selection_001](https://cloud.githubusercontent.com/assets/996623/4335536/9dcfc040-3ffd-11e4-840d-e7eee817d0a6.png)
![selection_002](https://cloud.githubusercontent.com/assets/996623/4335535/9dc51fbe-3ffd-11e4-8697-37515ebe40cd.png)
I've tried to dig into the code, but couldn't find anything that might be causing this.

**Comment by nmccready** [comment]
I believe this is resolved on 2.0.X and 2.1.X use control.getPlurals()
