### ISSUE TITLE
refresh attribute is not working

### ISSUE THREAD

**Issue by pabloleone** [angular-ui/angular-google-maps#721]
I have this markup using bootstrap UI:
        < tabset>
          < tab heading="Media">
            < div class="well my-drop-zone" nv-file-drop nv-file-over uploader="uploader">
              Base drop zone
            </ div>
          </ tab>
          < tab heading="Map" select="map.refresh = true" deselect="map.refresh = false">
            < google-map refresh="map.refresh" center="map.center" zoom="map.zoom"></google-map>
          </ tab>
        </ tabset>

When the Map tab is selected the map.refresh change to true but the map is not refreshed.
I saw in angular-google-maps.js on line 5885 is the $watch for that attribute. I added a console.log to see if that code is executed but nothing.

Am I doing something wrong? Is how the refresh is sopouse to work?

Thanks!

**Comment by DaSchTour** [comment]
Can you please please please update your documentation! I lost about an hour just because of your outdated documentation!

**Comment by nmccready** [comment]
Other people need to contribute to the docs as well. The time I have available to fix things does not mean I have time to always update docs.
