### ISSUE TITLE
lodash/underscore dependency should be internally managed

### ISSUE THREAD

**Issue by zacronos** [angular-ui/angular-google-maps#730]
lodash/underscore is a required dependency (i.e. there is code that references _ without null checks), but currently the dependency must be fulfilled externally.  This provides no mechanism for version standardization -- if, for example, we want to use a lodash 3.x feature, the only current option is to tell all uses that they have to load loadash 3.x (rather than their own flavor/version of choice).

In my particular use case as an angular-google-maps developer, I want to use a lodash-specific function, but there's no way for me to ensure the library loaded isn't underscore (or an underscore-compatible build of lodash).  Simply documenting the dependency on a full version of lodash is not a great solution.

An ideal solution would perform checks when angular-google-maps loads, to determine if there is an appropriate library loaded as _.  If there isn't, then an appropriate library should be loaded asynchronously in noConflict mode.  All use of the library should then be moderated as an internal dependency rather than referencing the _ global.

**Comment by mtyeh411** [comment]
+1 for this.  is this no longer on the roadmap?

i would go so far as to suggest always having lodash in noConflict mode, not just the case outlined above.  it's not at all outside the realm of possibility for angular apps injecting this module to be using underscore.js ;)

**Comment by nmccready** [comment]
I am closing this unless someone else wants to take this on. This is out of scope as no one else really helps on this project.
