### ISSUE TITLE
Dynamically Adding Markers after the first paint/draw of the map

### ISSUE THREAD

**Issue by gplusdotgr** [angular-ui/angular-google-maps#731]
Hey,

I m trying to add a bunch of markets who come after a promise has been resolved, as such:

```
GetLocations.getLocations().then(function (data) {
  $scope.data = data;
}).then(function (data) {
  $scope.loadMap = true;
  $scope.marker = {
    id: 0,
    coords: {
      latitude: 40.1451,
      longitude: -99.6680
    }
  };
  $scope.map = {
    center: {
      latitude: 45,
      longitude: -73
    },
    zoom: 2
  };
});
```

Is this possible? Could you add this to your examples?

On a sidenote: is ng-show or ng-if supported? Can I display the map only after a condition has been met?

**Comment by jesmith17** [comment]
+1, this is a common feature and would be really useful to have an example of.
