### ISSUE TITLE
Markers not cleaning up ...

### ISSUE THREAD

**Issue by david-hollifield** [angular-ui/angular-google-maps#754]
I just upgraded to 2.4.1 with all of the documented changes and my markers are no longer being totally refreshed after updating the markers array. I show, at most, 5 markers for each page of locations. The first page shows fine. After going to another page, I request my new locations from my API, clear out my old markers array (length = 0), push my new markers and I end up with something like this: 

![2014-10-10_15-32-23](https://cloud.githubusercontent.com/assets/686784/4598177/025f87ac-50b6-11e4-8f21-67aa7ac42368.png)

Any ideas what could be causing this? I tried adding doRebuildAll, but that didn't change anything.

**Comment by returnempty** [comment]
@david-hollifield thanks for $timeout solution, only this solution worked +1

**Comment by nmccready** [comment]
Just a final note, bluebird is no longer required. It hasn't been for some time.

**Comment by jadjoubran** [comment]
On version `2.0.x`, I was able to fix it by adding an `ng-if` for the marker
