### ISSUE TITLE
Searchbox doesn't work

### ISSUE THREAD

**Issue by upmauro** [angular-ui/angular-google-maps#759]
TypeError: Cannot read property 'protocol' of undefined

plnkr here

http://plnkr.co/edit/MV6WAtC3AIxSG7tDSPIG?p=preview

**Comment by fotoflo** [comment]
Hi! I'm having a similar problem. Can you post your final working code?

**Comment by gyril** [comment]
Similar problem, so I defined the $scope.searchbox outside the promise. But that means the searchbox has no bounds. So I tried to change the bounds of the searchbox afterwards, in the returned promise, but it doesn't seem to affect the directive at all. The code below only returns generic searches (I tried changing the events, or the template, or anything else, but the directive never refelects it):

    self.searchbox = { template: './templates/searchbox.tpl.html', events: { places_changed: placesChanged }, options: {}}
    uiGmapGoogleMapApi.then(function (maps) {
      // make sure self.control has the map
       var bounds = self.control.getGMap().getBounds()
        , sw = bounds.getSouthWest()
        , ne = bounds.getNorthEast()

        self.searchbox.options.bounds = new maps.LatLngBounds(sw, ne)
      }

**Comment by topikito** [comment]
@fotoflo Can you paste your code?

**Comment by kencaron** [comment]
Having a pretty similar issue. Been trying to avoid ng-controller altogether, so my searchbox is actually inside a directive. The error is actually a little different and points to the native angular function `urlIsSameOrigin` and it looks like the request isn't getting a URL or something. I can oddly only recreate this bug when I try to deploy my code, or step through breakpoints on my local.


Code
```
angular.module('pc.map', [])
  .directive('pcMap', function(uiGmapGoogleMapApi) {
  return {
    templateUrl: 'templates/map.html',
    link: function(scope, element, attrs) {
    	scope.center = { latitude: 45, longitude: -73 };
    	scope.zoom = 8;

    	var events = {
        places_changed: function (searchBox) {
        	var places = searchBox.getPlaces();
        	if (places) {
        		scope.center.latitude = places[0].geometry.location.lat();
        		scope.center.longitude = places[0].geometry.location.lng();
        	}
        }
      };

    	scope.searchbox = { template:'searchbox.tpl.html', events:events};

      uiGmapGoogleMapApi.then(function(maps) {
        console.log(maps);
      });
    }
  };
});
```

Markup
```
<script type="text/ng-template" id="searchbox.tpl.html">
        <input type="text" placeholder="Search Box">
    </script>
	<ui-gmap-google-map center="center" zoom="zoom">
		<ui-gmap-search-box template="searchbox.template" events="searchbox.events"></ui-gmap-search-box>
	</ui-gmap-google-map>
```

Config
```
uiGmapGoogleMapApiProvider.configure({
	        key: '[removed]',
	        v: '3.17',
	        libraries: 'places'
	    });
```

Cryptic I know, but I have deduced that removing the `ui-gmap-search-box` directive eliminates this problem.

**Comment by nmccready** [comment]
@kencaron did you try creating a controller in your directive? It may be odd but it would satisfy your issue.

**Comment by kencaron** [comment]
@nmccready Thanks that worked. Been so used to using `link` in my directives instead of `controller` that I didn't even consider it.
