### ISSUE TITLE
[r1-dev] [bug] If map is not visible, then becomes visible, it's rendered improperly. 

### ISSUE THREAD

**Issue by facultymatt** [angular-ui/angular-google-maps#76]
See plunkr for demo
http://plnkr.co/edit/dOMKgE?p=preview

It seems the only way to get the map working is to resize the window. Note the refresh prop is set and this doesn't work either. 

This was working in Master, FYI, which is the only reason I noticed it.

**Comment by geostima** [comment]
I have been spending a number of hours now and cannot get this to work at all following the instructions. An actual angular fiddle would help where this is resolved. Can this be done directly from the controller and not from some other directive?

**Comment by nmccready** [comment]
@geostima this ticket is way old start a new issue. Locking this ticket.
