### ISSUE TITLE
custom icon image not working with ui-markers directive

### ISSUE THREAD

**Issue by dgriego** [angular-ui/angular-google-maps#763]
I am currently using this url =
http://chart.apis.google.com/chart?chst=d_map_pin_letter_withshadow&chld=1|37455C|FFFFFF

for my icon.. I have attached it to $scope.icon in my controller as well as plugging this url straight into the html, like so:
<ui-gmap-google-map center="map.center"
                            zoom="map.zoom"
                            options="map_options">
            <ui-gmap-markers
                    models="map.markers"
                    icon="'map.icon'"
                    coords="'self'">
            </ui-gmap-markers>
</ui-gmap-google-map>

and: 

icon="'http://chart.apis.google.com/chart?chst=d_map_pin_letter_withshadow&chld=1|37455C|FFFFFF'"

neither one works, am I missing something?

**Comment by super-coder** [comment]
you have to use  icon= '{url:    "//developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png" }' see
http://stackoverflow.com/a/29399020/631527

**Comment by shekspir55** [comment]
@captainmarkos thanks

**Comment by DaveCollinsJr** [comment]
@super-coder thanks for the url tip.
