### ISSUE TITLE
Map tiles using X/Y/Z coordinates

### ISSUE THREAD

**Issue by onorok** [angular-ui/angular-google-maps#764]
The vanilla implementation of Google Maps tiles requires the usage of X/Y/Z coordinates.  Is there a decent example out there utilizing this method with Angular Google Maps?  The only thing I've found so far is map-layer, but I don't see a way to get that to work with the standard for tiles.

Thanks again for all you guys do!

**Comment by nmccready** [comment]
@onorok ever figure this out?

**Comment by onorok** [comment]
I did, sorry, this should be marked as closed. I can update the answer with code if it's still useful!

**Comment by nmccready** [comment]
Yes please and or add something to the documentation. Ty
