### ISSUE TITLE
Cannot load maps switch to online

### ISSUE THREAD

**Issue by Ti-webdev** [angular-ui/angular-google-maps#767]
1. Load app without configure google maps
2. Disable internet connection
3. Open map screen
4. Enable internet
Result: Maps not load

For fix:
Add script onerror= and/or timeout.
Add error event if cannot load maps and api for retry.

**Comment by QuentinFchx** [comment]
This is particularly useful with hybrid apps :)
We need to play with `navigator.connection.type == Connection.NONE`
I'll try to come with a PR if I find the time !
