### ISSUE TITLE
Fit on ui-gmap-markers / ui-gmap-marker

### ISSUE THREAD

**Issue by adoueb** [angular-ui/angular-google-maps#775]
Hello,

I have a map.
When I use ui-gmap-markers and set fit="true", it works fine.
When I use ui-gmap-marker and set fit="true", it doesn't work. "fit" is not an attribute of ui-gmap-marker.

The reason I changed from ui-gmap-markers to ui-gmap-marker is that I have a onMarkerClicked(marker) function on my controller.
When the user clicks on a marker, I want the function to be called using click="onMarkerClicked", but I don't know how to get the clicked marker in the function.

What do you advise to do both things (fit and onMarkerClicked with marker) ?

Regards,
A. Doueb.

**Comment by nmccready** [comment]
I plan on removing marker in 2.1.0 so this change is meaningless. Also functions / expressions are supported by markers on develop / 2.1.X.
