### ISSUE TITLE
ui-gmap-windows has problem

### ISSUE THREAD

**Issue by bogomips** [angular-ui/angular-google-maps#789]
Hello, 
i have this html:

<ui-gmap-google-map center="map.center" zoom="map.zoom" options="options" events="map.events">

```
        <ui-gmap-marker
            idKey='myself.id'
            coords='myself.coords'
            icon='myself.icon'>
        </ui-gmap-marker>

        <ui-gmap-markers
            models='items'
            coords="'loc'"
            icon="'icon'"
            doCluster=true
            clusterOptions='map.clusterOpt'>

            <ui-gmap-windows show="show"
                                //i tried to add and remove models attr here
                             >
                <div ng-non-bindable>TEST</div>
            </ui-gmap-windows>          

        </ui-gmap-markers>

    </ui-gmap-google-map>
```

the model is an array of
item  = {  
        id:myid,    //this is inside a for so each id are differente
        icon : myIcon,
        show:true,
        loc:[lng,lat]
}

markers appear without problems.
After I added ui-gmaps-windows directive I noticed in console (I have Logger.doLog = true;)

j: no valid models attribute found 
some rows after
No models to create windows from! Need direct models or models derrived from markers! 

The strange thing is that reloading many times, sometime i don't get the error and over the markers the infowindow appears !

tnx

**Comment by hautotd** [comment]
Setting the initial array solved my issue ! Thanks !!
