### ISSUE TITLE
fit="true" + single marker => zoom too big

### ISSUE THREAD

**Issue by adoueb** [angular-ui/angular-google-maps#791]
Hello,

I'm using release 2.0.3.

What are the options to change the zoom when 'fit' is true and there is a single marker ?

Regards,
A. Doueb.

**Comment by devotis** [comment]
Too bad. Reading the title, this seemed not a bug, but an feature request for a minimum zoom while using fit. Auto fitting with a single marker leads to a superzoom which is useless most of the time.
