### ISSUE TITLE
markers events

### ISSUE THREAD

**Issue by bogomips** [angular-ui/angular-google-maps#818]
Hi,
I noticed a couple of behaviours about marker's events that I would like to clarify.

1) With infowindow setted, even if I don't set any event, by clicking on the marker the infowindow appears. Is it a wanted feature ?

2) Using vanilla js and v3 api, from mobile I'm able to intercept the "click" event by

google.maps.event.addListener(this.marker, 'click', function() {

Using this module I cannot catch it instead, As I read around I setted the mousedown event.
why this difference ?

3) Even if I use mousedown event I've a big problem: I need a pause between two tap.
I mean, if I wait some seconds I'm able to fire again the event by tapping but, if I tap immediatly after, the event doesn't fires at all !

**Comment by yoooee** [comment]
Bogomips,

Thank You!  Your recommendation worked perfectly.

**Comment by nmccready** [comment]
:+1:

**Comment by trishfromtisch** [comment]
Thanks @bogomips !

**Comment by bogomips** [comment]
Welcome guys ;)
