### ISSUE TITLE
ng-repeat in  <ui-gmap-windows

### ISSUE THREAD

**Issue by wallstudios** [angular-ui/angular-google-maps#823]
Not sure if this is an issue or if it simply isn't possible.
I'm trying to do a ng-repeat inside of either a <ui-gmap-windows or <ui-gmap-window using a ng-repeat on the marker.

in neither one can I get them to render from the controller.

 <ui-gmap-markers models="map.markers" coords="'self'" icon="'icon'" click="'onClicked'" options="'options'" events="map.markers2Events">
 <ui-gmap-windows show="'showWindow'" closeClick="'closeClick'" ng-cloak>
 <p ng-repeat="item in items">{{item}}</p>

displays nothing

 if I do 
 <p ng-repeat="item in [1,2]"> {{item}} </p>
it renders
1
1
2
2

any thoughts?

thanks

**Comment by micheltl** [comment]
Hi Guys,

it's not clear for me. Does this issue closed ? It seems not but I'm not sure, so I prefer to ask the question...

I use angular-google-maps 2.0.12, and ng-repeat/ng-if/ng-show/ng-hide don't work in ui-gmap-window, even if I have another controller for the div :

`<div id="infoWindow">
    <div ng-controller='InfowindowImgCtrl'>
          blabla1
          <div ng-repeat="im in images">
                <img ng-src="{{im.url}}" height="30" width="30"></img>
          </div>
          blabla2
     </div>
</div>`

I can see blabla1 blabla2 but no image between .

Anyone can give a help ? Thanks in advance.

**Comment by blckshrk** [comment]
Hi,

Actually I agree with you one this it's not clear. I will try to get this more clear.

If you want use `ng-repeat` and all you have to use the `templateUrl` and `templateParameter` attributes. No need to dedicated controller, as you can see on the following.

```html
<ui-gmap-google-map center="map.center" zoom="map.zoom">
    <ui-gmap-window show="map.window.show" coords="map.window.model" options="map.window.options" closeClick="map.window.closeClick()" templateUrl="'views/modules/templates/infowindow.tpl.html'" templateParameter="map.window.model"></ui-gmap-window>
    <ui-gmap-markers idKey="'bid'" models="map.markers" coords="'self'" doCluster="false" fit="'true'" icon="'icon'" events="map.markersEvents" options="'options'"></ui-gmap-markers>
</ui-gmap-google-map>
```

```javascript
$scope.map = {
    center: {
        latitude: 50.6278,
        longitude: 3.0583
    },
    zoom: 12,
    markers: [], // array of models to display
    markersEvents: {
        click: function(marker, eventName, model, arguments) {
            $scope.map.window.model = model;
            $scope.map.window.show = true;
        }
    },
    window: {
        marker: {},
        show: false,
        closeClick: function() {
            this.show = false;
        },
        options: {} // define when map is ready
    }
};
```

And finally the `infowindow.tpl.html`
```html
<div class="gm-pro-popup">
    <header>
        <h3>{{parameter.title}}</h3>
    </header>
    <u>Users</u>
    <ul>
        <li ng-repeat="user in parameter.users">{{user.username}}</li>
    </ul>
</div>
```

Hope this is clearer for you! =)

**Comment by deveshsinghal22** [comment]
Thanks @blckshrk , This works for me.

**Comment by amgadfahmi** [comment]
@blckshrk thanks body, love clean code :+1:

**Comment by blckshrk** [comment]
Happy to help :)

**Comment by namelivia** [comment]
Commenting on @blckshrk solution, that worked for me (thanks!). I had to pass `map.window.model` as the parameter and not just `map.window`, that is firing a `cyclic oject value` error for me.
