### ISSUE TITLE
Error: [$compile:ctreq] Controller 'uiGmapGoogleMap', required by directive 'uiGmapMarker', can't be found!

### ISSUE THREAD

**Issue by topikito** [angular-ui/angular-google-maps#838]
Hi,

I'm trying to implement the markers, but I get this error when doing almost the same as the example in the documentation (I'm excluding the events).

```
        <ui-gmap-google-map draggable="false" center="map.center" zoom="map.zoom" options="map.options"></ui-gmap-google-map>
    <ui-gmap-marker coords="marker.coords" options="marker.options" idkey="marker.id"></ui-gmap-marker>
```

JS:

```
       $scope.map = {
        center: {
            latitude: 0,
            longitude: 0
        },
        options: {scrollwheel: false},
        zoom: 3
    };

    $scope.marker = {
        id: 0,
        coords: {
            latitude: 0,
            longitude: 0
        },
        options: { draggable: false }
    };
```

Thats the HTML. The map loads perfectly but stops executing JS after this error.

![image](https://cloud.githubusercontent.com/assets/694244/4875091/f36c2eba-6282-11e4-91be-2e399ca9e26a.png)

**Comment by fulup-bzh** [comment]
With new version  IdKey is mandatory. But if you place the marker outside of map directive you still get the 'uiGmapMarker', can't be found!.

**Comment by nmccready** [comment]
Yes uiGmapMarker is required to be inside uiGmapMap.

**Comment by iBasit** [comment]
<ui-gmap-google-map center="{latitude: 32.779680, longitude: -79.935493}" zoom="13">
                <ui-gmap-marker coords='{latitude: 32.779680, longitude: -79.935493}' idkey="marker.id"></ui-gmap-marker>
            </ui-gmap-google-map>

gives error "gMarker.key undefined and it is REQUIRED!!"
