### ISSUE TITLE
documentation mistyped 

### ISSUE THREAD

**Issue by bogomips** [angular-ui/angular-google-maps#864]
Hello,
in http://angular-ui.github.io/angular-google-maps/#!/api
  var map = int.map;
  sould be 
  var map = inst.map;

/*CODE*/
  IsReady.promise(2).then(function (instances) {
            instances.forEach(function(inst){
                var map = int.map;
                var uuid = map._id;
                var mapInstanceNumber = inst.instance; //starts at 1
            });
        });

**Comment by escapedcat** [comment]
Sorry for the two commits. Please use this one: https://github.com/escapedcat/angular-google-maps/commit/71ff791c0063cc1e63d484c5c8838db05ab67555
