### ISSUE TITLE
searchbox bounds

### ISSUE THREAD

**Issue by wallstudios** [angular-ui/angular-google-maps#891]
Hello,

I'm trying to use your searchbox example as a basis for a location search but I'm having issues with the bounds not being set.

Also the options seem to be being ignored. 

e.g.  position:'top-left',
if I change this nothing happens also if I try to set a search option like "type" it doesn't make a difference to the results.  types: ['establishment']
I assume it should be something like this

```
       searchbox: {
  template:'searchbox.tpl.html',
  position:'top-left',
  options: {
           types: ['establishment'],
            bounds: {} 
  },
```

With the searchbox bounds I am doing a current location lookup and on success refreshing the map on current location.

in that success call I am also doing the following to update (or) set bounds for the searchbox

```
                var bounds = $scope.map.control.getGMap().getBounds();
                var ne = bounds.getNorthEast(); // LatLng of the north-east corner
                var sw = bounds.getSouthWest(); // LatLng of the south-west corder
                //
                $scope.searchbox.options.bounds = new google.maps.LatLngBounds(ne, sw);


                console.log('bounds ' + $scope.searchbox.options.bounds);
```

The console.log returns valid bounds. 

but search results are still generic.
ok as I'm writing this I've been able to set the initial bounds but I can't seem to change them.

thanks in advance.

**Comment by gyril** [comment]
hi apparently wallstudios got his issue resolved but I seem to have the exact same problem: if I update the bounds of the searchbox, I still get generic values. I commented in #759 but this issue seems to be closer to my own problem.

**Comment by wallstudios** [comment]
Once I do a location update / refresh I do the following...

        var onSuccess = function(position) {
            $scope.map.control.refresh({
                latitude: position.coords.latitude,
                longitude: position.coords.longitude
            });
            $scope.map.control.getGMap().setZoom(14);
            $scope.myLocation.coords = {
                latitude: position.coords.latitude,
                longitude: position.coords.longitude
            };
            $scope.$apply();
            var markers = [];
            $scope.map.markers = [];
            markers = newData2;
            $scope.map.markers = markers;

            var bounds = $scope.map.control.getGMap().getBounds();
            var ne = bounds.getNorthEast(); // LatLng of the north-east corner
            var sw = bounds.getSouthWest(); // LatLng of the south-west corder
            //
            $scope.searchbox.options.bounds = new google.maps.LatLngBounds(sw, ne);

            $ionicLoading.hide();

        }

Not sure if that will help or not.

**Comment by gyril** [comment]
@wallstudios helps a lot! the $scope.$apply is key. Fixed my problem.

**Comment by nmccready** [comment]
Better performance if you use $cope.$evalAsync

**Comment by wallstudios** [comment]
@nmccready thanks. is there much performance to be gained? and having a quick read it seems to work better on the latest versions of angularjs is that correct?

**Comment by nmccready** [comment]
I am not totally sure when evalAsync came into play. But if it agm (ui-gmap) is working on 1.2.X of angular then you should be good (unless you need 1.1 angular). That is we are using evalAsync a lot in our code base.

**Comment by wallstudios** [comment]
just had a look and its ionic with angularjs v1.3.3. with that being said should I change my $apply to $evalAsync?

**Comment by wallstudios** [comment]
@nmccready  ok, just changed my code and its still working correctly.
thanks.
