### ISSUE TITLE
Switch to gulp for the build system?

### ISSUE THREAD

**Issue by cthrax** [angular-ui/angular-google-maps#915]
Given the number of operations that we perform on every file, it seems like we could benefit from the stream philosophy of gulp. I was looking at adding ng-annotate to our build, so we don't have to use the array syntax for every dependency, and gulp would make this fairly trivial.

Basically I'm creating this ticket to solicit, discussion. I'm happy to do the work, as I just got done doing a grunt to gulp conversion, but I don't want to impose my shiny new hammer on others.

@gitnik
@aesnyder
@kandizzy
@nmccready

What do you guys think?

**Comment by nmccready** [comment]
I love gulp, but there is a ton going on in our grunt build. I have little motivation and anything to gain at this point by switching to gulp. Unless we ever go with an angular2 version I see no point. I see that there are other angular 2 google maps libraries anyway (fine by me).
