### ISSUE TITLE
[need direcives] Real Animation not working

### ISSUE THREAD

**Issue by yaniv-fink** [angular-ui/angular-google-maps#953]
I tried to create delay using $timeout
when drawing the markers, this way markers look a live
but it does not work.

example for animation code: 
https://developers.google.com/maps/documentation/javascript/examples/marker-animations-iteration

Can any one check that?
or maybe add example how it's done?

The thing I tried:
```
   $scope.map.zoom=2;
                $scope.arrMarkers = [];
                for (i = 0; i < $scope.arrTempMarkers .length; i++) {
                    $timeout(function () {
                        $scope.arrMarkers.push($scope.arrTempMarkers [i]);
                    }, i * 1000);
                }
```
Result was:
 the marker where drawn
without delay(which was need to be)
follow by this console error: Error: [ngRepeat:dupes] 

p.s I used ui-gmap-polylines

**Comment by wrummler** [comment]
@yaniv-fink Closing this one. If you still want to follow up, please include the [runnable example](https://github.com/angular-ui/angular-google-maps/wiki/MCVE) that was previously requested. Thanks.
